### ISSUE TITLE
Add tests for over-long request and response bodies

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1005]
It would be useful to have some tests for what happens when the body is longer than that Content-Length says, e.g. `Content-Length: 1` and body "Hello, World!"

I guess if we get an overly-long message body on a connection we *should* close that connection (don't process any requests/responses remaining on that connection) and log an error. However, I don't know what we actually do.

**Comment by seanmonstar** [comment]
In the case of HTTP1, hyper enforces the content-length, and returns back just `H` as the body. If the connection is being kept-alive, then the following read will expect the bytes to be part of a new request. In the example case, it would return a parse error since `ello, World!` isn't a valid start line. If this were a server request, it would send back a 400 and close the connection. If it were a client response, the connection pool will have noticed the parse error and simply drop the connection.
