### ISSUE TITLE
linkerd-control-plane issuer are not able to reference an existing secret containing certificate and keys required for linkerd deployment

### ISSUE THREAD

**Issue by mainey** [linkerd/linkerd2#10087]
### What problem are you trying to solve?

Initially deploying linkerd with helm chart with IaC (Infrastructure as Code) in mind requires the individual to copy paste raw certificates and key to a .yaml file. 

### How should the problem be solved?

Make the deployment able to reference an external secret.

### Any alternatives you've considered?

No

### How would users interact with this feature?

Pass an argument for the deployments to reference an existing secret containing crt.pem and key.pem

### Would you like to work on this feature?

yes

**Comment by mateiidavid** [comment]
Hey @mainey please see the comment I left in the PR:

> @mainey thanks for submitting a PR, it's appreciated! I'm not sure this is a change we should be making though. Linkerd already supports referencing _an already created Secret_ which should be enough for most usecases, including IaC and automating rotation through third party tools.
> 
> > It is important to note that the mechanism that Linkerd provides for setting issuer certificates and keys is also usable outside of cert-manager. Linkerd will read the linkerd-identity-issuer Secret, and if it’s of type kubernetes.io/tls, will use the contents as its TLS credentials
> > https://linkerd.io/2.12/tasks/automatically-rotating-control-plane-tls-credentials/
> 
> Provided a `Secret` named `linkerd-identity-issuer` already exists in the `linkerd` namespace, you can install Linkerd and instruct it _NOT_ to create the same secret, and instead use what's in the namespace already.
> 
> ```
> linkerd install --identity-external-issuer
> # or
> linkerd install --set "identity.issuer.scheme=kubernetes.io/tls"
> # or through helm
> helm install linkerd-control-plane -n linkerd \
>   --set-file identityTrustAnchorsPEM=ca.crt \
>   --set identity.issuer.scheme=kubernetes.io/tls \
>   linkerd/linkerd-control-plane
> ```

I think this is already covered by Linkerd. I'm going to go ahead and close both the issue and the PR. If you want either of them re-open, please comment and ping me :)

**Comment by robgordon89** [comment]
@mateiidavid 

Is it possible to reopen this, using something like FluxCD (Gitops) it is not possible to inject this ca.crt file when creating the helm release and thus this issue is valid.

Having to place the Certificate directly in the values is kind of annoying when using cert-manager to generate the identity certificate.

Can we look at this again? It has been brought up a couple of times, and being able to provide the identityTrustAnchorsPEM that is already in the secret that cert-manager created would be great.

**Comment by mateiidavid** [comment]
Hey @robgordon89! Not opposed to it, but need to understand why the current approach doesn't solve your problems. We'd like to avoid adding too much configuration. Going ahead with the change described in this issue also involves more work than the scope of the (now) closed PR.

If you want to use cert-manager to bootstrap your CA and have Linkerd pick it up automatically, you can do that already. See https://github.com/linkerd/linkerd2/issues/7345#issuecomment-979207861. We don't support mounting CA secrets created by cert-manager and our stance on that won't change (due to the security implications). However, you can specify your own configmap that holds the CA public key; linkerd won't create it.

Let me know if this all makes sense.
