### ISSUE TITLE
Setting `proxy-log-level` annotation on the control-plane deployments does not affect proxy log level

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#10122]
### What is the issue?

Setting `config.linkerd.io/proxy-log-level` annotation on the control plane components does not modify the actual proxy log level of the control plane injected proxies. 

Current workaround is to manually adjust the `LINKERD2_PROXY_LOG` env var in the deployment.

### How can it be reproduced?

1. Deploy Linkerd
2. Set `config.linkerd.io/proxy-log-level: debug` annotation on `linkerd-destination` component
3. Bounce all pods and observe no change in log level taking effect

### Logs, error output, etc

n/a

### output of `linkerd check -o short`

n/a

### Environment

Linkerd 2.12+

### Would you like to work on fixing this bug?

no

**Comment by mateiidavid** [comment]
This is by design. The control plane components won't go through the injector (lest we introduce a circular dependency), so annotation configuration won't do much for control plane components. You can modify the endpoint on the fly though by port-forwarding: https://linkerd.io/2.12/tasks/modifying-proxy-log-level/ or you can do an upgrade. I'd go for (1) and port-forward.

**Comment by deusxanima** [comment]
Closing per explanation from Matei above. Will confirm and update docs accordingly.
