### ISSUE TITLE
Revise resource labels in extensions and update upgrade instructions for extensions

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#10262]
We have [instructions](https://linkerd.io/2.12/tasks/upgrade/#with-the-linkerd-cli) for upgrading the control plane using `--prune` and `--prune-whitelist` to delete no longer used objects when doing `linkerd upgrade`. We should do the same for the extensions upgrade [instructions](https://linkerd.io/2.12/tasks/upgrade/#upgrading-extensions), especially since changes like #10079 renamed some resources.

But before that, we need to make sure all the resources hold the necessary labels used in the prune flags.

**Comment by adleong** [comment]
One thing that's a bit of a problem with this approach is that the `--prune` kubectl behavior seems to only apply to resource types which are included in the input.  This means that if we remove all instances of a resource type from our chart, any existing instances of that type will not be pruned.  This would be the case here because we removed all instances of `ServerAuthorization`.

This can be worked around using the `--prune-whitelist` flag.  However, doing so would require passing a `--prune-whitelist` flag for every single resource type which has ever been included in the chart, which is prohibitively cumbersome.  

The lack of tools in `kubectl` for doing this kind of thing really points to the fact that `kubectl` is not a release management tool.  One path forward would be to document that using the CLl is not suitable for 0-downtime extension upgrades and doing an extension upgrade with the CLI requires uninstall -> reinstall.  For 0-downtime extension upgrades, users should be using Helm.
