### ISSUE TITLE
Customize mirrored service name

### ISSUE THREAD

**Issue by whiskeysierra** [linkerd/linkerd2#10275]
### What problem are you trying to solve?

I'd like to control how the local service name (in the source cluster) of a mirrored service is being generated.

The reason for this being that I want to hide the presence/names of clusters from our applications.
We treat clusters (and their respective names) as implementation details.
Application developers shouldn't be concerned with where a particular service that they want to consume is deployed.

Let's say I have two clusters `east` (source) and `west` (target).
The `west` cluster contains a namespace `sales` and a service `api` within it.

Today, when this service is being mirrored, then:
The `east` cluster contains a namespace `sales` and a service `api-west` within it.

When this service is moved from one cluster to another (e.g. due to organizational changes), then each consumer needs to update their configuration to change `api-west.sales.svc.cluster.local` to `api-south.sales.svc.cluster.local` (or whatever).
In case the service moves to the `east` cluster directly, then local consumers would need to use `api.sales.svc.cluster.local`.

If I could customize the name to be exactly the same as the remote service name, in this case `api`, then I wouldn't need to do anything at all.
All the consumers stay the same, because they don't care which cluster currently hosts that service.

### How should the problem be solved?

Right now the logic is hard-coded as:

https://github.com/linkerd/linkerd2/blob/032845c846fe2e5d12922f0cf3b291b70013f802/multicluster/service-mirror/cluster_watcher.go#L203

One option would be to switch from `Sprintf` to templating: https://pkg.go.dev/text/template.
The template string could be made configurable but default to the equivalent of what it is today:

```golang
tmpl := "{{.remoteName}}-{{.targetClusterName}}"
```

I envision three places where this ultimately needs to be added:

1. Flag to the `service-mirror` CLI command
2. Flag to the `multicluster link` CLI command
3. Helm value in the `multicluster-link` chart.

### Any alternatives you've considered?

In the discussion at https://linkerd.slack.com/archives/C89RTCWJF/p1675168940457469, it was suggested to use TrafficSplit (on the source cluster, I'd assume) to create a _virtual_ service with the desired name.

I tried to follow this discussion https://github.com/linkerd/linkerd2/discussions/7144, but it didn't get me anywhere (too confusing, tbh).

### How would users interact with this feature?

Pass e.g. `--mirrored-service-name-pattern="{{.remoteName}}"` to the `multicluster link` CLI command when linking two clusters.

### Would you like to work on this feature?

yes

**Comment by adleong** [comment]
Hi @whiskeysierra, thanks for opening this.  It makes total sense to want to ability to customize the mirror service name so that clients can be agnostic to which cluster the exported service is running in.  I'm not sure that passing in a go template for the name is the right approach, however.

One advantage of the TrafficSplit based approach you mentioned above is that it gives you more flexibility and control over where the traffic is sent.  For example, if you have both `api-west` and `api-south` mirror services, you can use a traffic split to declare whether traffic to the `api` service should go to `api-west` or `api-south` (or a weighted mix).  This also allows you to instantaneously switch from one target cluster to another.  

If, instead, you configured the Links to name the mirror service `api` regardless of the target cluster, you would need to ensure that only one Link was active at a time to avoid service name collisions.  Switching from one target cluster to the other would involve a period of downtime after one Link had been removed and before the other had been created.

I know that TrafficSplits are confusing (trust me :sweat_smile:) and not very ergonomic.  However, making this kind of configuration simpler and easier to declare using traffic policy (instead of SMI TrafficSplits) is the main focus of Linkerd 2.13, so this kind of thing will be easier to express soon.

**Comment by whiskeysierra** [comment]
> you can use a traffic split to declare whether traffic to the `api` service should go to `api-west` or `api-south`

That's true, however this `TrafficSplit` would live in the `east` cluster and someone needs to actually manage it.
Unfortunately, this someone will be one of the engineers of a service who likes to consume `api`.
In terms of hiding clusters from consumers of services, I haven't really achieved my goal here.

**Comment by adleong** [comment]
That's very true.  In terms of design tradeoffs, our philosophy has generally been that clients should be ultimately in control of where they send traffic.

**Comment by wmorgan** [comment]
@whiskeysierra the approach we've seen work best in practice is for responsibility for the TrafficSplit (or future 2.13 equivalent) to fall under the same team as those responsible for Links. Typically this is platform team, who owns the clusters and the location of where the services are deployed. The developers who consume "api" are then decoupled from the implementation detail of where that service actually lives.

(It is an additional resource to maintain. But this approach allows you to decouple cross-cluster connectivity (link) from naming (TrafficSplit), which means you can do gradual shifts of traffic between clusters, etc.)

**Comment by whiskeysierra** [comment]
Thank you for the detailed explanation. I see now that there is more to this than I initially thought. It's great to see that you made conscious design decisions and I follow your reasoning.

From my perspective this issue can be closed now. TrafficSplits give me enough freedom to customize the consumed service name without sacrificing cross cluster traffic shifting.
