### ISSUE TITLE
Extend linkerd-viz charts to allow disabling tap components via helm

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#10441]
### What problem are you trying to solve?

Users who want to use linkerd-viz metrics exporter but don't want to utilize tap or web components do not currently have a way to disable those via the existing helm charts. The options are to either fork and maintain their own helm charts or not use linkerd-viz metrics exporter at all, both of which add additional operational overhead, or to manually scale down the non-metrics-exporter components and clean up superfluous webhook configs after deployment. 

### How should the problem be solved?

We should extend an option in our helm charts to disable tap and web deployments like we do with the prometheus deployment currently.

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

helm

### Would you like to work on this feature?

None

**Comment by mateiidavid** [comment]
Mm, so `viz` would only deploy `metrics-api` and `prometheus`? `metrics-api` would only be needed to run queries for the dashboard and CLI, it's a layer in between metrics consumers and prometheus (the source).

I'm trying to understand if this is more about making our scrape configs more visible, or slimming down the extension. Viz is not a requirement for having access to metrics, it's just a convenience layer to make those metrics more accessible. Instead of overloading the extension with more configuration and deployment modes, we could just as well have a prompt somewhere saying "if you want to scrape endpoints in your own prometheus, use this recommended configuration".

**Comment by jeremychase** [comment]
Thanks for the clarification Matei! Closing.
