### ISSUE TITLE
linkerd-destination ImagePullBackoff

### ISSUE THREAD

**Issue by linuxeryt** [linkerd/linkerd2#10459]
### What is the issue?

pod image pull backoff

### How can it be reproduced?

helm upgrade linkerd

### Logs, error output, etc

kubectl describe:

  Normal  Pulling  46m (x26 over 154m)   kubelet  Pulling image "ghcr.io/olix0r/policy-controller:nativetls.40ab223a"
  Normal  BackOff  87s (x675 over 154m)  kubelet  Back-off pulling image "ghcr.io/olix0r/policy-controller:nativetls.40ab223a"

### output of `linkerd check -o short`

pod/linkerd-proxy-injector-6b8f6b854d-v7fdt container proxy-injector is not ready

### Environment

linkerd version: 2.11.1

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
@linuxeryt what version of linkerd-cli, or what version were you trying to upgrade to? Seems like an odd build :D

**Comment by olix0r** [comment]
Is that helm chart set in your values.yaml for some reason?

**Comment by linuxeryt** [comment]
@olix0r  

I got the  image from here
[Is that image set in your values.yaml for some reason?](https://github.com/linkerd/linkerd2/issues/7275)

**Comment by mateiidavid** [comment]
Ah, that's a test image that was published only to see if changing the TLS implementation of the policy-controller would fix the error. That issue has since been fixed. If you try the most recent stable version, you won't run into any issues. I think most versions after `2.11.1` should have the TLS implementation changed.

Going to close this for now. If you're in doubt, I'd look over the release notes (you can find those in CHANGES.md in the root of this repository, or in the releases section where images are published).

Thanks for raising this!
