### ISSUE TITLE
unable to delete server_port_subscribers metric with labels 

### ISSUE THREAD

**Issue by dwilliams782** [linkerd/linkerd2#10764]
### What is the issue?

Since upgrading to 2.13.0, our destination logs are spammed with:

```
level=warning msg=“unable to delete server_port_subscribers metric with labels map[name:loki namespace:monitoring port:7946]” addr=“:8086" component=server
```

We don't run the Viz Prometheus, incase that's related at all.

### How can it be reproduced?

Unsure. This happened after upgrading.

### Logs, error output, etc

.

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- v1.23.16-gke.1400
- 2.13.0

### Would you like to work on fixing this bug?

None

**Comment by adleong** [comment]
I believe that this can happen because of the way that the pod name label is computed on the server_port_subscribers gauge.  The gauge is labeled with the first segment of the pod name only, i.e. the pod's workload name.  This means  that portPodPublishers for different pods within the same workload (each with their own distinct list of listeners) will have conflicting gauge labels.

This means that the gauge value is incorrect (it will be set to the number of listeners for an individual podport instead of the total across the entire workload) and each update from a podport will overwrite the value from any other podport in the same workload.

It also means that it's possible for there to be two subscriptions to two different podports in the same workload (with one listener each) and then when these become unsubscribed, the following happens:
* the first unsubscribe removes itself from the list of listeners for that podport, causing the listeners list to become empty and deleting the gauge
* the second unsubscribe removes itself from the list of listeners for THAT podport, also causing it to become empty and attempting to delete the gauge again, resulting in the error message described in this issue.

I think there's a fundamental mismatch here between keeping a separate list of listeners for each podport while trying to report a gauge which is an aggregate over an entire workload.  It may be possible to modify the code so that the gauge accurately reflects the total number of listeners summed across all podports within a workload, but a simpler solution may be to replace this gauge with a pair of counters: one for subscriptions and one for unsubscriptions.  This composes more easily since counter increments from different podports in the same workload will both apply instead of overwriting each other.  And we can still determine the number of active subscriptions by subtracting unsubscriptions from subscriptions (assuming we account for counter resets).

**Comment by SansDK** [comment]
@adleong here are some logs from one of our destination pods. If you need anything else, let me know :)
```
time="2023-07-26T06:25:55Z" level=warning msg="unable to delete server_port_subscribers metric with labels map[name:consul namespace:configuration port:8301]" addr=":8086" component=server
time="2023-07-26T06:26:04Z" level=warning msg="unable to delete server_port_subscribers metric with labels map[name:xyz namespace:kafka port:4191]" addr=":8086" component=server
time="2023-07-26T06:26:21Z" level=warning msg="unable to delete server_port_subscribers metric with labels map[name:xyz namespace:kafka port:4191]" addr=":8086" component=server
time="2023-07-26T06:26:34Z" level=warning msg="unable to delete server_port_subscribers metric with labels map[name:xyz namespace:kafka port:4191]" addr=":8086" component=server
time="2023-07-26T06:26:34Z" level=warning msg="unable to delete server_port_subscribers metric with labels map[name:xyz namespace:kafka port:4191]" addr=":8086" component=server
time="2023-07-26T06:26:37Z" level=warning msg="unable to delete server_port_subscribers metric with labels map[name:xyz namespace:kafka port:4191]" addr=":8086" component=server
```

Hopefully this helps!
