### ISSUE TITLE
Viz Dashboard: filter taps for HTTP status code

### ISSUE THREAD

**Issue by ngc4579** [linkerd/linkerd2#10951]
### What problem are you trying to solve?

The Linkerd Viz Dashboard features a variety of HTTP related filters for taps, among them path, scheme and HTTP method.

<img width="1045" alt="SCR-20230526-lnrl" src="https://github.com/linkerd/linkerd2/assets/25631871/c608e724-97b1-413c-938b-94da6650e9d5">

While this already offers excellent ways to filter requests, I'm missing an HTTP status code filter.

### How should the problem be solved?

I'd suggest adding an HTTP status code filter that might be helpful in certain scenarios, e.g. high request throughput while looking only for specific (rare) HTTP status responses.

### Any alternatives you've considered?

The `linkerd viz tap` CLI command might help using the `--selectors` flag, but I couldn't find concise documentation or examples.

### Would you like to work on this feature?

None

**Comment by ngc4579** [comment]
*bump*

**Comment by adleong** [comment]
Hi @ngc4579 

Sorry for the delay in responding to this issue.  Unfortunately, it's not possible to tap only requests with a certain HTTP response code because the proxy needs to decide whether to tap a request when it first processes the request.  It is not possible to retroactively tap a request based on the response.

With that said, you can always postfilter the results from tap to select only the tap events which pertain to a certain HTTP response code.  This is probably most easily done by using the `linkerd viz tap` CLI command in JSON format output mode, and your favorite JSON processing tool.

**Comment by ngc4579** [comment]
@adleong Yeah, NP, and thanks for clarification. 🙃

**Comment by kflynn** [comment]
Thanks @ngc4579! I'm going to go ahead and close this; reopen if need be. 🙂
