### ISSUE TITLE
Add resource requests to control plane components

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1101]
There are no resource requests on control plane components. This can lead to resource starvation and over-provisioning.

As a best practice, default resource requests should be added to the YAML. These should be sized for a small cluster out of the box and allow users to override them.

**Comment by grampelberg** [comment]
This might have an impact on configuration (sizing the requests based on potential workload). If that's the case, it might make sense to leave this specific issue out of the gibraltar release.

**Comment by benjdlambert** [comment]
@grampelberg - I’d be more than happy to take this if that works? Pretty similar implementation to #1480 but with defaults if that’s still the desired functionality?

**Comment by benjdlambert** [comment]
@grampelberg that is an interesting question! You could just start off by t-shirt sizing it, but I mean
It can totally depend on the hosts cluster setup.

Another angle though, If I remember correctly, the only thing you can’t run more than one replica of in the control plane is prometheus? Would it be a better approach to horizontally scale the control plane rather than vertically? So we add some standard requests and let HPA deal with scaling the control plane instead of having fixed requests on linkerd install?

**Comment by benjdlambert** [comment]
This is all with the caveat that I’m not super sure how much the control plane pods need to scale with the meshed services, so it might be useless scaling the control planes horizontally if it’s not going to scale with the sidecars and their deployments

**Comment by grampelberg** [comment]
@klingerf has definitely put more thought into how the control plane scales than I.

I was more focused on the difference between an install on minikube (basically just schedule everything, I don't care) to a more production level install (give me some extra padding just in case).

The other piece to this is that I'm a little concerned with how many command line options are getting added to install/inject. It feels like there's a better solution than looking through the install docs to understand every little knob you can tweak.

**Comment by benjdlambert** [comment]
Well, I guess you don’t really care for requests on minikube? I’ve not used it heavily, so I don’t know all use cases, but I’m guessing that more of a test environment locally, whereas on a real k8s cluster, you’d expect sensible defaults, and best practice as default.

What is the footprint of the control plane under different conditions? Does it scale with the amount of meshed services? 

On different note, and Re: adding more flags to the cli. Yeah, I agree fully that it might get out of hand pretty quickly exposing everything as options and flags to change every detail.

The more flags and options that get added, the closer it becomes something like a helm chart, which is designed for templating variables into .yml, and being able to configure everything. I’m not sure that the CLI should try to solve that problem.

**Comment by klingerf** [comment]
Nice, this is all good discussion. Related to @grampelberg's comment, rather than making this infinitely configurable, maybe it would be better to support different modes for the control plane.

Without giving it too much thought, I imagine that there would be 2 different modes initially:

* In _development_ mode, we run a single instance of each deployment, and none of the pods make any resource requests (current default).
* In _production_ mode, we run 3 instances of the controller, web, and grafana deployments, and all deployments in the control plane have sane resource requests and deployment strategies set (basically anything that we'd want for HA).

... or something like that.

Regarding the actual defaults that we use for CPU and memory requests: I'm not sure we have enough data points at the moment to pick something reasonable. Maybe folks running in prod already can report on how the control plane is performing at steady state?

**Comment by benjdlambert** [comment]
@klingerf - that’s a nice solution! What do you think should be the default? 

On the defaults, I can take a look at what our control plane consumes on both busy and quiet times and report back.

I’m curious to see what effect adding more services to the mesh has on the resources used by the control plane. The controller pod specifically. 👍

**Comment by grampelberg** [comment]
@klingerf why are you thinking about running 3x instances of web and grafana? Since they're stateless and more about debugging, it feels totally fine to have them be 1x even in production.

fwiw I've been doing a teensy bit of load testing lately. With 1-2k rps, 120 or so pods and 10 services, the controller itself stays pretty low on memory (100-200Mi) and cpu is in the 3-10m range. Prometheus ends up hovering in the 300Mi range at 25m-50m cpu.

**Comment by benjdlambert** [comment]
This is probably more of a HA question, but I think that running only one of the `controller` pods in production could be risky. We run two as a precaution right now so that if one of them gets rescheduled or dies, it has minimal impact on production systems. 

Can also confirm, that right now in our stack prometheus has the biggest footprint. Maybe the load test is a sensible starting point for the requests @grampelberg though?

**Comment by grampelberg** [comment]
Yeah! I'm a big +1 on running 3x controller for the "production" configuration. It feels like this is a good incremental change that we can watch and see how it works out in the real world.

**Comment by grampelberg** [comment]
I actually feel pretty strongly that the production configuration should never be the default, but we should have some more in depth discussions when we get there.

**Comment by benjdlambert** [comment]
So I'd like a little bit of feedback for implementation here, I'm not sure if adding a load of variables to `InstallConfig` for this is the right approach, it's going to grow quite a lot.

Should the logic be moved to the templating layer to automatically override the defaults if `EnableProduction` is set?

**Comment by grampelberg** [comment]
@klingerf and I have talked about an "addon" system that lets you do things like this. You'd `linkerd install` the development version and then `linkerd add production` (which would update with resource requests and increase the replica count).

For now, my vote is to just have a `--production` flag.

**Comment by klingerf** [comment]
@benjdlambert Sorry for the delay here. I agree with @grampelberg that we should add a `--production` flag, which will set sane resource requests and adjust the number of controller replicas. If the existing `--controller-replicas` flag is set, that should override the number of replicas that's implied by the `--production` flag.

Related to this change, I'd be in favor of removing the `--web-replicas` and `--prometheus-replicas` flags entirely, since they shouldn't change between development and prod (as we discussed previously, we should still run a single replica of both of those deployments, even in prod mode). But I could also undertake that change in a follow-up PR, once the `--production` flag has been created.

**Comment by benjdlambert** [comment]
I can take the removal of the `--replicas` also, as it makes the template much cleaner I think.

One more note, given the /unique/ nature of how `k8s` works, you can't specify requests for pods. You request it for the individual containers. Which means that the limits have to be set individually on `destination`, `proxy-api`, `public-api`, `tap` and the `linkerd-proxy`. 

@grampelberg - could you re-run your load test and use `docker stats` to get some more fine grained metrics or is that overkill? Otherwise I can just double what we're currently using on our Live cluster and go from there?

**Comment by benjdlambert** [comment]
From the control plane - I got the following metrics.

*destination*
- ~1% CPU
- 50mb Memory

*proxy-api*
- ~1% CPU
- 12mb Memory

*public-api*
- <1% CPU
- 28mb Memory

*tap*
- <1% CPU
- 28mb Memory 
(Even when tap'ing an our entire NS)

*linkerd-proxy*
- <1% CPU
- 4mb Memory

**Comment by klingerf** [comment]
In one of my lightly used test clusters with TLS and auto-injection enabled, and the linkerd dashboard open, I see:

| Container | CPU | Memory |
| -------- | --- | ------ |
| ca | 0 | 17Mi |
| destination | 1m | 16Mi |
| grafana | 8m | 23Mi |
| prometheus | 372m | 209Mi |
| proxy-api | 0 | 10Mi |
| proxy-injector | 0 | 5Mi |
| public-api | 19m | 22Mi |
| tap | 0 | 17Mi |
| web | 6m | 10Mi |

And here are the linkerd-proxy container stats per pod:

| Pod | CPU | Memory |
| --- | --- | ------ |
| ca | 0 | 4Mi |
| controller | 7m | 18Mi |
| grafana | 0 | 4Mi |
| prometheus | 6m | 7Mi |
| proxy-injector | 0 | 4Mi |
| web | 1m | 5Mi |

I think doubling what you're seeing in your prod cluster would be a good starting point for this feature.

**Comment by benjdlambert** [comment]
Who knew that tables were better at displaying data than what I did.. Perfect. I've made some progress, just needed some values to write some nice `.golden` templates to make sure everything works as expected :tada:

**Comment by benjdlambert** [comment]
Hey - sorry turns out I had to do some of my own job work so got a little busy. Picked this up again today and noticed that `ControllerReplicas` is also used in `install/template.go` for the `ca` and `proxy-injector`.

I'm guessing that it might be better defaulting these to `1` also? Or should they also directly scale with the `controller` pods?

**Comment by klingerf** [comment]
Hey @benjdlambert, no prob at all! I agree that configuring it so that `ca` and `proxy-injector` always run with 1 replica is the right behavior. Especially for the `ca`, I'm not even really sure what would happen if we tried to run more than 1.
