### ISSUE TITLE
inconsistent logging when using json

### ISSUE THREAD

**Issue by jack1902** [linkerd/linkerd2#11360]
### What is the issue?

I have configured `json` logging for all components within linkerd and assumed the json style would be similar, however there is a clear difference in the `keys` exposed even for components that make up the `control-plane`.

### How can it be reproduced?

Deploy linkerd control-plane with the following additions (using values-ha.yaml aswell):

```yaml
controllerLogFormat: json
proxy:
  logFormat: json
proxyInit:
  logFormat: json
networkValidator:
  logFormat: json
```

### Logs, error output, etc

- `policy` (destination pod): `{"timestamp":"2023-09-11T15:45:48.092188Z","level":"INFO","fields":{"message":"Lease already exists, no need to create it"},"target":"linkerd_policy_controller"}`
- `sp-validator` (destination pod): `{"level":"info","msg":"running version stable-2.13.6","time":"2023-09-11T15:45:47Z"}`
- `destination` (destination pod): `{"level":"info","msg":"running version stable-2.13.6","time":"2023-09-11T15:45:47Z"}`
- `proxy-injector` (proxy-injector pod) : `{"level":"info","msg":"running version stable-2.13.6","time":"2023-09-11T15:45:54Z"}`
- `identity` (identity pod) : `{"level":"info","msg":"running version stable-2.13.6","time":"2023-09-11T15:45:47Z"}`
- `linkerd-init` (any pod) : `{"level":"info","msg":"/sbin/iptables-save -t nat","time":"2023-09-11T15:45:45Z"}`
- `linkerd-proxy` (any pod) : `{"timestamp":"[     0.002057s]","level":"INFO","fields":{"message":"Using single-threaded proxy runtime"},"target":"linkerd2_proxy::rt","threadId":"ThreadId(1)"}`

### output of `linkerd check -o short`

```text
Status check results are √
```

### Environment

- Kubernetes Version : 1.25
- Linkerd Version: 2.13.6
- Host OS: MacOS

### Possible solution

Ensure that the logs are output in a standard format for all components of linkerd where applicable. Since the control-plane components have different log-out formats i have to configure numerous parsing mechanisms if i wish to use `json` log format (i prefer json log format as it makes parsing multi-line output significantly better with tools such as Grafana Loki). The only outliers assuming `msg` is the better path are `policy` and `proxy`.

Unsure if `proxy` is better suited in the form of `message` but having `msg` and `message` seems confusing

### Would you like to work on fixing this bug?

None

**Comment by hawkw** [comment]
This is because logs from the proxy and policy controller are emitted using a different logging library than the logs emitted by the destination and identity controllers. This is because the proxy and policy controllers are written in Rust, while the destination and identity controllers are written in Go.

We can easily configure the policy controller logs to more closely match the style emitted by the proxy (and vice versa). It should also be possible to configure the Rust and Go logging libraries to emit logs in a consistent format, but this will require somewhat more effort than ensuring consistency between binaries that use the same logging library.

**Comment by hawkw** [comment]
The proxy timestamps are expressed as uptime of the proxy process, rather than as UTC timestamps, because this avoids getting the system timestamp every time a log is written, reducing performance overhead. We do this because `kubectl logs` can add timestamps, so it's not necessary to emit the same timestamp in the proxy. So, if we wanted to make the timestamp format consistent, we would probably want to change the control plane components to emit similar uptime-based timestamps. 

There is also a `logfmt`-style formatter for the logging library used by the Rust components (proxy and policy-controller): https://github.com/EmbarkStudios/tracing-logfmt. We could consider introducing the `logfmt` formatter if we want to depend on this library, giving us a non-JSON format that's consistent with the Go controller logs. I find this format less human-readable, though, so it might be desirable to add it as an additional `LINKERD_PROXY_LOG_FORMAT` option, retaining the current format...

**Comment by Laakso** [comment]
Yes, I've also noticed this. It would be nice if the log format were consistent across all Linkerd components.

**Comment by Laakso** [comment]
Additionally, it would be beneficial if all log level messages followed a consistent style, either being capitalized or not capitalized.

**Comment by kflynn** [comment]
After discussion amongst the maintainers, we're not going to do this.

Ultimately, the problem here is that the code in question isn't actually in Linkerd, as noted by @hawkw earlier -- it's down in the logging libraries, and those are used by a great many projects other than Linkerd. So in order to make this change, we'd need to either fork the libraries, make the change, and maintain the fork for all time, _or_ change them upstream, which would change the output format for everyone using the libraries.

We totally understand that the differences in format are annoying! but neither of those paths to make everything completely consistent is feasible for us -- and since tools that consume logs already have to be able to cope with variance like this, it's hard to see value in spending cycles making our logging just a little bit more consistent. So I'm going to go ahead and close this, with apologies.
