### ISSUE TITLE
Service Mirror not handling resourceVersion errors correctly

### ISSUE THREAD

**Issue by DavidMcLaughlin** [linkerd/linkerd2#11494]
### What is the issue?

We see reports from customers that the service mirror restarts when it encounters an error that the resourceVersion is too old:
```
time="2023-10-06T18:55:20Z" level=error msg="Error processing &{%!s(*v1.Endpoints=&{{ } {echosvr test bff2f1c1-a298-45c1-a2bb-27121fc8febf 3087652562 0 {{0 63806043566 0x3172ae0}} <nil> <nil> map[app:echosvr mirror.linkerd.io/exported:true] map[endpoints.kubernetes.io/last-change-trigger-time:2023-09-21T15:10:57Z] [] [] [{kube-controller-manager Update v1 0xc00011c750 FieldsV1 0xc00011c768 }]} [{[{172.17.105.56 0xc0007f6290 0xc0001ac070}] [] [{http-api 8080 TCP <nil>}]}]})} (giving up): Inner errors:\n\tendpoints \"...\" not found" apiAddress="..." cluster=remote
time="2023-10-06T18:55:58Z" level=error msg="Unknown object type detected: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:The resourceVersion for the provided watch is too old.,Reason:Expired,Details:nil,Code:410,}"
```

These errors should be handled gracefully, as they are expected part of the watch. 

### How can it be reproduced?

We'd have to simulate the resourceVersion pruning in etcd. 

### Logs, error output, etc

```
time="2023-10-06T18:55:20Z" level=error msg="Error processing &{%!s(*v1.Endpoints=&{{ } {echosvr test bff2f1c1-a298-45c1-a2bb-27121fc8febf 3087652562 0 {{0 63806043566 0x3172ae0}} <nil> <nil> map[app:echosvr mirror.linkerd.io/exported:true] map[endpoints.kubernetes.io/last-change-trigger-time:2023-09-21T15:10:57Z] [] [] [{kube-controller-manager Update v1 0xc00011c750 FieldsV1 0xc00011c768 }]} [{[{172.17.105.56 0xc0007f6290 0xc0001ac070}] [] [{http-api 8080 TCP <nil>}]}]})} (giving up): Inner errors:\n\tendpoints \"...\" not found" apiAddress="..." cluster=remote
time="2023-10-06T18:55:58Z" level=error msg="Unknown object type detected: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:The resourceVersion for the provided watch is too old.,Reason:Expired,Details:nil,Code:410,}"
```

### output of `linkerd check -o short`

N/A

### Environment

- Linkerd Version: 2.12.6

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
I looked into this. I believe the resourceVersion errors to be a red herring.

```
time="2023-10-06T18:55:20Z" level=error msg="Error processing &{%!s(*v1.Endpoints=&{{ } {echosvr test bff2f1c1-a298-45c1-a2bb-27121fc8febf 3087652562 0 {{0 63806043566 0x3172ae0}} <nil> <nil> map[app:echosvr mirror.linkerd.io/exported:true] map[endpoints.kubernetes.io/last-change-trigger-time:2023-09-21T15:10:57Z] [] [] [{kube-controller-manager Update v1 0xc00011c750 FieldsV1 0xc00011c768 }]} [{[{172.17.105.56 0xc0007f6290 0xc0001ac070}] [] [{http-api 8080 TCP <nil>}]}]})} (giving up): Inner errors:\n\tendpoints \"...\" not found" apiAddress="..." cluster=remote
time="2023-10-06T18:55:58Z" level=error msg="Unknown object type detected: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:The resourceVersion for the provided watch is too old.,Reason:Expired,Details:nil,Code:410,}"
```

Looking closer at this message, we can see that instead of parsing an expected object (a Link in this case) we parsed a Status. The relevant code in the [service-mirror can be found here](https://github.com/linkerd/linkerd2/blob/stable-2.13.0/multicluster/cmd/service-mirror/main.go#L151-L153). The issue is benign and to understand it we need to have a look at the reflector code.

1. The reflector will start a [watch loop](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L727-L730). Typically, it will receive an event (`ADDED | MODIFIED | DELETED`). Whenever it encounters an error, it will turn the object into a `Status` (complete with the error message). We can trace that through the [code linked above and the called functions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L122-L142).
2. The reflector is fundamentally responsible for doing watches; a watch is initialised with a `List`. The `List` will return an ItemList with a resourceVersion (e.g. a `PodList` with rv=20). A watch will have to be torn down every so often (for a variety of reasons). It will re-start itself with the last observed resourceVersion (can be the list if no events were observed, or the last observed resource). From there, any updates with a rv higher than the last rv will be observed.

Which brings me to the matter at hand. The watch is simply too old. The resourceVersion is no longer "known" by etcd. This is normal. The watcher hasn't observed any events (links don't experience high churn), and the last observed state is stale by etcd's standards. It will restart itself with a `List` and `Watch` and do the whole dance. I managed to trigger this myself in a day old cluster when attempting to list a resourceVersion:

`List`:
```
:; curl -s -H "Accept: application/json" "http://localhost:8001/api/v1/namespaces/kube-system/pods?&watch=1" | jq {'ev: .type, name: .object.
metadata.name, rv: .object.metadata.resourceVersion'}
{
  "ev": "ADDED",
  "name": "helm-install-traefik-jgj98",
  "rv": "752"
}
{
  "ev": "ADDED",
  "name": "helm-install-traefik-crd-9bvtv",
  "rv": "706"
}
{
  "ev": "ADDED",
  "name": "coredns-b96499967-nhmzv",
  "rv": "477"
}
{
  "ev": "ADDED",
  "name": "metrics-server-668d979685-wmkkk",
  "rv": "810"
}
{
  "ev": "ADDED",
  "name": "traefik-7cd4fcff68-klmc6",
  "rv": "836"
}
{
  "ev": "ADDED",
  "name": "local-path-provisioner-7b7dc8d6f5-2lpqc",
  "rv": "481"
}

```

`Watch`
```
:; curl -s -H "Accept: application/json" "http://localhost:8001/api/v1/namespaces/kube-system/pods?&watch=1&resourceVersion=481" | jq .
{
  "type": "ERROR",
  "object": {
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "too old resource version: 481 (2502)",
    "reason": "Expired",
    "code": 410
  }
}
```


Going through the `2.12` code, I did notice we have an issue that can cause panics.  If a Link watch is restarted, `loadCredentials` in the code below is fallible. We still attempt to restart the cluster watcher:

https://github.com/linkerd/linkerd2/blob/5b422851089832e411892f2f8994ca1eb658f346/multicluster/cmd/service-mirror/main.go#L125-L136

however, since credentials do not exist, no kubeconfig is parsed, so we exit. But not before signalling shutdown to the cluster watcher.

https://github.com/linkerd/linkerd2/blob/5b422851089832e411892f2f8994ca1eb658f346/multicluster/cmd/service-mirror/main.go#L180-L187

On the next iteration of the loop, regardless of the state of credentials, when we enter `restartClusterwatcher` we will close (e.g. send a unit) a closed channel. Writing on a closed channel panics. This has been fixed in 2.14 with the introduction of HA mode.

Will be closing this for now.
