### ISSUE TITLE
rfc: HA Control Plane

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1307]
## Components

- Prometheus
- Web
- Grafana
- tap
- proxy-api
- destination
- public-api

## Configuration

A flag at install time: `conduit install --ha`

## Monitoring

- Add `HA` to `conduit check`

**Comment by grampelberg** [comment]
Probably worth removing `--prometheus-replicas` from install to smooth some possible rough edges. See #454 for more discussion there.

**Comment by grampelberg** [comment]
We should also get a better handle on what HA really means for us. I'm concerned about providing too many knobs to users and hoping that we can get a "works for most folks" solution out of the box.

>  in particular, how the user schedules the pods of the control plane to be on separate nodes in different environments (especially GCP and AWS). 

This is actually something we can do right now pretty well via. anti-affinity. Past that we're going to start running into questions around multi-AZ and multi-region deployments.

**Comment by briansmith** [comment]
> We should also get a better handle on what HA really means for us.

Right, this is what I'm asking for.

> I'm concerned about providing too many knobs to users and hoping that we can get a "works for most folks" solution out of the box.

It would be nice. It's too early to tell without seeing more details of how it would work.

> This is actually something we can do right now pretty well via. anti-affinity. Past that we're going to start running into questions around multi-AZ and multi-region deployments.

We don't do any anti-affinity stuff now and we don't document how to do it. My understanding is that this RFC is basically supposed to become the specification for how to make anti-affinity and similar things work; i.e. what we need to implement in the code, and what we're going to document.

Also, if we can really do HA with just a boolean flag, then shouldn't the default value of the flag be "on"? In general we've been trying to make the defaults the right answer for most people's production use.

**Comment by grampelberg** [comment]
> Also, if we can really do HA with just a boolean flag, then shouldn't the default value of the flag be "on"? In general we've been trying to make the defaults the right answer for most people's production use.

Maybe this'll help us answer the question of what configuration means to begin with. I'd like to optimize for the *new* user, who will be on a resource constrained cluster (minikube) and not care about HA.

Theoretically, as we're just outputting YAML and letting kubectl do a patch, "upgrading" a control plane from non-HA to HA is pretty simple.

**Comment by briansmith** [comment]
> I'd like to optimize for the new user, who will be on a resource constrained cluster (minikube) and not care about HA.

Because the minikube user doesn't have lots of objects in the minikube cluster (I think this is a fair presumption) and low network traffic, and the control plane's resource consumption is mostly a function of the number of objects in the cluster (especially pods, especially proxy-injected pods) and the amount of traffic, I would hope the resource consumption difference wouldn't be considerably different with 3x (or whatever) the number of control plane pods. In particular, if we're eating a non-trivial amount of resources with a HA control plane in minikube then that's indicative that we wouldn't be able to scale to a moderately-high number of pods and a moderately-high amount of traffic. Regardless of that, I think that the HA configuration has to work pretty well in minikube because we want people to be able to evaluate the HA configuration in minikube if they want.

Also, if I evaluate linkerd2 in the default configuration, then any change I need to make to deploy it in production results in me needing to redo the evaluation. That seems really suboptimal to me in terms of workflow.

That said, we could start out with HA not being enabled by default while we develop it. I just think the end-state should be that the default does the right thing, if we've reduced things down to a single boolean flag.

**Comment by wmorgan** [comment]
After a brief experiment with @klingerf tonight, here's what I see as the current state:

if you kill the control plane, the proxies just keep working according to their old state. When the CP restarts, life returns to normal. However, any proxies that are started when the CP is down hang requests for 10s, then return a 500. As soon as the CP is back up, they start working normally.

Assuming that's true, I propose that we tackle this issue by 1) documenting the above behavior,  2) figuring out the right combination of Kubernetes's anti-affinity, disruption budget, etc features that increase the availability of the necessary control plane components, and 3) turning those features into some form of `--ha` flag.

**Comment by bourquep** [comment]
I am far from being an HA expert, but I feel like having the option to deploy the control plane as a DaemonSet would be a good and easy start which would address the most basic HA use case: make sure the control plane survives a killed node.

**Comment by klingerf** [comment]
The `--ha` flag was added in #1852. Am going to close this out.

**Comment by bourquep** [comment]
@klingerf Makes sense. Thanks for the feedback!

**Comment by grampelberg** [comment]
@klingerf do we have an issue open for configuring affinity? That's a great starter issue.

**Comment by klingerf** [comment]
@bourquep @grampelberg Ok cool, thanks for weighing in. I opened #1895 to track setting up anti-affinity.
