### ISSUE TITLE
tap filters

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1308]
Tap can be a little bit of a firehose. To help solve specific problems, I'd like to have some filters added so that (as a service owner), I can narrow down what's going wrong with my app specifically.

## Problems

- Some request is not successful.
- A response has a long latency.
- There is a bad actor sending requests.
- There is a bad downstream service.
- A specific path is being sketchy.

## Filters

```
Usage:
  conduit tap [flags] (RESOURCE)

Examples:
  conduit tap deploy/web --field-selector "status=200"

  conduit tap deploy/web --field-selector "latency>100ms"

  conduit tap deploy/web --field-selector "status=200,latency>100ms"

  conduit tap deploy/web --field-selector "src in (10.0.0.1,10.0.0.2)"

  conduit tap deploy/web --field-selector "dst!=deploy/voting"

  conduit tap deploy/web --field-selector "path~=VotePray"

Flags:
      --field-selector           
```

## Outstanding questions

- `--field-selector` is from k8s, but I'm not sure it works here. `filter` feels better
- `src in (10.0.0.1)` I'm not sold on needing set operations
- `status=200,latency>100ms` AND feels right, do we need OR as well?

## Prior Art

- See [label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) for the writeup on how kubernetes is handling it.
- Wireshark has [display filters](https://wiki.wireshark.org/DisplayFilters)

**Comment by briansmith** [comment]
I think it would be worth considering using wireshark capture filter syntax instead, and maybe other kinds of syntax. IMO the more this feature eventually becomes equivalent to a distributed wireshark, the more successful it will be. The k8s field selector syntax seems very limiting especially since it doesn't support `OR`.

**Comment by grampelberg** [comment]
Great call, the wireshark displayfilters look like they'd support most of the examples right out of the box as well.

**Comment by briansmith** [comment]
Note that there are display filters, read filters, and capture filters in tshark/wireshark/tcpdump, and this distinction matters as far as the UX is concerned, at least.

**Comment by briansmith** [comment]
Using Wireshark terminology, I think it would be better for the filters to be capture filters, where the filtering happens at capture time, inside the proxy, instead of display filters, which would happen in the CLI app, because that would be the most efficient. This should be answered early (in part to figure out who would be responsible for the implementation and who would be designing the implementation).

It would be useful to see what the MVP filtering functionality would be; i.e. what fields would we filter on, and which operators (`=`, `!=`, `AND`, `OR`, etc.) to support.

**Comment by grampelberg** [comment]
I'm onboard with doing capture filters to make this all more efficient. The biggest question in my mind is around implementation difficulty/complexity. Would it be possible to do this on the display side (eg. CLI) and move it back to the proxy over time? Interested to see if we have any large architecture dead ends based off this decision right now.

> It would be useful to see what the MVP filtering functionality would be; i.e. what fields would we filter on, and which operators (=, !=, AND, OR, etc.) to support.

As a straw man:

- Fields: status, latency, src, dst, path, protocol
- Operators: ==, !=, ~=, >, <, AND

**Comment by briansmith** [comment]
> Would it be possible to do this on the display side (eg. CLI) and move it back to the proxy over time? Interested to see if we have any large architecture dead ends based off this decision right now.

It would definitely be possible. I don't think it's any harder to implement it in the proxy than in the client and it's time-consuming enough to implement that we should try to avoid implementing it twice. Thus, I'd recommend starting with implementing it in the proxy because that's what makes sense long-term (why generate a bunch of network traffic and memory allocations for data that's going to get thrown away?).

**Comment by grampelberg** [comment]
That's exactly what I was wondering about. Perfect.

**Comment by grampelberg** [comment]
We're tackling this via pipes today. Once tap gets some more usage we'll be able to revisit (and create a more directed issue).
