### ISSUE TITLE
Remove ClusterRole requirements for control plane operation

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1336]
The goal is to allow installation of the control plane and operation of the data plane within a single namespace when the originating user does not have RBAC allowing the creation of ClusterRoles or ClusterRoleBindings.

## Open Questions

- Do we want global control planes?
- What should the default be?
- Should this be configuration based?
- How do we display that this control plane is not global?
- What are the TLS implications?

**Comment by briansmith** [comment]
> The goal is to allow installation of the control plane and operation of the data plane within a single namespace when the originating user does not have RBAC allowing the creation of ClusterRoles or ClusterRoleBindings.

The GKE documentation implies that one needs cluster-admin privileges to create `Role`s too, not just `ClusterRole`s. We should verify whether or not that's the case. If so, supporting a more restricted form won't make things easier because a cluster-admin would have to do the installation either way (at least for the RBAC objects).

Also, the proxy works much better when the control plane has "view" level permissions for pods and endpoints (and related things) so that load balancing works better. If the creation of the linkerd-controller `ClusterRole` for this is actually a problem, but creating `ClusterRoleBinding`s is OK, we could instead create a `ClusterRoleBinding` for the system view role, which is a superset of the functionality required.

> Should this be configuration based?

If we're going to support multiple modes, one where the control plane is restricted to managing things in its own namespace so that fewer permissions are required, and another where a control plane can manage things outside its own namespace (the current default), then we need some configuration mechanism for this at `conduit install` time. Also we'd need to document how to switch from one mode to the other, especially how to switch from the one-namespace mode to the multi-namespace mode.

> What are the TLS implications?

It depends on whether it is actually easier for users to manage `Role`s and `RoleBinding`s vs. `ClusterRole`s and `ClusterRoleBinding`s. If creating `Role`s and `RoleBinding`s requires fewer permissions than `ClusterRole`s and people would normally have such permissions but not have the `ClusterRole` related permissions, then we can perfectly scope the `RoleBinding`s to the `Secret`s and `ConfigMap`s needed. If creating `Role`s and `RoleBinding`s is something only cluster admins can do then we'd need to make some difficult choices about the UX and the convenience vs. principle of least privilege trade-offs.

So, the first order of business, from my point of view, is finding out whether users who can create `Role`s and `RoleBinding` but who can't create `ClusterRole`s and `ClusterRoleBinding`s actually exist.

**Comment by grampelberg** [comment]
> So, the first order of business, from my point of view, is finding out whether users who can create Roles and RoleBinding but who can't create ClusterRoles and ClusterRoleBindings actually exist.

I'm working at getting some real world data on this one still, but in the mean time I tested it on a GKE cluster. By creating a `RoleBinding` to the `ClusterRole` for `admin`, I have a user that can do anything within a namespace (including create `Role`s and `RoleBinding`s) but has no access to anything else in the cluster.

**Comment by briansmith** [comment]
> By creating a RoleBinding to the ClusterRole for admin, I have a user that can do anything within a namespace (including create Roles and RoleBindings) but has no access to anything else in the cluster.

That's good news! I guess the next step is to find out how often cluster administrators grant `admin` access at the namespace level to the team responsible for that namespace.

**Comment by grampelberg** [comment]
@klingerf this is taken care of by `--single-namespace` right?

**Comment by klingerf** [comment]
Yep! This was fixed by #1721, #1974, and #1980.
