### ISSUE TITLE
proxy process_cpu_seconds_total is too coarse to be useful

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1384]
The proxy does not seem to export a value for process_cpu_seconds_total.

On a prometheus pod that has been running for ~10 minutes, I see:
```
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0
```

This seems likely to be related to https://github.com/linkerd/linkerd2-proxy/pull/7

**Comment by olix0r** [comment]
Will leave this running overnight to see if the value changes.

**Comment by olix0r** [comment]
This value does change...

```
:; kubectl get po -n linkerd |grep prom 
prometheus-786669fdf5-7k82d   2/2       Running   0          12h
#; golly ~ 
:; kubectl exec -c linkerd-proxy -n linkerd prometheus-786669fdf5-7k82d -- curl -s localhost:4191/metrics |grep ^process_cpu
process_cpu_seconds_total 53
```

So, in ~12 hours the proxy uses less than a minute of CPU time?  This seems plausible (though it seems plausible to me this is inaccurate, too).

In any case `_seconds` seems to be far too coarse of a unit for this metric. I know we cargo-culted this from the Go library. Can anyone offer a good reason that this should not be tracked in _msec?

**Comment by hawkw** [comment]
@olix0r 
> In any case `_seconds` seems to be far too coarse of a unit for this metric. I know we cargo-culted this from the Go library. Can anyone offer a good reason that this should not be tracked in `_msec`?

We expose this metric with this precision because [the Prometheus documentation](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics) defines it as "standard" (which is why the Go library also exports it).

I agree that seconds seems like insufficient precision for this stat. Perhaps we ought to also expose a higher-precision CPU time metric? I'd prefer not to remove any metrics that Prometheus considers conventional...

**Comment by hawkw** [comment]
I think this may still be worth looking into? @olix0r WDYT?

**Comment by olix0r** [comment]
Hypothetically, yes. Practically, no.
