### ISSUE TITLE
Some h1 calls from web to controller failing

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1404]
It appears that a change introduced in linkerd/linkerd2-proxy#32 is causing some h1 calls from the control plane's web pod to the controller pod to fail.

In the web container in the web pod, I see:

```
2018-08-04T00:16:51.374119301Z time="2018-08-04T00:16:51Z" level=error msg="error reading byte stream header: error while reading message length: EOF"
```

In the linkerd-proxy container in the web pod, I see:

```
2018-08-04T00:16:51.373642566Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.9:41668} linkerd2_proxy turning Error caused by underlying HTTP/2 error: protocol error: stream no longer needed into 500
```

I don't see any error logs in the controller pod, but in the web UI, I see:

![image](https://user-images.githubusercontent.com/9226/43670544-b22fa344-9741-11e8-810e-3848a9f0a449.png)

The failing call is to `/api/tps-reports?resource_type=all&all_namespaces=true&window=1m`, and the error response is:

```
{
"error": "error reading byte stream header: error while reading message length: EOF"
}
```

If I roll back linkerd/linkerd2-proxy#32, the error goes away.

**Comment by seanmonstar** [comment]
As an update on investigating the cause: HTTP/1.1 requests or responses that are streaming their body, by setting `transfer-encoding: chunked`, are failing. This is due to the proxy stripping the `transfer-encoding` header in the translation to HTTP2 (because transfer-encoding is illegal there), and then not putting it back when translating back to HTTP/1.1.
