### ISSUE TITLE
Kubernetes like navigation in the GUI

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1449]
The CLI does a pretty good job of matching the k8s experience. The GUI should be updated to mirror the k8s dashboard navigation as well as the look and feel. This primarily includes:

- Move the namespaces from a list in the sidebar to a dropdown selector
- Move the resource types (deployments, daemonsets) to the top level
- Show actual resources in the sidebar

**Comment by zachalbert** [comment]
This is the current iteration of the sidebar navigation, which currently mirrors k8s look and feel. The visual design needs more work, but the content should be solid.

![image](https://user-images.githubusercontent.com/2305040/44130169-fb584f90-a000-11e8-8b7c-bbcaf1209110.png)

**Comment by rmars** [comment]
TBD
- what criteria do we use to colour the dot red/yellow/green
- what to do with unmeshed resources?

**Comment by admc** [comment]
@zachalbert @dadjeibaah @rmars It looks like we need some additional UX thinking (maybe it exists and I missed it), around what happens if a section is expanded but it has so many items that they expand out of the viewport. We also have some overlapping components that don't look great in that case.
![screen shot 2018-08-21 at 4 39 51 pm](https://user-images.githubusercontent.com/5144/44434594-df80be00-a560-11e8-85fc-e39485024100.png)

**Comment by grampelberg** [comment]
> do you have any opinions about the sidebar being collapsible?

I like the idea of emulating the k8s dashboard around hiding the sidebar:

![](http://g.recordit.co/diSYqNlXBa.gif)

> what criteria do we use to colour the dot red/yellow/green

For now, let's use success rates for the colors, any ideas on what the limits should be? As something to get the discussion started:

- green: 100%
- yellow: 51-99%
- red: <51%

> what to do with unmeshed resources?

Let's actively not show them in the sidebar. I've seen a mockup floating around that has them on the namespace detail page and that feels like a good spot for it. Ideally, the things in the sidebar are *your* things which should be meshed.

> what happens if a section is expanded but it has so many items that they expand out of the viewport

Personally, I would prefer to show the full list of items with only a couple sections open by default (show deployments, hide pods for example). If we're limiting this to the namespace selector by default and only showing meshed resources, the number of items should be small for now.

I don't get a ton of value from the social links (or most of that footer) in the sidebar. Maybe we could move them elsewhere? The "right" way for the sidebar to act would be via. scrolling independently from the main view. For now, we could pin the social links to the bottom, make its background opaque and have the sidebar scroll independently.

**Comment by grampelberg** [comment]
> what are folks thoughts about having the sidebar and the future breadcrumb bar be fixed on the dashboard and allow the content to be scrollable?

- Sidebar should be fixed with scrollable content (see comment above)
- Breadcrumb feels like it should be in the main content pane and *not* fixed for now. It'd be great if we could make it fixed, but I'm a little uncomfortable about the styles and making sure it all feels right together. When we update the headers/nav bars to more closely match the aspirational mockups, that'd be a good time to fix the breadcrumb in place.

**Comment by dadjeibaah** [comment]
> For now, let's use success rates for the colors, any ideas on what the limits should be? As something to get the discussion started:

We should already have criteria for this somewhere in one of the resource pages so, we could replicate the same idea into the sidebar.

> Let's actively not show them in the sidebar. I've seen a mockup floating around that has them on the namespace detail page, and that feels like a good spot for it. Ideally, the things in the sidebar are your things which should be meshed.

I was on the fence about this one. Initially, I thought we could use the colored dots to indicate something that wasn't meshed i.e. a gray dot instead of red, yellow, green. However, I like the idea of not including them as that reduces the number of resources a user has to see therefore reducing clutter.
