### ISSUE TITLE
Tap sampling is windowed and that is odd

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1525]
When using the tap defaults against emojivoto/web, I don't see a stream of requests (instead a bucket every 10s). It is a little odd to see 10 requests come in all at once via. tap even though they were evenly spread throughout the 10s window.

Assuming a `--max-rps 1`, I would expect to see a single request immediately with any others in that one second bucket suppressed.

**Comment by adleong** [comment]
I tried to solve this by simply reducing the window size down to 1 second.  This means that if `--max-rps 1` is set then the controller should send a tap request to the proxy with `limit=1` once per second.

This fixed the issue of the updates bunching up but revealed some other weirdness.  Namely, when we send a tap request to the proxy with `limit=1` we always get back the same request type.  In the emojivoto example it is this inbound request to /api/list:

```
req id=0:3206 proxy=in  src=10.233.66.179:50114 dst=10.233.66.177:80 tls=disabled :method=GET :authority=web-svc.emojivoto:80 :path=/api/list
rsp id=0:3206 proxy=in  src=10.233.66.179:50114 dst=10.233.66.177:80 tls=disabled :status=200 latency=2539µs
end id=0:3206 proxy=in  src=10.233.66.179:50114 dst=10.233.66.177:80 tls=disabled duration=244µs response-length=4558B
```

I find it surprising that we always get back this request (and never, for example, any outbound requests or any requests to other paths).  I would expect that we should get a random request depending on the exact timing of the tap request and which request the proxy happens to be processing at that point, which should lead to a random sampling of all requests going through the proxy.

@olix0r is this an expected behavior of the proxy when the limit is small?  Do the proxy telemetry refactors influence this?
