### ISSUE TITLE
Increase `--wait` timeout

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1586]
When doing an install locally with no images cached, `linkerd check --wait` times out (and fails). Could the timeout be extended some?

**Comment by grampelberg** [comment]
@klingerf what do you think?

**Comment by klingerf** [comment]
@grampelberg For sure. What would be an appropriate timeout? Right now it's 50 seconds. 90 seconds?

**Comment by grampelberg** [comment]
How about 300s? 5 minutes feels like the point where it'll either have worked or die, even on a slow connection.

**Comment by klingerf** [comment]
@grampelberg Works for me.

**Comment by klingerf** [comment]
@alenkacz, thanks for offering to help with this! Per @olix0r's comment in #1640, it would be great for the `--wait` flag to specify a duration to wait fo the checks to succeed, and default the flag to 300s. 

From an implementation standpoint, I think we should modify the flag type in `cmd/cli`, and then modify the `healthcheck.HealthCheckOptions` struct to support a `RetryDeadline` field, instead of the existing `ShouldRetry` field. We can set the value of `RetryDeadline` using the value of the `--wait` flag. I'm picturing something like:

```diff
@@ -88,7 +89,7 @@ func configureAndRunChecks(options *checkOptions) {
                KubeConfig:                     kubeconfigPath,
                APIAddr:                        apiAddr,
                VersionOverride:                options.versionOverride,
-               ShouldRetry:                    options.wait,
+               RetryDeadline:                  time.Now().Add(options.wait),
                ShouldCheckKubeVersion:         true,
                ShouldCheckControlPlaneVersion: !(options.preInstallOnly || options.dataPlaneOnly),
                ShouldCheckDataPlaneVersion:    options.dataPlaneOnly,
```

When performing the checks in `healthcheck.go`, instead of checking if `maxRetries` has been exceeded, we can instead check if the current time is before the deadline. Something like:

```diff
@@ -378,11 +377,6 @@ func (hc *HealthChecker) RunChecks(observer checkObserver) bool {
 }
 
 func (hc *HealthChecker) runCheck(c *checker, observer checkObserver) bool {
-       var retries int
-       if c.retry {
-               retries = maxRetries
-       }
-
        for {
                err := c.check()
                checkResult := &CheckResult{
@@ -391,8 +385,7 @@ func (hc *HealthChecker) runCheck(c *checker, observer checkObserver) bool {
                        Err:         err,
                }
 
-               if err != nil && retries > 0 {
-                       retries--
+               if err != nil && c.retry && time.Now().Before(hc.RetryDeadline) {
                        checkResult.Retry = true
                        observer(checkResult)
                        time.Sleep(retryWindow)
```

Note that in order to do this, we'd need to explicitly set `retry: true` on all retryable checks, instead of `retry: hc.ShouldRetry`, as it's currently written.

**Comment by klingerf** [comment]
@alenkacz Also, just a heads up that I opened #1645 to bump the hardcoded retry duration that we have now. Switching to a duration flag will be a great improvement, but I just wanted to make sure we bumped up the existing duration prior to the next release.
