### ISSUE TITLE
Seconds long TLS request times on larger Ruby on Rails apps

### ISSUE THREAD

**Issue by zparnold** [linkerd/linkerd2#1648]
Hi there, I'm not quite sure what degugging details could help with an issue like this but...we're having issues turning on the TLS feature of linkerd2 due in large part to the amount of time it takes to complete a request. We have a RoR app running as a LoadBalanced deployment (behind a service) in Kubernetes 1.10. We currently terminate SSL at the ELB level and it travels over the Amazon CNI (EKS) to our deployment presumably over `http` to the running pods inside of a namespace. We have linkerd2 deployed to the _same_ namespace as this deployment. I'm not sure what we're doing wrong but it seems that traffic has slowed to a crawl. It takes about 30 seconds to have a page load (compared with the normal 2-3). These metrics don't seem to show up on the linkerd dashboard, but they are the latencies our users faced.

**Comment by klingerf** [comment]
I'm also seeing this issue (or something similar), when trying to run a [Ruby demo app](https://github.com/BuoyantIO/booksapp) with TLS enabled.

In my docker-for-desktop env, if I deploy linkerd and the books app without TLS enabled everything works:

```
linkerd install | kubectl apply -f -
linkerd check
kubectl create ns booksapp
curl https://run.linkerd.io/booksapp.yml | linkerd inject - | kubectl apply -n booksapp -f -
linkerd check --proxy -n booksapp
sleep 45 && open http://localhost:7000
```

That successfully loads the app running on port 7000.

Whereas if I enable TLS, the mysql-init pod never finishes.

```
linkerd install --tls optional -l linkerd-tls | kubectl apply -f -
linkerd check -l linkerd-tls
kubectl create ns booksapp-tls
curl https://run.linkerd.io/booksapp.yml | linkerd inject --tls optional -l linkerd-tls - | kubectl apply -n booksapp-tls -f -
linkerd check --proxy -n booksapp-tls -l linkerd-tls
```

That passes, but none of the pods enter the ready state, since the mysql-init pod runs forever:

```
$ kubectl -n booksapp-tls get po
NAME                       READY     STATUS    RESTARTS   AGE
authors-6644bc54bf-5rf7m   1/2       Running   0          1m
authors-6644bc54bf-7ftj8   1/2       Running   0          1m
authors-6644bc54bf-lpnj8   1/2       Running   0          1m
books-99f46946c-7llvb      1/2       Running   0          1m
books-99f46946c-djbjs      1/2       Running   0          1m
books-99f46946c-jsldn      1/2       Running   0          1m
mysql-54768d9fbf-8mxgl     2/2       Running   0          1m
mysql-init-zbh75           2/2       Running   0          1m
traffic-7498b669fc-5jbmq   2/2       Running   0          1m
webapp-64665d97c4-6ww8z    1/2       Running   0          1m
webapp-64665d97c4-q795q    1/2       Running   0          1m
webapp-64665d97c4-zdnvd    1/2       Running   0          1m
```

The mysql-init pod appears to be stuck on this line:

```
require 'sinatra/activerecord'
```

Which makes an outbound connection to the mysql database.

In the linkerd-proxy logs for that pod, I see:

```
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.1.21.89:55038} linkerd2_proxy::proxy::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
```

**Comment by hawkw** [comment]
@klingerf I think I know why the `booksapp` demo doesn't work with TLS. When TLS is enabled, the inbound proxy tries to detect an incoming TLS handshake _before_ performing protocol detection, regardless of whether or not protocol detection is enabled for that port. Since MySQL is a server-speaks-first protocol, the inbound proxy for the `mysql` pod never receives any bytes to peek for the handshake. 

I'm not sure if there's an easy fix for this --- ideally, we would just proxy this traffic over TLS, but in the current implementation, we only establish TLS connections to destinations for which we have metadata provided by the control plane. Since the connection to MySQL isn't HTTP, we proxy it as raw TCP and don't perform a destination lookup, so the proxy has no way of knowing the TLS identity of the MySQL pod.
