### ISSUE TITLE
use port-forward for linkerd dashboard

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1696]
The `linkerd dashboard` command uses a kubernetes proxy to allow the user to connect from their laptop to the Linkerd dashboard and Grafana.

Instead, port-forward from the user's machine. This has several advantages:
- simple tcp forwarding vs. http proxy
- kubernetes proxy inspects and rewrites http
- Linkerd dashboard and Grafana may be served at `localhost:1234/` root, rather than a long proxy URL, this would help solve the `root_url` Grafana issue discussed in #1692

**Comment by olix0r** [comment]
Part of the goal for using a proxy to the API master is to leverage the TLS infrastructure between the CLI and kubernetes master. If we're going to pursue this, we'll need to ensure that we can secure the connection to the control plane.

**Comment by grampelberg** [comment]
I'm pretty sure that proxy -> api server uses the same TLS infrastructure. The api server -> control plane connection, however, would be a different beast.

**Comment by olix0r** [comment]
I believe @briansmith has plans for securing the connection between the K8S API server and the control plane.  My point is, we shouldn't change this without understanding how the change impacts the TLS plan.

**Comment by grampelberg** [comment]
@briansmith any insight? What would we lose by going to port-forward instead of proxy?

**Comment by briansmith** [comment]
> * simple tcp forwarding vs. http proxy
> * kubernetes proxy inspects and rewrites http

What problems are we running into where the above two points are problematic? I'm not sure we can do anything that depends on there not being an HTTP proxy between us and the dashboard because some networking configurations might insert HTTP proxies (e.g. anti-virus) that we can't control or avoid.

> * Linkerd dashboard and Grafana may be served at `localhost:1234/` root, rather than a long proxy URL, this would help solve the `root_url` Grafana issue discussed in #1692

Like I mentioned in #1692, the main reason we use the k8s proxy and the reason why we have/had plans to expose the control plane as a k8s API extension server is so that we can integrate with the k8s security mechanisms for authentication and authorizing access to the control plane. That is, k8s currently ensures that our control plane is only accessed from within the cluster and/or by authenticated users from outside the cluster. IIUC, supporting the use of just a simple port forward would disable these security protections.

**Comment by grampelberg** [comment]
> IIUC, supporting the use of just a simple port forward would disable these security protections.

Digging through the RBAC documentation, there is the same RBAC protection for `port-forward` that there is for `proxy` inside of the set that we're using today. The difference is that you can also block by HTTP method for `proxy`.

(Man it is hard to figure out what endpoints do and don't work with RBAC, shame on you k8s)

**Comment by briansmith** [comment]
OK, so you're saying that the port forwarding would be the kind done by the k8s API server. AFAICT, that would still require that `linkerd dashboard` be run though, to establish the port forwarding.

Also, does port forwarding require `socat` to be installed locally? See https://prefetch.net/blog/2018/02/03/how-the-kubectl-port-forward-command-works/. FWIW, `socat` isn't installed on any of my systems I have `kubectl` on (I'm not using macOS; I use Ubuntu and Windows).

**Comment by grampelberg** [comment]
Yeah! This issue is totally separate from #1692. There's an odd lingering websocket issue we think would get fixed (and I can't seem to find the issue). Joe brought it up during TGIK8s, mentioning that we'd have an easier time of things by using `portforward` and that is what kicked this specific issue off.

> Also, does port forwarding require socat to be installed locally?

Reading through that article, I'm under the impression that it is the kubelet that needs `socat` and not your local host. But, do you mind testing? `portforward` is how helm exposes tiller, just do an install and see if you can get any releases (or, check out ksync where I do the same thing).

**Comment by sudermanjr** [comment]
I just ran into a need for this on a private GKE cluster that uses a google Cloud NAT gateway.  I can port-forward and see the dashboard, but going through kubectl proxy doesn't work at all.

**Comment by klingerf** [comment]
@grampelberg mentioned that as part of this change we should start checking that the user has access to the "pods/portforward" RBAC resource when running `linkerd check --pre`. Note that we're not currently checking that the user has access to the "services/proxy" resource, even though that's required for the existing proxy approach that we're using.

**Comment by adleong** [comment]
Sorry to comment on a long closed issue but I have a couple questions about these bullet points:

* simple tcp forwarding vs. http proxy
* kubernetes proxy inspects and rewrites http

What is undesirable about the kubernetes api server being an http proxy?  Does it do some undesirable behavior?

**Comment by grampelberg** [comment]
@adleong nothing specifically, there have been bugs and undesirable behavior in the past that I can't remember specific issues for right now ....
