### ISSUE TITLE
Destination.GetProfile should serve a default profile

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1795]
When a client tries to resolve a service profile for a name that does not have an explicitly configured profile, the destination service should return a default profile so that the stream may be updated if a profile is created after the initial observation is attempted.

This will simplify the client logic with regards to re-establishing profile watches.

**Comment by adleong** [comment]
My thinking here is that the client must already have a default profile that it uses when the destination service is not reachable.  Since that is case, it would be nice to maintain the default profile in just one place (the client) instead of two (the client and the server).  However, since the default is basically an empty route list, maybe this is a non-issue.

I'm unclear on why the current API behavior makes re-establishing profile watches difficult, though.

**Comment by olix0r** [comment]
This was reported when the proxy-api was returning immediately without a response. I think this can be closed now that the controller properly responds with a stream.
