### ISSUE TITLE
single-namespace should take a namespace argument

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#1849]
I don't think there's a valid reason for `--single-namespace` to be used without `--linkerd-namespace`. Having seen users get confused by the relationship between these two commands, I propose that `--single-namespace` take a mandatory namespace argument so that it can be used without having to also specify `--linkerd-namespace`.

(And possibly we error out if --linkerd-namespace is also specified, or is specified with a different value.)

**Comment by klingerf** [comment]
As an additional bullet point, based on feedback from #1847, we might also want to consider:

* Update `linkerd install --single-namespace foo` to stop including a YAML configuration for the "serviceprofiles.linkerd.io" custom resource definition, since users who are locked down to a single namespace probably can't create new CRDs at the cluster level

**Comment by klingerf** [comment]
All of the other changes that I described in my previous comment have been made, but I held off on modifying the `--single-namespace` flag to override the `--linkerd-namespace` flag, as described in the initial description for this issue.

The `--single-namespace` flag only applies when running `linkerd check` and `linkerd install`, whereas the `--linkerd-namespace` flag applies globally to all commands. So it feels a bit weird to me to override a global flag for just the `install` and `check` commands, but not provide that flag for the rest of the commands. Maybe we could just rename the existing boolean flag to make it clearer what it actually does?

**Comment by olix0r** [comment]
The single-namespace flag has been removed, which simplifies this.
