### ISSUE TITLE
Flexible auto-injector targeting

### ISSUE THREAD

**Issue by hypnoglow** [linkerd/linkerd2#1862]
## Feature Request

I propose to consider more flexible auto-injector targeting. 

Auto-injecting is an awesome feature, but we want to have more control over it. For example, we want to auto-inject only for namespaces **a** and **b** without labeling all other existing and future namespaces with `linkerd.io/auto-inject: disabled`. And in addition, to have even more granular control, we may also want to require an explicit annotation on the pod template like `linkerd.io/auto-inject: enabled`.

Maybe we can add support for additional flags for **install** command that will enable auto-injection only on explicitly annotated namespaces and pods.

As discussed per https://github.com/linkerd/linkerd2/issues/1820#issuecomment-438066895

**Comment by klingerf** [comment]
Great, thanks for opening this @hypnoglow! It seems reasonable to me to add a new boolean install flag to make the auto-inject behavior opt-in or opt-out, and default to opt-out. Then you could opt-in namespaces or pod specs by adding the `linkerd.io/auto-inject: enabled` annotation, as you describe.

**Comment by monkeymorgan** [comment]
I'm evaluating istio and linkerd2 for use in multi tenant k8s clusters and I would also argue that it should be possible to configure linkerd2 to have auto-inject feature on but only for namespaces that opt-in. Having to explicitly opt-out is not ideal, since we have existing high value tenants and do not wish to effect their workloads or namespaces in any way.

**Comment by wmorgan** [comment]
Yep, this is a good idea. It's marked as a P1 currently on the roadmap, but might be a good first issue if you want to take a crack at a PR. 😄
