### ISSUE TITLE
Fresh install of linkerd2 with auto-injector doesn't start

### ISSUE THREAD

**Issue by JonathanBennett** [linkerd/linkerd2#1961]
### What is the issue?
Upon a fresh install of Linkerd2 (on Client version: edge-18.12.2 Server version: edge-18.12.2) the proxy-injector pod never starts and so auto-injection doesn't function. Other parts of Linkerd2 start unaffected.

### How can it be reproduced?
Installing edge-18.12.2 on Kubernetes version v1.10.11-eks (Amazon EKS)

### Logs, error output, etc

Linkerd check output:

`The "linkerd-proxy-injector" pod's "proxy-injector" container is not ready`.

Inside the container the same repeated error:

 `time="2018-12-07T16:02:23Z" level=info msg="mount not ready: /var/linkerd-io/identity/certificate.crt"`

#### `linkerd check` output

```kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[retry] -- The "linkerd-proxy-injector" pod's "proxy-injector" container is not ready
linkerd-api: control plane pods are ready..................................[retry] -- The "linkerd-proxy-injector" pod's "proxy-injector" container is not ready
...
```

### Environment

- Kubernetes Version: 1.10.11
- Cluster Environment: (GKE, AKS, kops, ...) Amazon EKS
- Host OS: EKS AMI
- Linkerd version: edge-18.12.2

**Comment by ihcsim** [comment]
Is there a secret named `linkerd-proxy-injector-service-tls-linkerd-io` in your Linkerd namespace? Also, can you check the CA controller logs for errors? Normally, when the mutating webhook configuration is created, ([iirc](https://github.com/linkerd/linkerd2/blob/692c4ca75b4a7a54fab6737d83fc353de1621b1e/controller/ca/controller.go#L187-L195)) the CA controller should create the secret, containing the TLS cert. The proxy-injector pod will then mount the secret to `/var/linkerd-io/identity/`.

**Comment by klingerf** [comment]
Hey @JonathanBennett, thanks for reporting this. I read the scrollback in slack, and I think you're running into an issue with the rename that happened in #1920. You mentioned that you're fully uninstalling linkerd in your cluster with:

```
linkerd install --tls optional --proxy-auto-inject | kubectl delete -f -
```

That's the right approach, but it doesn't delete the mutatingwebhookconfiguration that handles auto-inject, since that object is created after install by the proxy-injector pod. And the service name that's referenced in the mwc changed in the latest release. So if you had an old one hanging around, I suspect that's what causing problems. 

To fix, can you run the delete command above and then additional run:

```
kubectl delete mutatingwebhookconfigurations/linkerd-proxy-injector-webhook-config
```

And then try reinstalling to see if the proxy-injector pod is able to start successfully?

**Comment by grampelberg** [comment]
@klingerf does that mean we need to update the upgrade instructions a little?

**Comment by klingerf** [comment]
@grampelberg Good call -- I opened linkerd/website#82 for the docs change.

**Comment by JonathanBennett** [comment]
Thanks for the info @klingerf (and @grampelberg and @ihcsim) - Just to confirm that deleting the mwc did indeed allow the project to successfully deploy, but auto-injector doesn't appear to be working.

As this solved my issue I'll mark this as closed, and open another issue if I see something specific about the auto-injector.

Cheers all.
