### ISSUE TITLE
Wire up stats and dashboards for StatefulSets

### ISSUE THREAD

**Issue by robertrbruno** [linkerd/linkerd2#1983]
I saw in the issue for adding injection of StatefulSets mention of Grafana support, but didn't see an issue for it yet.  Sorry if this is a repeat.

**Comment by klingerf** [comment]
@robertrbruno Thanks for opening this! When wiring up stats originally we only got through a subset of Kubernetes workloads for which we can provide stats -- see #627 for more details about that. Unfortunately we never made it to statefulsets, but we can use this issue to track adding CLI / Web UI / Grafana support for them.

**Comment by klingerf** [comment]
Just wanted to add a bit more context here. Setting up stat support for StatefulSets will be very similar to PR #2086, which added stat support for DaemonSets.

The `statefulset` label already exists in our Prometheus metrics, so this should not require any proxy changes. We'll need a new Grafana dashboard that displays these stats. We'll also want to update the `linkerd stat`, `linkerd tap`, and `linkerd top` commands to support the resource, which will require some changes to the public-api and tap servers, and we'll want to start displaying StatefulSet data in the web UI.

**Comment by ihcsim** [comment]
@grampelberg It looks like at the moment, we aren't capturing any metrics for non-http stateful applications. The dashboard, CLI and grafana all show zero metrics. The pods don't even show up in grafana, as seen in the screenshots below. @klingerf mentioned that this happens because when the protocol detection failed, the proxy won't call `proxy-api` and hence, it receives no metadata including the pod name.

![image](https://user-images.githubusercontent.com/1330522/52390062-59dbc680-2a4b-11e9-9dd3-100eae4d332b.png)

![image](https://user-images.githubusercontent.com/1330522/52390103-81329380-2a4b-11e9-8777-5c2be1be71cb.png)

@klingerf and I discussed about whether it is worth continuing with this issue at this point, as it might confuse some users, seeing that the meshed statefulsets appeared, but have no data any where.

WDYT?

**Comment by ihcsim** [comment]
Relevant #2224.

**Comment by grampelberg** [comment]
Also, #2223.
