### ISSUE TITLE
remove proxy bind timeout

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2013]
The bind timeout currently does not constrain discovery, but is effectively an outbound response timeout.

With https://github.com/linkerd/linkerd2-proxy/pull/165, we have user-configurable response timeouts.

Let's remove the bind timeout entirely and figure out proper service discovery semantics separately.

**Comment by olix0r** [comment]
the CLI will also need to change to remove this option from install/inject

**Comment by hawkw** [comment]
@olix0r as far as removing the CLI options for the bind timeout goes, do you think we should continue to accept those flags and _warn_ the user that they no longer do anything (and remove them from the docs), or completely remove them so that invoking install or inject with `--proxy-bind-timeout` will _fail_? 

I'm wondering if a "soft" removal (the former option) might be a better choice to avoid breaking anyone's existing scripts etc. Also, if we eventually re-introduce a timeout that _does_ constrain discovery rather than outbound responses, we might want to re-use the `--proxy-bind-timeout` flag and/or env var, so temporarily breaking and then re-adding them might not be ideal. What do you think is the proper UX around this?

**Comment by olix0r** [comment]
I think it would be especially confusing if we change the semantics of an existing flag later.

I think I'm mostly in favor of removing the flag now that we'll have timeouts in service profiles; so that, if we do choose to add the flag later, existing scripts won't have the semantics changed out from nder them.

If we feel it's important to deprecate this incrementally, that's an option; though it may not be worth it. cc @grampelberg

**Comment by grampelberg** [comment]
I'm behind a hard failure, we can document why it changed if folks ask. My suspicion is that it won't be an issue for something like this.

**Comment by hawkw** [comment]
Okay, that makes sense to me, thanks for the input.

**Comment by olix0r** [comment]
FWIW, It does look like the bind timeout is at least in-part removed in https://github.com/linkerd/linkerd2-proxy/pull/165 (I hadn't looked at the PR closely before opening this).

**Comment by hawkw** [comment]
@olix0r ah, in that case, I'll just look at that branch and make sure it's completely removed, I suppose.

I've opened #2017 to remove the `--proxy-bind-timeout` flag from `install` and `inject`.

**Comment by seanmonstar** [comment]
The support in the proxy was just removed, though this may wish to track the CLI options also?

**Comment by grampelberg** [comment]
I'm fine addressing it in the changelog.
