### ISSUE TITLE
proxy: Make inbound servers aware of client identities

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2126]
Once https://github.com/linkerd/linkerd2/issues/2125 is complete:
1. we need tests that validate that the server properly validates the client's authenticator (i.e. that it can be verified with the trust chain)
2. the client id should be included in the TLS status, as noted on inbound server metrics
3. the client id should be included in inbound tap events.
4. A `l5d-client-id` header should be added (similar to [`l5d-server-id`](https://github.com/linkerd/linkerd2/issues/2124))

**Comment by seanmonstar** [comment]
In order to provide this, we want to grab a verified SAN from the client certificate. As of today, there's two ways we could do this, but both will require additional work outside the proxy:

1. Add the necessary API to [webpki to get the verified DNS names](https://github.com/briansmith/webpki/issues/64). This is because there's otherwise no way to get the SAN from the `rustls::Certificate`. There's an in-progress PR, but [it seems to have stalled](https://github.com/briansmith/webpki/pull/65).
2. Add a way for the inbound proxy to get a list of all `TlsIdentity`s that the controller knows about. This would allow us to use `webpki::EndEntityCerty::verify_is_valid_for_dns_name`, but we'd need to supply the DNS name, and iterate through a list.

**Comment by seanmonstar** [comment]
PR for webpki filed: https://github.com/briansmith/webpki/pull/91
