### ISSUE TITLE
Introspect current service discovery

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2165]
### What problem are you trying to solve?

There is a set of problems (see #1595 for example) where the visible state of a workload in k8s differs from what appears to be happening on the linkerd side. It can be particularly frustrating to debug this set of problems because of where all the information lives.

### How should the problem be solved?

Introduce a new CLI command:

```
$ linkerd -n emojivoto endpoints web
IP         PORT  POD                   VERSION WEIGHT IDENTITY
10.0.0.1   8080  web-6c6f6dbf44-9qjst  41519   10     web.deployment
10.0.0.2   8080  web-6c6f6dbf44-abcde  41519   10     web.deployment
10.0.0.3   8080  web-6c6f6dbf44-12345  41519   10     web.deployment
```

During an update, the versions would change during the rollout. 

Some other nice additions:

- Show the parents (replicaset, deployment) and their versions.
- Show both endpoints in k8s *and* endpoints from discovery. For any disagreements, show the source as a new column.

### Any alternatives you've considered?

```
$ linkerd check
endpoints
----------
√ is in sync with the kubernetes api
```

It'd be nice to have both, but the detailed visibility is more important.

**Comment by hawkw** [comment]
It would be nice if there was similar tooling for inspecting the service discovery state of a particular proxy, so that failures can be diagnosed by comparing the state of a proxy with the state as seen by the control plane and as seen by the k8s API. 

That's probably out of scope for this particular ticket but it seems worth mentioning.
