### ISSUE TITLE
move off the scratch Docker image as a base for the control plane

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2167]
## Current State

The Linkerd controller Docker image uses scratch as a base image:
https://github.com/linkerd/linkerd2/blob/872e1bb0262d47a5f65bde43cbf9e26f5fc6d4ec/controller/Dockerfile#L13

This approach ensures a maximally-streamlined Docker image, at the expense of tooling and/or shell access for debugging.

The linkerd2-proxy uses `gcr.io/linkerd-io/base` as a base image:
https://github.com/linkerd/linkerd2-proxy/blob/edd124fa9fac493c8c9f63209267d35f5fb2246b/Dockerfile#L11

...which in turn uses `debian:jessie-slim` as a base image, and includes `curl`, `jq`, `nghttp2`, and other useful tools:
https://github.com/linkerd/linkerd2/blob/e5cce1abaf36ad297c7aae1cc5ea08aade90dd42/Dockerfile-base#L10

## Proposal

Modify the Linkerd controller Docker image to use `gcr.io/linkerd-io/base` as a base image.

An alternative approach could be to build and support a debug version of the control-plane Docker image, to be deployed as-needed.

**Comment by klingerf** [comment]
I'm also not in love with the `scratch` base image, but I wanted to provide just a bit of background for how we ended up here. The decision to move to `scratch` was made in #368, and the basic rationale was that since control plane containers run in pods that are injected with the linkerd proxy, and since the linkerd proxy container builds from `gcr.io/linkerd-io/base`, one could exec into that container instead to get access to basic command line utilities.

There's more info in #523 about why `scratch` is a good choice from a security perspective. Namely we could create a `PodSecurityPolicy` for the control plane that sets `ReadOnlyRootFilesystem`. If we intend to do that, then it would probably be easier to leave the `scratch` base image in place for now. If we don't intended to go that route, maybe we can just close #523 before proceeding? @olix0r, any thoughts on this?

**Comment by siggy** [comment]
Closing this in favor of #2199.
