### ISSUE TITLE
Handle innocuous error messages during control plane startup

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2168]
### What problem are you trying to solve?

When the controller containers start up, they log a lot of connection refused lines. This is a timing issue between the proxy and the controller container. As the proxy is not yet ready to receive traffic, the connections get retried.

Unfortunately, this scares users and can provide misleading information around debugging. In the past, it was not possible to opt-out of these lines because of glog.

### How should the problem be solved?

The underlying problem here is that a `Sync` is kicked off before the proxy is ready to forward traffic. This feels like a general linkerd problem, and possibly something that could help our users out.

I would like to see a way for sidecars to know when they can start sending traffic out. It feels like this could be a readiness probe for the proxy. Then, the controller code could wait for the probe to pass and continue starting.

### Alternatives considered

- Mute klog - there are valid messages that will just make debugging more difficult if klog is completely muted.
- Toggle klog around sync - feels pretty magical and fragile.

**Comment by grampelberg** [comment]
@klingerf should the klog setting be `-v3` or just ignore that for now?

**Comment by grampelberg** [comment]
Updated to reflect the problem statement and a more sustainable solution.

**Comment by dadjeibaah** [comment]
For this, what about just hitting the pods `/metrics` endpoint exposed by the proxy and once that gives us a success response proceed with the `Sync`. That endpoint is what's used for the readinessProbes for the kubelet. We could use it in each of the control plane components to effectively do the same thing the kubelet readiness checks are doing.

**Comment by klingerf** [comment]
@dadjeibaah That makes sense to me, especially since that's what we're already using for the proxy's readiness checks. I wanted to weigh in with a bit of additional info though.

I think this issue is more complicated to fix than it seems on the surface. The easiest fix is to suppress these logs messages entirely, unless `--controller-log-level` is set to "debug". That's my preferred fix.

Alternatively, if we're worried about debuggability when the logs are suppressed, then we can introduce some sort of delay in the controller components that waits for their sidecar proxies to initialize. Frankly that feels a bit anti-linkerd to me. The whole idea behind proxy injection is that your applications should be unaware that they're running with a sidecar, and in my mind, that includes the control plane.

Fwiw, other projects have hit this issue too, and there's been some push for container startup/shutdown ordering supported natively by Kubernetes. The original issue for that was tracked in kubernetes/kubernetes#65502, and it has now been converted to a KEP, here:

https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md

I'm not sure what happens now, but assumedly there will be some support for this in future versions of Kubernetes, and my recommendation would be to wait for that instead of applying application-level fixes at this time.

**Comment by siggy** [comment]
Closed by #2221.
