### ISSUE TITLE
Clean and update Gopkg.lock

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2169]
As part of #2160, the client-go dependency was bumped to 1.13.1. As part of this, some of the dependencies are no longer required (glog) and a little bit out of sync. There should be an update/cleanup pass to make sure the right dependencies and versions are being used.

**Comment by klingerf** [comment]
Running `bin/dep ensure` keeps `Gopkg.lock` synced with all of the project's transitive dependencies. It should be removing packages that are no longer used. Are you seeing cases where this isn't happening? In the case of glog, many packages, including k8s.io/klog, still import glog, which is why it shows up in Gopkg.lock.

**Comment by klingerf** [comment]
Also, we should never be modifying `Gopkg.lock` by hand. That file is managed entirely by dep.

**Comment by klingerf** [comment]
Hmm, ok, removing `Gopkg.lock` entirely and re-running `bin/dep ensure` will have varying effects depending upon the state of your global go source tree. I think any packages found there will be pinned at the revision where they're checked out, and anything not found there will be pinned to the head of the repository. So it's possible that upgrading all transitive dependencies could put us into a state where glog was no longer imported, but definitely not guaranteed. We could use this issue to track upgrading all of our transitive deps to latest, but I'd prob just opt to close it.

**Comment by grampelberg** [comment]
Works for me, I was just concerned I'd left the packages in a half-state.
