### ISSUE TITLE
proxy: redundant metrics scopes?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2203]
The proxy's metrics exposition can include redundant metrics scopes:

```
:; kubectl -n linkerd exec -c linkerd-proxy $(kubectl -n linkerd get po | awk '$1 ~ /^linkerd-controller-/ && $3 ~ /^Running$/ { print $1 }' |head -n 1) -- curl -s localhost:4191/metrics   | grep tls=
request_total{direction="inbound",tls="no_proxy_tls"} 46
request_total{direction="inbound",tls="no_proxy_tls"} 44
request_total{direction="inbound",tls="no_proxy_tls"} 44
request_total{direction="inbound",tls="no_proxy_tls"} 18
request_total{authority="linkerd-prometheus.linkerd.svc.cluster.local:9090",direction="outbound",dst_control_plane_ns="linkerd",dst_deployment="linkerd-prometheus",dst_namespace="linkerd",dst_pod="linkerd-prometheus-785b984cd5-2977q",dst_pod_template_hash="785b984cd5",dst_service="linkerd-prometheus",tls="true"} 28
request_total{authority="linkerd-proxy-api.linkerd.svc.cluster.local:8086",direction="inbound",tls="true"} 24
...
```

This indicates a bug in the proxy's metrics system. Scopes should be unique.

**Comment by hawkw** [comment]
Looking at the `FmtLabels` implementation for `EndpointLabels`, I think I know what's going on here. 

It looks like when the `EndpointLabels`' `dst_name` and `labels` fields are empty, [the labels format as a direction and a TLS status](
https://github.com/linkerd/linkerd2-proxy/blob/0fc35e257e54f6e0ed5a9d7e0a45d7f914b4caf6/src/app/metric_labels.rs#L128-L136). However, the `EndpointLabels` [also contains a `SocketAddr` field](https://github.com/linkerd/linkerd2-proxy/blob/0fc35e257e54f6e0ed5a9d7e0a45d7f914b4caf6/src/app/metric_labels.rs#L21), which is considered as part of the `Hash` and `Eq` impls derived for `EndpointLabels`. It appears the `SocketAddr` field is never formatted. The practical upshot of all this is that it seems like it's currently possible to have a set of labels which are not equal (and thus produce separate scopes) but format identically. 

Some potential options for resolving this issue:
1. Remove the `SocketAddr` field from `EndpointLabels` entirely. Other than in the `EndpointLabels` constructors, the field is currently completely unused. This would result in all inbound requests without a destination authority being grouped in a single scope.
2. Always include the `SocketAddr` in the formatted output `EndpointLabels`. This would result in metrics being grouped into scopes as they are currently, but each scope would have properly unique labels. We'd need to determine an appropriate name for the new label field --- `dst_addr`?
3. Only format the `SocketAddr` when an authority is _not_ present. In order to get correct behaviour, if we do this, we'd have to change the `Hash` and `Eq` impls so that the socket address is only considered for uniqueness when an authority is not present. This seems like it's not the best solution IMHO, as it adds more complexity. However, it would reduce cardinality for metrics with both authorities and addresses, which might be a good thing...
@olix0r WDYT is the correct option here? 

Given that the type is named `EndpointLabels`, this implies to me that the intention is to have a unique  set of labels per endpoint, so to me, it seems like the correct option is the second one, always adding the `SocketAddr` field to the formatted output.

**Comment by hawkw** [comment]
After talking to @adleong yesterday, we determined that the right thing was probably to remove the `SocketAddr` field from `EndpointLabels` entirely (to reduce cardinality). I believe @kleimkuhler is currently working on making this change.

@olix0r do you agree that removing the socket address from `EndpointLabels` is correct, or would you prefer to see it included in the metrics output?
