### ISSUE TITLE
Inject output shows empty YAML

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2273]
### What is the issue?

For [this YAML](https://gist.github.com/grampelberg/110db89003542231403364a5c58bda19), the inject output is:

```bash
secret "release-name-traefik-default-cert" skipped
configmap "release-name-traefik" skipped
serviceaccount "release-name-traefik" skipped
clusterrole "release-name-traefik" skipped
clusterrolebinding "release-name-traefik" skipped
service "release-name-traefik-dashboard" skipped
service "release-name-traefik" skipped
deployment "release-name-traefik" injected
ingress "release-name-traefik-dashboard" skipped
 "" skipped
 "" skipped
 "" skipped
 "" skipped
```

I would expect the last four lines to not be there at all.

**Comment by Pothulapati** [comment]
I am willing to take this issue! 

I started looking at the code, and another condition checking if the `injectReport.Kind` is empty string or not [here](https://github.com/linkerd/linkerd2/blob/907f01fba67d69967afa534259883db0b41c1971/cli/cmd/inject.go#L489) would be enough I guess as every resource will have a non-empty kind field.
`uninject.go` should also have a similar condition I guess.

WDYT? :)

**Comment by ihcsim** [comment]
@Pothulapati That's great! Checking `Kind` does sound the right thing to do. But instead of performing the check in the `generateReport()` method, I think we can do that in the [`ProcessYAML()` method](https://github.com/linkerd/linkerd2/blob/907f01fba67d69967afa534259883db0b41c1971/cli/cmd/inject_util.go#L92), which is called by both `inject` and `uninject`. WDYT?

In addition to testing with the YAML provided by @grampelberg, perhaps also test with a YAML with `Kind: List`, to see if what we talk about here will work.

**Comment by grampelberg** [comment]
@ihcsim is there a `Kind: List` that would be empty like that?

**Comment by ihcsim** [comment]
For all intents and purposes, I doubt we will ever see a list like this:
```
apiVersion: v1
items:
- # Source: traefik/templates/acme-pvc.yaml
- # Source: traefik/templates/dns-provider-secret.yaml
- ....
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

The only reason why I brought that up is because I notice that the `transform()` methods are returning a slice to `ProcessYAML()`. The only place where that makes a difference is when we are dealing with [list](https://github.com/linkerd/linkerd2/blob/907f01fba67d69967afa534259883db0b41c1971/cli/cmd/inject_util.go#L108). Hence, I thought it will be good to test things out, just to make sure nothing regresses when changes are made in `ProcessYAML()`.

**Comment by grampelberg** [comment]
👍 makes sense to me!

**Comment by Pothulapati** [comment]
@ihcsim A `Kind: List` returns the same error with and without the check in `processYAML`. 

I also did try it with the yaml [here](https://gist.github.com/Pothulapati/db90c546798f642d1fab7c025ece6495) which has a deployment resource, followed by empty resources (as per your example). The check did work and didn't add the empty `injectreport` item into the list. 

If everyone is okay with the fix, Ready to submit a PR :+1:

**Comment by ihcsim** [comment]
@Pothulapati Please go ahead and submit your PR. Thanks!
