### ISSUE TITLE
linkerd2-proxy too many open files

### ISSUE THREAD

**Issue by rnd4222** [linkerd/linkerd2#2322]
### What is the issue?
linkerd2-proxy hangs when sending data via tcp to proxy port of linkerd2-proxy

### How can it be reproduced?
curl http://localhost:4140

### Logs, error output, etc
Script used to start linkerd2-proxy

```
export LINKERD2_PROXY_POD_NAMESPACE=""
export LINKERD2_PROXY_LOG="DEBUG"

linkerd2-proxy
```
Sending HTTP-request to proxy:
curl http://localhost:4140

Log is flooded with messages:

```
DBUG proxy={server=out listen=127.0.0.1:4140} linkerd2_proxy::transport::connection error handshaking: Too many open files (os error 24)
```

And lsof shows lots of connections for linkerd2-proxy

#### `linkerd check` output
Not applicable.

### Environment

- Kubernetes Version:
N/A
- Cluster Environment: (GKE, AKS, kops, ...)
N/A
- Host OS:
ubuntu 16.04
- Linkerd2-proxy version:
stable-2.2.0

**Comment by wmorgan** [comment]
Thanks for filing this, @rnd4222 . Are you running this proxy locally? What is your file descriptor ulimit?

**Comment by rnd4222** [comment]
@wmorgan Yes, proxy is running locally.
The problem, I believe, is that linkerd2-proxy expects CONNECT method.
File descriptors are leaking in a tight loop, so it doesn't matter what ulimit I set - it does exhausted very quickly anyway.

**Comment by klingerf** [comment]
@rnd4222 Thanks for reporting this. Getting the proxy to run locally isn't a high priority for this project, but if you could provide detailed instructions to reproduce this in your environment, that would be really helpful.

**Comment by rnd4222** [comment]
@klingerf Please see OP for instructions on how to reproduce this. Let me know if you need any additional information.

**Comment by jonrichards** [comment]
I've also run into this issue running the linkerd2-proxy outside of the cluster as a transparent proxy. Here is the configuration used:

**- Host OS:** Debian Stretch w/backports
**- Host iptables rules:** `iptables -t nat -A PREROUTING -p tcp -m tcp -j REDIRECT --to-ports 4140`
**- linkerd2-proxy version:** latest `master`
**- linkerd2-proxy code changes:** `DEFAULT_OUTBOUND_LISTEN_ADDR` set to `0.0.0.0`
**- environement variables:** `LINKERD2_PROXY_IDENTITY_DISABLED=1,LINKERD_PROXY_LOG=error,linkerd2_proxy=error`
**- ulimit nofiles:** 500000

When load testing the proxy, I see a similar error (`ERR! [   419.227769s] linkerd2_proxy::app::main outbound proxy background task failed: Too many open files (os error 24)`) when initiating ~500+ concurrent connections. When doing fewer than ~500 concurrent connections, I haven't observed that error.

**Comment by olix0r** [comment]
@jonrichards Thanks for the helpful info. We'll take a look into this. To help, though: Can you share details about your load generator? Specifically, if this is an HTTP test that does not reuse connections? Any other relevant details about the client to this outbound proxy?

For posterity, `master` is currently 3e0e00c6dfbf5a9155b887cfd594f611edfc135f.

**Comment by jonrichards** [comment]
@olix0r you bet, here's the info:

I use the https://github.com/giltene/wrk2 utility for load testing.  `wkr2` does http requests, with connections kept open. You can quickly compile it on Debian Stretch with the following steps:

```bash
sudo apt-get install git build-essential libz-dev libssl-dev
git clone https://github.com/giltene/wrk2.git
cd wrk2
make
```
Here is the setup I used for testing this scenario:

- All systems in AWS
- All systems were c5.9xlarge instance type
- 2 VPCs created (`vpc01` and `vpc02`)
- Both VPCs contain a `dmz` subnet (`dmz01` for `vpc01`, and `dmz02` for `vpc02`), and an `internal` subnet (`int01`) for `vpc01`
- The load generator system lives in `int01`
- The transparent proxy system lives in `dmz01`
- The nginx system lives in `dmz02`
- The route table for `int01` has `0.0.0.0/0` pointed at the ENI of the transparent proxy system in `dmz01`

I ran the load test with the following paramters:  `./wrk -c 1000 -t 30 -d 600 -R 5000 -U http://<PUBLIC IP ADDRESS OF NGINX SERVER>`. When hitting the nginx system directly from the load generator system, there are no issues. And for comparison, when running netty on the transparent proxy system instead of the linkerd2-proxy, there are no issues.

And just to be 100% identical, `master` was at `5d5eed6f8180b8db4090d995e71fdf7b0890c647` for the release build of the `linkerd2-proxy` used in the testing.

Also, I've used the same load generation for load testing linkerd2 in a k8s cluster many times now, and haven't run into this issue there.

Let me know if any other information would be helpful. I can also screenshare and walk someone through our setup if that would help.

**Comment by olix0r** [comment]
That you hit this at 500 concurrent connections reminded me of [this post on TIME_WAIT](https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux#connection-table-slot):

> On Linux, the client port is by default allocated in a port range of about 30,000 ports (this can be changed by tuning net.ipv4.ip_local_port_range). This means that only 30,000 connections can be established between the web server and the load-balancer every minute, so about 500 connections per second.

This may not be exactly what you're hitting, but this does raise a good point: Is it possible for you to share the output of `ss -an` (or netstat) from the proxy? It will be helpful to know the breakdown of how many sockets are in each TCP state.

**Comment by jonrichards** [comment]
[lsof-baseline.txt](https://github.com/linkerd/linkerd2/files/3198897/lsof-baseline.txt)
[lsof-during.txt](https://github.com/linkerd/linkerd2/files/3198898/lsof-during.txt)
[ss-baseline.txt](https://github.com/linkerd/linkerd2/files/3198899/ss-baseline.txt)
[ss-during.txt](https://github.com/linkerd/linkerd2/files/3198900/ss-during.txt)

@olix0r here you go. I've included the output of both `ss -an` and `lsof`. The `baseline` files are from before doing load testing, and the `during` files are during load testing.

I receive the `linkerd2_proxy::app::main outbound proxy background task failed: Too many open files (os error 24)` error message almost instantly upon starting the load testing.

Please let me know if there's any other information that would be useful for looking into this.

**Comment by wmorgan** [comment]
For posterity: standalone proxy mode isn't a high priority and so we're not planning on tackling this in the near future.
