### ISSUE TITLE
remove vertical line in dashboard header

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#2325]
Minor, but there is a vertical line in the dashboard header to the right of the Linkerd logo, and it would look better to follow the K8s dashboard's approach of "no such line".

![image 14](https://user-images.githubusercontent.com/4026/53042258-bd49f900-343a-11e9-9d19-6f08af5d83d1.png)

**Comment by scottcarol** [comment]
@wmorgan @grampelberg, do you want just a vertical line deletion in the header, or do you also want the behavior of the K8s dashboard, where the full header bar remains at the top of the screen when a user is scrolling downward? 

K8s header when user is at top of screen:

![k8s1](https://user-images.githubusercontent.com/2289389/53197148-72f98100-35ce-11e9-9c3e-82b81bfc32c2.png)

K8s header when user scrolls downward:

![k8s2](https://user-images.githubusercontent.com/2289389/53197160-78ef6200-35ce-11e9-9211-a26a7e948e85.png)

Linkerd header when user is at top of screen:

![linkerd1](https://user-images.githubusercontent.com/2289389/53197778-c0c2b900-35cf-11e9-9d36-40aa31fb8887.png)

Linkerd header when user scrolls downward:

![linkerd2](https://user-images.githubusercontent.com/2289389/53197781-c4564000-35cf-11e9-8175-e5870bfa31f1.png)

To me, the K8s sticky header behavior is more clear, because the user always knows which section they're viewing. However, this will be a bit more reorganization of the code since currently the lefthand `Drawer` component is independent of the righthand `Main` content.

**Comment by grampelberg** [comment]
+1 to having it be sticky

**Comment by wmorgan** [comment]
Agreed!

**Comment by wmorgan** [comment]
The line continues to haunt me

**Comment by scottcarol** [comment]
Closing - new design does not include a full-width vertical navbar
