### ISSUE TITLE
New Annotation To Trigger Automatic Proxy Version Upgrade

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2339]
### What problem are you trying to solve?
Support a new annotation (`linkerd.io/upgrade:true`) to trigger automatic proxy version upgrade using the proxy injector during workload updates. This can help to streamline the users' proxy version upgrade process, without the needs for CLI interaction. Currently, the proxy injector will skip all workloads that are already injected with the Linkerd proxy.

Continuation of #2260.
Depends on #2289.

### How should the problem be solved?
The logic around the [`healthcheck.HasExistingSidecars()`](https://github.com/linkerd/linkerd2/blob/5dcb9086f54e4cd290b499b8ba7285c01fdcc50c/controller/proxy-injector/webhook.go#L228) needs to be a bit smarter, by checking for the existent of the `linkerd.io/upgrade: true` annotation, and comparing the current vs latest proxy version. The latest proxy version can be retrieved from the proxy config. See #2298.

Once the upgrade is completed, the annotation needs to be removed.

We also need to consider version rollback mechanism if the version upgrade failed, and not leave the workload in a limbo state.

### Any alternatives you've considered?
Stick with the manual upgrade process using the CLI.

### How would users interact with this feature?
Via the `linkerd.io/upgrade: true` annotation.

**Comment by olix0r** [comment]
@ihcsim do you think something like this is still valuable or necessary given the auto-inject and config changes we've made?

I can see a use case for this, but, rather than linkerd drive the actual rolling of pods, i think we'd want to be able to trigger a deployment operator of some sort to cause a new rollout. In that scenario, I'd imagine the operator would watch the linkerd control plane's config object and, when it changes, trigger a (gradual, guarded) redeploy.

**Comment by ihcsim** [comment]
It will be super cool to be able to do what you said through a deployment operator. I can totally see how a smart (configurable?) auto-upgrade will be super useful for large data planes. Gonna keep this issue open for now.
