### ISSUE TITLE
Uninject does not remove linkerd.io labels

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2377]
### What is the issue?

Running `uninject`, I would expect all the labels that linkerd adds to be removed.

### How can it be reproduced?

```bash
kubectl get --all-namespaces daemonset,deploy,job,statefulset -l "linkerd.io/control-plane-ns" -o yaml | linkerd uninject - | kubectl apply -f -
```

Labels are still there.

### Environment

- Linkerd version: stable-2.2.0

**Comment by alpeb** [comment]
We only inject annotations and labels at the pod spec template level, so that's what `uninject` is currently removing. But it appears that when the deployment we injected gets applied in Kubernetes, the labels (not the annotations) get copied from the pod spec template into the Deployment metadata. I'll see if I can have `uninject` get rid of those as well.

**Comment by grampelberg** [comment]
That's useful to be aware of in relation to #2376.

**Comment by klingerf** [comment]
@alpeb Good find! This also relates to #2342.

**Comment by alpeb** [comment]
While we're at it, we're gonna fix this while also removing _all_ the labels and annotations that start with "linkerd.io/", not just the list of hard-coded ones we currently have.
