### ISSUE TITLE
destination: Increase MAX_CONCURRENT_STREAMS

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2395]
The destination service's grpc interface should use a larger MAX_CONCURRENT_STREAMS value (of, let's say 10K).

This should be configurable on the grpc server:

https://github.com/grpc/grpc-go/blob/3aaef9f0c1b114366cb4507ba4f3c083b17d2f4e/server.go#L259-L265

This isn't really important until https://github.com/linkerd/linkerd2/issues/2390 is done.

Once this is done, linkerd router capacity limits should be rethought to make more sense (they don't make sense right now).

**Comment by seanmonstar** [comment]
In both the server and client case, unless otherwise limited, the max is `u32::MAX` (in grpc-go) as well. That `defaultMaxStreamsClient = 100` bit appears to be used by the client [until it receives the first `SETTINGS` frame](https://github.com/grpc/grpc-go/blob/3aaef9f0c1b114366cb4507ba4f3c083b17d2f4e/internal/transport/http2_client.go#L985), probably to protect from sending thousands of streams without knowing how the server feels about that.
