### ISSUE TITLE
Generate non-changing installation yaml

### ISSUE THREAD

**Issue by hazsetata** [linkerd/linkerd2#2506]
## Feature Request

I would like to have an option to generate stable (non-changing) installation yaml when running "linkerd install". 

### What problem are you trying to solve?

I’m trying to integrate linkerd2 to my provisioning script (Pulumi). I created a resource that calls “linkerd install --proxy-auto-inject” to generate the install yaml (this way the user can use any version of linkerd (edge / stable / older)). I ran into a problem with the Deployment named “linkerd-web”: one of its container arguments is a UUID, and it is randomly generated every time the “linkerd install” is run. Because of this change, Pulumi always thinks there is a change to be applied.

### How should the problem be solved?

Maybe the simplest option would be to make this UUID configurable. This way if somebody needs this "stable" behaviour, a UUID can be pre-generated and saved in the provisioning system's configuration and passed on to linkerd.  

### Any alternatives you've considered?

The output could be transformed (sed, parsing, etc.) but that makes it dependent on the yaml's structure, and could break if that structure changes in the future.

### How would users interact with this feature?

Using the optional CLI flag.

**Comment by grampelberg** [comment]
It would be nice to have `install` hit the cluster first to see what's there. 

@ihcsim @alpeb do you think this issue is an extension of the work to get `inject` working off config in the cluster or something completely separate?

**Comment by ihcsim** [comment]
I don't think it's directly related to the `inject` config work, since the goal here is to pin/configure the `web` UUID during `install`. fwiw, it can just be a new `install` flag, in which case, this can be a good first issue.

**Comment by grampelberg** [comment]
@ihcsim makes sense as a good first pass.

**Comment by klingerf** [comment]
I'd prefer for us to solve this a bit differently. We should start storing the UUID as a field in the `linkerd-config` ConfigMap that's created when you first install the control plane. As of #2455, the control plane has a `Config()` endpoint that we can call from the CLI to get the contents of the ConfigMap. I think it would make sense for `linkerd install` to start calling that endpoint if it's available, and then use the UUID if it exists when constructing the new install YAML. This will cause use to use the same UUID across multiple installs.

Note that this approach also relates to the identity work that's ongoing, since upgrading the control plane will also require fetching the `linkerd-config` ConfigMap if it exists.

**Comment by grampelberg** [comment]
@klingerf that's definitely my preferred approach!

**Comment by olix0r** [comment]
The install yaml has changed significantly in the past few months. @hazsetata I'm going to close this as I think we've addressed this, but please reopen if you think further changes are warranted! Thanks.
