### ISSUE TITLE
Linkerd dashboard start button stays disabled when using top

### ISSUE THREAD

**Issue by drholmie** [linkerd/linkerd2#2549]
Bug Report:
What is the issue?
In the linkerd dashboard top page, when selecting resource as daemonset or statefulset for any namespace, starting and stopping works fine, but the start button remains disabled until page is refreshed. Top works correctly for every other resource. 

How can it be reproduced?
Start linkerd dashboard and in the top page, select any namespace and select resource as daemonset or statefulset. Start and stop it. 

Possible Solution
The tap page does not go through this issue (as it stops itself) when daemonset or statefulset is selected as a resource. Using the same function on the top page may help.

**Comment by scottcarol** [comment]
Hey @drholmie 👋thanks for reporting this. Could you confirm what version of Linkerd you are running, by typing `linkerd dashboard` in the CLI or looking at the bottom of the sidebar in the Web UI? I believe this is fixed as of `edge-19.3.3` (#2437).

**Comment by drholmie** [comment]
Hey there! Currently running 2.2.1(stable)

**Comment by scottcarol** [comment]
Hey @drholmie, yep, that issue has been fixed in the most recent edge release, `edge-19.3.3` -- thanks again for reporting! 🌟 (Edge release info [here](https://linkerd.io/2/edge/))

When I'm doing development for the UI/CLI, as you are doing, I pull the latest changes to our codebase from the `master` branch and build the website and the CLI from my local files. The steps in `BUILD.md` starting at the `Go` section should help, particularly the `bin/go-run` instructions. That way I am working from the most updated code.
