### ISSUE TITLE
Split proxy-init into separate repo

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2563]
The proxy-init container rarely changes. Yet, we build it on every build, publish it on every release, etc. Furthermore, because the proxy version we inject with needs to match the init version, it complicates testing proxy versions.

Why don't we split this code out into a separate repo (i.e. linkerd/proxy-init) and depend on a less-frequently-changing version during inject? This streamlines the normal build, release, and development workflows.

**Comment by klingerf** [comment]
This also relates to #1318.

**Comment by ihcsim** [comment]
In light of the conversation in https://github.com/linkerd/linkerd2/issues/2819 around privilege escalation, will it make sense to eventually replace proxy-init entirely with the CNI plugin? AIUI, the only reason why privilege escalation is needed is because proxy-init requires the `NET_ADMIN` capability to modify the iptables, right?

**Comment by alpeb** [comment]
I think privilege escalation is not needed when asking for the `NET_ADMIN` capability. As a proof you can see the yaml for an injected pod from emojivoto, and `allowProvilegeEscalation` is not set, so it takes its default value (false). Also `privileged` is set to false.

Defaulting to CNI would definitely be simpler, but I think it needs further testing. I've seen some odd behaviors in my own testing, and we also have to see how it behaves with other CNI plugins (#2456)
