### ISSUE TITLE
docs: How to set the proxy log level on controller pods?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2591]
There's no longer a way to configure the proxy log level in the control plane without configuring it for all future injected pods.

Now, when an install/upgrade uses --proxy-log-level, this is stored in the configuration to be used at inject-time.

But what if we want to update a controller deployment with a different log level without making it a global default?

We should be able to run `kubectl annotate -n linkerd deploy/linkerd-controller config.linkerd.io/proxy-log-level=trace` and have that take effect.

This seems like it might be ~trivial if we set the `LINKERD2_PROXY_LOG` variable via the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) from the annotation.

**Comment by alpeb** [comment]
`kubectl annotate` only lets you annotate at the `deployment.metadata` level, which doesn't trigger pod re-creation.

But if you do `kubectl edit` and insert that annotation at the `deployment.spec.template.metadata` level then that'll trigger pod re-creation, which will get caught by the auto-injector and the new proxy will have the new log level.

Also a simple CLI `linkerd inject --proxy-log-level=trace` on the deployment yaml should do the trick without affecting the global config.

Am I missing something?

**Comment by olix0r** [comment]
That sounds reasonable. At a minimum we need to be able to document how to enable controller logging without adding it to all pods, because this is something we ask folks to do when submitting an issue. The prior mechanism will no longer be suitable...

**Comment by harsh-98** [comment]
@olix0r `kubectl edit` will do the trick for individual pods too.

**Comment by harsh-98** [comment]
@olix0r I have a design for this. `LINKERD2_PROXY_LOG` should be read using downward api from 
`config.linkerd.io/proxy-log-level`. And instead of having proxyLogLevel here https://github.com/linkerd/linkerd2/blob/master/cli/cmd/install.go#L174, we would set it by using `&v1.EnvVarSource{FieldRef: &v1.ObjectFieldSelector{FieldPath: "metadata.annotations.config.linkerd.io/proxy-log-level"}}` and set `config.linkerd.io/proxy-log-level` to `warn,linkerd2_proxy=info`. In this way, if we use `kubectl annotate` command to change the log level it will work.

**Comment by olix0r** [comment]
hi @harsh-98. per @alpeb's comment, i'm not sure that my proposed change makes much sense after all.

**Comment by ihcsim** [comment]
Using the annotation override method won't work here, because the proxy injector will skip the control plane components (due to the presence of the proxy spec YAML). In addition to what @alpeb suggested with `linkerd inject --proxy-log-level`, we can also edit the `LINKERD2_PROXY_LOG` env var in the spec, right? Let me know what else is required for this issue.

**Comment by klingerf** [comment]
Apologies for chiming in late here. Is the goal of this issue to allow users to change the log level for control plane proxies only, without changing the configured global default that applies to proxies injected into other namespaces? If so, can't we `kubectl edit` a control plane deployment post-install and change the `LINKERD2_PROXY_LOG` env var directly? Is the goal of switching that env var to use the downward API to make changing the log level more ergonomic?

**Comment by olix0r** [comment]
Per conversation, this is basically a documentation task and not a code change... TLDR: we need a workflow for users to enable debug logging on specific controller pods without upgrading the whole cluster to use debug logging.

**Comment by ihcsim** [comment]
:+1: I will track this under https://github.com/linkerd/website/issues/222, where I do all the config docs.
