### ISSUE TITLE
l5d headers are leaked from https ingresses

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2597]
### What is the issue?

When using HTTPS with an injected ingress controller, it is possible for internal cluster details to leak via headers.

```
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 500
< date: Fri, 29 Mar 2019 17:51:31 GMT
< l5d-remote-ip: 10.4.0.17
< l5d-server-id: linkerd-web.linkerd.serviceaccount.identity.linkerd.cluster.local
< vary: Accept-Encoding
```

### How can it be reproduced?

I injected Traefik, had it terminate TLS and curl'd.

### Environment

- Linkerd version: edge-19.3.3

**Comment by olix0r** [comment]
specifically, this happens because _outbound_ routers include response headers so the application can  know about the connection details for debugging and diagnostics. We strip these header on upstream responses, except, in this case, the ingress terminates TLS, so the inbound router cannot modify requests on the edge-side of the ingress.

**Comment by grampelberg** [comment]
The docs have been updated to explain that these headers need to be removed in your ingress. For the time being, I propose that these headers are removed by default until there is a larger story around identity verification.

**Comment by olix0r** [comment]
For 2.3, I agree we should just strip these headers. After that, we should move this to 2.3 backlog and figure out a strategy for surfacing this information to applications...

**Comment by olix0r** [comment]
followup https://github.com/linkerd/linkerd2/issues/2612
