### ISSUE TITLE
Add --skip-check flag to CLI

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2653]
Some Linkerd CLI commands (such as linkerd dashboard) perform checks before running the command to verify that the Linkerd installation is in a good state.  However, if there are any false positives in the checks, this prevents these commands from being run.

By adding a `--skip-check` flag, we always have a work-around in the case of false positives in check.

**Comment by Thomas-Fitzpatrick** [comment]
Hi @adleong, I'm interested in learning more about linkerd's CLI commands as well as the check suite of tests specifically and so was wondering if it'd be ok for me to work on this as my first issue? 

If so, do you have any advice on how to best start this? It sounds straightforward enough but any guidance is greatly appreciated.

**Comment by olix0r** [comment]
see also https://github.com/linkerd/linkerd2/issues/1854

**Comment by klingerf** [comment]
👍 to making this change, but I wanted to provide some additional context.

When #1854 first came up, we were running the full set of `linkerd check` checks before every CLI command, and if any check failed, we would preemptively fail the command. We decided at that time that if we reduced the scope of checks run to just the set of checks that was absolutely necessary to run the command, then that would remove the need for a `--skip-checks` flag, since we shouldn't be triggering spurious failures or false positives at that point. That's the approach we took in #2033. We decided at the time, however, that `linkerd dashboard` should continue to run the full set of checks, since the dashboard provides a full representation of the control plane, and it would be broken if any part of the control plane was broken.

That said, I can see the value of running the dashboard even if the control plane is in a broken state. How would folks feel about making the `--skip-checks` flag exclusive to that command? If other CLI commands are negatively impacted by the limited set of checks that we're now running, my vote would be to continue to scope down the set of checks for those commands to what is absolutely necessary for them to function, instead of providing a mechanism for bypassing them.

**Comment by adleong** [comment]
@Thomas-Fitzpatrick I think this would be a great first issue!  I recommend taking a look at the [checkPublicAPIClientOrRetryOrExit](https://github.com/linkerd/linkerd2/blob/master/cli/cmd/public_api.go#L39) function, which is called by the CLI commands.  This is where the checks occur.

**Comment by Thomas-Fitzpatrick** [comment]
Great, thanks for all the info! I feel like I have much more context for this now. I'll get started into this over the next few days.
