### ISSUE TITLE
Pass arbitrary pod labels through as prometheus labels

### ISSUE THREAD

**Issue by nickjackson** [linkerd/linkerd2#2657]
## Feature Request
Pass arbitrary pod labels through as prometheus labels like [these docs](https://linkerd.io/2/reference/proxy-metrics/#example ) suggest you already can.

### What problem are you trying to solve?
I'm looking to build some custom graphs that require some extra prometheus labels to be passed through. 

In particular, I want to pass through two labels that might look something like this `app=foo, version=v1.0.0`

### How should the problem be solved?
Not certain. Is it as simple as modifying the prometheus scrape config for the `linkerd-proxy` [here](https://github.com/linkerd/linkerd2/blob/65a228fe6c4a4daac6190889834692790d0d926d/chart/templates/prometheus.yaml#L198) to allow all labels through?

### Any alternatives you've considered?
So currently by default all labels prefixed with `linkerd.io/` will be passed through and remapped. I'm currently using this to get my labels through, but this is clearly not ideal.

### How would users interact with this feature?
Just add labels to the pod spec as they normal do.

**Comment by olix0r** [comment]
One issue to overcome is that, i believe, prometheus cannot have labels with dots, slashes, or dashes; so we'll need some rules about translation...

**Comment by siggy** [comment]
For reference, we used to have this functionality, I'd be in favor of adding it back:
https://github.com/linkerd/linkerd2/pull/1402#discussion_r207943459

**Comment by matipan** [comment]
Is this issue being worked on? Since is a good first issue I would be ok with working on it 👍

**Comment by siggy** [comment]
@matipan Go for it! I'd love to see this get implemented!

**Comment by daxmc99** [comment]
@matipan Are you still working on this? 
@siggy Is it ok to add that line back? 

Looks like this is the place to add it 
https://github.com/linkerd/linkerd2/blob/b8f7b959d2efcef8639fb5615a339c9ff5579ca4/cli/install/template.go#L480

I am doing this personally for some metrics scraping 
https://github.com/rancher/mesh-metrics/blob/master/prometheusConfig.yaml#L99

I am a bit of loss of how to safeguard Prometheus though. Is the worry about query time increasing?

**Comment by siggy** [comment]
@daxmc99 I think it's fine to add this back.

Query time increasing is a concern, though that won't directly affect Linkerd proxy performance, just a slower `linkerd stat` and `linkerd dashboard` experience.  Bigger concerns are probably Prometheus CPU and storage. Today the `linkerd-prometheus` deployment's resource requirements tracks roughly with O(# of proxies X service topology density). This would change that to O(# of proxies X service topology density X # of extra labels). I'm still in favor of this, we'll just need to be thoughtful about communicating the possible increase in resource requirements during release. /cc @grampelberg

**Comment by adleong** [comment]
I'm a bit hesitant about this because it makes it very difficult for us to know how Prometheus will perform without knowing the number of labels and cardinalities of label values on the cluster.  To make this even more difficult, folks use labels for a wide variety of purposes and may or may not want to break down their Linkerd metrics along these dimensions.

On one hand, I'd be more comfortable if this was opt-in, but on the other hand I'm always very reluctant to add more configuration to Linkerd.  I'm not sure what the right answer is but here are some probing questions that might help us get closer:

* Is it possible to accomplish this with an "after-market" modification to the Prometheus yaml?  Obviously diverging from the upstream yaml isn't ideal...  is Kustomize helpful here?
* Is it possible to write the label regex such that it only maps labels with a specific prefix?  This allows users to opt-in to pod labels that they specifically want to use in metrics.
* Presumably you don't actually need to break down your metrics by arbitrary pod labels and there's actually some specific labels/dimensions you have in mind for a particular use case.  Can you tell us more about that?  Maybe there's another way to accomplish that task.

**Comment by grampelberg** [comment]
@adleong as these are going to come from the pod definition .... it shouldn't introduce any extra cardinality issues as far as I'm aware? Should be 1:1 with the existing pod name label.

**Comment by adleong** [comment]
Ah, that makes sense @grampelberg!  Thanks for pointing that out!

**Comment by christyjacob4** [comment]
@adleong I'd like to work on this

**Comment by adleong** [comment]
@christyjacob4 thanks for your interest!  I believe this was already addressed in https://github.com/linkerd/linkerd2/pull/3833
