### ISSUE TITLE
Integration test for reading Kubernetes events

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2713]
A class of Kubernetes issues, such as #2694, are not currently caught in our integration tests. Introduce an integration test that reviews Kubernetes events post-install.

**Comment by alpeb** [comment]
We're consistently getting k8s warnings after install, for failed readiness probes on proxies seemingly because they won't succeed until the main container is not ready. Possible ways to fix:
- appropriately setting the injected proxy's `initialDelaySeconds` depending on the main container (e.g. Prometheus takes 30s for its probe to succeed)
- not use readiness probes in proxies. Proxies aren't added to Endpoints so I think it makes sense to forgo them

**Comment by siggy** [comment]
> appropriately setting the injected proxy's initialDelaySeconds depending on the main container (e.g. Prometheus takes 30s for its probe to succeed)

i think i'd rather we have some failed probes on startup, and come up as quickly as possible, rather than setting `initialDelaySeconds`.

> not use readiness probes in proxies. Proxies aren't added to Endpoints so I think it makes sense to forgo them

i think it's worthwhile to explore removing this. if it does not cause unexpected failure, i'd be in favor of it.

for a bit more context, the goal of this particular ticket is just to wire up the integration tests to Kubernetes events, and report anomalies, similar to our logging tests.

**Comment by alpeb** [comment]
@klingerf proved me in #2798 we can't just remove the probes. I'll most likely then just consider those warnings as expected, as alluded to by @siggy
