### ISSUE TITLE
Move ServiceProfile generated code into pkg

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2751]
## Background

The ServiceProfile generated [client](https://github.com/linkerd/linkerd2/tree/cd37d3f0f50600ce21644f9ae3884b23867a5555/controller/gen/client) and [api](https://github.com/linkerd/linkerd2/tree/cd37d3f0f50600ce21644f9ae3884b23867a5555/controller/gen/apis/serviceprofile) code lives under `./controller/gen` primarily that is where all generated code is centralized. As non-controller components, namely the CLI, depend on this code, it makes less sense to have it there.

## Proposal

Move ServiceProfile generated code into `./pkg`.

This would allow us to move [`NewSpClientSet`](https://github.com/linkerd/linkerd2/blob/cd37d3f0f50600ce21644f9ae3884b23867a5555/controller/k8s/clientset.go) into [`pkg/k8s`](https://github.com/linkerd/linkerd2/blob/cd37d3f0f50600ce21644f9ae3884b23867a5555/pkg/k8s/k8s.go), which would then allow us to make `k8s.GetConfig` private.

This is a continuation of #2747.

**Comment by klingerf** [comment]
We have the same issue for all of the protobuf bindings in `controller/gen` too. Files in the web, pkg, and cli dirs all import protobuf from `controller/gen`, which doesn't seem right.

Based on the layout of the [sample codegen project](https://github.com/kubernetes/sample-controller/tree/master/pkg), maybe we could:

* Move `controller/gen/apis` to `pkg/apis`
* Move `controller/gen/client` to `pkg/generated`
* Move `controller/gen/common` to `pkg/pb/common`
* Move `controller/gen/config` to `pkg/pb/config`
* Move `controller/gen/controller` to `pkg/pb/controller`
* Move `controllergen/public` to `pkg/pb/public`

(note that I previously requested we put all of the codegen code in the `controller/gen` directory, since I was concerned about mixing generated and non-generated code in `pkg`, but on reflection I'm not actually concerned about that)

**Comment by alpeb** [comment]
Will be addressing this one after #2786 lands, to avoid merge conflicts.
