### ISSUE TITLE
Add namespace to MWC

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2887]
### What problem are you trying to solve?

When running multiple control planes on a single cluster, the MWC resources are named identically and clobber each other.

### How should the problem be solved?

Match the other components naming schema and add the control plane namespace to the name so that each can coexist.

**Comment by olix0r** [comment]
Specifically, I think this means that we need to change the `linkerd.io/inject: enabled` annotation to something like `config.linkerd.io/control-plane: my-other-cp-ns` so the the proxy injector can match namespaces rather than just "should I inject?"

I'd suggest that we maintain `linkerd.io/inject: enabled` as a shorthand for `config.linkerd.io/control-plane: linkerd`
