### ISSUE TITLE
Add namespaceSelector that matches control plane namespace to MWC

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2888]
### What problem are you trying to solve?

When multiple MWC mutators are running in a cluster, each one needs to know what pods it is authoritative for.

### How should the problem be solved?

Each MWC will have a label selector in this form:  `"namespaceSelector": { "matchLabels": { "config.linkerd.io/control-plane": "ns-of-proxy-injector" }}` . 

This will match all the workloads under any namespace that has the label `config.linkerd.io/control-plane: ns-of-proxy-injector`

### Open questions

- This feature only works at the namespace level. Meaning each namespace that gets added must have `config.linkerd.io/control-plane: namespace`. In its labels. How do we solve this for namespaces that were added before Linkerd was installed?

- What happens we a MWC doesn't have a namespaceSelector and there are multiple MWC. we will then have pod specs sent to all webhooks and will put the cluster in a bad state. One solution might be to check if the MWC doesn't have a selector and if there are multiple MWC, we reject the admission request with some error message.

**Comment by dadjeibaah** [comment]
Marking this as related to #2909. The idea is to add a `namespaceSelector` in the MWC to get this working properly.

**Comment by ihcsim** [comment]
@grampelberg @dadjeibaah @alpeb After catching up on the to-date comments, I will like to propose we reconsider using the MWC's namespace selector to define the proxy injectors' authoritative scope. My primary concern lies in potentially conflating the implication of the presence or absence of the MWCs' namespace selectors.

Can we simplify the workflow to:

1. A user installs multiple control planes with `linkerd install -l <ns-*>`
1. `linkerd check` reports a warning that there are multiple MWCs in the k8s cluster, linking to the doc with more info on the implication of multiple MWCs.
1. The doc explains that either this is the byproduct of an upgrade (see https://github.com/linkerd/website/issues/336), or it's part of the user's multi control plane setup.
1. The proxy injector is updated to compare its namespace with the `config.linkerd.io/control-plane` annotation in the workload's YAML to decide if it's responsible for injecting the given workload.
1. The `linkerd inject` code is updated to inject the `config.linkerd.io/control-plane` annotation (or just reuse the existing `linkerd.io/control-plane-ns` annotation).
1. To support auto-inject, our doc will advise the user to annotate either the namespace or the workload with `config.linkerd.io/control-plane`, instead of the existing `linkerd.io/inject` annotation (per https://github.com/linkerd/linkerd2/issues/2887#issuecomment-499125309). For backward compatibility purposes, `linkerd.io/inject` will just become a legacy annotation and the shorthand of `config.linkerd.io/control-plane: linkerd`. 

One caveat is that all proxy injectors will have visibility into all workloads across all the control planes. I feel this is ok because a truly multi-tenant (not just a multi control plane) model should be governed and enforced by some higher level policy abstraction, instead of relying on the MWC namespace selector.

**Comment by grampelberg** [comment]
@ihcsim I'm good with using an annotation, I was under the impression that the namespace selector was a better solution though?

I still think the injector should return an error if there is more than one MWC and the namespace is not annotated.

**Comment by ihcsim** [comment]
> I still think the injector should return an error if there is more than one MWC and the namespace is not annotated.

Agreed. As a matter of fact, getting the injector to check the namespace and/or workload annotation is more reliable than checking the MWC namespace selectors, because the selectors can be something else that isn't related to multi control plane setups.

> under the impression that the namespace selector was a better solution though?

Previously, I was under the same impression. But after chatting with @alpeb and @dadjeibaah, a few issues surface, including:

1. the MWC namespace selector has to be opt-in, as we don't want to tell users to go back to re-annotate all existing data plane namespaces
1. hence, we need to add new install option to differentiate between single control plane installation and control plane installation which is part of a bigger multi control plane setup (to decide whether to include the MWC namespace selector)
1. the proxy injectors need to check all MWCs for namespace selectors to decide if they are operating in a correctly configured multi control plane setup. As pointed out above, the namespace selectors can be something that is irrelevant to multi control plane setup.

**Comment by ihcsim** [comment]
Superseded by https://github.com/linkerd/linkerd2/issues/2913.
