### ISSUE TITLE
`top` output has no column headers

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#3121]
The output of `linkerd top` has no column headers, making it unclear what is actually being reported. (2.4.0)

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/4026/61723195-8d23c080-ad20-11e9-9339-accc3707c7ca.png">

**Comment by aimof** [comment]
This problem seems to cause from [this line](https://github.com/linkerd/linkerd2/blob/065dd3ec9d4b84c90383b31be16ccadd34a8ab0d/cli/cmd/top.go#L621)

```
termbox.SetCell(x, y, c, termbox.AttrBold, termbox.ColorDefault)
```

The param termbox.AttrBold should be set color but is not.
So both forground and background colors are `termbox.ColorDefault` (black).

We should set color white.

```
termbox.SetCell(x, y, c, termbox.AttrBold|termbox.ColorWhite, termbox.ColorDefault)
```

I'll make PR.

**Comment by adleong** [comment]
@wmorgan @aimof on what environment are you seeing this issue?  I tried in `iterm` and `terminal` on MacOS and couldn't reproduce it.

![Screen Shot 2019-07-29 at 10 17 37 AM](https://user-images.githubusercontent.com/3979810/62068152-4c2d1f80-b1ea-11e9-9965-1c4967e2c71d.png)
![Screen Shot 2019-07-29 at 10 17 46 AM](https://user-images.githubusercontent.com/3979810/62068155-4df6e300-b1ea-11e9-9597-6cd0ddf82abe.png)

**Comment by wmorgan** [comment]
Oops, this was user error on my part. Sorry!
