### ISSUE TITLE
Support detection of server-speaks-first protocols?

### ISSUE THREAD

**Issue by VojtechVitek** [linkerd/linkerd2#3166]
### What problem are you trying to solve?
I'd like linkerd2 to be able to detect [server-speaks-first protocols](https://linkerd.io/2/features/protocol-detection/), ie. NATS, MySQL, MongoDB, InfluxDB, SMTP etc., so I can see all the linkerd2 metrics in the dashboard for these microservices and ideally so I can turn on automatic TLS for these pods too.

Are you guys planning to support this feature in the future?

### How should the problem be solved?

Well, this is an open question for the maintainers. Is this solvable?

And.. if there's no way to implement server-speak-first protocol detection, would it be possible to force the protocol via some special linkerd2 annotation?

**Comment by grampelberg** [comment]
There's two separate problems here:

- Degrading to TCP for protocols that Linkerd does not have a codec for.
- Providing visibility into protocols other than TCP.

There are some open issues for protocol support, if you see a protocol you'd like to use that doesn't have an open issue, please open one! There's some work going on around Kafka right now.

Around correctly degrading, it is super difficult for Linkerd to detect the protocol generally when the server is required to speak first. It is definitely something worth doing, but might end up being so complex that configuration is the only option.

**Comment by wmorgan** [comment]
The workaround for now is that either 1) you TLS these connections yourself (which is a client-speaks-first protocol!), or 2) you annotate them with `--skip-*` annotations (which `linkerd inject` can do for you) to skip proxying. When we add mTLS for TCP connections, we probably will need an additional annotations to skip protocol detection but not skip proxying. When we have protocol-level support in Linkerd for a server-speaks-first protocol (e.g. NATS), we'll probably need protocol-level annotations the way that you suggest.

**Comment by kellycampbell** [comment]
We got bit by this today when first trying out linkerd. Sending email from a django server via AWS smtp on port 587 was hanging. That is supposed to be TLS, so I don't know why it's not working as a client-speaks-first protocol.

I don't remember seeing anything about this kind of issue in the documentation and it took me a while to figure it out, so might be good to highlight this limitation and how to fix somewhere in troubleshooting or faq's.

**Comment by wmorgan** [comment]
@kellycampbell we have some documentation in https://linkerd.io/2/features/protocol-detection/ , but I'm definitely open to suggestions about better places to put it.

In your case, to confirm, is the Django app initiating the TLS? Or are you trying to use Linkerd's TLS?

**Comment by kellycampbell** [comment]
Yup, I totally missed the importance of that section of the docs. I kind skipped over it since I was only serving http and grpc. Maybe something in the first paragraph there about outgoing connections hanging or emphasizing that both outgoing and incoming traffic goes through the proxy.

I did a bit more research. Port 587 is a server-speaks-first port using "STARTTLS" https://tools.ietf.org/html/rfc8314#section-3, https://tools.ietf.org/html/rfc8314#section-3.3

The documentation provided by both AWS and Django say this is the preferred method, but the new rfc changes the recommendation back to the implicit TLS using port 465.

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-connect.html
https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_USE_TLS

Django's doc mentions hanging connections there.

**Comment by kellycampbell** [comment]
Another idea I just had would be to surface something in the UI showing that an outgoing connection wasn't able to be protocol sniffed.

**Comment by wmorgan** [comment]
@grampelberg what do you think we should do with this issue?

**Comment by grampelberg** [comment]
We'll need to add debugging tools to figure out what isn't HTTP and go from there.

**Comment by wmorgan** [comment]
Ok, let's keep this open then.
