### ISSUE TITLE
TrafficSplit dashboard integration

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3261]
## What problem are you trying to solve?

With TrafficSplit visibility landing as part of #3106, it should be added to the dashboard as well. This should include both a detail and overview page and match the other existing resources, such as deployments.

## How should the problem be solved?

Here's some mockups.

### Sidebar

![Screenshot 2019-08-21 13 33 21](https://user-images.githubusercontent.com/47992/63467582-a2246a00-c41a-11e9-973d-1893d78e6461.png)

### Namespace List View

Nest the table from the list view below.

### List View

![Screenshot 2019-08-21 13 58 52](https://user-images.githubusercontent.com/47992/63468109-e2d0b300-c41b-11e9-9a5f-9dd5ff896144.png)

### Detail View

This view should only contain the octopus and table, there should not be any other information here.

![Screenshot 2019-08-21 13 40 22](https://user-images.githubusercontent.com/47992/63467577-a05aa680-c41a-11e9-908d-cecb4eed094a.png)

![Screenshot 2019-08-21 13 49 26](https://user-images.githubusercontent.com/47992/63467576-9df84c80-c41a-11e9-9a73-2dd2dd2e67bb.png)

### Out of Scope

- Adding any information to the overview screen.
- Adding links or tables to any other list/details views (excluding namespaces).

**Comment by scottcarol** [comment]
Ready to jump in on this one. @grampelberg are you creating mockups for this?

**Comment by grampelberg** [comment]
Yup! First on my priority list today!

**Comment by grampelberg** [comment]
@scottcarol take a look at TMWYT.

**Comment by scottcarol** [comment]
Thanks! Some clarifying questions:

1. In the List View mockup, you have a heading of `TrafficSplit` and beneath that is `web`. Is `web` the trafficsplit name, the apex service name or a leaf service name?
2. In the List View mockup, the table name is "HTTP Metrics." Did you mean to title this "Traffic Splits" and have this be a new table? 
3. Your mockups include a Grafana icon. Should this open the `service` view in Grafana?
4. The octopus graph shows an arrow pointing to the lefthand side of the apex service, what does that signify?
5. For the detail view, can you elaborate on the data you are showing for `svc/web` on the left vs. `svc/web` on the top right? I'm assuming `svc/web` on the **left** is the apex service and `svc/web` on the **top right** is the leaf service (in this case the same service).

If my assumptions in #5 are correct, in #3176 @adleong made [these comments](https://github.com/linkerd/linkerd2/pull/3176#discussion_r309784836) about apex service traffic, saying that the apex service can get a unique stream of traffic that is unrelated to the traffic split. Since this is UI specifically for the traffic split and not a Services view -- and if we want to be consistent with `linkerd stat ts` -- I don't think we should report separate metrics for the apex service.

@adleong comments on apex service traffic: 
> Since traffic splitting is done on the client side, if an unmeshed resource sends traffic to the apex service of a traffic split, the traffic split logic will not be applied and the traffic will go directly to the apex service.
...
> Yes, there is a scenario where apex, leaf1, and leaf2 all get unique streams of traffic: any unmeshed pods sending to apex will not use the traffic split and the traffic will simply go to apex; meanwhile any mesh pods sending to apex will use the traffic split and divide that traffic between leaf1 and leaf2 according to the weights.
...
> But I'd argue that the traffic from the unmeshed source which goes directly to apex is not part of the traffic split (the unmeshed source doesn't use the traffic split) and should not be included in the traffic split UI. (This is one of the key distinctions between showing stats for the service and showing stats for the traffic split)

**Comment by grampelberg** [comment]
1. My thinking was the name of the split, not any of the services. The idea is that this is a list of TrafficSplits and not something else.

2. I really struggled with what to put on the list view. The idea was that the table is http metrics as that whole page is TrafficSplit by definition.

3. I was hoping we’d introduce a set of Grafana dashboards for TrafficSplits.

4. I just didn’t erase that, sorry!

5. That sounds fine if we can’t show stats for the apex, I primarily would like a visualization of the leaves.

**Comment by scottcarol** [comment]
Re: No. 2, we don't currently report a single SR, RPS, L99 etc. for the split as a whole, only for each leaf service. (As the case in No. 5, metrics for the apex service don't necessarily reflect traffic split stats.) 

We could theoretically combine the metrics from each leaf service -- so if `svc/web` had 4 RPS and `svc/web-canary` had 1 RPS, `ts/web` would have 5 RPS. However this gets confusing and inaccurate because the trafficsplit itself doesn't have RPS, the services within it do. Also, those combined numbers don't tell you anything about the efficacy of your trafficsplit.

Alternatively the List View could display the basic K8s info for each traffic split - name, apex, leaf, weight. This has value because leaf names and weights aren't available with `kubectl get ts -A`. Because a trafficsplit is a different kind of resource than the other resources we list in the sidebar, I think it's ok to have the List View look and feel different.
```
NAME            APEX      LEAF            WEIGHT
authors-split   authors   authors           500m 
authors-split   authors   authors-clone     500m
webapp-split    webapp    webapp               1
webapp-split    webapp    webapp-clone         0
```

**Comment by grampelberg** [comment]
Hmm, I like that idea, what would be clickable? The name? That's probably good enough (tm).

**Comment by scottcarol** [comment]
The table could look like this. It doesn't make sense to name the table HTTP Metrics if we do this, but naming it "Traffic Splits"  is redundant due to the green header on top. "Details", "Summary", "All Traffic Splits"?

![Screen Shot 2019-08-22 at 9 38 46 AM](https://user-images.githubusercontent.com/2289389/63532963-aacf7b80-c4c0-11e9-80f5-b21470b07a68.png)

**Comment by adleong** [comment]
Regarding the list view: I think it *does* make sense for a traffic split to have aggregated top line metrics over its leaves.  This represents the characteristics of the traffic split as seen by clients sending requests to it.  For example, if you have a split called authors that sends 50% of traffic to a leaf service called authors-v1 that has a 50% SR and 50% of traffic to a leaf service called authors-v2 that has a 100% SR, then you would expect the SR of the traffic split as a whole to be 75%.  In other words, 75% of requests sent to the traffic split apex will succeed.

That said, I also really like the suggestion of mirroring the behavior of the `linkerd stat ts` command and listing each leaf as a row in the list view.  In this case we wouldn't show the traffic split topline metrics in the list view, but we could show it in the detail view.

Regarding the detail view, I'm really hesitant to put an octopus graph on here.  In my mind, the octopus graph isn't ever intended to show metrics that aren't already conveyed in the tables.  Instead, the point of the octopus graph is visually convey the idea of network topology.  But in the case of a traffic split, that's giving a misleading impression of what is happening (there is no network hop between an apex service and a leaf service, as the octopus graph might suggest).

My preference would be just to display the topline metrics for the traffic split (perhaps in a box, just like the central box of an octopus graph, but without arms) and a table of the leaves.  Or, we could come up with some other visual metaphor that represents traffic split delegation instead of network topology, but I don't have anything in mind and it kinda feels like overkill.

**Comment by scottcarol** [comment]
After in-person conversation with @grampelberg @adleong we decided:
* The List View will show exactly the results of `linkerd stat ts -A` 
* We will be aware of table width and if necessary we will cut P50 and P95 from the List View table
* The Detail View will contain the octopus graph as shown in mockups above. The metrics shown for the apex service in the graph are the aggregated metrics from all the leaf services. We will clarify this with a tooltip. 
* The table in the Detail View will be named Leaves and each leaf name will be preceded by `svc` i.e. `svc/authors`
* No Grafana dashboards in this iteration
