### ISSUE TITLE
Launch proxy as part of CNI setup

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3263]
### What problem are you trying to solve?

Kubernetes has somewhat lacking sidecar support. When an application with a sidecar starts, and issues a request to an external source more quickly than the proxy starts, it is possible for there to be connection failures. It is difficult for an application to determine whether this is because the proxy has taken time to start or something more fundamental is wrong. In particular, it requires application developers to write custom code in preparation for being meshed. While there will be a native solution to this soon ([issue](https://github.com/kubernetes/enhancements/issues/753)), it is unclear when this will land and how long it will take to be adopted by all the providers of Kubernetes.

In addition, the sidecar pattern forces developers to at least be aware of the proxy running. It must be added to the pod's specification and get started. When moving into more secure enterprise environments that are dictating configuration, operations prefers to keep the details of the proxies to themselves. This includes keeping the versions and settings external from something that developers can observe.

### How should the problem be solved?

There is already a CNI plugin for Linkerd. This moves the iptables concerns from a developer to the operations team and is primarily used to remove NET_ADMIN permissions to make more secure environments. The plugin can run arbitrary processes and is setup/torndown as part of the pod's lifecycle. 

The CNI plugin should be improved to also start and manage the proxy's lifecycle alongside setting up iptables. This would result in there no longer being a sidecar in the pod, init containers sending connections through the proxy and having policy applied and removing the proxy's concerns from developers.

**Comment by zaharidichev** [comment]
## CNI proxy life cycle

### The current state of things
We currently use a CNI plug-in which is essentially a daemon set that installs a CNI binary that gets called every time a pod is created. This plug-in is currently responsible for setting the IP tables rules that are needed to pass traffic through the proxy. This effectively removes the need for init containers. It does not however remove the concern of having a proxy running in the pod. So form the perspective of the developer, the proxy needs to be in the pod, needs to be injected through the inject command or needs to be added through the auto injector feature of linkerd. 

### The "ideal" scenario
In an ideal scenario, this cni plug-in will also handle the creation/shutdown of the proxy itself as part of the network setup, removing the need for any kind of other injection. This pretty much makes the existence of the proxy invisible to developers. It also removes the need for auto injection, init containers or manual injection as every pod that is added to the cluster will be configured to work with a proxy. 

### Benefits
- Remove concerns of adding proxy containers into pods
- Remove the need for init containers
- Remove the need for NET_ADMIN privileges in pods
- Ensure proxy is up and running before the other containers in the pod are


### How would that work
Well in order for that to happen the CNI plug-in is split into two components, the cni command itself and the proxy-scheduler. These have quite distinct responsibilities. 
- **CNI command** - stays largely the same apart from the fact that it is also responsible for making an API call to the proxy scheduler to allow it to start the proxy for the pod that is being meshed. 
- **Proxy scheduler** - responsible for serving proxy start and proxy stop requests as well as continuously monitoring the health of the proxy and restarting it whenever needed. 

### How does that work in more detail? 
In order to understand the scope of the work we need to take a look at what actually happens when a pod is being added to the cluster. Lets take the emoji app for example and look at whats going on both sides of the cni plugin component. 

#### CNI command
The emoji-web pod gets added to the cluster. At that point as part of the CNI life cycle the `func cmdAdd(args *skel.CmdArgs)` of the cni command plug-in is called transferring config data for this pod. What we do with that is setup the ip tables rules that are needed for the proxy to function correctly. Once this is done, we issue a API call to the proxy-scheduler to allow it to start the proxy for this pod. The request looks like: 

```go
type StartProxyRequest struct {
	PodIP        *string `json:"pod-ip"`
	PodSandboxID *string `json:"pod-sandbox-id"`
	PodName      *string `json:"pod-name"`
	PodNamespace *string `json:"pod-namespace"`
	CniNs        *string `json:"cni-ns"`  // this is the linux namespace of the pod in which the proxy needs to be started
}
```

Once this call returns we know that the proxy initialization process has started for this pod. This does not mean that the proxy is up and running. There is a separate call to the scheduler that we can use to determine whether the proxy is up, running and ready. This looks very similar:

```go
type ReadinessCheckRequest struct {
	PodName *string `json:"pod-name"`
	PodNamespace *string `json:"pod-namespace"`
	PodIP *string `json:"pod-ip"`
	CniNs *string `json:"cni-ns"`
} 
```

We repeatedly call this api endpoint (with some back-off and timeout) and block the creation of the pod until the scheduler responds with an indication the proxy is up and running. At that point we can proceed to the creation of the pod itself. If all goes well, we have a pod with a proxy that is healthy and passes traffic.

When the pod is deleted the `func cmdDel(args *skel.CmdArgs)` of the plug-in gets invoked, this issues a delete request to the proxy scheduler which in turn kills the proxy container. So from the perspective of the stateless cmd plug-in, things are pretty simple.

#### Proxy scheduler
This is where things get more interesting. This is effectively a small container scheduler that serves the purpose of starting, monitoring and stopping proxy containers. It needs to deal with quite a few interesting things. First of all, when we receive a `StartProxyRequest` here, we need to do a some  bootstrapping that otherwise kubelet would do for us. 

1. We use the k8s API to get the linkerd-config map that lives in the linkerd namespace. This gives us all the configuration for the proxy, such as ports, trust anchor pems, etc. 
2. Secondly, because our pod is not yet created really, we need to take care of providing all the data that the proxy container mounts from the pod and needs to run

    - Identity mount
    An end identity mount with container path` [/var/run/linkerd/identity/end-entity] `and host path 
`[/var/lib/kubelet/pods/<pod-uuid>/volumes/kubernetes.io~empty-dir/linkerd-identity-end-entity] `needs to be created. So create this empty directory that will be mounted on the container

    - Hosts mount
    We need to have a mount with container path `[/etc/hosts]` and host path `[/var/lib/kubelet/pods/<pod-uuid>/etc-hosts]`. To have that, we use some code very similar to the one found in kubelet itself. Take a look [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L296) 

    - Svc Account Mount
    So we also need to have the default service account that k8s automounts anyway. That would be container path `[/var/run/secrets/kubernetes.io/serviceaccount/<svc-acc-secret-name>]` and host path `[/var/lib/kubelet/pods/<pod-uuid>/volumes/kubernetes.io~secret/<svc-acc-secret-name>] `But since we are outside the scope of kubelet at the moment of starting the proxy and yet we need that mounted into its container, we use the k8s api to obtain the secret for the corresponding pod, create the directory on the host path, read the secret and write it to the file system. Now we can safely mount all of that onto the container that we want to start (the proxy one). 


3. We use all of the data that we have to put together a CRI container config that looks a bit like: 
    ```go
	containerConfig := criapi.ContainerConfig {
	    LogPath: "/some-log",
		Mounts: mounts,
		Metadata: &criapi.ContainerMetadata {
		    Name: k8s.ProxyContainerName,
		},
		Image: &criapi.ImageSpec{
		    Image:  fmt.Sprintf(  "%s:%s", l5dCfg.Proxy.ProxyImage.ImageName, l5dCfg.Proxy.ProxyVersion),
		},

	    Linux: &criapi.LinuxContainerConfig {
		    SecurityContext: &criapi.LinuxContainerSecurityContext{
			    RunAsUser:          &criapi.Int64Value{l5dCfg.Proxy.ProxyUid},
			    SupplementalGroups: []int64{0},
			    Privileged:         false,
			    ReadonlyRootfs:     true,
		    },
	    },
	    Envs:   envVars,

	    Labels: map[string]string {
		    schedulerCreatedContainerLabel: trueValue,
		    containerNameLabelKey: k8s.ProxyContainerName,
		    podNameLabelKey:       pod.Name,
		    podNamespaceLabelKey:  pod.Namespace,
		    podUIDLabelKey:        string(pod.UID),
	    },
    }
    ```

4. We create and start the container. At that point we can return success to the cni plug-in. All is not finished yet, because we cannot be sure the proxy is up and running and healthy. So before we return a success to the server, we kick off an asynchronous job to register the container for health monitoring. 


##### Readiness and health monitoring of the container. 
Although the container has been created and started, it might not be ready yet. This is why an asynchronous job, checks periodically the /ready endpoint of the container to determine whether it is ready. On the cni command plug-in side pretty much we loop repeatedly querying the proxy scheduler while waiting for the proxy to be ready. On the scheduler side what happens after starting the container is: 

1. The container is started
2. The scheduler loops and tries to hit the /ready endpoint of the proxy. For that purpose it uses the NetNs linux namespace that it knows this container is running in and on every call to /ready it enters and exits the namespace. There are some complications with asynchronous code here, but this has been solved.
3. When the proxy is deemed ready, it is registered for continuous health monitoring. 
4. The latter means that two annotations are added to the pod for which the proxy has been started: 
- `l5d.proxyscheduler.pod.n`s = the linux namespace in which this pod is running `/proc/<some-pid>/ns/net`
- `l5d.proxyscheduler.managed.pod` = true

5. The health monitoring loop hits the k8s api, gets all pods and filters the ones that have these annotations.
6. It finds the proxy container for this pod, enters linux NS (known from the ns annotation on the pod) and hits the[ /metrics](url) endpoint.
7. If this cannot happen the proxy is deemed not healthy and can be restarted. 


### What has been implemented so far? 
Most of what I described has been implemented and tested and works. So all of this is possible to happen.

### Why is this a risky change? 
First of all, this is quite a bit of code that needs to be maintained and is effectively a mini scheduler that takes care of managing the proxy life cycle. Secondly this uses CRI (container runtime interface), which is the very same interface that kubelet uses to interface with the container runtimes present on cluster nodes. As powerful as that is, it is quite low-level and requires a lot of additional things such as obtaining and mounting secrets, writing etc-hosts files manually, etc. All of these are potential failure points. 

What the biggest problem is however is that this changes drills a few verticals through the linkerd2 codebase that affect things profoundly. 

#### Installation
To begin with the whole installation process changes. IF we are to rely only on CNI, things like init containers and inject go away. Of course it can be made possible for these to work alongside, but that requires even more consideration. 

#### Monitoring/CLI tools
Currently things like tap and top do not work. The reason for that is because as I take it, they actually require the proxy container to be present in the pod spec (might be wrong here). Currently it is not. So these need to be modified to account for that. 

#### Prometheus data acquisition
As far as I take it this data is retrieved through the /metrics endpoint for proxies. How does Prometheus gather the data through. I hear from other team members that its relying on the k8s service discovery machinary to do that. That would not work because there is nothing to discover now. The proxy is completely invisible to k8s and is not present in the pod spec. 

#### Problems around CRI and integration with runtimes. 
I know there are some problems when using the CRI to interface with containerd and cri-o. I think this can be easily solved however. All the k8s kubelet code is on github and this is essentially what it does - start containers, monitor containers, kill containers using this very same interface. So that is not too much of a worry for me but is yet another thing to figure out.


#### A note on static pods. 
Static pods seem to be a good option to also explore if we are to do this. They provide us with a way to create and retire a pod that contains only the proxy and is managed by the kubelet itself. So we can use that instead of going through CRI. This will however not remove a lot from the things we need to take care of. Really the benefit of using static pods are:
- No need to take care of low level operations like mounting hosts and secrets ourselves
- No need to take care of managing the healthiness of the proxy. 
- We will not rely on CRI

We still need to take care of starting and stopping this pod. We will also need to modify the cli/install commands as well (i think) because now our container is in a pod/namespace. So although this relives us of some burdens, it still leaves us with quite a bit of things that we need to modify. But yes, its a possible scenario as well. 

### Final remarks. 
I have to say that based on my progress so far all of this is doable and is certainly a very nice feature as it abstracts away a lot of the proxy and effectively fuses it into the network layer. It is a big job though and because its so big, its quite risky. And as much as I can get my hands even dirtier and bring that to the finish line, its up to you to determine whether its worth it.

### Resources
- [CRI interface blogpost](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) 
- [CNI spec](https://github.com/containernetworking/cni/blob/master/SPEC.md)
- [Part of kubernetes soruce that deals with mounting hosts etc](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go) 
- [Cri tools - a nice command line tool that uses CRI to do various things with the container runtime. Good source for figuring out how to use the api](https://github.com/kubernetes-sigs/cri-tools)
- [The pr that I submitted, containing a working POC of this approach](https://github.com/linkerd/linkerd2/pull/3471)

**Comment by grampelberg** [comment]
That's a fantastic writeup @zaharidichev. I'm going to close this issue out for now, given the added complexity and lack of users asking for this specifically. We can revisit in the future depending on what's happening with k8s itself.
