### ISSUE TITLE
How mTLS works with API Gateway?

### ISSUE THREAD

**Issue by illidan80** [linkerd/linkerd2#3359]
Hi,

In order to mTLS work, both parties (e.g. client and server) have to validate certificates of each other.

I understand how that could work inside service mesh managed by Linkerd (e.g. Linkerd generates and distributes all required certificates across its sidecars)

However, its not clear for me how API Gateway may automatically get client certificate, which will be accepted by ingress pod (there is a http traffic between API gateway and Linkerd Ingress pod, right?)

I would appreciate if you could clarify about how traffic between API Gateway and Ingress is secured (in particular, how mTLS is enabled there)

**Comment by grampelberg** [comment]
Linkerd does not manage ingress. In this example, you would have a public certificate served up by your ingress controller (nginx for example). I would recommend that certificate was created via. let's encrypt and cert-manager.

When you've injected your ingress controller with Linkerd, the incoming connection to the ingress controller is encrypted with the public certificate. The proxy is unable to see any of this communication because it is encrypted. The traffic from the ingress controller to other pods inside your cluster, however, will be managed by Linkerd and encrypted correctly.

external user -> ingress controller (public certificate) -> linkerd (private certificate) -> linkerd (private certificate) -> your app

**Comment by illidan80** [comment]
@grampelberg: thank you for your replay. I really would like to get more details about traffic between ingress and linkerd.

if i understand correctly, there is a http traffic between ingress and linkerd (after all, they can be located on different machines). so, both parties have to trust each other. how exactly that achieved?

**Comment by olix0r** [comment]
@illidan80 we recommend that the ingress pod is injected with the linkerd sidecar, as well, so that its outbound requests can be routed through mTLS'd connections.

**Comment by grampelberg** [comment]
As the ingress controller's pod contains the linkerd proxy in the same network namespace, the unencrypted communication never leaves the pod. For communication between pods, Linkerd establishes trust via the included CA.
