### ISSUE TITLE
Enable debug sidecar for control plane components

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3396]
### What problem are you trying to solve?

I would like to use the debug sidecar with the control plane components. It is not surfaced as part of `install`, which is okay as I don't want it on for all the components. Trying to add the sidecar via `inject`, however, results in:

```bash
$ kubectl -n linkerd get deploy linkerd-controller -o yaml | linkerd inject --enable-debug-sidecar --manual - | kubectl apply -f -

deployment "linkerd-controller" injected

The Deployment "linkerd-controller" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"linkerd.io/control-plane-ns":"linkerd", "linkerd.io/proxy-deployment":"linkerd-controller"}: `selector` does not match template `labels`
```

I would like `inject` to be able to add the debug sidecar to control plane components as well as data plane components.

**Comment by ihcsim** [comment]
fwiw I started playing around with a kubectl plugin called [ksniff](https://github.com/eldadru/ksniff) which uploads tcpdump to the pod and directs the output to a local wireshark. One caveat is that because the control plane is built from scratch images, I need to run sniff in privileged mode in order for it to launch a separate in the `linkerd` namespace to perform the sniffing. Not recommended for prod environment though.

E.g
```sh
kubectl sniff -n linkerd linkerd-controller-95b8b4f4d-wt5zf -i any -f <tcpdump-filters> -p 
```

**Comment by grampelberg** [comment]
@ihcsim you’re just mentioning that we’ll be able to do that now?

**Comment by ihcsim** [comment]
While waiting for #3507, I came across ksniff few days ago as part of my kubecon talk prep. If it suits our needs, then we don't need #3507.

**Comment by grampelberg** [comment]
Ahhh, I see! I would still like #3507 as I use the debug containers for more than just traffic sniffing.
