### ISSUE TITLE
N+1 queries to prometheus

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3399]
### What is the issue?

When the `public-api` service receives a request to `StatSummary`, there can be a list of resources. This ends up regularly containing many resource types such as deployments and pods. Each resource type fires off its own query, creating a 10x increase in the number of requests that are issued to prometheus.

See [stat_summary.go](https://github.com/linkerd/linkerd2/blob/master/controller/api/public/stat_summary.go#L107) for the code that is creating the n+1 requests.

**Comment by ihcsim** [comment]
So far what I am seeing is that when the dashboard is launched, it continually sends requests to fetch metrics, selecting on the `All` type. This type got translated into a slice that looks like `[daemonset statefulset job deployment replicationcontroller pod service trafficsplit authority]`. Each of these resource types is then used to built the group-by condition of the PromQL queries (in the above linked source code).

In my debug code, they get translated to the following labels and group-by conditions:
```
reqLabels: {direction="inbound", namespace="emojivoto"}, groupBy: (namespace, authority)
reqLabels: {direction="inbound", namespace="emojivoto"}, groupBy: (namespace, deployment)
reqLabels: {direction="inbound", namespace="emojivoto"}, groupBy: (namespace, statefulset)
reqLabels: {direction="inbound", namespace="emojivoto"}, groupBy: (namespace, pod)
reqLabels: {direction="inbound", namespace="emojivoto"}, groupBy: (namespace, replicationcontroller)
etc..
```

Regardless of which page on the dashboard I'm on, there is always a request that triggers a query to fetch the `response_total` metrics, selecting on the `All` type, resulting in something like:
```
sum(increase(response_total{direction="inbound"}[1m])) by (namespace, deployment, classification, tls)
sum(increase(response_total{direction="inbound"}[1m])) by (namespace, statefulset, classification, tls)
sum(increase(response_total{direction="inbound"}[1m])) by (namespace, k8s_job, classification, tls)
sum(increase(response_total{direction="inbound"}[1m])) by (namespace, pod, classification, tls)
etc.
```

Experimenting with this query on the Prom console, the amount of time series data returned is bounded by two times the number of workloads (i.e. one for `classification=success` and the other for `classification=failure`).

On the _Overview_ page, I can see requests are being made to trigger these four queries, selecting on the `All` type:
```
sum(increase(tcp_read_bytes_total{direction="inbound", namespace="emojivoto"}[1m])) by (namespace, statefulset)
sum(increase(tcp_write_bytes_total{direction="inbound", namespace="emojivoto"}[1m])) by (namespace, statefulset)
sum(increase(response_total{direction="inbound", namespace="emojivoto"}[1m])) by (namespace, statefulset, classification, tls)
sum(tcp_open_connections{direction="inbound", namespace="emojivoto"}) by (namespace, statefulset)
```

I am not sure if attempts to refactor/optimize the code in `stat_summary.go` will yield a big difference, if these metrics are continually needed by the dashboard. We can consider experimenting with using recording rules for these queries. Alternately (though less preferred), we can experiment with doing the metrics aggregation in the `public-api` code (which I doubt will yield any improvement, if it doesn't make things worse.)

**Comment by siggy** [comment]
Agree with @ihcsim that while `stat_summary.go` may have some areas for optimization, looking at what the dashboard actually needs is perhaps a better starting point.

A few areas to look at:
- i assume the "all" queries are for the sidebar. we should consider:
  - only performing these queries when the sidebar is expanded
  - query less often than every 2 seconds
  - share the query responses with the rest of the dashboard
- collapse the `sum(increase(response_total{direction="inbound"}[1m])) by (namespace, *, classification, tls)` into a single query (not sure if that's possible?)

**Comment by scottcarol** [comment]
Re: @siggy @ihcsim comments re: Dashboard, I'm currently digging into how we can reduce and/or consolidate the queries we make to the API from the dashboard. I have a few options (including the ones siggy suggested above) and am talking with @rmars today for some additional context on architecture. I can update this issue and/or break it out into a separate issue relating only to the dashboard.

**Comment by grampelberg** [comment]
I'm currently putting mockups together for a new sidebar that gets rid of the prometheus query entirely. I've got a couple other ideas in scoping down what the queries do.

**Comment by ihcsim** [comment]
> collapse the sum(increase(response_total{direction="inbound"}[1m])) by (namespace, *, classification, tls) into a single query (not sure if that's possible?)

@grampelberg brought up the same idea this morning. At first glance, a query like:
```
sum(increase(response_total{direction="inbound"}[1m])) by (namespace, daemonset, statefulset, k8s_job, deployment, replicationcontroller, pod, service, trafficsplit, authority, classification, tls)
```
does seem to do what we want. The results it generates seem to match those generated by the queries with the `(namespace, [deployment|statefulset|job|etc.])` group-by conditions. And AFAICT, the grouping shouldn't require code change on the dashboard. Currently, I'm trying to understand the [existing code to generate the `pb.StatTable` response](https://github.com/linkerd/linkerd2/blob/a5a6e8ff9f01a2c63a3c4d9b7895eab1fc9ebd2d/controller/api/public/stat_summary.go#L210-L248), and how the new query will fit in.

**Comment by scottcarol** [comment]
@grampelberg thanks for the update on the dashboard plan.

Here's what I came up with for options for the current dashboard after talking with @rmars. 

Even if we change the default dashboard display to only display resources and metrics for a single namespace, like the k8s dashboard, these options are still relevant 

However, it may make sense to hold off changing until @grampelberg has finished the mockups.

**Current situation** 

When I'm on `/overview` in the dashboard, we make these 4 API requests every 2 seconds:

1. metrics for all resources in all namespaces
   * so sidebar menu can show names and green/red status dots for meshed resources
2. metrics for all namespaces
   * so sidebar menu can show namespace info - `linkerd stat all` does not return namespace data
3. k8s info for all namespaces (no metrics - `skip_stats=true`)
   * needed for `NamespaceLanding` (shown in `/overview`) to determine whether we display `meshed` on collapsed accordion namespaces
4. metrics for a selected namespace
   * needed for `NamespaceLanding` to display metrics for whichever namespace in accordion is expanded

**Options to Speed Up Dashboard**

1. Instead of making these 4 calls, make only the **1** and **2** calls and store them in the app context, available to all components.
2. (Very easy) Increase the default `pollingInterval` from `2000` ms to `5000` ms
3. Modify `linkerd stat all` to include namespace metrics - this may be a complex endeavor and not reduce the actual number of Prometheus queries, but would reduce the number of API queries to 1.
4. Store metrics info on the server side, and make a single API endpoint for dashboard metrics queries that returns a consistently formatted object for display.

**Comment by ihcsim** [comment]
@scottcarol Re changes to the Prometheus queries, when repeatedly using `curl` to hit the Prometheus API, so far the single query yields a slightly better CPU utilization result. There isn't much difference with the memory consumption. In a way, I guess the slight improvement didn't come as a surprise, because as previously discussed, most of work is done to process the `by(namespace, pod)` queries, which returns the most number of time series data. And the modified big query returns the same number of time series data as the former.
