### ISSUE TITLE
Flakey test: TestInjectAutoNamespaceOverrideAnnotations

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3480]
This test appears to fail spuriously:

```
--- FAIL: TestInjectAutoNamespaceOverrideAnnotations (32.38s)
    inject_test.go:139: failed to wait for condition=available for deploy/inject-test-terminus in namespace l5d-integration-inj-ns-override-test: exit status 1: error: timed out waiting for the condition on deployments/inject-test-terminus
FAIL
FAIL	github.com/linkerd/linkerd2/test/inject	32.552s
```

**Comment by alpeb** [comment]
That results from a `kubectl wait` command that timed out. Currently the timeout is set at 30s. When this happens, the cluster is not cleaned-up, so one can look what's going on. Instead of increasing that timeout, I suggest that when this happens again, this ticket gets updated with a link to the failed CI run. I'll then check that ASAP.

**Comment by grampelberg** [comment]
@alpeb are you looking at this still?

**Comment by alpeb** [comment]
I haven't caught that error again...

**Comment by alpeb** [comment]
Closing this. If it happens again, #4522 allows us to see some logs that might explain the cause of the timeout.
