### ISSUE TITLE
Tracing configuration

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3487]
### What problem are you trying to solve?

There are a couple different ways to configure tracing with competing concerns. This issue strives to make each piece explicit.

#### Control Plane

```bash
linkerd [install|upgrade] --control-plane-trace-collector oc-collector.tracing:55678
```

This should:

- Configure each control plane component (eg `linkerd-web`).
- Set `config.linkerd.io/trace-collector` for each proxy used by the control plane.
- Set `-sampling-probability=1` for each control plane component. The assumption is that if tracing is happening on the control plane, someone is actively debugging an issue and would like to see everything.

This should not:

- Configure tracing for anything else in the data plane.

#### Data Plane

```bash
linkerd inject --trace-collector oc-collector.tracing:55678
```

This should:

- Add the `config.linkerd.io/trace-collector` annotation to each spec being passed in.

This should not:

- Configure anything else except the specs that are passed in.

Note: for anyone wanting a default configuration, the annotation should be added at the namespace level.

### Open Questions

- What happens when there's an annotation at the namespace level and a user runs `linkerd inject` on a resource that will live in that namespace? Do they compose?
- In the long term, I would really prefer that linkerd does discovery of the collector's service account. This proposal does not discuss how that is done as it isn't happening today.
- @Pothulapati has mentioned that there's a chicken/egg problem with sending traces to a collector injected with linkerd before the control plane is installed. What are the implications here?

### Out of Scope

- Dynamically enabling tracing for any control plane component or data plane proxy.
- Allow updating control plane injection via `linkerd inject`, see #3396.

**Comment by olix0r** [comment]
What do you think about distinguishing them as:

`linkerd [install|upgrade] --control-plane-trace-collector` and `linkerd inject --proxy-trace-collector`?

Since these flags configure different things, I don't think they should have identical names, especially because many of the install-time flags configure defaults for inject. I also think it would then be suitable to support `--proxy-trace-collector` at install/upgrade time to serve as a default (though this is not a requirement in my view).

The annotation name should probably be proxy-trace-collector as well, then?

**Comment by olix0r** [comment]
Also note that the control-plane setting should be persisted in the config flags so upgrade uses them by default as well. How does one disable a control plane trace collector once it's been configured?

**Comment by grampelberg** [comment]
> `--control-plane-trace-collector`  

+1, updating the issue to reflect that.

> `--proxy-trace-collector`

From a contextual perspective, I still prefer `--trace-collector` here.

>  I also think it would then be suitable to support `--proxy-trace-collector` at install/upgrade time to serve as a default

I'm really, really hesitant to do this one right now because it will require figuring out how to disable it on a per-pod basis. From a reasoning perspective, I much prefer opt-in instead of conditional opt-in/opt-out.

> How does one disable a control plane trace collector once it's been configured?

`linkerd upgrade --control-plane-trace-collector=''` makes sense but feels ugly.

**Comment by adleong** [comment]
If control plane tracing is intended as a debugging tool for Linkerd developers, what do you think of having the `--control-plane-trace` flag:
* Add jaeger and the oc-collector manifests to the install
* Use a fixed service name rather than accepting it as a flag parameter

This makes the tool much easier to use, and we don't need the flexibility of supporting other tracing setups.

**Comment by grampelberg** [comment]
> Add jaeger and the oc-collector manifests to the install

I'd like to tackle this as part of #3582.

> Use a fixed service name rather than accepting it as a flag parameter

+1 from me, that's how #3539 ended up actually.

**Comment by adleong** [comment]
I don't think it makes sense to do control plane tracing configuration and #3582 separately.  What makes sense the most in my mind is to have:

* a PR which implements #3582 (adds a flag to install tracing components and configure the control plane to use them).  I think #3539 could be updated to be this.
* a separate PR which adds a flag to configure data plane tracing
