### ISSUE TITLE
Tap not returning any data, missing content-type header in logs

### ISSUE THREAD

**Issue by jamesmmchugh** [linkerd/linkerd2#3506]
### What is the issue?

Using the tap CLI (or via dashboard) seems to return no data for any deployment. 
For example when running:

`linkerd -n linkerd tap deploy/linkerd-controller`

The process just sits there and does not print anything. This is the same for deployments in the default namespace also.

Everything else seems to work as expected.

### How can it be reproduced?

`linkerd -n linkerd tap deploy/linkerd-controller`

### Logs, error output, etc

```
linkerd-tap-7f9f9c9fcf-ljc6f tap time="2019-10-01T15:09:41Z" level=info msg="Tapping 1 pods for target: {Namespace:linkerd Type:deployment Name:linkerd-controller XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}"
linkerd-tap-7f9f9c9fcf-ljc6f tap time="2019-10-01T15:09:41Z" level=info msg="Establishing tap on 10.88.9.37:4190"
linkerd-tap-7f9f9c9fcf-ljc6f tap time="2019-10-01T15:09:44Z" level=error msg="[10.88.9.37] encountered an error: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: missing content-type field"
linkerd-tap-7f9f9c9fcf-ljc6f linkerd-proxy WARN [  5732.041959s] proxy={server=out listen=127.0.0.1:4140 remote=10.88.7.171:34880} linkerd2_proxy::app::errors request aborted because it reached the configured dispatch deadline
```

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.2
- Cluster Environment: Openstack
- Host OS: RedHat Enterprise 7.5
- Linkerd version: 19.9.5 (edge)

### Additional context

* selinux disabled
* tried deleting the tap pods, and letting them recreate - no difference

**Comment by grampelberg** [comment]
This is a bug that occurs from how linkerd was installed. If you install with:

```bash
linkerd install --cluster-domain foo.bar
```

This will fail because the tap controller is expecting a different identity from what the proxies are serving.

As a workaround, you should install with:

```bash
linkerd install --cluster-domain foo.bar --identity-trust-domain foo.bar
```

Note: I've not tested the rest of the control plane operation, so there are no guarantees as to whether other things are broken when these two settings are not in agreement.

**Comment by alpeb** [comment]
From my understanding, in theory it shouldn't matter if the cluster domain differs from the trust domain. It appears this is a bug in the proxy because the tap controller simply hits the target proxy using its IP:
```
time="2019-11-04T22:14:17Z" level=info msg="Establishing tap on 10.1.0.136:4190"
```
and then just waits for the reply, which in this case never happens.

And the debug log on the target proxy shows something like:
```
DBUG [   312.556537s] admin={server=tap listen=0.0.0.0:4190} linkerd2_proxy::transport::tls::listen accepted connection from 10.1.0.64:49370 to None; attempting TLS handshake                                                               
DBUG [   312.556575s] tokio_reactor loop process - 2 events, 0.000s
DBUG [   312.556616s] tokio_reactor loop process - 1 events, 0.000s
DBUG [   312.556643s] admin={server=tap listen=0.0.0.0:4190 remote=10.1.0.64:49370} h2::codec::framed_write send; frame=Settings { flags: (0x0) }                                                                                            
DBUG [   312.556680s] admin={server=tap listen=0.0.0.0:4190 remote=10.1.0.64:49370} h2::server connection error PROTOCOL_ERROR -- read_preface: invalid preface;                                                                             
DBUG [   312.556713s] admin={server=tap listen=0.0.0.0:4190 remote=10.1.0.64:49370} linkerd2_proxy::app::tap tap connection error: http2 error: protocol error: unspecific protocol error detected                                           
DBUG [   312.556743s] admin={server=tap listen=0.0.0.0:4190 remote=10.1.0.64:49370} tokio_reactor dropping I/O source: 3
```
CC @olix0r

**Comment by ihcsim** [comment]
My guess is that the `name` declared [here](https://github.com/linkerd/linkerd2/blob/e91f2020db861d60b1e6d862a1ee6514f6c1909a/controller/tap/server.go#L131) should be using the trust domain, instead of the cluster domain.

**Comment by olix0r** [comment]
@ihcsim we _definitely_ shouldn't be manually building identity strings in various places. That should be a library function that is reused throughout the codebase

**Comment by olix0r** [comment]
@ihcsim we _definitely_ shouldn't be manually building identity strings in various places. That should be a library function that is reused throughout the codebase

**Comment by alpeb** [comment]
@ihcsim that uses the same logic used in the proxy template:
https://github.com/linkerd/linkerd2/blob/e91f2020db861d60b1e6d862a1ee6514f6c1909a/charts/partials/templates/_proxy.tpl#L57-L58

@grampelberg I agree tap should do a better job at exposing errors (also covered in #3518). But I still believe the proxy is the culprit here because trust domain doesn't necessarily require to match the cluster domain, as explained [here](https://github.com/linkerd/linkerd2/pull/2535#discussion_r267925203).

**Comment by olix0r** [comment]
@alpeb 

> But I still believe the proxy is the culprit here because trust domain doesn't necessarily require to match the cluster domain, as explained here.

Hm? AIUI, the tap controller is incorrectly using a clusterDomain when it should use a trustDomain. I don't think the proxy is doing anything incorrect? Or are we saying that the proxy doesn't provide sufficient error messages to the tap controller?

**Comment by alpeb** [comment]
I stand corrected. Like @ihcsim said, the identity string is being build incorrectly. I'm testing if fixing that and having different cluster an trust domains still works with tap.

**Comment by alpeb** [comment]
It works! I've created #3675 to fix that.

I approved yesterday the new integration tests for custom `--cluster-domain` (#3660) knowing that they only cover the tests in `install_test.go`, but more extensive tests would have uncovered a problem like this one. I'm thinking now we might wanna run all the integration tests in that scenario, which shouldn't hurt the overall tests running time anyways since those would be done in parallel. Agreed? CC @zaharidichev
