### ISSUE TITLE
2.7 control plane upgrade causes 503 errors in the data plane

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3537]
After upgrading the stable-2.5 control plane to the latest RC, the injected services started to show 503 errors. This is the result of a recent work to migrate the `destination` container into its own `Deployment`. While restarting all the pods in the data plane (so that the proxies picked up the new spec) resolve the problem, this may not be feasible for large cluster. A workaround may require users to temporarily uninject the services, to avoid downtime.

To reproduce:

1. Install a stable-2.5 control plane
1. Inject and deploy emojivoto 
1. Inject and deploy curl
1. From within the curl pod, run `curl -v web-svc.emojivoto/api/list`
   1. Expect a 200 response
1. Upgrade the control plane to the latest RC. Do not restart the data plane
1. Re-run the `curl -v web-svc.emojivoto/api/list` command
   1. Notice a 503 error
   1. Restarting the emojivoto **and** curl at this point will resolve the problem

Relevant logs from the `web-svc` pod:
```
WARN [   539.134884s] linkerd-destination.linkerd.svc.cluster.local:8086 linkerd2_proxy::proxy::reconnect connect error to ControlAddr { addr: Name(NameAddr { name: "linkerd-destination.linkerd.svc.cluster.local", port: 8086 }), identity: Some("linkerd-controller.linkerd.serviceaccount.identity.linkerd.cluster.local") }: received corrupt message
...
WARN [   835.640294s] resolve{authority=voting-svc.emojivoto.svc.cluster.local:8100}: linkerd2_proxy_resolve::destination::resolution Destination.Get stream error: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"
WARN [   835.640378s] resolve{authority=emoji-svc.emojivoto.svc.cluster.local:8100}: linkerd2_proxy_resolve::destination::resolution Destination.Get stream error: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"
WARN [   839.660914s] linkerd2_proxy::app::profiles error fetching profile for emoji-svc.emojivoto.svc.cluster.local:8100: Status { code: Unknown, message: "the request could not be dispatched in a timely fashion" }
WARN [   839.664641s] linkerd2_proxy::app::profiles error fetching profile for voting-svc.emojivoto.svc.cluster.local:8100: Status { code: Unknown, message: "the request could not be dispatched in a timely fashion" }
WARN [   839.664716s] linkerd2_proxy::app::profiles error fetching profile for web-svc.emojivoto.svc.cluster.local:80: Status { code: Unknown, message: "the request could not be dispatched in a timely fashion" }
WARN [   840.641603s] resolve{authority=voting-svc.emojivoto.svc.cluster.local:8100}: linkerd2_proxy_resolve::destination::resolution Destination.Get stream error: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"
WARN [   840.641694s] resolve{authority=emoji-svc.emojivoto.svc.cluster.local:8100}: linkerd2_proxy_resolve::destination::resolution Destination.Get stream error: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"
```

No obvious logs (to my untrained eyes) in the proxy.

The only relevant changes in the proxy's Helm template seems to be the `LINKERD2_PROXY_DESTINATION_SVC_NAME` (identity) environment variable as seen in the [PR](https://github.com/linkerd/linkerd2/pull/3407/files#diff-97d38a8542d07721180ecdb51a63a559R61-R62).

**Comment by adleong** [comment]
In the above PR, the `linkerd-destination` service changed so that it now points to the dedicated linkerd-destination deployment rather than the linkerd-controller-api deployment.  This is fine except for the fact that the `linkerd-destination` pods run under a different service account (`linkerd-destionation` rather than `linkerd-controller`) which breaks old proxies which are expecting the `linkerd-controller` service account.

**Comment by adleong** [comment]
@ihcsim what do you think about this:

Running two copies of the `linkerd-destination` deployment:

1. 
Deployment: `linkerd-destionation`
Service: `linkerd-destination`
Service Account: `linkerd-controller`
Old proxies use the `linkerd-destination` service and connect to a pod in this deployment, which runs in the `linkerd-controller` service account, which is what the proxy expects.

2.
Deployment: `linkerd-dst`
Service: `linkerd-dst`
Service Account: `linkerd-dst`
After upgrading the data plane, new proxies would use this new `linkerd-dst` service to connect to a pod in the `linkerd-dst` deployment which runs in the new `linkerd-dst` service account which the new proxies would be configured to expect.
(or any "new" name can be used here instead of `linkerd-dst`)

**Comment by adleong** [comment]
I believe this would require the following changes:

* Modify the install templates to run 2 copies of the destination controller as described above
* Modify the injector to configure proxies to connect to the new `linkerd-dst` service for discovery and to expect the new `linkerd-dst` service account

**Comment by Pothulapati** [comment]
In that case, We would also want `public-api`, to talk to the corresponding new destination as per https://github.com/linkerd/linkerd2/pull/3476

**Comment by adleong** [comment]
@Pothulapati yup, great point
