### ISSUE TITLE
External issuer support in Helm chart

### ISSUE THREAD

**Issue by StupidScience** [linkerd/linkerd2#3669]
### What problem are you trying to solve?

AFAIK there is no way to integrate with cert-manager via helm chart though i think it should have more customization option than CLI.

### How should the problem be solved?

Add boolean value to helm chart 
```
Identity:
  Issuer:
    External: false
``` 

### Any alternatives you've considered?

I see no alternatives here :)

### How would users interact with this feature?

```
helm install \
  --set Identity.Issuer.External=true \
  --set-file Identity.TrustAnchorsPEM=ca.crt \
  linkerd/linkerd2
```

**Comment by zaharidichev** [comment]
@StupidScience We have taken a bit more flexible approach with the helm chart compared to the cli. That being said at the moment we do not have a `bool` in the chart but a string field `Issuer.Scheme`. Setting that to `kubernetes.io/tls` (corev1.SecretTypeTLS) will work, given that you have the linkerd-identitiy-issuer secret in the `kubernetes.io/tls` format and managed by cert-manager. In fact in order to achieve the latter, you can follow some of the instruction right [here](https://github.com/linkerd/linkerd2/pull/3600#issue-329672028) Does that work for you?

**Comment by StupidScience** [comment]
@zaharidichev so, i think you should update the docs about helm chart installation as well according to issue https://github.com/linkerd/linkerd2/issues/3662 
Coz atm it is not clear how make it work.

Also, why do not automate all of these manifests creation via helm chart?

**Comment by zaharidichev** [comment]
>  i think you should update the docs about helm chart installation as well 
Working on it atm

> Also, why do not automate all of these manifests creation via helm chart?
What are you referring to more precisely?

**Comment by StupidScience** [comment]
> What are you referring to more precisely?

I mean all these dependent cert-manager resources can be created with linkerd's helm chart.

**Comment by zaharidichev** [comment]
@StupidScience 
Well because we really did not want to tie any cert-manager specific resources with linkerd. This is out of scope for us. In its core what we support is reading certs from tls typed secrets and continuously monitoring these secrets for changes. It just happens so that managing these certs can be achieved with cert-manager. But if there is any other piece of software that can do that, we can support it as well. This is why we prefer not to create any cert-manager resources.  Does that make sense?

**Comment by StupidScience** [comment]
Sounds reasonable.
I'll close it as docs will be added in https://github.com/linkerd/linkerd2/issues/3662
