### ISSUE TITLE
Idea: Consider adding a JS formatter like gofmt for more readable codebase

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3679]
@grampelberg pointed out in #3667 that frequently lines in our JS files are over 80 characters. We could install a JS formatter like gofmt to enforce linebreaks at 80 characters or less.

**Comment by scottcarol** [comment]
Other inconsistencies a formatter could solve: trailing commas, newline errors.

If there are other ideas, please add to this issue, so we can make decisions before beginning work.

**Comment by cynthia-sg** [comment]
Other inconsistencies would be: 

- use of double/single quotes

<img width="791" alt="3679_01" src="https://user-images.githubusercontent.com/1440981/70712766-d29f5500-1ce4-11ea-836a-f0b8ccec8efc.png">

- `propTypes` definition 

<img width="773" alt="3679_03" src="https://user-images.githubusercontent.com/1440981/70712802-dfbc4400-1ce4-11ea-937f-804dee9d6d4c.png">

<img width="791" alt="3679_02" src="https://user-images.githubusercontent.com/1440981/70712808-e480f800-1ce4-11ea-8c33-9623a488581f.png">

**Comment by cynthia-sg** [comment]
Perhaps a good solution for fixing some of these inconsistencies would be [Prettier](https://github.com/prettier/prettier). This code formatter provides a common ground for all styling and ensures that all outputted code conforms to a consistent style. Although, there are a few customisable things like:
* tab width
* use of tabs vs spaces for indentation 
* use of single quotes vs double quotes
* line columns number
* use of trailing commas
* use of semicolons at the ends of statements
* bracket spacing
* arrow function parenthesis
* and only a few others more due to `Prettier` tries to keep the number of those customisations under control, to avoid becoming too customisable.

#### How does Prettier work with linters like ESLint?
`Prettier` can replace all formatting rules such as `max-len`, `comma-style`, `keyword-spacing`… but it doesn’t help with code-quality rules such as `no-unused-vars`, `no-implicit-globals`… So, linter can be focused only on these rules.


**Note**: There is an extension for VS Code, which runs `Prettier` formatting every time you save.

**Comment by scottcarol** [comment]
This issue is largely closed by #3882 - @klingerf will open up follow-up issues for specific linting issues.
