### ISSUE TITLE
Linkerd scale testing

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3692]
We should put together a reproducible way to deploy Linkerd at a non-trivial scale and collect some baseline performance metrics from this cluster.  This will allow us to measure performance impacts of future changes for non-trivial clusters.

# Cluster Size and Configuration
* Linkerd installed in HA mode

* 49 emojivoto namespaces
  * each with 4 deployments (traffic, web, voting, emoji) of 5 replicas for a total of 20 pods per namespace
  * 20 pods per namespace * 49 namespaces = 980 pods
* (these pods are not very "connected".  each pod is connected to at most 1 upstream deployment of 5 replicas and 2 downstream deployments of 5 replicas each for a total of 15 connections)

* 1 slowcooker namespace
  * with 1 slowcooker deployment of 20 replicas
  * the slowcookers fanout traffic to each of the web services in each of the emojivoto deployments
* (these pods are highly "connected".  each pod is connected to 49 deployments of 5 replicas each for a total of 245 connections)

* total of 1000 pods

# Metrics to Gather

* total number of timeseries in Prometheus
* memory usage of control plane components, especially the destination controller and Prometheus
* CPU usage of control plane components, especially the destination controller and Prometheus
Pometheus query latency of the queries needed to serve the namespaces dashboard page.  (maybe can be measured with `time` and `promtool`)
* Proxy metrics payload size

**Comment by adleong** [comment]
Some prior art: https://github.com/linkerd/linkerd2/issues/3258

**Comment by ihcsim** [comment]
Here's my setup to test #3541. I think it's reasonable enough to be scripted, so that the setup is reproducible for future scale testing effort (across different cloud providers?).

The `emojivoto` application is repeatedly deployed to 50 namespaces, where each workload has 3 replicas. Hence, there are 20 injected pods in a namespace.

Create two zonal GKE clusters in `us-west1-a` and `us-east1-b` with 3 node pools:

Pool Name      | Node Count | Node Spec | Node Selector | Taint 
------------------- | ---------------- | --------------- | ------------------- | -------
`workers`         | 30 nodes     | 2CPUs, 7.5GB, preemptible | 
`control-plane` | 3 nodes       | 2 CPUs, 7.5GB | `linkerd.io/control-plane-component="true"` | `linkerd.io/control-plane-component=true:NoScheudule`
`monitoring`     | 1 node         | 4 CPUs, 15GB | `linkerd.io/control-plane-component=prometheus` | `linkerd.io/control-plane-component=prometheus:NoSchedule`

Label kube-system namespace to ensure admission webhooks don't interfere with critical workloads restarts:
```
k label ns kube-system config.linkerd.io/admission-webhooks=disabled
```

Add `tap` RBAC:
```
k create clusterrolebinding isim-tap-admin --clusterrole=linkerd-linkerd-tap-admin --user="<email address>"
```

Install Linkerd with Kustomize patches. The `kustomize.yaml` script can be found [here](https://gist.github.com/ihcsim/4b89e43929d98ffd65658356e761f868). The patches add resource requirements, node selectors and tolerations to the control plane components. The control plane YAML also have resource requirements for the proxies.

Install emojivoto using the `install-emojivoto.sh` shell script found in the same [gist](https://gist.github.com/ihcsim/4b89e43929d98ffd65658356e761f868). This script is a stripped-down version of `bin/test-scale`, to install only emojivoto across multiple namespaces. Note that all resource requirements are also removed from the workloads to ensure better node resource utilization.

**Comment by srv-twry** [comment]
@adleong 

> each with 4 deployments (traffic, web, voting, emoji) of 5 replicas for a total of 20 pods per namespace

What is "traffic"? I saw the `emojivoto.yaml` and couldn't find a deployment with name "traffic". Is it called `vote-bot`?

**Comment by ihcsim** [comment]
@srv-twry `vote-bot` is the right one.
