### ISSUE TITLE
Classify some gRPC status codes as non-errors

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#3729]
### What problem are you trying to solve?

Linkerd classifies all gRPC status codes as errors, other than `OK`. This can negatively affects a gRPC server's success rate, even when it is only returning things like `NOT_FOUND ` or `INVALID_ARGUMENT `.

For reference: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

### How should the problem be solved?

Classify some status codes as non-errors, specifically `NOT_FOUND` and `INVALID_ARGUMENT` (and maybe `UNIMPLEMENTED`?)

### Any alternatives you've considered?

The user could specify their own gRPC classification via ServiceProfiles, as described in #3376.

### How would users interact with this feature?

In Go:

https://godoc.org/google.golang.org/grpc/status
https://godoc.org/google.golang.org/grpc/codes

```go
import (
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

func (*MyGRPCServer) MyEndpoint(req *Request) error {
	return status.Errorf(codes.Unimplemented, "method MyEndpoint not implemented")
}
```

**Comment by anzellai** [comment]
I'm also supporting this proposal, as this is a well understood inconvenience, and where I work we are also embracing ServiceProfile as an interim solution.

Going forward, I think what would make more sense, is to use "policy" to define rules what are considered errors/OK, and can be attached to individual ServiceProfile or meshed Deployment.

Ideally we will have some sane defaults mapping *NOT_FOUND* and *INVALID_ARGUMENT* grpc error codes as non-errors.

This would make life so much easier.

**Comment by olix0r** [comment]
Having thought through this a bit more, see my [comments from the proxy PR](https://github.com/linkerd/linkerd2-proxy/pull/395#issuecomment-560781421) -- basically, it seems like _most_ status codes don't naturally map to 5XX server failures. Most indicate 4xx client failures. Let's get crisp on the exact set of errors codes that are actually errors and, after making _that_ change, ensure that this policy is documented on the website.

**Comment by olix0r** [comment]
I'd like to propose that only error codes 13-15 be considered failures. From [the docs](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md):

Name | Code | Description
-- | -- | --
INTERNAL | 13 | Internal errors. This means that some invariants expected by the  underlying system have been broken. This error code is reserved for  serious errors.
UNAVAILABLE | 14 | The service is currently unavailable. This is most likely a  transient condition, which can be corrected by retrying with a backoff.  Note that it is not always safe to retry non-idempotent operations.
DATA_LOSS | 15 | Unrecoverable data loss or corruption.

**Comment by adleong** [comment]
To be conservative, I think it makes sense to consider the following as 5xx style failures in addition to the ones @olix0r listed above:

* UNKNOWN(2)
* DEADLINE_EXCEEDED(4)
* ABORTED(10)

**Comment by olix0r** [comment]
@adleong why? specifically, `ABORTED` seems to indicate the caller did something to abort the request? `UNKNOWN` seems similarly questionable and likely to be used for application failures, especially given that `INTERNAL` exists for unknown server errors.

I agree about deadline exceeded, though.

**Comment by olix0r** [comment]
@adleong specifically, with regard to `ABORTED`, the doc says:

>  Use `ABORTED` if the client should retry at a higher level (e.g., when a client-specified test-and-set fails, indicating the client should restart a read-modify-write sequence).

**Comment by siggy** [comment]
One of the production services I work on returns `UNKNOWN` in cases that I'd consider a failure. It seems to be a pretty common pattern:
https://github.com/search?q=%22codes.Unknown%22+*.go&type=Code

I intentionally called out `NOT_FOUND` and `INVALID_ARGUMENT` in the issue description with the assumption that Linkerd2 should be conservative when classifying non-OK status codes as successful. I think it's preferable to classify the majority of codes as failure, and allow the end-user to reclassify them as success, rather than risk hiding actual failures by default.

**Comment by olix0r** [comment]
@siggy That's helpful context with `UNKNOWN`, I'm fine with that being considered a failure. I think the test is: does this correspond to an HTTP 5XX? Many of the status codes have clear analogs in the 4XX error codes:

`grpc-status` | HTTP translation | description
-- | -- | --
CANCELLED | 499 Canceled | The operation was cancelled, typically by the caller.
UNKNOWN | 500? | Unknown error. For example, this error may be returned when a Status  value received from another address space belongs to an error space  that is not known in this address space. Also errors raised by APIs that  do not return enough error information may be converted to this error.
INVALID_ARGUMENT | 400 Bad request | The client specified an invalid argument. Note that this differs from FAILED_PRECONDITION. INVALID_ARGUMENT indicates arguments that are problematic regardless of the state of the system (e.g., a malformed file name).
DEADLINE_EXCEEDED | 504 Gateway timeout | The deadline expired before the operation could complete. For  operations that change the state of the system, this error may be  returned even if the operation has completed successfully. For example, a  successful response from a server could have been delayed long
NOT_FOUND | 404 Not found | Some requested entity (e.g., file or directory) was not found. Note  to server developers: if a request is denied for an entire class of  users, such as gradual feature rollout or undocumented whitelist, NOT_FOUND may be used. If a request is denied for some users within a class of users, such as user-based access control, PERMISSION_DENIED must be used.
ALREADY_EXISTS | 409 Conflict | The entity that a client attempted to create (e.g., file or directory) already exists.
PERMISSION_DENIED | 403 Forbidden | The caller does not have permission to execute the specified operation. PERMISSION_DENIED must not be used for rejections caused by exhausting some resource (use RESOURCE_EXHAUSTED instead for those errors). PERMISSION_DENIED must not be used if the caller can not be identified (use UNAUTHENTICATED  instead for those errors). This error code does not imply the request  is valid or the requested entity exists or satisfies other  pre-conditions.
UNAUTHENTICATED | 401 Unauthorized | The request does not have valid authentication credentials for the operation.
RESOURCE_EXHAUSTED | 429 Too man  requests | Some resource has been exhausted, perhaps a per-user quota, or perhaps the entire file system is out of space.
FAILED_PRECONDITION | 412 Precondition failed | The operation was rejected because the system is not in a state  required for the operation's execution. For example, the directory to be  deleted is non-empty, an rmdir operation is applied to a non-directory,  etc. Service implementors can use the following guidelines to decide  between FAILED_PRECONDITION, ABORTED, and UNAVAILABLE: (a) Use UNAVAILABLE if the client can retry just the failing call. (b) Use ABORTED  if the client should retry at a higher level (e.g., when a  client-specified test-and-set fails, indicating the client should  restart a read-modify-write sequence). (c) Use FAILED_PRECONDITION  if the client should not retry until the system state has been  explicitly fixed. E.g., if an "rmdir" fails because the directory is  non-empty, FAILED_PRECONDITION should be returned since the client should not retry unless the files are deleted from the directory.
ABORTED | 409 Conflict? | The operation was aborted, typically due to a concurrency issue such  as a sequencer check failure or transaction abort. See the guidelines  above for deciding between FAILED_PRECONDITION, ABORTED, and UNAVAILABLE.
OUT_OF_RANGE | 416 | The operation was attempted past the valid range. E.g., seeking or reading past end-of-file. Unlike INVALID_ARGUMENT, this error indicates a problem that may be fixed if the system state changes. For example, a 32-bit file system will generate INVALID_ARGUMENT if asked to read at an offset that is not in the range [0,2^32-1], but it will generate OUT_OF_RANGE if asked to read from an offset past the current file size. There is a fair bit of overlap between FAILED_PRECONDITION and OUT_OF_RANGE. We recommend using OUT_OF_RANGE (the more specific error) when it applies so that callers who are iterating through a space can easily look for an OUT_OF_RANGE error to detect when they are done.
UNIMPLEMENTED | 501 Unimplemented | The operation is not implemented or is not supported/enabled in this service.
INTERNAL | 500 Internal Server Error | Internal errors. This means that some invariants expected by the  underlying system have been broken. This error code is reserved for  serious errors.
UNAVAILABLE | 503 Service Unavailable | The service is currently unavailable. This is most likely a  transient condition, which can be corrected by retrying with a backoff.  Note that it is not always safe to retry non-idempotent operations.
DATA_LOSS | 500 Internal Server Error Unrecoverable data loss or corruption.

This probably adds a few more into the failure category, but I think we should make the decision based on a reasonable interpretation of the spec.

**Comment by adleong** [comment]
It sounds like the final list of error codes is:
* UNKNOWN(2)
* DEADLINE_EXCEEDED(4)
* INTERNAL(13)
* UNAVAILABLE(14)
* DATA_LOSS(15)

UNIMPLEMENTED maps to a 5xx HTTP code, but that doesn't really feel right to me.

**Comment by tegioz** [comment]
Thanks, updated in https://github.com/linkerd/linkerd2-proxy/pull/395 and https://github.com/linkerd/linkerd2/pull/3736 👍

**Comment by riking** [comment]
RESOURCE_EXHAUSTED will also be issued by the framework, might be worth adding.
