### ISSUE TITLE
Follow helm chart standards

### ISSUE THREAD

**Issue by nesl247** [linkerd/linkerd2#3744]
## Feature Request
Please follow the standards set by helm.

### What problem are you trying to solve?
A lot of the helm chart is done differently than what is done by nearly every other chart.

Examples include:

* PascalCase values
* Using `.Values.Namespace` instead of `.Release.Namespace`
* Using `{{with .Values -}}`

### How should the problem be solved?

Follow helm standards.

### Any alternatives you've considered?

Nothing to consider

### How would users interact with this feature?

Release a new major version of the chart that uses the standards. When users upgrade, they will need to make changes to their installation.

**Comment by grampelberg** [comment]
We've discussed this in the past, some of these are possible and some are pretty tough:

> PascalCase values

Unfortunately it will require massive refactoring in the client code as the values are serialized out of go structures that must use PascalCase on that side. I'm not opposed, it is just a minor improvement for a quite a bit of work.

> Using .Values.Namespace instead of .Release.Namespace

We can't do anything here because of how helm is managing namespaces. It'll get a little bit better with v3 and I'd love to revisit, just not something we can do until v2 is deprecated in a year.

> Using {{with .Values -}}

This is an easy change that I'm totally behind.

**Comment by nesl247** [comment]
I'm not sure I understand the issue you have with the way it manages namespaces. If you put the namespace explicitly in the templates, instead of relying upon helm to automatically add it, the release namespace will work just fine.

Regarding the PascalCase values, I'm not sure I understand. Are you saying that the helm charts are being automatically built? Is there a reason for this?

**Comment by grampelberg** [comment]
The core issue is that we're using the helm chart as part of the implementation of `linkerd install`. This means that we need to pass some of the go-isms down to the chart itself currently (like PascalCase and the namespaces).

**Comment by nesl247** [comment]
Personally I'd advise not having that coupling. This is the first time I've heard of this being done, and certainly doesn't lead to a good first experience with the helm charts. I honestly did not trust them at all because of their non-standard design. Because of this we had not started to try out linkerd yet.

On top of this, it looks like either the coupling has required the installation of prometheus and grafana, as there doesn't appear to be any way to disable them. Or am I misunderstanding the coupling? It seems like the only way to not install them is if `linkerd install` makes them optional.

**Comment by grampelberg** [comment]
> Personally I'd advise not having that coupling.

The alternative is to maintain two distinct install flows which is unfortunate for obvious reasons.

> On top of this, it looks like either the coupling has required the installation of prometheus and grafana

Prometheus is required, grafana isn't ... but you'll get a semi-broken experience today if you disable it. We're in the process of splitting those out into their own charts and making them optional. Unfortunately, we won't be able to actually use the third party charts for them because of limitations inside helm itself.

**Comment by javaducky** [comment]
@grampelberg , I can go ahead and cleanup the YAML templates to discontinue use of the `with .Values` shortcut.

**Comment by grampelberg** [comment]
That'd be awesome @javaducky !

**Comment by ihcsim** [comment]
Reopening this issue, as #3765 didn't address all the items listed in this issue.

**Comment by alpeb** [comment]
On 2.12 the main chart got replaced with a new one following best practices, so closing this item out.
