### ISSUE TITLE
Refactor TLS verification logic

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#3828]
As @adleong pointed out [here](https://github.com/linkerd/linkerd2/pull/3811#discussion_r357318209), it will be wise to consolidate the details of verifying the roots against the issuer cert even more through combining that logic into a single method.

**Comment by ihcsim** [comment]
Thanks for creating this issue. I am wondering if we can untag this as a p0, and spend some times post 2.7 to revisit the abstraction and interfaces of the `pkg/issuercerts` package. I like the motivation behind the package, where we try to unify the different TLS assets retrieval and verification mechanisms. I think at present, trying to get it to work cleanly with the different consumers (i.e. CLI, `healthcheck`, `identity`) have proven to be challenging, due to the constraints imposed by the surrounding existing code. This package will really help to keep all the important logic in one place, and I just don't want us to rush it due to the current time constraint. LMKWYT.

**Comment by grampelberg** [comment]
Do we have a concrete plan for what we'd like to do? Definitely doesn't feel like a 2.7 thing unless it is explicitly blocking some behavior. I'm a little sensitive to refactors in general unless they're serving a specific goal.

**Comment by zaharidichev** [comment]
its certainly a post 2.7 thing. I think this is an imporat refactor as @ihcsim points out. Not massive, but it touches quite a bit of areas. The point of it all is to make a final pass over the tls data extraction of verification logc. Howe we represent a issuer + roots certs together, how we verify them, how we parse them, etc. This currently spans the issuercert package as well as the tls package. It will be great to unify that all together. This refactor should not manifest in any changes to functionality or UX
