### ISSUE TITLE
stat: Suport omitting unmeshed resources

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3871]
I frequently want to monitor a cluster with a command like `watch linkerd stat po -A`; but this includes all unmeshed (kube-system, etc) resources as well. I don't really care about unmeshed resources when I'm using Liinkerd.  I'd prefer that we provide a flag to _opt-in_ to view unmeshed resources; but I'd live with a flag that let me opt out.

**Comment by olix0r** [comment]
Alternatively, if we supported label selectors, this could be a simple label selector query.

**Comment by mayankshah1607** [comment]
Does https://github.com/linkerd/linkerd2/pull/4040 fix this issue?

**Comment by kleimkuhler** [comment]
@mayankshah1607 This is helpful for displaying meshed pods:
```
linkerd stat -A -l linkerd.io/control-plane-ns pods
```
Unfortunately it doesn't cover all cases such as deployments since they do not have a label that can be selected on. There is an inject annotation, but those cannot be selected on.

A possibility is that we just do not display rows that have a `0` meshed pod count. It would be fairly straightforward to implement and would cover any type of resource since `0/x` meshed pods would just not be displayed. An opt-in view would show all rows regardless of number of meshed pods.
