### ISSUE TITLE
When a CI build fails, provide access to the control plane logs

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#3912]
### What problem are you trying to solve?

When there's a CI build failure, the test clusters get cleaned up and we're only left with the output of the failed test, which often isn't enough.

### How should the problem be solved?

It would be very helpful to have access to the control plane component logs. We could catch the error before cleanup, fetch the logs, pack them and upload them into the CI build artifact storage, and then proceed to cleanup.

### Any alternatives you've considered?

- We could avoid the clusters being cleanup up upon failure. But this would require manually cleaning them up every time this happens.
- Instead of uploading all the logs, we could just fetch the error logs and append them to the failed test output. But we might need info from the non-error logs as well.

### How would users interact with this feature?

They would click on the failed run under the Actions tab, and the file should show up under the artifacts section.

**Comment by ihcsim** [comment]
If you are going to invest time into hardening our CI, per https://github.com/linkerd/linkerd2/issues/3911#issuecomment-573132373, we should consider running the integration tests on separate clusters, so that any failures with one build won't block the entire pipeline. We can keep failed clusters around for diagnosis, and if on Azure, use something like Azure Function to schedule removal of orphaned clusters at the EOD.

**Comment by alpeb** [comment]
This is mostly about the `kind` tests, which already run in separate clusters. We definitely could leave the clusters around in case of failure and have a separate GC process clean them up. One disadvantage is that to debug a failure, people would have to be granted access into the build server, whereas a log dump would be readily available.

**Comment by ihcsim** [comment]
> One disadvantage is that to debug a failure, people would have to be granted access into the build server

If we make the tests run on throw-away AZ public clusters, we can access them remotely with `az aks get-credentials`. I think when it comes to debugging and reproducing test failures, access to the entire clusters is more useful than just logs.

**Comment by grampelberg** [comment]
If we ignore the implementation detail (clusters, kind, ...), being able to automate the environment provisioning and switch between backends seems like a top priority.

**Comment by alpeb** [comment]
> > One disadvantage is that to debug a failure, people would have to be granted access into the build server
> 
> If we make the tests run on throw-away Azure public clusters, we can access them remotely with `az aks get-credentials`. I think when it comes to debugging and reproducing test failures, access to the entire clusters is more useful than just logs.

I believe it's important to distinguish between quick testing in a low resource consumption environment such as kind, and cloud integration testing; and IMO both have their place in our suite. Are you suggesting we drop the kind jobs and run all on AKS?

**Comment by alpeb** [comment]
> If we ignore the implementation detail (clusters, kind, ...), being able to automate the environment provisioning and switch between backends seems like a top priority.

Yes, there's a lot of boilerplate in `workflow.yaml` that we can abstract away and parametrize for different cluster types.

**Comment by ihcsim** [comment]
I notice that I got ahead of myself. (Sorry!) Basically, I think when the integration test failed, having easy, direct access to the failed clusters is more helpful than access to the bundled logs.

---

> Are you suggesting we drop the kind jobs and run all on AKS?

My understanding is that many (not all) CI test failures from the past 2 months, along with these [workarounds](https://github.com/linkerd/linkerd2/blob/36ddc263c26e3bda772fedd1dc02605d02277795/test/install_test.go#L86-L95), are related to the kind infrastructure setup. And there are some new, recent ones related to kubeconfig in concurent kind clusters. If that's true, then we should evaluate other more reliable solutions.

> I believe it's important to distinguish between quick testing in a low resource consumption environment such as kind, and cloud integration testing

Do the matrix in the quick tests (when added) resemble the cloud integration test?

**Comment by alpeb** [comment]
Thanks for the feedback @ihcsim.

So one thing to decide is whether to keep kind clusters around whenever there's a failed test (and provide the appropriate GC), or providing other debugging means like the current proposal.
I'd like to get @siggy's opinion as well.

OTOH I'd like to defend our choice of kind for CI. The recent problems were mainly created by lack of disk space, which shouldn't be a big deal. As for the event warnings, that's an issue I've also seen in k3s and minikube (kubernetes/minikube#5235), not fatal errors as they're resolved through retries. Still IMO not reason enough to drop kind.
Oh and about the kubeconfig issue, is that related to a comment I made last week? I saw an error in CI that I thought was related to that, but it ended not being so.

> Do the matrix in the quick tests (when added) resemble the cloud integration test?

They're the same, except for the `custom_domain` one (testing `--cluster-domain`) which is not run in the cloud because it requires configuring the cluster when it's created. And in kind the items in that matrix run concurrently, in cloud sequentially.

To reiterate, I still think we should provide a common abstraction over cloud providers tests (using whatever tool deems appropriate (pulumi or terraform like you suggested)), but that can remain a separate step in the CI flow, after the kind tests which give us a faster feedback when there's a failure.

CC @kleimkuhler

**Comment by siggy** [comment]
Appreciate all the thoughts on this, my brain dump on a few points...

### 1) What debugging info to provide? Logs? Clusters?

I agree that access to the cluster is ideal. I do recognize cluster access creates challenges around authentication and GC, all solvable problems, just more work.

I also agree an easier first step would be to collect all k8s logs, events, workload/pod states, and push them up as an artifact. We could do this for all builds, not just failed ones. The `kind_cleanup` step seems like a natural place, as it's always guaranteed to run:
https://github.com/linkerd/linkerd2/blob/0ee409eaa359c5b441e177164d116f5f53eb3da4/.github/workflows/workflow.yml#L343-L346

`kind` even provides a `kind export logs` subcommand. I'm not sure if that would give us everything, but it's a start:
https://kind.sigs.k8s.io/docs/user/quick-start/#exporting-cluster-logs

### 2) Cloud vs. Kind

Fortunately, our integration tests are already unaware of whether they are running in the cloud or kind:
https://github.com/linkerd/linkerd2/blob/0ee409eaa359c5b441e177164d116f5f53eb3da4/bin/test-run#L3-L7

I think there's value in running both. `kind` provides a cheap way to spin up and down lots of clusters quickly. Cloud tests allow us to run more resource-intensive tests in real-world scenarios.

We definitely need to solve #3911, at least for master merges, and I think that may involve provisioning AKS clusters on-demand, or keeping a pool of them warm.

### 3) `kind` stability
In late 2018 the folks behind `kind` reported they run [10,000 jobs/day](https://youtu.be/pz0lpl6h-Gc?t=130), testing Kubernetes itself, so I'm confident any stability/flakiness issues we're having in our integration tests is our own tests (mostly my fault ;) ), and not issues with `kind`.

Our integration tests could definitely be more stable. Some of this is due to limited resources on our singleton packet host, which has motivated hacks like [limiting parallel clusters](https://github.com/linkerd/linkerd2/blob/0ee409eaa359c5b441e177164d116f5f53eb3da4/.github/workflows/workflow.yml#L230) and [retrying cluster creation](https://github.com/linkerd/linkerd2/blob/0ee409eaa359c5b441e177164d116f5f53eb3da4/.github/workflows/workflow.yml#L220-L226). The tests are also [very sensitive to log output](https://github.com/linkerd/linkerd2/blob/0ee409eaa359c5b441e177164d116f5f53eb3da4/test/install_test.go#L61-L66), err'ing on the side of failing a healthy build rather than letting a broken one through. I'm happy and motivated to work through improving them. One quick win could just be to use more than one packet host.

**Comment by ihcsim** [comment]
@alpeb @siggy Thanks for sharing your thoughts. My concern lies in the amount of maintenance work we have to put in to support our current kind infrastructure setup; not kind itself. (I use kind daily.) 

I just don't think we should be bitten by low-level infrastructure issues around disk space, [networking](https://github.com/linkerd/linkerd2/blob/36ddc263c26e3bda772fedd1dc02605d02277795/test/install_test.go#L86-L95) (which I attribute to some lower non-k8s factors in kind, docker, vm etc.), and concurrent CI runs (#3911). These problems are already solved by the cloud. Do we feel like, after 2 months of tuning our CI, we are at a place where the amount of manual maintanence tasks will start to diminish going forward? However we are going to tackle this, I think we should aim at removing manual administrative tasks from the pipeline, to get o the point where CI becomes this seamless background thing.

As for collecting integration tests k8s logs, events etc., any thoughts on where these artifacts will be stored? It should be a location that everyone on the team has access to (S3, GCS, GH Actions (how long does Actions retain the artifacts for?) etc.), without needing a CI administrator. I'm just concerned that this approach might appear easy to code, but not necessarily easy to maintain and scale, without introducing new manual administrative tasks.

**Comment by alpeb** [comment]
Thanks again guys. We're on the same page about having CI be as automated as possible, and that's indeed one of the main goals of the overall CI revamp project. 

Now let me answer some punctual questions:
> kind even provides a kind export logs subcommand. I'm not sure if that would give us everything, but it's a start:

`kind logs` ended up being pretty extensive. You get logs for all the pods and  containers in all the namespace, containerd, kubelet, etc. :+1: 

> As for collecting integration tests k8s logs, events etc., any thoughts on where these artifacts will be stored? It should be a location that everyone on the team has access to (S3, GCS, GH Actions (how long does Actions retain the artifacts for?) etc.), without needing a CI administrator

We'll use Github Actions artifacts, that we already used for storing the linkerd's source code when we had in place the workaround for the `checkout` action. That's hosted by Github, publicly accessible, associated to each build run.

> The tests are also [very sensitive to log output](https://github.com/linkerd/linkerd2/blob/0ee409eaa359c5b441e177164d116f5f53eb3da4/test/install_test.go#L61-L66), err'ing on the side of failing a healthy build rather than letting a broken one through. I'm happy and motivated to work through improving them.

@siggy we'll be soon drafting the complete plan for the CI revamp. I think that'll be mostly infra stuff, but you're welcome to jump in if you'd like to improve the tests :+1:
