### ISSUE TITLE
Add an integration test for CNI

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#3944]
It should be quite easy to add an integration test for CNI. In light of some recently uncovered problems (#3941), this will be quite useful. What we can do is follow the same logic we have for testing the external cert issuer and apply it to the CNI plugin, effectivelly spinning a separate cluster.

**Comment by christyjacob4** [comment]
Hey @zaharidichev  I'd like to take this up

**Comment by zaharidichev** [comment]
@christyjacob4 Feel free to take a stab. You can see some of my previos work on it right here https://github.com/linkerd/linkerd2/pull/3954/files. At the time our CI was causing us trouble when trying to implement this so it was not possible. Now.. since there have been quit a lot of changes on the CI part it might be the case that things are easier. I am sitll a bit skeptical though...

**Comment by christyjacob4** [comment]
Thanks @zaharidichev  That will help me understand it better. Can I understand what was it, that was causing the issue?

**Comment by zaharidichev** [comment]
The problem was that kind (which is what we use for integration testing) uses a very rudimentary network setup called kind-net. This does not support CNI plugin chaining. I tried to deisable that and install calico in place (as far as I remember correctly), but this did not quite work either. The just of it is that kind was nto built with the full fledged functionality of the CNI interface so that is why we cannot test it on CI.

**Comment by christyjacob4** [comment]
So you're saying that you were unable to enable CNI on the CI?

**Comment by christyjacob4** [comment]
@zaharidichev  What are the testcases to be checked as part of the Integration tests? Here are a few that come to mind
1. Install linkerd with cni plugin
2. Install a sample application without CNI, 
3. Check that you are able to make a request the pod and get a response back
4. Install the application with CNI
5. Check that you are able to make a request the pod and get a response back

What do you think?

**Comment by zaharidichev** [comment]
The CNI plugin is in fact a facility to configure the ip tabls rules, much like the InitContainer, just a different way of doing it. That being said, you cannot install an application with or without CNI. You can install Linkerd with the CNI plugin, which means you need to install the CNI plugin beforehand. Then if linkerd works and you do some basic tests on an app that is meshed, this means the CNI plugin works as expected. This is what I attempted to do in the code I wrote but unfortunatelly I had some difficulties because of Kind and the approach it takes to network setup.

**Comment by christyjacob4** [comment]
@zaharidichev Thats exactly how I understood it but sorry I worded it the wrong way. 
In order to test if it is working correctly on the CI, do I have to raise a PR? is that the only way to test it?

**Comment by ihcsim** [comment]
@christyjacob4 This task isn't suitable for a fork. Since kind isn't the right infrastructure for this test, we will have to run this on the remote GKE clusters, which is part of the CI [`cloud_integration_test`](https://github.com/linkerd/linkerd2/blob/caf4e61daf16803324deb3a0093b25912e1c5c6a/.github/workflows/cloud_integration.yml#L71-L119) job. That job only get triggered by events in `master`. IOW, there isn't a way for you to test your code change.

For posterity, I think all we need to do is to extend the `install_cni_test.go` file to:

1. Install the CNI plugin: (on GKE) `linkerd install-cni --dest-cni-bin-dir=/home/kubernetes/bin|kubectl apply -f -`
1. Check the CNI installation: `linkerd check --pre --linkerd-cni-enabled`
1. Install the Linkerd control plane: `linkerd install --linkerd-cni-enabled|kubectl apply -f -`
1. Check the control plane installation: `linkerd check`
1. Install the emojivoto application: `linkerd inject https://run.linkerd.io/emojivoto.yml | kubectl apply -f -`
1. Check the data plane: `linkerd -n emojivoto check --proxy`

**Comment by Pothulapati** [comment]
I'm working on this, and will be following the steps mentioned by @ihcsim above!
