### ISSUE TITLE
linkerd completion command does not work as expected

### ISSUE THREAD

**Issue by mayankshah1607** [linkerd/linkerd2#3999]
## Bug Report
The `linkerd completion` command does not work as expected on zsh.

### What is the issue?
The completion scripts are generated, but sourcing them does not provide shell completion. Not sure if this error is restricted to only zsh.

### How can it be reproduced?
Run:
```bash
$ source <(linkerd completion zsh)
```
Completion does not work
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.16
- Cluster Environment: (GKE, AKS, kops, ...) minikube
- Host OS: linux
- Linkerd version: stable-2.6

### Additional context
Could be an issue with cobra completion script generator. Check https://github.com/spf13/cobra/issues/881

**Comment by grampelberg** [comment]
Looks like this is more about the instructions being wrong than a blocker bug itself?

**Comment by aisrael** [comment]
I was able to get linkerd shell completion to work on oh-my-zsh on macOS (10.15) by:

- First either add `autoload -U compinit && compinit` to `.zsrhrc` or use the [`zsh-completions` plugin](https://github.com/zsh-users/zsh-completions#oh-my-zsh) for oh-my-zsh
- Then, instead of `linkerd completion zsh > "${fpath[1]}/_linkerd"` I used `linkerd completion zsh > "~/.oh-my-zsh/completions/_linkerd"` (not that it matters, it's just that `${fpath[1]}` pointed to another oh-my-zsh plugin)

But what really got it working was changing the line 14 in the `_linkerd` script from:

```
'(-L --linkerd-namespace)'{-L,--linkerd-namespace}'[Namespace in which Linkerd is installed [$LINKERD_NAMESPACE]]:' \
```

to

```
'(-L --linkerd-namespace)'{-L,--linkerd-namespace}'[Namespace in which Linkerd is installed \[$LINKERD_NAMESPACE\]]:' \
```

With the `[` and `]` characters in the flag description escaped (thanks to clap-rs/clap#771 that pointed the way).

Indeed, it looks to be an issue with `spf13/cobra`, in particular, following the links from spf13/cobra#881:
- this pull request submitted a fix: https://github.com/spf13/cobra/pull/885
- but it was superceded by this: https://github.com/spf13/cobra/pull/899
- but the new zsh completion logic was revamped in https://github.com/spf13/cobra/pull/1070

Unfortunately, the changes in https://github.com/spf13/cobra/pull/1070 still haven't been released.

So... looks like we just have to wait for a new release of `spf13/cobra`, _or_ avoid using square brackets in the flag description.

**Comment by alpeb** [comment]
@aisrael good investigation :+1:  Cobra's releases are taking ages, so for now I'd vote for getting rid of the brackets. Would you be up for a PR? :wink:

**Comment by Flowkap** [comment]
Any updates on this issue? Is really noone using zsh completion? I'm trying out linkerd the first time and using oh-my-zsh as well (Linux). Still doesnt work. At least someone have a ready regexp for replacing the broken brackets on the fly? I will workround for now doing it manually. 
Anyhows linkerd seems awesome ^^

**Comment by jiraguha** [comment]
simple `()` will also work fine

**Comment by olix0r** [comment]
We've been patiently waiting for the upstream fixes, but if there are workarounds we can apply within Linkerd, we'd _love_ a PR.

**Comment by jiraguha** [comment]
> We've been patiently waiting for the upstream fixes, but if there are workarounds we can apply within Linkerd, we'd love a PR.

As I proposed, "simple ()" should work fine... PR 👆
