### ISSUE TITLE
Enable TLS for remote cluster gateways

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4127]
After the service mirroring component is merged, we want to enable tls-ed traffic between clusters. Assuming that our ingress is meshed and we have certs that share a common root, we need to be able to convery the remote identitiy that needs to be used when talking to the remote ingress. This can happend via an annotation on the mirrored service. I supposed this can actually happen without any changes to the proxy or the proxy API. What we need to do is the following.

- Have an annotation on the remote service `mirror.linkerd.io/remote-gateway-identitiy`
- Use that annotation when creating the a `WeightedAddr` in the `endpointTranslator.Add` - currently that happens only for non headless services. 

Now that I look at the code a bit more closely, it seems to me that it would be better to put the annotation onto the endpoints object itself, as it makes it easier to set it in the translator. 

@adleong @grampelberg Thoughts ?

**Comment by adleong** [comment]
I think that sounds more or less right.  I'd imagine that users would put the identity annotation on the gateway service itself so as to reduce coupling between the mirrored service and the gateway service.

**Comment by zaharidichev** [comment]
@adleong yes I imagine the same. However this will have to make its way to the local Endpoint, right? And be updated accordingly if the gateway changes

**Comment by adleong** [comment]
Yes, that sounds right to me.

**Comment by grampelberg** [comment]
> Have an annotation on the remote service mirror.linkerd.io/remote-gateway-identitiy

Won't we know the identity from the service account?

**Comment by adleong** [comment]
We need to know the service account of the gateway pods, which isn't intrinsically knowable from the gateway service.

**Comment by adleong** [comment]
The problem is that the gateway service may be backed by a number of pods which are running with different service account and thus have different identities.  This scenario would have a single externally facing load balancer IP mapping to multiple different identities and will not work for us.  

Having the user specify an identity on the gateway service makes it explicit that the service is uniformly backed by a single identity.

It is possible to do this lookup automatically, but a bit complicated.  We would need to look up all pods in the service, and look at their identities.  If not all of the pods have the same identity, we would need to somehow communicate to the user that this is an invalid state.
