### ISSUE TITLE
Automate the generation of the Helm chart's README files

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#4156]
Leverage a tool like [helm-docs](https://github.com/norwoodj/helm-docs) to generate the Helm chart's README files automatically based on annotations in the values.yaml files, prior to publishing the charts in CI.

**Comment by alpeb** [comment]
This would save us some time for sure... Added a couple of labels

**Comment by GMarkfjard** [comment]
Would love to pick this up as a part of my open source contribution course!

@alpeb Could you assign me to this?

**Comment by alpeb** [comment]
Thanks @GMarkfjard , that'd be amazing!

**Comment by GMarkfjard** [comment]
So when creating the CI steps for the generation, where would you want to have them? I figured `release.yml` should obviously contain a step for generating the readme:s so that the repo gets the generated readme:s. Would it be beneficial to also put it in, say, `static-checks` for reading any updates in a PR? 

@alpeb

**Comment by alpeb** [comment]
@GMarkfjard The problem with putting the README sgeneration in CI is that it'd require CI pushing changes into the repo, which can complicate things a bit. How about having a new script under `bin/` for generating this, to be run manually? And then have in `static-checks.yml` something that checks that the READMEs are up-to-date. Similar to the "Proto diff" job we have in there that checks the protobuf generated code is current.
