### ISSUE TITLE
proxy: Decouple controller configuration from profiling

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4158]
Our integration tests provide a mocked controller to integration tests so that they can perform discovery as they would in production. But they can be quite brittle, especially as the controller code is used in more places, especially the profiling use case.

The profiling use case, especially, should support traffic to an arbitrary number of services from an arbitrary number of clients, etc. In these cases, we really just want to provide a set of data (say, a JSON file or directory of JSON files) that can be used to satisfy the controller API. We do **not** want to have to manually instrument the controller logic in the profile's main.

The priorities goals are (in order) as follows:
1. Decouple the controller configuration from profile tests, so that profile test configurations can grow without changing code.
2. Be able to run the controller in a dedicated process so that it is not included in profiling.
3. Cleanup existing tests, making it easier to add new integration tests

I assume that any work in this space should target tokio-0.2 (not 0.1)

**Comment by hawkw** [comment]
Ideally, I think we want the setup of a mock controller to be more declarative than imperative. In the current design, each test is basically responsible for specifying exactly what RPC calls the mock controller should expect and how it should respond to them. This means that each test has to be aware of exactly how the controller behaves in a particular cluster state, making it easy to write tests that don't really simulate real behavior. In an ideal world, we would create a mock controller by specifying a mock cluster state, rather than a particular sequence of calls.

**Comment by hawkw** [comment]
Started on a standalone Destination server: https://github.com/linkerd/linkerd2-mock-dst 

Right now, it's not used in any of the existing integration tests, as it doesn't support everything the current tests need. However, it should be useable as a standalone process in benchmarks.

**Comment by hawkw** [comment]
This is closeable now that we're using `mock-dst` in the profiling suite, right?
