### ISSUE TITLE
Upgrade client-go for k8s v1.18

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4191]
Kubernetes v1.18 is due out soon. However, we will need to take care to upgrade `client-go`, as many APIs have changed (to use `context` as they should have).

Before any code changes, we need to enumerate our dependencies that have transitive `client-go` dependencies to determine an upgrade path.

**Comment by olix0r** [comment]
cc @adleong

**Comment by adleong** [comment]
This is blocked on a release from smi-sdk-go because we need to keep our client-go version synchronized.

**Comment by Pothulapati** [comment]
I tried working on this, as `smi-sdk-go` has been updated to `v1.18`. 

But Now the problem is https://github.com/kubernetes/client-go/issues/741. This is because `gnostic` broke their api in https://github.com/googleapis/gnostic/pull/155, and client-go, etc uses the unbroken version while `kube-openapi` was upgraded to `0.4.1`. We use `apiextensions-apiserver` (which takes a dependency on `kube-openapi`), and has to be updated to `v1.18` as it uses `client-go` which we can't as there are breaking changes between those versions.

A fix is targeted for k8s v1.19 which is very close, and I will jump on this back again once that happens!
