### ISSUE TITLE
Provide a stat(like) command for remote services

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4252]
We might want to have a command that much like stat displayes stats about remote services and the traffic flowing to them with some additional relevant information such gateway, cluster name, etc. I am imagining something like: 

```
LOCAL_NAME            REMOTE_NAME  NAMESPACE  CLUSTER_NAME  GATEWAY_NAME     GATEWAY_NAMESPACE  LATENCY_P50  LATENCY_P95  LATENCY_P99
service-1-cluster-a   cluster-a    test       cluster-a     default-gateway  test               50ms         75ms         150ms  
service-1-cluster-b   cluster-b    test       cluster-b     some-gateway     test               50ms         75ms         150ms  

```

**Comment by zaharidichev** [comment]
cc  @grampelberg @adleong

**Comment by adleong** [comment]
Where would the latencies be measured from?  Clients in the local cluster?  Clients in both clusters? On the server side?  From the gateway?  This difference is especially important for cross-cluster traffic because the cross-cluster hop will likely introduce significant latency.

I might take a step back here and think about what question the user is trying to answer.  

Can that question be answered by something like `linkerd stat deploy/foo --to svc` to see stats for traffic from foo to the mirror services?

**Comment by zaharidichev** [comment]
> Where would the latencies be measured from? 

They would be measured for clients initiating connections to the mirrored services, so yes the results I beleive shall be much like linkerd stat deploy/foo --to svc  fo traffic goign towards these services. The idea is that we would be able to provide a bit more data in order to identity that this is a remote srevice. WDYT ? We can scratch the whole idea and just rely on `stat` as it is atm

**Comment by grampelberg** [comment]
Stat is confusing enough for folks that my preference is to have this be a multi-cluster specific command. We can fill out all the options for end users and give them a good UI to see exactly what's happening outbound. Remember that cloud users are charged for egress, so a very specific command around this is going to be extremely beneficial for them.
