### ISSUE TITLE
Tag name contain redundant symbols

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4298]
I have noticed that recent tag names contain chars that cause problems. For example:

This is fine: 
```
[12:23] (master) | git name-rev --tags  00261033
00261033 tags/edge-19.11.2
```

This is not: 
```
[16:31] (zd/multicluster-checks) | git name-rev --tags  64aff41f
64aff41f tags/edge-20.4.4^0
```

The result of that is that if you check out an edge tag , build the cli and try to install linkerd, it will fail because the CLI will perform a regex match on the version and it will be illegal.

**Comment by alpeb** [comment]
Good catch :+1: 
I believe this is happening since we sign release tags, which creates "annotated" tags instead of lightweight tags. The former are separate git objects unlike the latter which are just a pointer. So `^0` is sorta the way of linking that tag object with its commit. I'll push something to fix this.

**Comment by zaharidichev** [comment]
Ahh.. that explains things. I was wondering why this started happening at a certain point in time.
