### ISSUE TITLE
Multicluster testing

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4387]
As a start you need to go through the [tutorial](https://linkerd.io/2/features/multicluster_support/) to bring yourself to a state where you can experiment with some other scenarios.

I have noted actions that take place on the local cluster with (A) and actions that take place on the remote cluster with (B

- [ ] Test service deletion from the remote cluster 
   - simply delete one of the exported services (B)
   - and make sure this is reflected on the local cluster (A)
- [ ] Test invalidating one of the remote services (removing the gateway name annotation)
   - remove the `mirror.linkerd.io/gateway-name` from the remote service that indicates the name of the cluster. (B)
   - make sure the service is deleted from the local cluster (A)
   - make sure this is reflected in the `num_services` on the `linkerd cluster gateways` cmd (A)
   - bring back the annotation (B)
   - make sure everything returns back to normal (A)
- [ ] Test invalidating one of the remote services (pointing it to an non existent gateway)
   - change the `mirror.linkerd.io/gateway-name` on the remote service to point to a gateway that does not exist (B)
   - Make sure the local service has its endpoints blanked (A)
   - Make sure the `linkerd cluster gateways` command reflects the fact that this service is not paired with the gateway anymore (A)
   - Change back the annotation (B)
   - make sure everything returns back to normal and the service is paired with the gateway (A)
- [ ] Test deleting the gateway
   - simply delete the gateway from the remote cluster (B)
   - make sure the endpoints of the local mirrored services are blanked (A)
   - make sure `linkerd cluster gateways` corresponds to the state (does not have any gateways) (A)
   - recreate the gateway (B)
   - make sure state goes back to normal and the remote mirrors have their endpoints populated with the new external IP of the gateway (A)
- [ ] Test breaking the gateway
   - update the gateway service and change its `mirror.linkerd.io/gateway-identity` to some random value (B)
   - this will cause the prober to fail and consider the gateway unreachable (A)
   - make sure that the gateway shows up as no Alive in the `linkerd cluster gateways` cmd (A)
   - make sure that when you run `linkerd check` the checks report to you that not all gateways are alive (A)
   - change back the annotation to its previous value (B)
   - make sure everything returns back to normal (A)
- [ ] Test deleting the credentials from the local cluster
   - simply delete the secret containing the remote credentials from the local cluster (A)
   - make sure the `linkerd cluster gateways` cmd does not show up any output (A)
   - make sure that the services that were mirrored are now not present (A)
   - recreate the secret (A)
   - make sure the services are back in place (A)
   - make sure the gateway is visible when you run `linkerd cluster gateways` and that it has the correct number of gateways (A)
- [ ] Scale testing
   - Create 500 remote services (in 5 different namespaces) (B)
   - Mirror them all (B)
   - Create a traffic split that has 500 leafs pointing to the mirrored services (A)
   - From a test container, hit the traffic split svc repeatedly and make sure all of your requests succeed
- [ ] Security
   - Ensure unmeshed communication through the gateway is impossible
   - Test case where trust roots are incompatible (checks should fail)
   -  Test a case where a request for a service that does not exist arrives at the gateway (need to probably kill the local service mirror and delete a remote service, while leaving the locally mirrored)
   - Try to hit a mirrored service from an umeshed pod (should not work)
   - Test using a LB other than GKE's, like MetalLB. Also scan ports on the LB ensuring only the probe and gateway ports are exposed.
- [ ] Network partitions
    - Get a local and a remote cluster mirrored and synced. Test a case where you cut the internet connection to your local kind cluster (not sure how to do that). Meanwhile, change something on the remote cluster (add a service and export it, delete another one). Wait a few minutes and recover the connection. Things should theoretically converge back to normal (fingers crossed)
- [ ] Test symmetrical cases
   - Try to have cluster A mirror a service from cluster B and vice versa. Ensure this works
   - Can you think of any scenarios that cna create cycles?

**Comment by zaharidichev** [comment]
@adleong @alpeb any other ideas about testing this ?

**Comment by alpeb** [comment]
- Ensure the gateway's ports can't be accessed using a simple cURL command without the proper cert
- Test using a LB other than GKE's, like MetalLB. Also scan ports on the LB ensuring only the probe and gateway ports are exposed.

**Comment by grampelberg** [comment]
I'd like to test:

- Unmeshed communication through the gateway.
- Trust roots that do not agree.
- Is there anything we can do to test a network partition?
- For the scale testing, should we test multiple namespaces? I'd love to know a max throughput.
- I'd love to know what happens when the gateway gets a request for a service that doesn't exist on the cluster.
- I'd love to at least know what the behavior is when something non-meshed uses a mirrored service.

Since I thought about it while I was reading through this, what events are we issuing on the mirrored service right now?

**Comment by zaharidichev** [comment]
> Ensure the gateway's ports can't be accessed using a simple cURL command without the proper cert

@alpeb But they cannot... because the proxy is configured to not accept any connection that is not TLSed on these ports. Right?

**Comment by alpeb** [comment]
> > Ensure the gateway's ports can't be accessed using a simple cURL command without the proper cert
> 
> @alpeb But they cannot... because the proxy is configured to not accept any connection that is not TLSed on these ports. Right?

Yea, I mean verify that's indeed the case.

**Comment by zaharidichev** [comment]
@alpeb ah sorry, I misread that...

**Comment by zaharidichev** [comment]
@alpeb @grampelberg @adleong I added a few more items and incorporated your suggestions. Anything else we should be thinking about?

**Comment by zaharidichev** [comment]
> Since I thought about it while I was reading through this, what events are we issuing on the mirrored service right now?

@grampelberg  We are currently not writing any events at all. I assume you are talking about k8s events. We can do that and it will probably be quite nice.

**Comment by olix0r** [comment]
Here are some other cases to exercise so that we have an understanding of what users will see when they hit these cases:

## p0

[ ] What happens when the target service has no available endpoints?
[ ] Can the gateway (presumably accidentally.. or maliciously) be installed without the proxy in some way (i.e. by namespace annotation, injector downtime, ...)? Does the client cluster fail to discover the gateway? Or do we attempt to send traffic to the unmeshed gateway? What diagnostics are exposed via `check`, etc?
[ ] What is reported when the gateway receives requests targeted at valid services that were not explicitly exposed via annotation? I.e. i have an unexported, `private.secretz.svc.cluster.local` and a client in the remote cluster sends the gateway meshed requests targeting this service?
[ ] What is reported when the gateway receives requests targeted at arbitrary DNS names? I.e. `linkerd.io`

## p1

[ ] What happens when a client-side (service-profile or app) request timeout cancels in-flight requests? Specifically, how do we record/report this in the remote cluster?
[ ] How are these requests reported when tapping the client?

--

What other failure modes do we expect folks to see? Can we get a handle on how these errors will be reported so we have a playbook for these reports?

**Comment by olix0r** [comment]
What happens if a user installs the service-mirror or the gateway into the `linkerd` namespace?

**Comment by zaharidichev** [comment]
> What happens if a user installs the service-mirror or the gateway into the linkerd namespace?

Yes there should be a guard against that on the install command. I have the strange feeling I added this one but by the looks of it I have missed to do that
