### ISSUE TITLE
linkerd-gateway allows access to non-exposed services

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4452]
The `linkerd cluster setup-remote` command installs a linkerd-gateway for the purposes of multi-cluster traffic.  This gateway should only route requests to services which have been exposed using the `linkerd cluster export-service` command (or the corresponding annotation).  However, a client in a peer cluster can access services which have not been exposed by modifying the `mirror.linkerd.io/remote-svc-fq-name` annotation on a mirrored service.

Steps to reproduce:

1. Follow the [multicluster set up tutorial](https://linkerd.io/2/features/multicluster_support/) to get a working multicluster environment with a `local` and `remote` cluster.
2. Expose a service in the `remote` cluster using the `linkerd cluster export-service` command, let's call it `exposed-svc`.
3. Notice in the local cluster a mirror service will be created called `exposed-svc-remote` and it's Endpoints object will have the annotation: `mirror.linkerd.io/remote-svc-fq-name: exposed-svc.default.svc.cluster.local`
4. Use `kubectl edit` to edit this annotation on the Endpoints object and change the value to `private-svc.default.svc.cluster.local` the name of a service in the remote cluster which has not been exposed.
5. Now requests sent to the `exposed-svc-remote` mirror service in the local cluster will be routed to the `private-svc` service in the remote cluster which should not be exposed.

**Comment by zaharidichev** [comment]
@adleong Nice find! Yes  I would expect that to be the case. We may need to think about that a bit more. I am not entirely sure if we can solve that in a non invasive way. 

I guess one way to do that is to have the destination service give the proxy some data wrt to whether the target service is actually exposed or not. And if it is not, the proxy on the gateway just drops the connection. @olix0r WDYT?

**Comment by grampelberg** [comment]
@zaharidichev wouldn't the best solution be to have the gateway only route services that have been exported? Then we wouldn't need to do any special logic in the proxy itself.

**Comment by olix0r** [comment]
Yeah, I think this will need to be enforced in the gateway.

**Comment by olix0r** [comment]
To summarize a discussion:

I don't think it's practical to limit this by policy for 2.8. For now, this is the nature of trusting the other cluster's root. By adding a trust root, or sharing a trust root, between clusters, you agree to allow communication between these clusters. The service-export annotations are purely a means to limit which services are advertised, to prevent mirrors from syncing unnecessary services.

I think, ideally, we would not attach any hard semantic meaning to this annotation though: I think, instead, the service-mirror should configure which services it mirrors (via a label selector). I think the export-service command should set this label (instead of annotation) and the service-mirror should use this label selector by default...

But inverting this to a read-time configuration instead of an export-control configuration makes this relationship much clearer, imo.

**Comment by olix0r** [comment]
We've modified the multicluster implementation to eliminate the concept of 'exposing' services from a target cluster. Instead, source clusters select which services they import.
