### ISSUE TITLE
pkg.go.dev discovers an older version of `linkerd2` module

### ISSUE THREAD

**Issue by mayankshah1607** [linkerd/linkerd2#4497]
I tried importing some of the packages from this (linkerd2) repo into a project using the following command:
```bash
$ go get github.com/linkerd/linkerd2@latest
```
While the module was pulled successfully, I ran into some fairly strange dependency issues while trying to build the code. On further inspection, it turns out the the "latest" tag causes [this](https://pkg.go.dev/mod/github.com/linkerd/linkerd2@v18.9.1+incompatible) version of the module to be pulled from [pkg.go.dev](pkg.go.dev), which happens to have last updated in 2018. 
This problem was solved by using a commit version (`v0.5.1-0.20200508195943-a3c42b138065`) instead of `latest`.

It would be nice to have [pkg.go.dev](pkg.go.dev) discover the latest version of the module so that folks can effortlessly pull the module using the `@latest` tag.

**Comment by grampelberg** [comment]
@mayankshah1607 any ideas how we can fix this? I don't know enough about go deps =(

**Comment by adleong** [comment]
This release v18.9.1 was the last Linkerd release that used the `vX.Y.Z` semantic versioning scheme that go modules expects.  Since then we've switch to date based versioning like `edge-x.y.z` and `stable-2.x.y`.

Since we don't follow go modules naming convention for releases, people who want to depend on linkerd will need to manually specify a pseudoversion and won't be able to use "latest".

**Comment by mayankshah1607** [comment]
Thanks, @adleong ! But that would also mean that pkg.go.dev would not be able to index the GoDoc on the upstream repo. Is there a workaround for that, if that's desirable?
