### ISSUE TITLE
Create helm chart for installing the control plane

### ISSUE THREAD

**Issue by robdefeo** [linkerd/linkerd2#452]
For helm users provide an alternative to `conduit install` Create a helm chart that installs the conduit control plane with sensible defaults into kubernetes. Mirroring the end state of `conduit install` if possible for consistency. Further discussion found in #343

**Comment by briansmith** [comment]
/cc @siggy who has had thoughts about this recently.

Internally, `conduit install` already has its output stored in a template that is parameterized by a few parameters.

One way we could make this work, to ensure consistency of the Helm Chart we publish and the output of `conduit install` would be to store the template for the output of `conduit install` in Helm Chart format in template.go. Implement a mini interpreter for Helm charts in `conduit install` that does the same substitutions that `conduit install` does now and get it to output the same results.

Further, we could store the Helm chart as a separate file in the .git repo for Conduit, and convert it to a Go source file (e.g. just `cat <go-boilerplate-before> <heml.chart> <go-boilerplate-after> > template.go` before compiling the Go code).

Then we could publish the Helm chart along with the binaries.

There's a wrinkle that I think we should consider: Conduit will eventually make Tiller work better, e.g. by providing automatic TLS and enforced access control for it and by providing it with better observability & serviceability. In a cluster that starts off with neither helm not Conduit, IMO it makes more sense to install Conduit first and then install Helm and everything else so that Helm/Tiller can take advantage of Conduit's service mesh features. If one instead installs Helm first and then Conduit, then ideally we would provide an option to convert the existing Helm installation to use the Conduit service mesh. That is, eventually the Helm chart for Conduit should have some way to configure it to reconfigure Helm too. However, that can/should be done separately from the initial Helm chart.

**Comment by wmorgan** [comment]
Tracking admission controller work in #561

**Comment by alpeb** [comment]
This has been superseded by the tickets under the [Helm support project](https://github.com/orgs/linkerd/projects/13).
