### ISSUE TITLE
Don't install prometheus components if --prometheus-replicas is set to 0

### ISSUE THREAD

**Issue by ahume** [linkerd/linkerd2#454]
When running `conduit install` with `--prometheus-replicas` set to 0, the Deployment, Service and ConfigMap objects for Prometheus are still installed into the cluster. 

It would be cleaner for these unrequired components not to be pushed into the cluster during install.

**Comment by ahume** [comment]
Actually, now I'm not sure this is a valid issue. If not installing the default prometheus components then the telemetry app needs to have the `prometheus-url` arg updated. In which case perhaps this is hitting a use case where `conduit install` isn't the right approach, and the k8s manifests should be adapted manually?

**Comment by briansmith** [comment]
Do I understand correctly that you already have Prometheus running and your goal is for Conduit to use your existing Prometheus rather than install its own? If so, then I think we should decide whether we want to support that configuration and then make it easy to do so in `conduit install` and any other way we support installing Conduit. I don't think anybody should have to edit the Conduit configuration files manually, for any supported configuration.

**Comment by ahume** [comment]
That's correct. We run prometheus as standard in our clusters so I've configured Conduit to connect to that existing service rather than install its own.

**Comment by wmorgan** [comment]
The approach so far as been to prioritize ease of installation over configurability. So currently, the best approach is to let Conduit install its control plane as normal, and then export those metrics into your own cluster via https://conduit.io/prometheus/.

In some sense it's not ideal to run two Prometheuses, but the Conduit one is pretty minimalist and shouldn't consume a lot of resources.

We could consider changing this in the future, but in the short term, being able to rely on a Prometheus installation that it has complete control over gives Conduit a lot of flexibility for upcoming features we'd like to add.

**Comment by siggy** [comment]
We may want to consider removing the `--prometheus-replicas` flag altogether, as setting it to anything but `1` will cause Conduit to not work properly.

**Comment by ahume** [comment]
Sure, fully understand the approach at this time. I'll let you close this, or re-open for removing `--prometheus-replicas` flag as you see fit.

**Comment by briansmith** [comment]
It would be good to know what specific reasons we have for having our own Prometheus instances, especially after the ongoing refactoring. In a big cluster where every pod is proxied through Conduit, it seems like it might be non-trivial overhead for Conduit's Prometheus instance and the user-managed Prometheus instance to both scrape metrics from every pod instance. Since our goal is to have minimal overhead, it seems like something we'll eventually need to address. Thus, it seems reasonable to at least document the issues with allowing the user to configure an alternative Prometheus instance and then see if we can resolve them. (No comment on prioritization.)

**Comment by ahume** [comment]
Having mulled this more I think having multiple isolated Prometheus installations in a single cluster, each monitoring some slice of the stack, is a reasonable option. And Conduit clearly retains some convenient control by installing and managing its own.

The issue then becomes one of appropriately configuring for e.g. HA, and scaling that installation as the cluster grows and the number of proxied pods grows.

**Comment by grampelberg** [comment]
Closing this out in preference of #1307.
