### ISSUE TITLE
config.linkerd.io/trace-collector seems not working ?

### ISSUE THREAD

**Issue by terrych0u** [linkerd/linkerd2#4586]
Hi:

I've followed the post to try distributed tracing with Linkerd.
https://linkerd.io/2/tasks/distributed-tracing/

However, When I try to add the following config into the example application **emojivoto**
```bash
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: linkerd-collector.linkerd:55678
```
And it seems like doesn't affect anything, with adding environment variable
`OC_AGENT_HOST` that is okay, and can see the result on Jaeger, it doesn't show anything about **linkerd-proxy** on dashboard. 
(the tutorial page below photo can see the vote-bot and linkerd-proxy result)

No matter I only added `config.linkerd.io/trace-collecto`, or add both `config.linkerd.io/trace-collecto`, `OC_AGENT_HOST` 

Am I missing something?

The webpage recommendation using `config.linkerd.io/trace-collector`, but it can't work on my lab environment.

Version:
  linkerd: 2.8.0
  k8s: AWS EKS 1.16.8

PS. I'm sure that linkerd-proxy has been injected into the example application **emojivoto** and the collector, and also with right serviceaccount.

**Comment by Pothulapati** [comment]
Hey @terrych0u, 
As per the doc you have to add both `config.linkerd.io/trace-collector` as well as `config.alpha.linkerd.io/trace-collector-service-account`. The second annotation is important because the `linkerd-collector` in `tracing` add-on, uses its own service account (which are used to establish mTLS). Can you add that and try?

Also, Yes both `config.linkerd.io/...` & `OC_AGENT_HOST` are important to get the full spans of the trace i.e application as well as the proxy! :)

**Comment by terrych0u** [comment]
Hi @Pothulapati 

yes, I did add `config.alpha.linkerd.io/trace-collector-service-account` on annotations and use applications service account or use `default`, still can't see anything about `linkerd-proxy` on the dashboard.

Am I misconfigured?

<img width="1439" alt="Screen Shot 2020-06-12 at 3 31 24 AM" src="https://user-images.githubusercontent.com/32168800/84431187-75696980-ac5d-11ea-8c65-12e735c1fd1b.png">
<img width="721" alt="Screen Shot 2020-06-12 at 3 32 19 AM" src="https://user-images.githubusercontent.com/32168800/84431194-79958700-ac5d-11ea-8058-45a5e3f64484.png">

So, I'm wondering about the purpose of  `config.linkerd.io/trace-collector` if `OC_AGENT_HOST` already can let applications send data into the collector. 

PS. there is a lot of log show on the sidecar proxy 
```
[  1254.929062319s]  WARN outbound:accept{peer.addr=10.23.75.208:51148}:source{target.addr=172.20.141.222:8080}:logical{addr=emoji-svc.emojivoto.svc.cluster.local:8080}:profile:balance{addr=emoji-svc.emojivoto.svc.cluster.local:8080}:endpoint{peer.addr=10.23.69.106:8080}: linkerd2_trace_context::layer: span dropped error=no available capacity
[  1254.929099880s]  WARN outbound:accept{peer.addr=10.23.75.208:51148}:source{target.addr=172.20.141.222:8080}: linkerd2_trace_context::layer: span dropped error=no available capacity                                                                                                                                                                   
[  1254.935626413s]  WARN outbound:accept{peer.addr=10.23.75.208:35118}:source{target.addr=172.20.41.41:8080}:logical{addr=voting svc.emojivoto.svc.cluster.local:8080}:profile:balance{addr=votingsvc.emojivoto.svc.cluster.local:8080}:endpoint{peer.addr=10.23.68.33:8080}: linkerd2_trace_context::layer: span dropped error=no available capacity
[  1254.935674703s]  WARN outbound:accept{peer.addr=10.23.75.208:35118}:source{target.addr=172.20.41.41:8080}: linkerd2_trace_context::layer: span dropped error=no available capacity
```

**Comment by Pothulapati** [comment]
Hey @terrych0u, 

Setting `OC_AGENT_HOST` sets the emojivoto demo application to send the spans to the endpoint, and the proxies also have to be configured for the same i.e on which endpoints the spans to be sent.

I think its failing because `config.alpha.linkerd.io/trace-collector-service-account` is configured to `default` which should actually be `linkerd-collector` as per the doc it should be **set to the name of the service account of the collector and is used to ensure secure communication between the proxy and the collector.**

**Comment by terrych0u** [comment]
Hi @Pothulapati

As you said, after change service account to `linkerd-collector`, very things work perfectly.

So, it was I misunderstand service account for applications, learn a lot.

Thank you very much! :D
