### ISSUE TITLE
Grafana has failed to load its application files.

### ISSUE THREAD

**Issue by mpouyakh7** [linkerd/linkerd2#4646]
## Bug Report
The grafana doesn't work for me after installing linkerd, although "linkerd check" shows everything is ok.
### What is the issue?
I have been struggling with this issue for few days and made me crazy. I can't figure out where the problem is. The grafana pops up a message saying "Grafana has failed to load its application files."
### Logs, error output, etc
Grafana can't read /etc/grafana/provisioning/notifiers anymore and its logs say:
t=2019-06-01T10:21:19+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output
Everything is in ok status.  
```text
your output here ...
```

### Environment

- Kubernetes Version: v1.18.3
- Cluster Environment: (GKE, AKS, kops, ...) Local
- Host OS: ubuntu 19.10
- Linkerd version: edge-20.6.3

**Comment by Pothulapati** [comment]
Hey @mpouyakh7, I just tried out the installation on k8s `1.18.2` with Linkerd `20.6.3` (same as in the description) and it worked for me as expected. 

We recently merged #4600 , but this does not seem related.
Did this happen after upgrading from a previous Linkerd version? If not, Can you tell us more about your environment so that we can replicate the issue?

**Comment by BouweCeunen** [comment]
I know it's closed, but anyone any resolution for this? I only installed viz through what the docs told me.
