### ISSUE TITLE
Use a different docker registry for non-release images

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4678]
## Feature Request

Push docker images built in CI, as well as part of the developer workflow, to a
registry other than `grc.io/linkerd-io` that is publicly available.

`gcr.io/linkerd-io` would contain only edge and stable tagged images.

### Description

Currently, CI will push non tagged images as part of the `cloud_integration`
workflow to the registry that we also use for releases.

`bin/docker-push` will also push to this registry if setup with the proper
permissions.

This adds a lot of images to the registry that are used only for developer and
testing purposes.

It would be best if these images were also pushed to a registry that we did not
care bloating with lots of testing images and did not scale our cost.

Additionally, CI could freely use this registry so that images built in *all*
PRs were available for pulling:

```bash
$ git checkout some-branch
$ bin/root-tag
git-abc123
$ bin/docker-pull git-abc123
```

### Possible solutions

Using a free, publicly available registry would be necessary for this change.
Docker Hub and GitHub Docker registry both fit these requirements. Other
solutions may exist.

### Changes

`kind_integration` workflow would push images to this registry as part of it's
workflow.

`bin/docker-push` when run in a context other than `release.yml` would push to
this registry.

`bin/docker-push` when run in `release.yml` would continue to push to
`gcr.io/linkerd-io`.

**Comment by alpeb** [comment]
I'm putting in writing some ideas we chatted about offline:

For non-forks this is trivial to implement; would just require setting up the credentials (for Docker Hub) or using GITHUB_TOKEN (for Github packages) and guard the push step with a condition for restricting it to non-forks, like we already do in many steps.

But ideally we'd like to do this uniformly for forks as well. Unfortunately all permissions associated to a workflow run initiated from a fork are all ready-only and so that run can't trigger anything.

We considered these options:
- Pushing to Docker Hub: Requires storing username and password in secrets, which are not visible in forks.
- Pushing to Github packages: It uses GITHUB_TOKEN for auth, but in the case of forks it doesn't have push permissions
- Triggering a repo dispatch event to signal another workflow to do the push: Can't trigger events from a fork.
- "ChatOps": adding a command in a comment in the PR that would trigger the workflow doing the push. But forks can't add comments either.

This would then require an external entity, i.e. a bot app with enough permissions, whose sole responsibility would be to watch for PRs and trigger the workflow for building the images.

LMKWYT!

**Comment by alpeb** [comment]
We finally decided to only keep on pushing release images, to ghcr.io, which has already been implemented. We stopped pushing images for the `main` branch. As for other builds, be it forks or not, one can easily push locally or to say your personal ghcr.io repo if needed, and feed that to your linkerd through the `--registry` flag.
