### ISSUE TITLE
`linkerd check --proxy` stalling on evicted pods

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#4690]
### What is the issue?

We're observing `linkerd check --proxy` take a very long time (5m+) to complete. It appears to be trying to connect to a large number (20+) of evicted pods that were injected.

### How can it be reproduced?

Run `linkerd check --proxy --verbose` on a cluster with many injected evicted pods.

#### `linkerd check` output

```bash
$ linkerd check --proxy --verbose
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

...

linkerd-data-plane
------------------
√ data plane namespace exists
DEBU[0090] Making gRPC-over-HTTP call to [http://localhost:55991/api/v1/ListPods] []
DEBU[0090] Response from [http://localhost:55991/api/v1/ListPods] had headers: map[Content-Type:[application/octet-stream] Date:[Mon, 29 Jun 2020 18:45:39 GMT]]
DEBU[0090] gRPC-over-HTTP call returned status [200 OK] and content length [-1]
DEBU[0090] Retrying on error: The "[NS]/pushgateway-54cc9678-pk22j" pod is not running
E0629 11:45:39.538935   23762 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:55991->[::1]:56495: read: connection reset by peer
| waiting for check to complete DEBU[0095] Making gRPC-over-HTTP call to [http://localhost:55991/api/v1/ListPods] []
| waiting for check to complete DEBU[0096] Response from [http://localhost:55991/api/v1/ListPods] had headers: map[Content-Type:[application/octet-stream] Date:[Mon, 29 Jun 2020 18:45:44 GMT]]
DEBU[0096] gRPC-over-HTTP call returned status [200 OK] and content length [-1]
```

### Environment

- Kubernetes Version: v1.16.7
- Cluster Environment: AKS
- Host OS: OSX
- Linkerd version: `stable-2.8.1 `

### Possible solution

`linkerd check --proxy` should filter out and not connect to evicted pods.

### Additional context

https://github.com/linkerd/linkerd2/issues/4680#issuecomment-651296780

**Comment by ihcsim** [comment]
It looks like the only error message we get back from k8s is `The "[NS]/pushgateway-54cc9678-pk22j" pod is not running`. I think it makes sense to keep this check as-is, since there can be many other reasons why a pod is not running. AIUI, this check will be auto-retried, and continue to fail (because the evicted pods are not removed automatically), until the [`retryDeadline` exceeded](https://github.com/linkerd/linkerd2/blob/cf34a149859a7a4eb5002de3149102ccdcfe4020/pkg/healthcheck/healthcheck.go#L1348-L1358). 

@siggy Do you know if `linkerd check --proxy` eventually time out? If not, there is probability a bug.

**Comment by siggy** [comment]
@ihcsim I didn't let `linkerd check --proxy` run long enough to complete or timeout.

For my own understanding: shouldn't `linkerd check --proxy` not attempt to connect to evicted pods?

**Comment by ihcsim** [comment]
My understanding thus far is that `Evicted` isn't one of the pod [phases](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase). To not select evicted pods, `linkerd check --proxy` will need to do the equivalence of `--field-selector=status.phase!=Running` at the API level. And I am assuming that eviction is not the only reason why a pod is not running.

**Comment by ihcsim** [comment]
I am starting to wonder if this stalling/retry isn't limited to just evicted pods. As part of tackling this issue, we should confirm how `linkerd check --proxy` behave when the pod's status is `Pending`, `Failing` and `Unknown`.

**Comment by adleong** [comment]
I've yet to confirm this since I don't have an evicted pod to look at, but I believe that when a pod is evicted, the `PodStatus.Phase` is "Failed" and the `PodStatus.Reason` is "Evicted".

I think we should handle this case specially in the ListPods API and set the `Status` field on the API response to be "Evicted" instead of "Failed".  Then in the healthcheck that validates the data plane, we should not error on pods with the "Evicted" status.

The motivation for this is that, unlike pods which are Failed for other reasons, pods which are evicted don't indicate a problem.  Assuming the correct number of healthy replicas exist for the workload, eviction is nothing to worry about.

**Comment by zaharidichev** [comment]
@adleong so do you suggest to actually explicitly check whether the pods is evicted or not and if it is not simply not fail. What about a situation where the pod  is Pending and its reason is "Unschedulable". This still results in the check hanging and retrying for this pod. 


 "status": {
    "conditions": [
      {
        "lastProbeTime": null,
        "lastTransitionTime": "2020-07-08T08:12:23Z",
        "message": "0/3 nodes are available: 3 Insufficient memory.",
        "reason": "Unschedulable",
        "status": "False",
        "type": "PodScheduled"
      }
    ],
    "phase": "Pending",
    "qosClass": "Burstable"
