### ISSUE TITLE
service profile route name for gRPC services

### ISSUE THREAD

**Issue by strobil** [linkerd/linkerd2#4726]
### What problem are you trying to solve?
`linkerd profile` generator for `proto` uses a grpc method name as route name.
In some cases it can be not very comfortable, because we can have the same method name in a different gRPC services.
For example service A has a method Foo, and the service B has a method Foo. Both of them will be listed in `Linkerd route` dashboard with the same name.

### How should the problem be solved?

Add ability to use custom prefix for generated gRPC route names.

### Any alternatives you've considered?
Use a path variable as a route name by default, pkg/profiles/proto.go:48
```
var path string
switch pkg {
case "":
    path = fmt.Sprintf("/%s/%s", service.Name, typed.Name)
default:
    path = fmt.Sprintf("/%s.%s/%s", pkg, service.Name, typed.Name)
}
```

### How would users interact with this feature?
Add some flags to `linkerd profile` cmd

**Comment by adleong** [comment]
Hi @strobil, thanks for filing this.  This seems like a reasonable feature request on its own but I wonder if allowing for a simple prefix on route names is really flexible enough.  Each user may have their own specific requirements on how they would like routes to be named.  Rather than try to accommodate all of these requirements, my instinct would be to say that this is outside of the responsibility of the `linkerd profile` command.

I think of the service profile that `linkerd profile` generates as a starting point.  Users can take that and modify the route names in whatever way they like, either by editing the service profile manually, or by feeding it through some kind of string processing pipeline.  This gives them total control over the route names (or any other aspect of the service profile).

What do you think about this philosophy?

**Comment by strobil** [comment]
Hmm, for the first time i was thinking that this small change will resolve 99% conflicts in naming with default settings.
But now i'm thinking that you are absolutely right. As you say - each user may have own specific requirements, and without total rethinking of `profile` command there is no sense to apply changes like this :)

**Comment by ihcsim** [comment]
@strobil Sounds like the approach that @adleong suggested will work for you. I'm closing this issue for now.
