### ISSUE TITLE
linkerd + linkerd-cni does not recover when a node restarts

### ISSUE THREAD

**Issue by jvandemark** [linkerd/linkerd2#4789]
### What is the issue?
linkerd + linkerd-cni fails to restart properly when a node restarts

### How can it be reproduced?

Start a 2 node cluster with ```cni``` configured.

delploy linkerd-cni
 ```linkerd install-cni | kubectl apply -f -```

deploy linkerd
```linkerd install --linkerd-cni-enabled | kubectl apply -f -```

deploy an ingress and some pods to ping: (optional for testing purposes)
I deployed Ambassador and a simple echo server app

sequentially restart the nodes in your cluster

### Logs, error output, etc
Pod distribution pre restart:
```
                                               Node IP     Pod Ip
linkerd-destination-7cc4f6495-rnpm2            10.0.0.4    10.0.0.25
linkerd-prometheus-8d8f48786-mmqbb             10.0.0.4    10.0.0.30
linkerd-controller-cb64778c6-4qdsj             10.0.0.4    10.0.0.34
linkerd-sp-validator-b959fd754-mnbjt           10.0.0.4    10.0.0.6

linkerd-proxy-injector-b4489cc47-v9mnr         10.0.0.35   10.0.0.37
linkerd-tap-799f6845f7-lbl6j                   10.0.0.35   10.0.0.42
linkerd-identity-68d946bd5d-tzrd8              10.0.0.35   10.0.0.46
linkerd-grafana-54b66789c6-gmgmh               10.0.0.35   10.0.0.50
linkerd-web-6fcbcd4df7-rcx5j                   10.0.0.35   10.0.0.60

linkerd-cni-54tsv                              10.0.0.4    10.0.0.4
linkerd-cni-tzr9b                              10.0.0.35   10.0.0.35
```

---

I restarted node 10.0.0.35

logs from linkerd pods which didn't restart completely: i.e. 1/2 containers

proxy-injector, linkerd-proxy logs
```
[   474.459661897s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:33944}: rustls::session: Sending fatal alert AccessDenied
[   474.961991772s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:33970}: rustls::session: Sending fatal alert AccessDenied
```

tap, linkerd-proxy logs
```
[   332.399462521s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:50008}: rustls::session: Sending fatal alert AccessDenied
[   332.902929795s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:50032}: rustls::session: Sending fatal alert AccessDenied
```

grafana, linkerd-proxy logs
```
[   787.189760937s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:45372}: rustls::session: Sending fatal alert AccessDenied
[   787.692810316s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:45398}: rustls::session: Sending fatal alert AccessDenied
```

web, linkerd-proxy logs
```
[   888.695663503s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:44438}: rustls::session: Sending fatal alert AccessDenied
[   889.198987512s]  WARN daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.0.0.30:44468}: rustls::session: Sending fatal alert AccessDenied
```

Other meshed pod on the node have 1/2 container started, I assume this occurred because proxy-inject was not running

System is not fully functional

#### `linkerd check` output
```linkerd check --pre --linkerd-cni-enabled``` was clean prior to deploying ```linkerd```

this output is prior to bouncing a node
```
linkerd check 
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.15.12 - we can't go to 1.16 yet do to changes
- Cluster Environment: (Azure)
- Host OS: ubuntu 16.04
- Linkerd version:
```
Client version: stable-2.8.1
Server version: stable-2.8.1
```

### Possible solution
The only way to fully restore the system is to scale all linkerd deployments to 0, then scale back up to 1.
Then it's necessary to restart all meshed pods.

### Additional context

I've see similar behavior on minikube using the latest version of Kubernetes (1.18.x) when you stop & restart minikube

**Comment by ihcsim** [comment]
@jvandemark We suspect this might have something to do with the general CNI plugins start up timing issue we've seen in other environments, where if there is a list/chain of CNI plugins, they step on each other's toes when (re-)starting. Do you have other CNI plugins set up? 

The `rustls::session: Sending fatal alert AccessDenied` error usually means there is a mismatch between the mTLS trust cert and proxy certs, which can happen if an existing control plane is overridden by another installation. How were your nodes restarted? Is there anything in the background that might overwrite Linkerd's installation config?

Potentially relevant https://github.com/linkerd/linkerd2/issues/2219, https://github.com/linkerd/linkerd2/issues/4049, https://github.com/linkerd/linkerd2/issues/4029.

**Comment by jvandemark** [comment]
@ihcsim the cni plugins are chained: 
```
{
  "cniVersion": "0.3.0",
  "name": "azure",
  "plugins": [
    {
      "type": "azure-vnet",
      "mode": "bridge",
      "bridge": "azure0",
      "ipsToRouteViaHost": [
        "169.254.20.10"
      ],
      "ipam": {
        "type": "azure-vnet-ipam"
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
      "snat": true
    },
    {
      "name": "linkerd-cni",
      "type": "linkerd-cni",
      "log_level": "debug",
      "policy": {
        "type": "k8s",
        "k8s_api_root": "https://10.1.0.1:443",
        "k8s_auth_token": " <token value> "
     },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
      },
      "linkerd": {
        "incoming-proxy-port": 4143,
        "outgoing-proxy-port": 4140,
        "proxy-uid": 2102,
        "ports-to-redirect": [],
        "inbound-ports-to-ignore": [],
        "outbound-ports-to-ignore": [],
        "simulate": false,
        "use-wait-flag": false
      }
    }
  ]
}
```
So is the problem only present with chained plugins?
And you believe the problem is load order? the writing of iptables rules/chains?
Is there any possibility that this is related to the cni plugins/adapter non being fully initialized/running before linkerd starts?

**Comment by jvandemark** [comment]
Regarding "mismatch between the mTLS trust cert and proxy certs"  there's basically nothing else running the system, just linkerd/linkerd-cni, an ingress (Ambassador) and a couple echo pods. I don't see how this issue would arise?

**Comment by jvandemark** [comment]
For what it's worth, when a node is restarted, the pods which don't restart properly are missing from the iptables NAT
```
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
linkerd-cni   linkerd-cni-7jh9f                              1/1     Running   0          86m
linkerd-cni   linkerd-cni-tgnzs                              1/1     Running   1          86m
linkerd       linkerd-controller-58975c8fbb-5chwq            2/2     Running   1          50m
linkerd       linkerd-destination-d98d7c94f-sx8kq            2/2     Running   1          50m
linkerd       linkerd-grafana-746cf5659d-xxsbv               2/2     Running   0          50m
linkerd       linkerd-identity-86b8485b84-6ghs2              2/2     Running   4          50m
linkerd       linkerd-prometheus-66dbb6c7cb-554n6            1/2     Running   2          50m
linkerd       linkerd-proxy-injector-7d5f54495c-glldl        1/2     Running   4          50m
linkerd       linkerd-sp-validator-54d874b5f6-48dpg          2/2     Running   1          50m
linkerd       linkerd-tap-78895b8bd7-l7jgg                   1/2     Running   4          50m
linkerd       linkerd-web-c665b7cf9-zr8vf                    1/2     Running   3          50m
```
NAT linked entries
```
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.0.0.0/17          10.1.83.80           /* linkerd/linkerd-controller-api:http cluster IP */ tcp dpt:8085
    0     0 KUBE-SVC-TCLZ33R6ZVEKUVWC  tcp  --  *      *       0.0.0.0/0            10.1.83.80           /* linkerd/linkerd-controller-api:http cluster IP */ tcp dpt:8085
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.0.0.0/17          10.1.46.193          /* linkerd/linkerd-sp-validator:sp-validator cluster IP */ tcp dpt:443
    0     0 KUBE-SVC-QC6GMSWWJ7LEIVL3  tcp  --  *      *       0.0.0.0/0            10.1.46.193          /* linkerd/linkerd-sp-validator:sp-validator cluster IP */ tcp dpt:443
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.0.0.0/17          10.1.62.149          /* linkerd/linkerd-grafana:http cluster IP */ tcp dpt:3000
    0     0 KUBE-SVC-BSCUQWYUYWTJE5M6  tcp  --  *      *       0.0.0.0/0            10.1.62.149          /* linkerd/linkerd-grafana:http cluster IP */ tcp dpt:3000
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.0.0.0/17          10.1.95.206          /* linkerd/linkerd-identity:grpc cluster IP */ tcp dpt:8080
    0     0 KUBE-SVC-U2TN5MI3KW4FHINL  tcp  --  *      *       0.0.0.0/0            10.1.95.206          /* linkerd/linkerd-identity:grpc cluster IP */ tcp dpt:8080
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.0.0.0/17          10.1.62.130          /* linkerd/linkerd-dst:grpc cluster IP */ tcp dpt:8086
    0     0 KUBE-SVC-Z54HJDVTKAHYPJRW  tcp  --  *      *       0.0.0.0/0            10.1.62.130          /* linkerd/linkerd-dst:grpc cluster IP */ tcp dpt:8086
```

**Comment by ihcsim** [comment]
> the cni plugins are chained

Yeah, this is a problem. What we have seen is that if the Azure CNI starts up first, the Linkerd CNI will append its config to the chain, as seen in the one you posted. If it's the other way, the Azure CNI will overwrite the Linkerd CNI config. Can you confirm that the problematic node only has the Azure CNI config, even though the Linkerd CNI daemonset is installed? There are more details in the issues I linked above.

**Comment by jvandemark** [comment]
hmm ...
```linkerd       linkerd-proxy-injector-7d5f54495c-5gfbt        1/2     Running   3          117m```

```
NAME                                           HostIP      PodIP
linkerd-proxy-injector-7d5f54495c-5gfbt        10.0.0.4    10.0.0.10
```
```
ifconfig | head
azure0    Link encap:Ethernet  HWaddr 00:0d:3a:9e:b0:6e
          inet addr:10.0.0.4  Bcast:0.0.0.0  Mask:255.255.128.0
```
```
cat /etc/cni/net.d/10-azure.conflist
{
  "cniVersion": "0.3.0",
  "name": "azure",
  "plugins": [
    {
      "type": "azure-vnet",
      "mode": "bridge",
      "bridge": "azure0",
      "ipsToRouteViaHost": [
        "169.254.20.10"
      ],
      "ipam": {
        "type": "azure-vnet-ipam"
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
      "snat": true
    },
    {
      "name": "linkerd-cni",
      "type": "linkerd-cni",
      "log_level": "debug",
      "policy": {
        "type": "k8s",
        "k8s_api_root": "https://10.1.0.1:443",
        "k8s_auth_token": " ... "
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
      },
      "linkerd": {
        "incoming-proxy-port": 4143,
        "outgoing-proxy-port": 4140,
        "proxy-uid": 2102,
        "ports-to-redirect": [],
        "inbound-ports-to-ignore": [],
        "outbound-ports-to-ignore": [],
        "simulate": false,
        "use-wait-flag": false
      }
    }
  ]
}
```
It appears that both plugin configs are present on this bounced node

**Comment by ihcsim** [comment]
Hmm.. not what I expected. I'll need to repro this. Are you blocked by this? I am assuming this isn't a problem with Linkerd's non-CNI setup?

**Comment by jvandemark** [comment]
We're in the process of rebuilding all our clusters dev -> prod, the new clusters are using Azure cni, the older cluster were not using cni. We are currently running linkerd 2.7.1 in prod. Without cni functioning thought I won't be able to deploy linkerd into our new clusters, which is kind of a problem.

**Comment by jvandemark** [comment]
If there's anything else I can provide let me know, I can setup and tear-down these 2 node clusters at will.

**Comment by Josepy** [comment]
@ihcsim I've been look at the journal logs (minikube where it fails also) and found something interesting, possibly:

```
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 < iptables: No chain/target/match by that name.                                                                                                                                                               
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 Ignoring uid 2102                                                                                                                                                                                             
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 Redirecting all OUTPUT to 4140                                                                                                                                                                                
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 Executing commands:                                                                                                                                                                                           
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 > iptables -t nat -N PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-common-chain/1595687972                                                                                                     
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 >> nsenter [--net=/proc/8612/ns/net iptables -t nat -N PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-common-chain/1595687972]                                                                  
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 < Another app is currently holding the xtables lock. Perhaps you want to use the -w option?                                                                                                                   
Jul 25 14:39:32 cnid2 kubelet[2554]: 2020/07/25 14:39:32 Aborting firewall configuration                                                                                                                                                                               
Jul 25 14:39:32 cnid2 kubelet[2554]: time="2020-07-25T14:39:32Z" level=debug msg="linkerd-cni: plugin is finished"
```
---
```
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Aborting firewall configuration
```

This for a pod which has only 1/2 containers started after a bounce/restart

```infra          ambassador-edge-stack-84c584fb6b-dldp5         1/2     Running   3          39h```

```Warning  Unhealthy       2m16s (x90 over 17m)  kubelet, cnid2     Readiness probe failed: HTTP probe failed with statuscode: 503```

Thoughts?

**Comment by ihcsim** [comment]
@Josepy Try the `linkerd install-cni --use-wait-flag` option.

**Comment by jvandemark** [comment]
I've been working with Charles & Thomas on this. The the iptables code in linkerd2-proxy-init is in the process of being re-written

**Comment by cpretzer** [comment]
The behavior described in the original post is reproducible without restarting the nodes and the [iptables changes](https://github.com/linkerd/linkerd2-proxy-init/pull/4) mentioned in the last comment don't address the CNI behavior described in this ticket.

Here's how to see what is going on:
- Create a cluster that supports CNI (I used GKE which uses calico for CNI)
- Install linkerd-cni
  - `linkerd install-cni --cni-log-level debug | kubectl apply -f -`
- Install linkerd
  - `linkerd install --linkerd-cni-enabled | kubectl apply -f -`
- Wait for the control plane to come up
  - `linkerd check`

The `linkerd-cni` and `calico-node` pods are managed by DaemonSet resources, so you will have one for every node. I had four nodes during this test, but you can probably repro with just a single node.

Get the names for a single calico-node pod and a linkerd-cni pod _on the same node_:

`kubectl get po -n linkerd-cni -owide`
`kubectl get po -n kube-system -owide  --selector=k8s-app=calico-node`

Once you have the pod names, `kubectl exec` into each one:

`kubectl exec -it calico-node-<pod-hash> -n kube-system -- /bin/bash`
`kubectl exec -it linkerd-cni-<pod-hash> -n linkerd-cni -- /bin/bash`

### Calico Node Pod
View the CNI plugin definition with
- `cat /etc/cni/net.d/10-calico.conflist`

You should see the linkerd-cni plugin there:

```JSON
cat /host/etc/cni/net.d/10-calico.conflist 
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "mtu": 1460,
      "log_level": "warning",
      "datastore_type": "kubernetes",
      "nodename": "<redacted>
      "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
      "snat": true
    },
    {
      "type": "bandwidth",
      "capabilities": {
        "bandwidth": true
      }
    },
    {
      "name": "linkerd-cni",
      "type": "linkerd-cni",
      "log_level": "debug",
      "policy": {
        "type": "k8s",
        "k8s_api_root": "<redacted>",
        "k8s_auth_token": <redacted>
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
      },
      "linkerd": {
        "incoming-proxy-port": 4143,
        "outgoing-proxy-port": 4140,
        "proxy-uid": 2102,
        "ports-to-redirect": [],
        "inbound-ports-to-ignore": [
          "4190",
          "4191"
        ],
        "outbound-ports-to-ignore": [],
        "simulate": false,
        "use-wait-flag": false
      }
    }
  ]
}
```

Detach from that pod, then restart the calico-node daemon set. **Note** You can probably delete the pod, but I did a restart when I reproduced this:
`kubectl rollout restart ds -n kube-system calico-node`

It may take a few minutes for the new pods to come up. Once they do, find the calico-node pod that is on the same node as the linkerd-cni pod from the earlier step and use `kubectl exec` to get into it:
`kubectl exec -it calico-node-<pod-hash> -n kube-system -- /bin/bash`

Check the output from the `10-caliico.conflist` file:
`cat /etc/cni/net.d/10-calico.conflist`

You should see that the linkerd-cni plugin is not in the list of plugins. Keep this terminal open for now.

**This is the point at which the two DaemonSet pods (linkerd-cni and calico-node) are out of sync**

### Linkerd CNI pod
If you're not already exec'd into the linkerd-cni pod, do that now:
`kubectl exec -it linkerd-cni-<pod-hash> -n linkerd-cni -- /bin/bash`

This should put you in the /linkerd directory which has the `install-cni.sh` script. Run this script:
`./install-cni.sh`

### Calico Node Pod
From the exec shell of the calico-node pod that you left open, view the `10-calico.conflist` file again:
`cat /etc/cni/net.d/10-calico.conflist`

Running the `install-cni.sh` script should install the linkerd-cni plugin and modify the `10-calico.conflist` file.

From my perspective, there are two issues:

1. When a node fails there is a race condition between the calico-node pod and the linkerd-cni pod. If the linkerd-cni pod starts before the calico-node (or any CNI) pod, then the *.conflist file won't be updated and the `linkerd-cni` plugin will never be called when a new pod is deployed

2. The calico-node (or any CNI) pod and the linkerd-cni pod don't have a mechanism to stay in sync with each other. That is to say, if the calico-node pod restarts, the configuration files and linkerd-cni executable written by the linkerd-cni plugin are not available in the new pod. The pod in the linkerd-cni namespace has no way of knowing that the calico-node pod has been restarted, and that it should also be restarted in order to re-run the install-cni.sh script.

We'll have to think of some approaches to dealing with the latter. The ones that are coming to mind right now don't seem viable or just bad ideas (like watching for CNI pods to restart).

I vaguely recall someone attempting to work around a similar issue using [Pod Priority](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass), and I think this is the [issue](https://github.com/linkerd/linkerd2/issues/5070).

**Comment by xynova** [comment]
We are currently trying to come up with some home-baked workarounds for the issues @cpretzer mentions, specifically in the GKE + calico setup in our own environments:

> When a node fails there is a race condition between the calico-node pod and the linkerd-cni pod. If the linkerd-cni pod starts before the calico-node (or any CNI) pod, then the *.conflist file won't be updated and the linkerd-cni plugin will never be called when a new pod is deployed

We are overriding the linkerd-cni docker image's entry point to run a script that waits for the `10-calico.conflist` file to be present before letting the `install-cni.sh` run. This solves any race conditions on the linkerd-cni side when nodes come up.

> The calico-node (or any CNI) pod and the linkerd-cni pod don't have a mechanism to stay in sync with each other. That is to say, if the calico-node pod restarts, the configuration files and linkerd-cni executable written by the linkerd-cni plugin are not available in the new pod. The pod in the linkerd-cni namespace has no way of knowing that the calico-node pod has been restarted, and that it should also be restarted in order to re-run the install-cni.sh script.

This one is a little bit trickier since Calico restarts can happen at any point in time triggered by a vertical autoscaler looking after them. We are a bit wary of having to continuously watch the file or API since it could potentially allow for a time window where containers can start up with an incorrect version of the CNI config: Calico without the Linkerd plugin chain. It also seems to be that the Kubelet caches the CNI config for a little time and therefore increasing the risk for broken containers starting on that node.

In our point of view, the GKE Calico install CNI OOTB daemonset should not be resetting any existing CNI configuration but updating the fields of its own concern instead. One possible option for us would be:

1. To customize the GKE OOTB daemonset so that it writes some mock linkerd-cni plugin configuration on restarts so that calls to the CNI component fail until they are fixed at a later stage.

2. Include a loop in the linkerd-cni `install-cni.sh` script that lets the pod restart if it doesn't find its own config in the file. On restart, it will run the process the file and inject the plugin chain.
