### ISSUE TITLE
Replacing default cniPluginVersion by a proper value

### ISSUE THREAD

**Issue by tvvignesh** [linkerd/linkerd2#4839]
Hi. Currently the linkerd2-cni plugin chart has `linkerdVersionValue` as the default value hence tries to download an invalid image when installing.

Its better to replace it with a valid image version value like `stable-2.8.2` or something valid so that people can install it without issues.

Also was wondering where I can get the cni plugin version (since I had a confusion whether linkerd2 version and cni plugin version would be the same or not), but then went to gcr and got the image tags to use.

Just thought of suggesting.

**Comment by alpeb** [comment]
Hi @tvvignesh ,

We have `linkerdVersionValue` as a placeholder in the source code, so that it gets replaced automatically during CI with the proper version without manual intervention. The version when released is the same as the linkerd2 version.

If your plan is to just install it, the recommended way is to grab it from our Helm repo. First add that repo locally:
```
helm repo add linkerd-edge https://helm.linkerd.io/edge
```
Then install it with:
```
 helm install linkerd2-cni linkerd-edge/linkerd2-cni
```

That was using the latestd edge version. For pulling the latest stable version, the commands are:
```
helm repo add linkerd https://helm.linkerd.io/stable
helm install linkerd2-cni linkerd/linkerd2-cni
```

**Comment by tvvignesh** [comment]
@alpeb Makes sense :+1:  . Will close this issue. Thanks for your quick reply.
