### ISSUE TITLE
Injected application may not be able to establish connections at startup

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#485]
When an pod that has been injected with the Conduit proxy is started, the order that the containers start in is not guaranteed.  This means that the application container may start before the sidecar container and attempt to establish network connections.  Since the init-container has already configured iptables to redirect these connection to the proxy's ports, these connections will be refused if the proxy container has not been started.

Ideally, we would be able to specify that the sidecar container must be started first but it does not appear that Kubernetes supports any way to configure container start orderings.  

A few potential workarounds to consider:

* Somehow trigger the launch of the sidecar container from the init-container and then block until the proxy is listening.  Is this even possible?
* Have the inject command modify the entrypoint of existing containers to add a wrapper script that polls the proxy and doesn't invoke the original entrypoint until the proxy is listening.
* Document that applications must retry on failed connections.  This would be unfortunate since one of the goals of the service mesh is to get this logic OUT of applications.
* Remove the init-container and have the proxy container do the iptables configuration AFTER it starts listening.  Unfortunately, this would mean that any connections established by the application before the proxy was ready would skip the proxy.

**Comment by dadjeibaah** [comment]
@adleong @briansmith could [Container lifecycle hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution) be a possible solution to implement workaround 1. The one concern is that that would mean we would have a strict dependency on k8s 1.9.

**Comment by pcalcado** [comment]
Would readiness probes help? https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by olix0r** [comment]
@adleong 

> Somehow trigger the launch of the sidecar container from the init-container and then block until the proxy is listening. Is this even possible?

I don't think it's possible.

>  Have the inject command modify the entrypoint of existing containers to add a wrapper script that polls the proxy and doesn't invoke the original entrypoint until the proxy is listening.

I don't think we can reliably modify the entrypoint, since it does not need to be specified in a pod spec.

>  Document that applications must retry on failed connections. This would be unfortunate since one of the goals of the service mesh is to get this logic OUT of applications.

All good applications _should_ do this. We should document it as a thing you _should_ do, but we should also have ways to solve this problem without modifying the application code.

>    Remove the init-container and have the proxy container do the iptables configuration AFTER it starts listening. Unfortunately, this would mean that any connections established by the application before the proxy was ready would skip the proxy.

This isn't an acceptable solution, as it would require that the proxy run in a privileged container. The proxy container can't require privileged execution.

---

Ultimately, i think we should do the following:

1. Document the types of failures applications should expect when working with the proxy, ideally with examples of how to instrument the appropriate resiliency.

2. Implement and host a binary that wraps a command with a proxy healthcheck. When the check succeeds, the script executes the original entrypoint.  This would require users to modify/extend their docker images to include this binary.

3. If users cannot modify docker images, suggest that a `sleep 30` might do the trick and point them at open Kubernetes issues we think might help address this.

**Comment by briansmith** [comment]
> > Document that applications must retry on failed connections. This would be unfortunate since one of the goals of the service mesh is to get this logic OUT of applications.
> 
> All good applications should do this. We should document it as a thing you should do, but we should also have ways to solve this problem without modifying the application code.

I agree that this would be excellent to document, at least until we have an automated solution. There are other things we need to document too, e.g. that you cannot rely on any particular endpoint receiving any sequence of requests, since we do load balancing, so we'll need such a document anyway.

> Remove the init-container and have the proxy container do the iptables configuration AFTER it starts listening. Unfortunately, this would mean that any connections established by the application before the proxy was ready would skip the proxy.
> 
> This isn't an acceptable solution, as it would require that the proxy run in a privileged container. The proxy container can't require privileged execution.

Plus, it's not acceptable for any requests to be sent or received by the application directly without the the proxy's help, because the proxy may be responsible for securing those requests.

> Ultimately, i think we should do the following:
> 
> Document the types of failures applications should expect when working with the proxy, ideally with examples of how to instrument the appropriate resiliency.

I agree with this.

> Implement and host a binary that wraps a command with a proxy healthcheck. When the check succeeds, the script executes the original entrypoint. This would require users to modify/extend their docker images to include this binary.

I don't think we should put ourselves on the hook for supplying and maintaining this. If we want to spend effort trying to work better for applications that weren't written with retry logic, then we should work towards an automated solution (see below).

> If users cannot modify docker images, suggest that a sleep 30 might do the trick and point them at open Kubernetes issues we think might help address this.

I think there's still opportunity for an automated solution. Note that daemonsets start before other pods on a node. Moving the proxying logic to a deamonset would solve this issue for everthing (except other daemonsets). Moving from the sidecar model to a deamonset model, or to a hybrid deamonset + sidecar model has other advantages (and disadvantages). I doubt we're going to switch to a deamonset-based implementation soon, but IMO it would be OK to defer work on an automated solution for this until at least we've fully vetted the possibility of using a deamonset to help.
