### ISSUE TITLE
destination: Mark opaque ports in profile resolutions

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4938]
The proxy will use profile resolution to bootstrap discovery for TCP streams, including whether the proxy should treat the stream as opaque, bypassing protocol detection. https://github.com/linkerd/linkerd2-proxy-api/pull/44 adds a flag to the destination response to facilitate this.

The destination services needs to be modified to set this flag to true as follows:

* Pods may be set with an annotation, `config.linkerd.io/opaque-ports`. The value is a port list, supporting both numeric and named ports, as well as numeric ranges. Valid values include, for example, `25,4320-4330,mysql`. In this exaple, `mysql` would match a `port.name` on the pod.
* When the destination lookup targets a pod IP:PORT, the port should be checked against the pod's opaque-ports, and the value should be set to true if it matches. 
* When destination lookups target a service, the typical service-to-pod-port resolution should be performed; and this value is set to true if the port is in the opaque-ports for _any_ pod in the service.
* Otherwise, the value is set to `false`.

**Comment by adleong** [comment]
Just to confirm my understanding: `config.linkerd.io/opaque-ports` is already used to configure the proxy's inbound opaque ports.  The idea here is that setting that one annotation on a workload should configure BOTH that workload's inbound opaque ports AND the outbound opaque ports of any other proxy sending to it?

Since this is a workload level annotation, it would feel a lot more natural to indicate opaqueness on the `WeightedAddr` instead of on the service profile.  (similar to ProtocolHint).  I'm guessing that this is impossible because of the way routing works in the proxy?  i.e. that protocol detection is done before load balancing?

Having the service profile depend on the individual endpoints is unfortunate and makes me feel like we have the wrong abstractions somewhere.

**Comment by olix0r** [comment]
@adleong That's right.

I think the alternative would be that we also require an annotation on services that matches the workload annotations. It's not strictly necessary, since we can infer it; but it would definitely be a simpler and probably more idiomatic scheme.

**Comment by kleimkuhler** [comment]
This is closed by #4972, #5294, #5421, and #5458.
