### ISSUE TITLE
Proxy: request_handle_us metric is always zero

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5043]
When checked in any proxy, all this histogram values are zero for some reason.
The only place this is currently used is in the heartbeat.

**Comment by hawkw** [comment]
The handle time metric implementation was disabled in the proxy in linkerd/linkerd2-proxy#611 --- the implementation causes a deadlock when the proxy is multithreaded. If I recall correctlym we opted to just remove it at the time because we weren't aware that anything was currently consuming that data.

**Comment by alpeb** [comment]
Thanks @hawkw . More specifically, this is was used in the `p99_handle-us` value sent in the heartbeat. Pinging @grampelberg in case he misses that piece of info an would like to prioritize a fix.

**Comment by olix0r** [comment]
We won't have this metric in the 2.9 release. We should reintroduce if it's useful,but it's not a priority.
