### ISSUE TITLE
multicluster: Support StatefulSets and Headless services 

### ISSUE THREAD

**Issue by LaumiH** [linkerd/linkerd2#5162]
## Feature Request

I want to add support for Headless Services exposing StatefulSets, so that the functionality of accessing individual pods via their stable DNS name is possible through Linkerd service mesh. Right now loadbalancing does not offer accessing a single pod.
 
K8s supports this by introducing [stable pod Ids](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#using-stable-network-identities) composed of `<pod-name>.<svc-name>.<ns>.svc.cluster.local`. Accessing e.g. a mongoDB pod would happen via `<mongo-0>.mongo.mongo.svc.cluster.local`.

The Headless Service in this case offers one single Service for all the underlying pods, and thus it scales automatically, as the StatefulSets' pod names are just incremented (`mongo-0`, `mongo-1` and so on).

### What problem are you trying to solve?

I want to connect two StatefulSets across two clusters, where each pod needs connectivity to each other pod. At the same time I want to preserve scalability. So adding a Service per pod does not suffice. 

More concretely, I want to be able to deploy a MongoDB ReplicaSet across two clusters, where each pod (primary and secondary) can connect to every other member. MongoDB needs this in order to perform leader election and syncing.

There has been a [discussion on the forum](https://discourse.linkerd.io/t/targeting-a-specific-kubernetes-pod/400/3) about this 3 years ago.

### How should the problem be solved?

What imho needs to be implemented is a way to bypass loadbalancing, and a solution for addressing an individual pod. The existing K8s stable network Id might be reused.

### Any alternatives you've considered?

I could expose each pod via its own Service, providing the full mesh capability I am searching for. But this would not be automatically scalable, at least not without a custom sidecar that exposes the services .

### How would users interact with this feature?

I would propose a special annotation to Headless Services that makes sure Linkerd handles them correctly. After that, users can can use the feature similar to the existing stable network Ids in K8s.

**Comment by olix0r** [comment]
@LaumiH Please try the newest release, stable-2.9.0. The linkerd proxy no longer load balances connections when the application targets an individual pod.

Note that there is a known [issue](https://github.com/linkerd/linkerd2/issues/5209) with our headless support that we plan to address in a stable-2.9.1, but I think the our updated approach to service discovery may meet your needs.

**Comment by LaumiH** [comment]
Fantastic! Is this feature documented somewhere? How would I address an individual pod? Help appreciated :)

**Comment by olix0r** [comment]
As long as your application connects directly to a pod IP address (and not a ClusterIP), no load balancing will be performed -- we'll do discovery on the endpoint and not treat it as service-bound traffic. So, simply by using a headless service, you'll get the desired behavior (since there is no cluster IP). Similarly, if your application targets an individual replica in a stateful set, the proxy will see the pod's IP address, and forward as you would expect.

There's a note about this in the [ServiceProfile docs](https://linkerd.io/2/features/service-profiles/) but we probably could use a better description of this in the architecture doc... If you'd like to submit a PR to help improve the docs :wink:, the website sources are at https://github.com/linkerd/website/.

**Comment by LaumiH** [comment]
I have to get back to this, as I still don't understand the answer. I now read how Linkerd works and try to understand this.

**Comment by bhavin192** [comment]
The actual problem of getting this working across multiple cluster is still there, I think. 
> I want to connect two StatefulSets across two clusters, where each pod needs connectivity to each other pod. At the same time I want to preserve scalability. So adding a Service per pod does not suffice.

This is with the latest release `stable-2.10.0` and the guide <https://linkerd.io/2.10/tasks/multicluster/>:

When I try to mirror the headless service `hello.htest.svc.cluster.local` from `east` cluster to `west`, it gets created as a ClusterIP service `hello-east.htest.svc.cluster.local` in the `west` cluster. 
```console
$ kubectl --context west get svc -n htest
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
hello-east   ClusterIP   10.100.3.128   <none>        80/TCP    42m
```
And when we try to reach to a specific pod with something like this, it gives error as it fails to resolve the domain.
```
# from a pod from west cluster
curl -vvv http://hello-0.hello-east.htest.svc.cluster.local
* Could not resolve host: hello-0.hello-east.htest.svc.cluster.local
* Closing connection 0
curl: (6) Could not resolve host: hello-0.hello-east.htest.svc.cluster.local
```
Is there something which I'm missing here?

**Comment by LaumiH** [comment]
No @bhavin192 , this is the behavior that Linkerd is offering for now. I came up with the idea of letting Linkerd create ClusterIP Services for each Pod in a StatefulSet in the remote cluster where they are mirrored. Otherwise, this can be regarded as a manual workaround.

**Comment by kleimkuhler** [comment]
@LaumiH Thanks for linking the Slack discussion. I see now you explained it well in the description, but reading the other conversation added some more context that I was missing. I'll reopen this for now because it's not fixed by changes in 2.10 and it's probably worth a little more discussion.

**Comment by mateiidavid** [comment]
Hey everyone, I have been looking into this in the past week and have a potential solution along with some questions. In coming up with a solution, I had these two statements into consideration:

> When I try to mirror the headless service hello.htest.svc.cluster.local from east cluster to west, it gets created as a ClusterIP service hello-east.htest.svc.cluster.local in the west cluster. (1)

> K8s supports this by introducing stable pod Ids composed of <pod-name>.<svc-name>.<ns>.svc.cluster.local. Accessing e.g. a mongoDB pod would happen via <mongo-0>.mongo.mongo.svc.cluster.local. (2)

The solution to me seems to be pretty simple -- if we can let K8s configure DNS entries for mirrored pods on the src cluster and if we can route to the right pod in the gateway then all's well.

**How does DNS work with headless services** is the first question I asked myself:

> A StatefulSet can use a Headless Service to control the domain of its Pods. The domain managed by this Service takes the form: $(service name).$(namespace).svc.cluster.local, where "cluster.local" is the cluster domain. As each Pod is created, it gets a matching DNS subdomain, taking the form: $(podname).$(governing service domain), where the governing service is defined by the serviceName field on the StatefulSet. [[ref]](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id)

> For headless Services that do not define selectors, the endpoints controller does not create Endpoints records. However, the DNS system looks for and configures either:
 *CNAME records for  [ExternalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) -type Services.
*A records for any Endpoints that share a name with the Service, for all other types. [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services)


This is how I interpret the above: we use a headless service to give our statefulset a stable network identity; if our headless service has a corresponding Endpoints object **WITH** a label selector then that selector will create a bunch of A records and the headless service serves as an SRV record that will point to all of the pod A records. For example, consider a statefulset called `mehdb` with 2 pods, `mehdb-0` and `mehdb-1` if they have a headless service `mehdb` with a selector this is what the DNS records look like:
```
root@srvlookup:/# dig SRV mehdb.default.svc.cluster.local

;; ANSWER SECTION:
mehdb.default.svc.cluster.local. 5 IN   SRV     0 50 9876 mehdb-0.mehdb.default.svc.cluster.local.
mehdb.default.svc.cluster.local. 5 IN   SRV     0 50 9876 mehdb-1.mehdb.default.svc.cluster.local.

;; ADDITIONAL SECTION:
mehdb-0.mehdb.default.svc.cluster.local. 5 IN A 10.244.1.10
mehdb-1.mehdb.default.svc.cluster.local. 5 IN A 10.244.1.11

(3)
```

Without a selector, we will still have A records provided that *Endpoints that share the same name with the Service* which got thinking that we can probably write endpoints objects ourselves and put an arbitrary IP address for arbitrary hosts.

**My solution is**:
 * Mark a service with a "headless" annotation (e.g `mirror.linkerd.io/headless=true`)
 * If our service is headless then we mirror it a bit differently: we pass `None` to its clusterIP
 * For the endpoints object, instead of having only one address that points to the gateway, we have as many addresses as 
    the source headless service is backing. We give each address a hostname and have its IP set to the gateway.
 * Since the endpoints object will have the same name as the service, then kube's dns service will create a bunch of A records for our "fake" hosts/pods -- all pointing to the gateway.

This is based on (2), (3) and (1) as a constraint (we don't want a service to have a clusterIP)

We should be able to have the same functionality as in the target cluster now, we can request the headless service directly (in which case the call will go to one of the A records that the headless service points to, so to the gateway and then to a random pod) or request a specific pod.

Here's an example service and endpoints object for a mirrored `mehdb` statefulset:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-resource-version: "18662"
    mirror.linkerd.io/remote-svc-fq-name: mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-east
  namespace: default
  resourceVersion: "226036"
  selfLink: /api/v1/namespaces/default/services/mehdb-east
  uid: a27a1e96-fad7-4e3a-bb1e-02c542582b36
spec:
  clusterIP: None 
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```
```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
    mirror.linkerd.io/remote-svc-fq-name: mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-east
  namespace: default
  resourceVersion: "226037"
  selfLink: /api/v1/namespaces/default/endpoints/mehdb-east
  uid: 5f6b99ca-e480-441f-a8df-f5b5fd4de8e1
subsets:
- addresses:
  - hostname: mehdb-0
    ip: 52.186.161.175
  ports:
  - port: 4143
    protocol: TCP

```

And here's what nslookup & dig return for the example posted above:
```
# nslookup mehdb-east.default.svc.cluster.local
Server:         10.0.0.10
Address:        10.0.0.10#53

Name:   mehdb-east.default.svc.cluster.local
Address: 52.186.161.175

# dig SRV mehdb-east.default.svc.cluster.local

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> SRV mehdb-east.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21992
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 80175e8fa5a3be60 (echoed)
;; QUESTION SECTION:
;mehdb-east.default.svc.cluster.local. IN SRV

;; ANSWER SECTION:
mehdb-east.default.svc.cluster.local. 5 IN SRV  0 100 4143 mehdb-0.mehdb-east.default.svc.cluster.local.

;; ADDITIONAL SECTION:
mehdb-0.mehdb-east.default.svc.cluster.local. 5 IN A 52.186.161.175

;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Fri Apr 16 17:06:13 UTC 2021
;; MSG SIZE  rcvd: 237

```

So far this all looks like a promising solution to me, however, I'm unsure how we can route everything when we get to the gateway. We can't do it based on the mirrored fqdn since that won't target a specific pod but the headless service. Also curious if what I came up with so far checks out with how DNS and K8s work together. Specifically, am I right to assume that if we do `curl mehdb-0.mehdb-east.default.svc.cluster.local` it would go to 52.186.161.175 (which in this case would be the gateway IP).

*N.B* that gateway IP looks a bit weird, messed up some gateway config mid testing but I'm fairly confident any arbitrary IP put in there would yield the same results; i.e replacing 52.186.161.175 with  20.81.24.63 should still create DNS records in the same way.

Also, I was curious if K8s would complain if we have the same IP address associated with different hosts, it doesn't seem to:
```
NAME         ENDPOINTS                                 AGE
mehdb-east   52.186.161.175:4143,52.186.161.175:4143   2m19s

apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
    ...
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
    mirror.linkerd.io/remote-svc-fq-name: mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T17:13:57Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-east
  namespace: default
  resourceVersion: "228671"
  selfLink: /api/v1/namespaces/default/endpoints/mehdb-east
  uid: a548c14b-4308-4576-a7bf-33520a553bee
subsets:
- addresses:
  - hostname: mehdb-0
    ip: 52.186.161.175
  - hostname: mehdb-1
    ip: 52.186.161.175
  ports:
  - port: 4143
    protocol: TCP

```

To give some credit, [mehdb comes from this helpful post](https://kubernetesbyexample.com/statefulset/)

**Comment by kleimkuhler** [comment]
Creating the endpoints object as you described seems like a good way to solve this. As for your question:

> So far this all looks like a promising solution to me, however, I'm unsure how we can route everything when we get to the gateway. We can't do it based on the mirrored fqdn since that won't target a specific pod but the headless service

_This is a possible solution I have not made any code changes to see if this works._

So right now when making a request from the source cluster for the non-headless service `foo-east.default.svc.cluster.local`, the client has to query the destination service for that destination. The destination service will return an address with the service name already overridden via the `AuthorityOverride` field ([source](https://github.com/linkerd/linkerd2/blob/78363ca89400eb7563491608156c554c2b60927b/controller/api/destination/endpoint_translator.go#L237-L241)) and the address set to the gateway. The `AuthorityOverride` field is set by the endpoints watcher which looks at the endpoints object's `mirror.linkerd.io/remote-svc-fq-name` label ([source](https://github.com/linkerd/linkerd2/blob/3f72c998b3c4f0f9616ddaa6193dea9f1bd52692/controller/api/destination/watcher/endpoints_watcher.go#L800-L802)).

In this new situation, we'll query the destination service for the instance ID of a headless service like `foo-0.foo-east.default.svc.cluster.local`. Similar to above, we want the destination response to have it's `AuthorityOverride` header be overridden to the instance ID on the target cluster (`foo-0.foo.default.svc.cluster.local`) and the address set to the gateway.

There are a few things that need to happen for this to work out:

1. Right now the address set created by a single endpoints object all have the same `AuthorityOverride` value because they all use the `mirror.linkerd.io/remote-svc-fq-name`'s value; this would need to change so that an endpoints object creates an address set where each endpoint has the unique instance ID (`foo-0`, `foo-1`) attached to it. That way, when we do a `Get` for `foo-0.foo-east.default.svc.cluster.local`, the response ensures that once it passes through the gateway it's authority will match the instance ID in the target cluster.
  _I think we still may be able to use the same value for this label, but it would be responsible for appending `foo-0` and so on for each subset._
  
2. I think the name we use for the `Get` call is from the `dst_override` field of `GetProfile` response. We would need to make sure we are using the full instance ID name instead of what is returned by the `dst_override` field. For example, if we have an instance ID `foo-0.foo.default.svc.cluster.local` and we do a `GetProfile` for that, the response drops the instance ID ([source](https://github.com/linkerd/linkerd2/blob/78363ca89400eb7563491608156c554c2b60927b/controller/api/destination/server.go#L276)). This results in a response:
  ``` INFO[0000] fully_qualified_name:"foo-0.foo.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"foo.default.svc.cluster.local.:9876" weight:10000} ```
  The `authority` is the service name—not the instance ID. We use this value in the `Get` call which is not want we want to do this case. _Note: I'm not sure we want to start propogating instance ID in this response since this is the actual "profile" for the `foo` service, but we probably want to change something here._
  

Once we have `1` and `2` wired up, I think the rest may fall into place. Ultimately, it's all based off properly setting `AuthorityOverride` in the `Get` response so that it's the name of the instance ID in the target cluster. It will go through the gateway and get properly routed in the target cluster once it arrives.

**Comment by mateiidavid** [comment]
Have an update with a conversation we had outside of this GitHub issue.

Kevin's suggestion seemed promising but it might be infeasible for this purpose. The main assumption we had was that the outbound proxy would perform a profile lookup on the fqn name of the instance we are trying to reach (e.g `mehdb-0.mehdb-east.default.svc.cluster.local`), then using the fqn again we would have a `Get` call which would give us an endpoint with its address (Gateway IP in this case).  We can't really use a logical address here though, we would need an actual IP address.

I'm looking into a different solution now. When we spoke collectively, we came up with two ways of doing this:
 1. Spin up some fake pods so we can get Kubernetes to allocate some IP addresses for us (this means the service mirror controller would also have to manage pods which would naturally introduce lots of complexity);
 2. Or introduce a service per StatefulSet instance; each service would have its own clusterIP and then each service would maintain an Endpoints object with a single host: the gateway address.
 
(2) seems like a better solution. In short, we might be able to have a headless service that "manages" all instance services. Instead of configuring DNS as I first suggested, we would have a mirrored headless service and then that service's endpoints would be all other services that are specific to each instance in the StatefulSet. The advantage of this method is that each clusterIP service would also have all relevant multicluster annotations so the outbound proxy would know precisely which service to connect in the outbound gateway.

I will be taking a look at the service mirror controller to see if we can set up all of these service redirects and update the comment with a more concrete solution.

**Comment by olix0r** [comment]
Note from https://kubernetes.io/docs/concepts/services-networking/service/

> Endpoint IP addresses ***cannot be the cluster IPs of other Kubernetes Services***, because kube-proxy doesn't support virtual IPs as a destination.

I'm not sure whether this means that the Kubernetes API will now allow this or whether kube-proxy doesn't support it. If only the latter, it could still be an option for us...

**Comment by mateiidavid** [comment]
### Testing service 'redirection'

In my last comment I offered two solutions that were suggested by the team:
  * back up the mirrored services with some pods (to get IP addresses allocated);
  * or build a set of clusterIP services for each instance of the StatefulSet (managed by the svc mirror controller).

I went with option (2) and built some manifests to test assumptions.

1. I created 2 clusterIP services for 2 `mehdb` instances. For each clusterIP I also created an Endpoints object whose only endpoint is the Gateway IP (no hostname).
2. I created a headless service (no clusterIP). This is what the service mirror would create as a "root" service (hypothetically). In the headless service's endpoints, I added the two clusterIP services.
3. I ran `nslookup` to see whether an instance's fqn resolves to the clusterIP we expect, ran dig to make sure we have SRV records created for the headless service and finally did some destination service queries. 


---
### Manifests

<details>
  <summary> ClusterIP for <strong>mehdb-0</strong> </summary>

```yaml
  apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-resource-version: "18662"
    mirror.linkerd.io/remote-svc-fq-name: mehdb-0.mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-0-east
  namespace: default
  resourceVersion: "226036"
  selfLink: /api/v1/namespaces/default/services/mehdb-0-east # might have to rm this
  uid: a27a1e96-fad7-4e3a-bb1e-02c542582b36
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
</details>

<details> <summary>Endpoints for <strong>mehdb-0</strong></summary>

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
    mirror.linkerd.io/remote-svc-fq-name: mehdb-0.mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-0-east
  namespace: default
  resourceVersion: "226037"
  selfLink: /api/v1/namespaces/default/endpoints/mehdb-east # rm or point to original endpoint?
  uid: 5f6b99ca-e480-441f-a8df-f5b5fd4de8e1
subsets:
- addresses:
  - ip: 52.186.161.175
  ports:
  - port: 4143
    protocol: TCP
```
</details>

<details><summary> ClusterIP for <strong>mehdb-1</strong></summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-resource-version: "186662"
    mirror.linkerd.io/remote-svc-fq-name: mehdb-1.mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-1-east
  namespace: default
  resourceVersion: "226036"
  selfLink: /api/v1/namespaces/default/services/mehdb-0-east # might have to rm this
  uid: a27a1e96-fad7-4e3a-bb1e-02c542582b36
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
  sessionAffinity: None
  type: ClusterIP
status:
```
</details>

<details><summary> Endpoints for <strong>mehdb-1</strong> </summary>

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
    mirror.linkerd.io/remote-svc-fq-name: mehdb-1.mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-1-east
  namespace: default
  resourceVersion: "226037"
  selfLink: /api/v1/namespaces/default/endpoints/mehdb-east # rm or point to original endpoint?
  uid: 5f6b99ca-e480-441f-a8df-f5b5fd4de8e1
subsets:
- addresses:
  - ip: 52.186.161.175
  ports:
  - port: 4143
    protocol: TCP
```
</details>


<details><summary>Headless service <strong>(mehdb-east)</strong></summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-resource-version: "18662"
    mirror.linkerd.io/remote-svc-fq-name: mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T10:14:11Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-east
  namespace: default
  resourceVersion: "170225"
  selfLink: /api/v1/namespaces/default/services/mehdb-east
  uid: 9ecd6294-c121-4ddb-b453-684202e580a8
spec:
  clusterIP: None
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
</details>


<details><summary> Headless Endpoints <strong>(mehdb-east)</strong></summary>

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
    mirror.linkerd.io/remote-svc-fq-name: mehdb.default.svc.cluster.local
  creationTimestamp: "2021-04-16T16:55:08Z"
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
  name: mehdb-east
  namespace: default
  resourceVersion: "226037"
  selfLink: /api/v1/namespaces/default/endpoints/mehdb-east
  uid: 5f6b99ca-e480-441f-a8df-f5b5fd4de8e1
subsets:
- addresses:
  - hostname: mehdb-0
    ip: 10.43.40.218
    # I added this in with the hope that
    # the dest service will give us an endpoint
    # on getProfile, spoiler: it didn't :( 
    targetRef:
      kind: Pod
      name: mehdb-0
  - hostname: mehdb-1
    ip: 10.43.41.204
  ports:
  - port: 4143
    protocol: TCP
```
</details>

<details><summary> <strong>DNS example</strong></summary>

```bash

❯ k exec dnsutils -it -- sh
/ $ nslookup mehdb-0.mehdb-east.default.svc.cluster.local
# only ran this for the first instance
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   mehdb-0.mehdb-east.default.svc.cluster.local
Address: 10.43.40.218

/ $ dig mehdb-east.default.svc.cluster.local

; <<>> DiG 9.11.6-P1 <<>> mehdb-east.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34392
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: dc15d19ccee644e5 (echoed)
;; QUESTION SECTION:
;mehdb-east.default.svc.cluster.local. IN A

;; ANSWER SECTION:
mehdb-east.default.svc.cluster.local. 5 IN A    10.43.40.218
mehdb-east.default.svc.cluster.local. 5 IN A    10.43.41.204

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Wed Apr 21 10:54:34 UTC 2021
;; MSG SIZE  rcvd: 181
```
</details>

---

re: 
> I'm not sure whether this means that the Kubernetes API will now allow this or whether kube-proxy doesn't support it. If only the latter, it could still be an option for us...

I was worried about this to when I first read it but it seems that the K8s API didn't complain this time around. I was able to query the destination service and get profiles back for both services.

When I queried by fqn I had the same answer as before, when I queried by the clusterIP the `dst_overrides` were different. Basically, this is how I understand it now:

1. Client app does a DNS look-up on the pod it wants to talk to (`mehdb-0.mehdb-east.default.svc.cluster.local`) -- as seen in the nslookup above, this would return `10.43.40.218` the clusterIP of its service, to confirm, I did a quick `kubectl get services`.

```bash
$ k get svc
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
mehdb-0-east   ClusterIP   10.43.40.218   <none>        9876/TCP   61m
mehdb-1-east   ClusterIP   10.43.41.204   <none>        9876/TCP   61m
mehdb-east     ClusterIP   None           <none>        9876/TCP   58m

```

2. With the IP resolved, the client app sends its request, this gets picked up by the proxy which does a getProfile on it.

*Note*: even though I added a targetRef in mehdb-0 (just the gvk of a pod) the responses between 0 and 1 are the same, presumably it would've been different if we did have a pod.

```
$ go run controller/script/destination-client/main.go -method getProfile -path 10.43.40.218 (mehdb-0)

INFO[0000] fully_qualified_name:"mehdb-0-east.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"mehdb-0-east.default.svc.cluster.local.:80" weight:10000}

INFO[0000] fully_qualified_name:"mehdb-0-east.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"mehdb-0-east.default.svc.cluster.local.:80" weight:10000}

$ go run controller/script/destination-client/main.go -method getProfile -path 10.43.41.204 (mehdb-1)
INFO[0000] fully_qualified_name:"mehdb-1-east.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"mehdb-1-east.default.svc.cluster.local.:80" weight:10000}

INFO[0000] fully_qualified_name:"mehdb-1-east.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"mehdb-1-east.default.svc.cluster.local.:80" weight:10000}

```

3. Since we don't have an endpoint, the normal path the proxy would take is to do a `Get` (not really what we would want), here's what that would look like for mehdb-0.

```bash
$  go run controller/script/destination-client/main.go -method get -path mehd
b-0-east.default.svc.cluster.local

INFO[0000] Add:
INFO[0000] labels: map[namespace:default service:mehdb-0-east target_cluster:east target_service:mehdb-0 target_service_namespace:mehdb]
INFO[0000] - 52.186.161.175:80
INFO[0000]   - labels: map[]
INFO[0000]   - protocol hint: H2
INFO[0000]   - identity: dns_like_identity:{name:"linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local"}
```

What I want to **note** here is that the target service is set correctly (ish) based on those additional labels we set on each clusterIP service. The service namespace is set to mehdb though (instead of default) since it's the next prefix in the service's fqn.

*Misc*:

```bash
# what we get if we just use the fqn, same resp as before
$ go run controller/script/destination-client/main.go -method getProfile -path mehd-0.mehdb-east.default.svc.cluster.local
INFO[0000] fully_qualified_name:"mehd-0.mehdb-east.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"mehdb-east.default.svc.cluster.local.:80" weight:10000}
INFO[0000]
INFO[0000] fully_qualified_name:"mehd-0.mehdb-east.default.svc.cluster.local" retry_budget:{retry_ratio:0.2 min_retries_per_second:10 ttl:{seconds:10}} dst_overrides:{authority:"mehdb-east.default.svc.cluster.local.:80" weight:10000}
INFO[0000]
```


**Closing notes**: this doesn't get us rid of the additional `Get` call and there are some discrepancies between the observed target cluster fqn and what we would expect (i.e foo-0.foo.svc.cluster.local instead of foo-0.foo.foo-ns.svc.cluster.local) but it looks promising.

cc: @kleimkuhler @olix0r @adleong wdyt?

**Comment by kleimkuhler** [comment]
@mateiidavid thanks for looking into this second issue. It's good to see that it seems like there are less open questions than the last solution!

In (3) your question about the wrong namespace looks to be related to a typo in your `-path`. It should be `mehdb-0.mehdb-east.default.svc.cluster.local`—right now it's missing the `mehdb-east` namespace section.

As for removing `Get` from the proxy path this will require a change in the destination service. Right now, `endpoint` is only populated in the destination profile response when the IP maps to a pod. We'll need to change this to now also populate the field when dealing with one of these types of services. This may need a new annotation value introduced. The destination service would see that this annotation value is set and do an endpoints lookup on the service; it would then take that single endpoint and set `endpoint` on the response.

This may require a change in the proxy as well. We may skip the `Get` call already though if `endpoint` is set—we do at least in the regular request path. It may be different though in the gateway.

**Comment by kleimkuhler** [comment]
This is being actively worked on in #6090
