### ISSUE TITLE
Argo Rollout Canary deployments are invisibile

### ISSUE THREAD

**Issue by shaikatz** [linkerd/linkerd2#5189]
## Feature Request
I would like to be able to see the [Rollout](https://argoproj.github.io/argo-rollouts/features/canary/#example) objects in the deployments tab.

### What problem are you trying to solve?
Argo Rollouts is a highly used Canary provider, which uses special `Rollout` CRD that replaces the native `Deployment` object.
Currently, it's invisible in linekrd's dashboard and grafana boards, and cannot be observed.

### How should the problem be solved?
The dashboard query to retrieve deployments should also include `Rollout` objects.

### Any alternatives you've considered?
Switch to flagger which doesn't use special CRD, but it will take time.

**Comment by grampelberg** [comment]
How do rollouts work? What resources does it create? What is the workflow?

**Comment by shaikatz** [comment]
Rollouts are direct replacements of Deployment object.
They manage replicasets for Canary deployments.
The flow is that you create `Rollout` object, and then Argo Rollouts takes care of rolling your stuff out slowly and safely.
You can see the `Rollout` object spec here: https://argoproj.github.io/argo-rollouts/features/specification/

There is no Deployment object involved anywhere in the flow, even when it's done.

**Comment by shaikatz** [comment]
@grampelberg any thoughts?

**Comment by grampelberg** [comment]
@shaikatz sounds reasonable. This is a pretty large feature that will require proxy work and updating how metrics are currently exported to be native. You could probably approximate things by doing some creative prometheus queries in the meantime though.

**Comment by shaikatz** [comment]
Can you enumerate roughly the steps needed in order to support that? as far as I can see the change is only in the Linkerd labels (to include rollout in addition to currently supported owners), and UI to show the Rollout section.

**Comment by grampelberg** [comment]
The `kind` and `dst_kind` labels would need to be updated in the proxy so that the owner type is there. Instead of hacking it, I'd recommend changing the way labels work entirely for metrics to something that would support *any* owner type. Once that work was done, it'd just bubble up through prometheus and the dashboard. To keep from supporting one-off CRDs in the dashboard, I'd populate the resource types based off observed metrics (from the reworked metrics labels).

You could *probably* hack this with some re-labeling configs in prometheus if you don't care about anything other than really raw server metrics. At that point though, it doesn't feel worth updating the UI until the more generic solution is in place.

**Comment by shaikatz** [comment]
Looks like the `dst` and `dst_kind` already flexible enough and they show the `rollout` kind.
I feel like the only missing part is actually the UI. 
Does it make sense?

**Comment by ankit-ls** [comment]
@grampelberg Any plans to support `rollout` objects?

As per @shaikatz's previous [comment](https://github.com/linkerd/linkerd2/issues/5189#issuecomment-736542153) it looks like the only missing part is in UI. Is it something that we can expect to be added soon?
