### ISSUE TITLE
cli: Reorganize diagnostic subcommand(s)

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5192]
There are a few purely diagnostic CLI subcommands that are generally useful, especially for Linkerd developers, but don't achieve any high-level user-facing tasks...

- `diagnostics`  Fetch metrics directly from the Linkerd control plane containers
- `endpoints`    Introspect Linkerd's service discovery state
- `metrics`      Fetch metrics directly from Linkerd proxies

I propose that we move all of these under `linkerd diagnostics` as follows:

- `linkerd diagnostics endpoints svc/foo [port]`

The `endpoints` command should become `linkerd diagnostics endpoints`. The authority-form of resolutions is somewhat of an implementation detail and, instead of a DNS-form name, the CLI should accept a service or pod reference and a port. Service lookups should be traffic-split aware, resolving via service profiles to obtain traffic splits before resolving individual leaf services.

- `linkerd diagnostics proxy-metrics -n NS po --selector ...` 

The `linkerd metrics` command should be renamed `linkerd diagnostics proxy-metrics`. It should accept the same CLI arguments as `kubectl get` (which it does not today); and it should dump the metrics from all selected resources.

- `linkerd diagnostics controller-metrics [-n NS] [workload]`

The `linkerd diagnostics` command, as it exists today, doesn't really fit into a world where controller is split across multiple namespaces. I.e., we already have a `linkerd-multicluster` namespace that isn't supported by the command. The command should be moved to `linkerd diagnostics controller-metrics`. By default it should dump the mertrics from the core control plane components, but it should also accept an optional workload reference (pod, deployment, label selector, etc) so that the command may be used with any linkerd controllers. I think we should assume/require that there is an `admin-http` container port for all control plane components, and this should be used to determine which port is read. (Alternately, there's no reason we need these ports to vary at all -- it seems easier/better to simply standardize on using the same port across all linkerd controllers, but this isn't really a requirement, i guess).

**Comment by adleong** [comment]
As things stand today, I'm not really sure who the `linkerd endpoints` command is for.  In practice, it's not that useful as a debugging tool when there are service discovery issues since these issues are often related to watches and the `linkerd endpoints` command initiates a new stream each time it is invoked.  The destination-client script ends up being a much more useful debugging tool for Linkerd developers.

We could make the `linkerd diagnostics endpoints` command work more like the destination-client script, but I'm not sure what the benefit would be.  If this is a tool used only by developers, I think the existing destination-client script is sufficient.  Unless this needs to be exposed to end users for some reason, I suggest removing the `linkerd endpoints` command altogether.

**Comment by adleong** [comment]
+1 to the `linkerd diagnostics proxy-metrics` and `linkerd diagnostics controller-metrics` commands.
