### ISSUE TITLE
Modularize a linkerd-viz extension

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5197]
`linkerd install` should only provide the components that are essential to operating Linkerd to support mTLS, load balancing, and routing/policy. This includes:

* A proxy injector that adds the proxy sidecar(s) to pods at injection-time.
* An identity controller that certifies proxy identities.
* A destination controller that serves service discovery for proxies.
  * Using SMI TrafficSplit
  * Also (should) host validators for relevant CRDs (like serviceprofiles). #5195
  * The contract between multicluster gateways & the destination should be made
    more explicit (and generic). #5196

The core `linkerd install` and `linkerd upgrade` logic should operate _only_ on these resources.

We should  split out the observability components into a module, such the core control plane and its install/upgrade flow have no knowledge of these components.

This includes at least the following control-plane components:

* Prometheus (Required, but pluggable)
* Grafana (Optional)
* Jaeger + OpenCensus (Optional)
  * Must provide its own proxy-injection logic.
* Tap (Optional???)
  * Powers the `linkerd tap` (sub-)command(s)
  * Must provide its own proxy-injection logic.
* Dashboard (Optional) -- uses ~all of the above components

There are a number of CLI commands that require some or all of these components:

* `dashboard`    Sets up port forwarding to open the Linkerd dashboard/grafana in a web browser
* `edges`        Display connections between resources, and Linkerd proxy identities
* `routes`       Display route stats
* `stat`         Display traffic stats about one or many resources
* `tap`          Listen to a traffic stream
* `top`          Display sorted information about live traffic

I propose that we move _all_ of these under a `linkerd viz` subcommand. Additionally, `linkerd viz` should have its own `install` command. We should avoid having specific `upgrade` logic if at all possible (AIUI `linkerd upgrade` is really only necessary to avoid regenerating certificates, so it should not be necessary for this extension).

All of these components should be installed into a separate namespace, `linkerd-viz`. These components need not be "manually" injected and instead should rely on the core control plane's proxy injector.

Any viz-specific `check` logic should be removed from the core `linkerd check` command into a separate `linkerd viz check`.

**Comment by grampelberg** [comment]
My straw argument here would be to aggressively split these all into separate "addons". My reasoning:

- Why have optional pieces of optional pieces? Feels like an extra abstraction layer for no real value?
- BYOP feels like an identical case to a separate prometheus "addon". Having the Linkerd controlled one still be a first class citizen just feels like we're gonna paint ourselves into a corner eventually.
- The Jaeger config at the moment is *purely* for demo purposes. Everyone *should* install their own. This falls into a super similar situation to BYOP and just keeping the optional pieces at the flat addon level.

From a UX perspective, I do think having a bundle is critical. Just like `apt install build-essentials` there should be something like `linkerd install the-kitchen-sink-please`.

From an architectural perspective, I think that we should force ourselves to treat each service as a third party solution and harden the interfaces so that it is a positive experience. This means that when someone BYOP/G/J they'll have that sweet experience with links and cli feedback right out of the box.

**Comment by adleong** [comment]
I think that having linkerd-prometheus be an optional component in the linkerd-viz addon makes sense for a combination of two reasons:
* linkerd-prometheus is purpose built for linkerd-viz.  you can have linkerd-viz without linkerd-prometheus, but not the other way around
* linkerd-viz cannot operate without a prometheus instance (either BYOP or linkerd-prometheus)
* the most common case will be linkerd-prometheus, especially for new users

Having a bundle install DOES solve most of my concerns above.  But it's unclear exactly which combinations we would offer (viz + prometheus, just viz, viz with tracing, viz with prometheus and tracing???, what about multicluster?????) and it might be confusing when users should use a bundled install versus installing addons directly.

It's definitely feasible to aggressively split things out, but to me it feels like a group of components which all work together to provide a piece of functionality belong together in the same addon.

**Comment by adleong** [comment]
I do think linkerd-tracing should be split out, as described in https://docs.google.com/document/d/11sf9mLojKA0OLERy9tgEDanzYXorZNLgQwR_r-mq-2Q/edit?usp=sharing

I could also see linkerd-garfana being split out because it doesn't provide a core piece of viz functionality the same way that prometheus does.

linkerd-tap is used heavily by the CLI and web dashboard and doesn't have any replacement (i.e. there's no Bring-Your-Own-Tap) so I don't think there's much value in splitting it out.

**Comment by olix0r** [comment]
I'm +1 on jaeger being split out--it really has minimal touch points with the rest of the viz experience, but I really do not think it makes much sense to split web/grafana/prometheus into independent pieces -- all of these inkerd-viz components are tightly coupled to prometheus's scrape config & format and, while we want to support using an alternate prometheus instance, they are not really independent. At least, I don't see a strong motivation to splitting them up in the short-term.

**Comment by olix0r** [comment]
This is now tracked by other issues and is mostly complete.
