### ISSUE TITLE
Proxy admin server should expose metrics

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5212]
We currently don't track tcp/http metrics for the proxy's admin server. It should be instrumented with transport and http metrics so we can understand its edges, etc.

**Comment by hawkw** [comment]
Per a conversation with @olix0r, we determined that the best way to go about this is probably by just changing the proxy's admin metrics to be part of the inbound metrics, rather than separating them. That would mean that all traffic to the admin listener will show up as "inbound" traffic. 

To distinguish inbound traffic to the admin listener from inbound traffic to the inbound proxy listener (e.g. to the application), we should also add ports to these metrics.

**Comment by olix0r** [comment]
@hawkw Is this complete?

**Comment by hawkw** [comment]
Yup, forgot to close this from the proxy PR!
