### ISSUE TITLE
Way to exclude pods from prometheus scrape

### ISSUE THREAD

**Issue by shaikatz** [linkerd/linkerd2#5280]
### What problem are you trying to solve?
When adding Prometheus and nginx-ingress to your mesh, they produce a huge amount of metrics, which makes Prometheus use an excessive amount of memory.

### How should the problem be solved?
We should provide the user with the option to edit the scrape configs of the Prometheus add on, to drop metrics from specific deployments.

### Any alternatives you've considered?
Remove the proxy from those targets, but I want the proxy in order to be able to take advantage of traffic splits.

### How would users interact with this feature?
Values.yaml

**Comment by olix0r** [comment]
@shaikatz have you considered [deploying prometheus seperately](https://linkerd.io/2/tasks/external-prometheus/)? Prometheus has very rich configuration surface area, so our goals with the default prometheus instance is to deploy something that Just Works without much extra configuration. For users that require additional prometheus configuration, we expect them to disable the default prometheus instance and manage that configuration outside of Linkerd.

**Comment by shaikatz** [comment]
I really like the coupling between linkerd and prometheus installations since it already includes all the required scrape configs.
If I'll maintain my own prometheus for that, I will have to makes sure for each update that my scrape configs are updated and nothing was changed in Linkerd side.

I think it makes sense to let us customize the scrape configs, instead of directing us to use our own prometheus installation - especially when other prometheus configs are already provided in the chart (`alertRelabelConfigs` for example)

**Comment by adleong** [comment]
Hey @shaikatz.  I can see where you're coming from about wanting to stay in sync with the Linkerd scrape configs.  I will point out, however, that our scrape configs change very rarely.  Another thing to note is that your proposed change will allow adding relabel configs, but not modifying or removing any of the existing relabel configs.

Since it's not really feasibly for Linkerd to support all of the many different ways users might want to configure Prometheus (relabel configs being just one of these), we'd really prefer to keep the Linkerd prometheus configuration as simple as possible; with the understanding that users who want a different configuration have the freedom to deploy an external Prometheus with any configuration they desire.

If our scrape configuration ever changes, we'll be sure to call that out in our upgrade notes so that users who have deployed their own Prometheus will know how to update their configs.

**Comment by adleong** [comment]
@shaikatz I'm going to close this issue and the associated PR for now.  Please feel free to re-open if you'd like to continue the discussion.
