### ISSUE TITLE
Make `linkerd check` comprehend mulit-cert CA bundles

### ISSUE THREAD

**Issue by cypherfox** [linkerd/linkerd2#5292]
### What problem are you trying to solve?
When running `linkerd check` where the contents of `IdentityContext.TrustAnchorsPem` are a set of certificates (i.e. a bundle), the test for the validity of the identity will produce the following error:

```
linkerd-identity
----------------
× certificate config is valid
    IdentityContext.TrustAnchorsPem does not match ca.crt in linkerd-identity-issuer
    see https://linkerd.io/checks/#l5d-identity-cert-config-valid for hints
```

even though the contents of `ca.crt` are in fact an element of that caBundle.

### How should the problem be solved?

Add support for bundles to the check command for this test.

**Comment by cypherfox** [comment]
I have had a look at the code, and this may not be as straightforward as I thought it to be initially:
In order to support arbitrary length cert chains, the code needs to properly parse the CA certs in the field `ca.crt` within the K8S secret `linkerd-identity-issuer`.
My *assumption* would be, that the **Root** of `ca.crt` should be contained as one of the certs in the field `global.identityTrustAnchorsPEM` in the config map `linkerd-config`. 

Is that the intended behaviour?

**Comment by adleong** [comment]
(copied my questions from Slack)

so I think this is the external issuer case, correct?  e.g. cert-manager

when you install Linkerd with the CLI, it automatically copies the ca bundle from the cert-manager created secret into the Linkerd config.  so those values are supposed to match exactly

if installing with Helm you have to do this yourself

the ca cert bundle in the Linkerd config is what’s distributed to proxies for them to use to validate certificates.  I think they need the entire cert chain in order to be able to do this

so if I’m understanding correctly, I think the check is correct as-is.  Or rather, my question is: what is the scenario where the configured ca cert bundle is not identical to the ca.crt file?

**Comment by cypherfox** [comment]
The check will fail when you work through the manual trust anchor rotation as documented (https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/), as the `ca.crt` will only contain the upper part of the cert chain from the identity issuer to its root, while the field `global.identityTrustAnchorsPEM` of the linkerd config will contain two root certs.
This case would be relatively simple to support: just parse both value string as a set of (root) certs and check if the former is a subset of the later.

The case *may* get more complex, when the upper chain contains more than one cert, e.g. when all of the linkerd certs are linked to an enterprise PKI. Then there are 1 or more certs in `ca.crt` and the top most of the chain they create will have to be contained in the list of trust anchors in `global.identityTrustAnchorsPEM`. 
In order to verify this, I would have to set up a suitably complex test case. 

I just wanted to check beforehand whether you will accept such complexity in the code tree. If the functionality is not accepted, `linkerd check` will not work in fully linked enterprise PKI setups, as described above. As the code works at the moment, it does not support root rotation without downtime, but is relatively quickly fixed.

**Comment by adleong** [comment]
I'm having a hard time following exactly what the scenario is here.  The check that you mention is only used when there is an external identity issuer (e.g. cert-manager).  The manual cert rotation docs don't cover how to rotate cert-manager's root certificate.

So it sounds like you're adding the multi-cert CA bundle to the Linkerd config with the intention of rotating the root credentials for cert-manager next.

In reality, the contents of `ca.crt` don't matter because Linkerd never uses this file directly (it simply copies this value into `global.identityTrustAnchorsPEM` at install time).  So having `global.identityTrustAnchorsPEM` and `ca.crt` out-of-sync isn't a problem, but it may indicate that the installation did not work correctly or that one of these values has changed since install.

I think my preference is that we split this check out of the "certificate config is valid" check into it's own line item and make it a warning rather than an error.  This will mean that `check` will warn while you're in the process of rotating these root certificates and serve as a reminder that the rotation process is not yet complete until ca.crt is brought in sync with the CA bundle.

**Comment by cypherfox** [comment]
Yes, I am adding a multi-cert CA bundle, because that is (IMO) the only way to rotate the trust anchors without a down time.

And regardless of the fact whether linkerd actually *needs* the `ca.crt` to be correct, the test is there and will stop the program when it does not succeed.

I think the test is pretty usefull, especially when rotating the anchors, as it will tell you when you a) have added the correct new anchor (potentially a chain of multiple certs), Also, b) when you have removed the right one (the one **not** in `ca.crt`) after the distribution of the new one is complete and you want to clean up.

**Comment by adleong** [comment]
Makes sense.  I'd be in favor of moving the check which compares `ca.crt` and `global.identityTrustAnchorsPEM` to its own line item and make that item a warning instead of an error.
