### ISSUE TITLE
`linkerd upgrade` used for changing settings (not for version upgrades) puts proxy injector in invalid state

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5341]
### What is the issue?

Issuing `linkerd upgrade` CLI to update a setting, e.g. `linkerd upgrade --enable-endpoint-slices`, but not for a full version upgrade, results in the injector webhook secret being regenerated, but the injector pod doesn't get rolled-out and thus it starts failing with certificate errors and pods are no longer injected.

### How can it be reproduced?

- Install linkerd 2.9.0
- `linkerd upgrade --enable-endpoints-slices | kubectl apply -f -`
- `kubectl logs -f deploy/linkerd-proxy-injector proxy-injector`
- `linkerd inject https://run.linkerd.io/emojivoto.yml | kubectl apply -f -`

The emojivoto pods won't be injected and you'll see the following errors in the logs.

### Logs, error output, etc

```
2020/12/04 17:33:43 http: TLS handshake error from 127.0.0.1:57128: remote error: tls: bad certificate
```

#### `linkerd check` output

The check output is normal.

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: (GKE, AKS, kops, ...): k3d
- Host OS: Linux
- Linkerd version: This only applies to Linkerd version 2.9

### Possible solution

This is fixed in `main` with #5282 that introduces dynamic cert reloading in the http server backing the injector. We could either back-port that into 2.9, or add some logic to avoid the CLI regenerating the secret.

### Additional context

This was found while testing #5299

**Comment by adleong** [comment]
It's good to know that on main the dynamic cert reloading fixes this eventually.  However, we should get an understanding of how much downtime this incurs.  Approximately how long after changing the config is it before the proxy-injector picks up the new certificates?  Can this be sped up by restarting the proxy-injector at the same time?  We have this line in the proxy-injector spec:

```
checksum/config: {{ include (print $.Template.BasePath "/proxy-injector-rbac.yaml") . | sha256sum }}
```

Which seems like is intended to force a restart when the config template changes.  That's not sufficient in this case because the TLS credentials are dynamically generated with Helm functions during rendering.  For this to work, I think it would need to hash the `.Values.proxyInjector.caBundle` if it is set and otherwise use a totally random hash to force a restart.

**Comment by alpeb** [comment]
I'll check exactly how long that delay is. Nevertheless, I think a cleaner fix would be having the injector restart, like you suggest. That is actually sufficient to fix this, even without the dynamic cert reload (which is not trivial to cherry-pick into 2.9.1 btw).
