### ISSUE TITLE
Allow linkerd check to continue evaluating all rules after failure

### ISSUE THREAD

**Issue by rnsv** [linkerd/linkerd2#5450]
## Feature Request
I want linkerd check to continue checking all rules after one or more failures

### What problem are you trying to solve?
Currently, linkerd check fails after the first failure which is not user friendly.

### How should the problem be solved?
Introduce new status between warning and fatal.  for example fail/error that records that the check failed but continues after marking it as failure(x)

### How would users interact with this feature?
No change in the cli implementation

Output would look like this
```
linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
× cni plugin PodSecurityPolicy exists
    missing PodSecurityPolicy: linkerd-kube-mesh-cni
    see https://linkerd.io/checks/#cni-plugin-psp-exists for hints
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
× cni plugin Role exists
    missing Role: linkerd-cni
    see https://linkerd.io/checks/#cni-plugin-r-exists for hints
× cni plugin RoleBinding exists
    missing RoleBinding: linkerd-cni
    see https://linkerd.io/checks/#cni-plugin-rb-exists for hints
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

Status check results are ×
```

**Comment by cpretzer** [comment]
@rnsv thanks for your thoughts on this, from your perspective, it is more user friendly to show all the errors rather than using a "fail fast" approach?

I can see the case where it is also user friendly to break on any check errors in order to enable users to quickly address those issues. Can you provide more information about how the user experience would be different? This is only my opinion, but the important thing is that the errors are reported so that users can address them.

**Comment by piyushsingariya** [comment]
Hi, it's an interesting problem and I would like to work on this? @cpretzer Can you explain a bit more what I exactly have to do here?
Thanks!

**Comment by adleong** [comment]
Check works this way because certain checks only make sense if previous checks have passed.  For example, if the Kubernetes API or Linkerd control plane are not reachable, then most other checks will be guaranteed to fail.  

Only checks which are explicitly marked as `fatal` will cause `linkerd check` to stop immediately.  Are there fatal checks which you think should not be marked as fatal?

**Comment by rnsv** [comment]
Here is a sample implementation
https://github.com/rnsv/linkerd2/commit/ba4c4af0d7bb57732989f457658c91621ea28e44
I introduced a new status name fail (between fatal and warning).

**Comment by adleong** [comment]
`fatal` and `warning` are already separate fields.  This means that checks can be set as as non-fatal errors (fatal=false, warning=false) which will count as check failures, but will allow check to continue to run.
