### ISSUE TITLE
Simplify SelfCheck API

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5575]
Currently the SelfCheck API returns multiple responses that require special handling in the healthcheck library. It's the only gRPC call made by health checks so it still requires to be handled a little different than the other checks, but we can simplify things by:
1) Simplifying the the gRPC function and its protobuf so that `SelfCheckResponse` consists of just a status field and an error message field, instead of the array of results that it currently has.
2) In `healthcheck.go`, processing the check with a regular `Checker.check` callback and getting rid of `Checker.checkRPC`. The callback should inspect the result and eventually return an error.

As an additional simplification we can merge that protobuf into `viz.proto`

This can be addressed after #5560 merges.

**Comment by adleong** [comment]
What I had in mind here was to move the SelfCheck related proto out of a common package and into the viz pacakge (since the metrics-api is the only thing that implements the SelfCheck API).  I don't think we need to modify the proto definition at all.  

Since we're getting rid of `checkRPC`, we lose the ability to have one check which generates multiple check results.  I think this is fine: the self-check checker in `viz check` can simply call `SelfCheck` and if multiple errors are returned, it can concatenate them together.
