### ISSUE TITLE
Upgrade HTTP1 to HTTP2

### ISSUE THREAD

**Issue by seanmonstar** [linkerd/linkerd2#559]
As an optimization, we can try to upgrade HTTP1 requests to HTTP2.

**Comment by briansmith** [comment]
I can see how we can transparently upgrade HTTP/1 to HTTP/2 for outbound HTTPS (TLS) connections when the server advertises HTTP/2 in its ServerHello ALPN extension. I'm not sure how we would do it otherwise. Also, I don't think there is a big reason to do so otherwise since almost all HTTP/2 servers use TLS.

**Comment by olix0r** [comment]
We can issue HTTP/1 requests with the `Upgrade: h2c` header to request upgrade if the server supports this.  This is typically done by issuing an `OPTIONS` request at connect-time, but it can also be piggybacked onto real `GET` requests, for instance.

**Comment by olix0r** [comment]
I think it's _especially_ important for us to upgrade HTTP/1 to HTTP/2 on the _server_ side. On the client, it's mostly important to be able to downgrade HTTP/2 to HTTP/1...

On the serverside, i think we need to support HTTP/1 requests with `Upgrade: h2c`.

On the clientside, we probably want to be able to issue HTTP/1 requests with `Upgrade: h2c`, so that we can leverage h2 for plaintext (e.g. go) services that do support upgrade to h2.

**Comment by hawkw** [comment]
I believe this has been implemented...
