### ISSUE TITLE
multicluster extension cannot be uninstalled if Linkerd is not installed

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5624]
If the main Linkerd control plane has been uninstalled, it is no longer possible to uninstall the multicluster extension.  

Uninstalling the multicluster extension should not required the main control plane.

```
bin/linkerd mc uninstall | k delete -f -
Error: you need Linkerd to be installed in order to install multicluster addons
Usage:
  linkerd multicluster uninstall [flags]
```

**Comment by piyushsingariya** [comment]
I read the issue and the related files. And I found this error to be triggered from https://github.com/linkerd/linkerd2/blob/main/multicluster/cmd/uninstall.go#L63 ;  where `buildMulticlusterInstallValues()` is being called from https://github.com/linkerd/linkerd2/blob/main/multicluster/cmd/install.go#L175
The error is being outputted when we are trying to extract `linkerd-config-map` and values from config-map is being used to create a new instance of InstallValues for multicluster

I thought to remove the step where we are trying to extract the `linkerd-config-map` ; but that's not possible.
Any views??

**Comment by kleimkuhler** [comment]
@piyushsingariya I'd recommend looking at how uninstall works for other extensions such as Jaeger and Viz. Instead of building install values, we look for the `linkerd.io/extension=...` label and delete those resources. Take a look at Jaeger's uninstall [here](https://github.com/linkerd/linkerd2/blob/74950e94076b416813125460df02ca43a16aaa2b/jaeger/cmd/uninstall.go#L37-L39).

If we change Multicluster's uninstall to work in a similar away we should be able to avoid the issue you described above.

**Comment by piyushsingariya** [comment]
Hi, @kleimkuhler @adleong I looked into the uninstallation process of Jaeger and Viz. The process of Multicluster is quite complex than Viz and Jaeger so I thought to show you sample code before start making changes in the file
So we have to change the code after "un-linking the cluster to uninstall the multicluster" and instead of building a new instance of install values [(here)](https://github.com/linkerd/linkerd2/blob/main/multicluster/cmd/uninstall.go#L63)

to something like this.
```
	resources, err := resource.FetchKubernetesResources(ctx, k8sAPI,
		metav1.ListOptions{LabelSelector: "linkerd.io/extension=linkerd-multicluster"},
	)
	if err != nil {
		return err
	}

	for _, r := range resources {
		if err := r.RenderResource(os.Stdout); err != nil {
			return fmt.Errorf("error rendering Kubernetes resource: %v", err)
		}
	}
	return nil
```
i.e. fetching the related resource and deleting them

**Comment by kleimkuhler** [comment]
@piyushsingariya Yep that is more similar to Jaeger and Viz extension uninstalls, so it's what I would expect.

I think something you'll need to double check is that the resources in the multicluster templates that need the `linkerd.io/extension: linkerd-multicluster` label have it.

The fact that `namespace.yaml` has it is good because once that is deleted, it should also delete all the namespace scoped resources meaning that the deployment and services don't need it—they'd be included in deleting the namespace.

The cluster role and cluster role binding in `remote-access-service-mirror-rbac.yaml` may need the label added? I would look at the Jaeger extension for reference on what `Kind`s of resource should have the `linkerd.io/extension` label. Also just testing your change and making sure everything is deleted is good too; those resources may be fine without the label.

Also, feel free to leave any more questions! I'm happy to help out.

**Comment by alpeb** [comment]
Hi @piyushsingariya , just touching base :wave: Is there anything we can help you with?

**Comment by piyushsingariya** [comment]
@kleimkuhler I checked the multicluster templates does contains the label as `linkerd.io/extension: linkerd-multicluster` 

I took references from rabc.yaml files of Jaeger and Viz to replicate and added the label to the `kind` of resources that should have it(ClusterRole, ClusterRoleBinding); (ServiceAccount had the label in case of Viz but not in Jaeger. Should I add the label?)

I think the next step is to replace the deletion code with the one I mentioned above :fire: 

@alpeb Sorry for no update for so many days, I was away due to bad health. And I do need a favor, as Kevin mentioned I should test my changes, could you explain how exactly I should test, in an efficient way :sweat_smile:

**Comment by alpeb** [comment]
> I should test my changes, could you explain how exactly I should test, in an efficient way

You can use the instructions in #5374 to set up a multicluster instance. Then you can check the output of `linkerd mc uninstall` and verify it lists all the multicluster-related resources that are in your source cluster.

**Comment by piyushsingariya** [comment]
Hi, @kleimkuhler I tested out the changes. These are the outputs with latest linkerd edge release
```
$ linkerd mc uninstall | kubectl delete -f -    
namespace "linkerd-multicluster" deleted
configmap "linkerd-gateway-config" deleted
deployment.apps "linkerd-gateway" deleted
service "linkerd-gateway" deleted
serviceaccount "linkerd-gateway" deleted
clusterrole.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
serviceaccount "linkerd-service-mirror-remote-access-default" deleted
clusterrolebinding.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
customresourcedefinition.apiextensions.k8s.io "links.multicluster.linkerd.io" deleted
```
and these are the outputs after making changes and adding labels to rbac.yaml 
```
$ bin/linkerd mc uninstall | kubectl delete -f -
clusterrole.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
clusterrolebinding.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
namespace "linkerd-multicluster" deleted
```

**Comment by piyushsingariya** [comment]
I only added the label i.e. `linkerd.io/extension: linkerd-multicluster` to ClusterRole and ClusterRoleBinding

**Comment by piyushsingariya** [comment]
Hey, @kleimkuhler @alpeb  
After testing out multiple times, I added the label to all the resources of multicluster. However, when I tried to delete the resources, only a few of them were deleted
```
$ bin/linkerd mc uninstall | kubectl delete -f -
clusterrole.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
clusterrolebinding.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
customresourcedefinition.apiextensions.k8s.io "links.multicluster.linkerd.io" deleted
namespace "linkerd-multicluster" deleted
```
I raised a PR to showcase the changes I made.

**Comment by alpeb** [comment]
Thanks @piyushsingariya, I'll comment in #5744
