### ISSUE TITLE
Document compatibilities between different versions

### ISSUE THREAD

**Issue by ahume** [linkerd/linkerd2#565]
What are the expected compatibilities (or upgrade paths) between different versions of Conduit? For example...

- Is `conduit install | kubectl apply -f -` expected to be idempotent?
- After a CLI upgrade, will `conduit install` provide clean upgrades between versions of the control plane? How closely are proxy upgrades tied to control plane upgrades?
- Is it supported to have injected one Deployment with the v0.3.0 proxy and another with v0.3.1?
- It is supported to have the v0.3.0 control plane installed and inject a Deployment with v0.3.1?

I guess the general concern here is whether it's possible to safely upgrade a cluster running a particular version of Conduit (control plane and data plane), to an unspecified future version of either.

**Comment by wmorgan** [comment]
Great set of questions. A partial answer is: there are no promises about  anything around this until Conduit gets to beta. Once it's beta, it should follow semver such that proxies and control plane will be compatible across minor version changes.

For 0.3.0 and 0.3.1 specifically, proxies *should* be compatible---but that was just a happy accident since we're still in alpha. 😄

**Comment by bourquep** [comment]
I'm about to upgrade my prod cluster from v18.8.2 to v18.9.1. What would be the recommended procedure?

**Comment by grampelberg** [comment]
This is sitting in a PR right now:

https://github.com/linkerd/website/blob/grampelberg/upgrades/linkerd.io/content/2/upgrade.md

**Comment by wmorgan** [comment]
This is in https://linkerd.io/2/tasks/upgrade/
