### ISSUE TITLE
Show namespaces for viz, cni and others

### ISSUE THREAD

**Issue by electrical** [linkerd/linkerd2#5899]
### What problem are you trying to solve?

Currently in the Service mesh details table it shows some details but would be great to add all other namespaces information to it.

### How should the problem be solved?

![Screenshot 2021-03-14 at 18 36 49](https://user-images.githubusercontent.com/271677/111080026-73864c80-84f4-11eb-832a-df454b784812.png)

It would be nice to add the other namespaces to this list if they are installed

**Comment by Pothulapati** [comment]
This is definitely a good suggestion. The dashboard did not get enough love of all the updates that happened w.r.t 2.0 yet. :\\

**Comment by de-sh** [comment]
Hey folks, I am just trying to learn more about the linkerd repo, could I contribute to solving this issue?

If yes
- I would like to know what all information are we trying to display
- To confirm, are we thinking of updating web/app/js/components/ServiceMesh.jsx? I am new to React/JSX, but I think I could learn this fast enough.

**Comment by dadjeibaah** [comment]
Hi @de-sh thanks for your interest in working on this! It would be super awesome to list all installed extensions on this page. 

Ideally, this extension info would look very similar to what we already display for the core control plane.
![image](https://user-images.githubusercontent.com/2197104/113349307-7313f100-92fd-11eb-87c5-26fd384ff4e1.png)

I envision adding a new section below the one above called "Installed Extensions" and then list all the installed extension ensuring that each extension name is linkable to their respective `/namespace/<namespace-name>` page. I think we can just display the extension names only for now in the table and  then if we want to add more info to each line, we can update accordingly. In order to get this list of extensions, we'll first need to modify the API at `/api/extension` to return a list of extensions instead of just a single extension name. 

The changes you'd be making would be here:
https://github.com/linkerd/linkerd2/blob/main/web/srv/api_handlers.go#L444-L461

You'd then need to modify the frontend's API so that we can get a list of extension and also support the behavior to also get a single extension from the API.
https://github.com/linkerd/linkerd2/blob/main/web/app/js/components/util/ApiHelpers.jsx#L149-L151

Next, we'd need to make changes in `web/app/js/components/ServiceMesh.jsx` to make requests to the API and then add a new table under the `Control Plane` table.

**Comment by de-sh** [comment]
Hey @dadjeibaah, I have to admit that I feel really bad not being able to setup linkerd from source at this point. Is there any good resource such as a video walk-through of the process to ensure that I am not faltering some where?

Extremely sorry if this isn't the right place to voice my discomforts faced in getting started.

**Comment by kleimkuhler** [comment]
@de-sh No worries! We have instructions updated for 2.10 that result in a locally built Linkerd installation [here](https://github.com/linkerd/linkerd2/blob/main/BUILD.md#comprehensive). If you make changes to the dashboard component, you can use those steps to see the changes you make.

For this change specifically, it may be a little quicker to not rebuild Linkerd each time. You may want to look at the instructions for building just the [Web component](https://github.com/linkerd/linkerd2/blob/main/BUILD.md#web).

**Comment by dadjeibaah** [comment]
@de-sh, thanks for working on this! and no worries on getting stuck during the local dev environment setup process. @kleimkuhler  is correct in that you can follow the web development docs to get squared away. Let us know if we need to update the instructions!

**Comment by dadjeibaah** [comment]
@de-sh, checking in to see if I can be of any help with issue :)?

**Comment by de-sh** [comment]
Hey @dadjeibaah, I am sending a detailed email about the issues I am facing right now.

**Comment by sannimichaelse** [comment]
@dadjeibaah is this task still available?

**Comment by dadjeibaah** [comment]
@sannimichaelse, Yep its still available. Feel free to submit a PR 😄

**Comment by sannimichaelse** [comment]
Nice, you can assign it to me

**Comment by sannimichaelse** [comment]
Hi all,

For the get all installed extensions task - what av done so far is to add the installed extensions section as well as modify the `handleGetExtension` api.

For the `handleGetExtension` what i did is to check if the `extensionName` has a value then I call `GetNamespaceWithExtensionLabel` which is the normal method there to get by extension name - then if the extension name doesnt have a value i call `GetAllNamespacesWithExtensionLabel`. Just want to be sure am on the right track

![image](https://user-images.githubusercontent.com/37812752/120788853-b9b5df80-c528-11eb-9406-e6c88c243d44.png)

**Comment by dadjeibaah** [comment]
@sannimichaelse, that sounds like you are on the right track. We basically want to extend the `handleGetExtension` so that it returns all installed extensions. Then the frontend will display that data in table format. Let me know if you have any additional questions! Looking forward to your PR.

**Comment by sannimichaelse** [comment]
What about getting installed extensions by name - should that be supported too?

**Comment by dadjeibaah** [comment]
> What about getting installed extensions by name - should that be supported too?

Yes, we should still be able to support that since there are other places in the frontend that use that code. e.g. the multicluster gateway page

**Comment by dadjeibaah** [comment]
@sannimichaelse, checking in to see if there is anything I can help out with. 😄

**Comment by sannimichaelse** [comment]
Hi @dadjeibaah , still on it, been occupied with some things recently, should get to it this weekend. 

WIll let you know if I have any questions - for now, none yet

**Comment by sannimichaelse** [comment]
Hi @dadjeibaah. The `GetNamespaceWithExtensionLabel(ctx, extensionName)` expects an extension name, to get all installed extensions am i using the same method or `GetAllNamespacesWithExtensionLabel(ctx)`

Also i currently start the web with `bin/web dev`. does the API changes also reloads automatically or i need to restart?

**Comment by dadjeibaah** [comment]
> The GetNamespaceWithExtensionLabel(ctx, extensionName) expects an extension name, to get all installed extensions am i using the same method or GetAllNamespacesWithExtensionLabel(ctx)

@sannimichaelse, That seems correct.

> Also i currently start the web with bin/web dev. does the API changes(changes made in api_handles.go) also reloads automatically or i need to restart?

That is correct as well. Unfortunately, live reloading only works for the frontend. If you make a API changes in `api_handler.go`, you'd need to re-run `bin/web dev` again to pick up the new changes.

**Comment by sannimichaelse** [comment]
Just raised a PR @dadjeibaah Kindly take a look and drop feedbacks

https://github.com/linkerd/linkerd2/pull/6391
