### ISSUE TITLE
Linkerd viz octopus graphs no longer allow you to interact with them.

### ISSUE THREAD

**Issue by JasonMorgan** [linkerd/linkerd2#5902]
### What is the issue?

You can no longer click on and drag the octopus graphs provided by the Linkerd dashboard.

### How can it be reproduced?

Run `linkerd viz dashboard` and click on a namespace that has proxies injected.

### Logs, error output, etc
N/A

#### `linkerd check` output

N/A

### Environment

- Kubernetes Version: 1.18.5
- Cluster Environment: k3d
- Host OS: Ubuntu
- Linkerd version: 2.10.0

**Comment by wmorgan** [comment]
Was this working for you in 2.9.4? Any obvious errors in the browser's console log?

**Comment by adleong** [comment]
To clarify, I think this is happening in the topology map, not the octopus graph.

Clicking on a node in the topology map logs this error in the browser console:

```
Uncaught TypeError: lu is null
```

I'm not sure how to get more helpful details out of that error because of webpack, but this should be easy to reproduce on a local web instance.
