### ISSUE TITLE
Linkerd-proxy forwards traffic to the wrong Pod

### ISSUE THREAD

**Issue by rustrial** [linkerd/linkerd2#5975]
## Bug Report

We observe that Pods running in [proxy ingress mode](https://linkerd.io/2.10/tasks/using-ingress/) send traffic to the wrong (Service) target Pods.

It took us 8 hours of debugging today, to figure out that a production incident is actually caused by the buggy behaviour of linkerd2 described below. 

### How can it be reproduced?

We can reproduce with the following setup:

- Pod A (`10.40.39.46`) is acting as ingress gateway and runs in proxy ingress mode with linkerd.io/inject: ingress annotation.
- Deployment with 2 Pods B1 (`10.40.0.78`) and B2 (`10.40.33.132`) is serving HTTP traffic exposed as Service B  (`gh-mgmt-service-api.nx-devices`) with ClusterIP `172.20.53.184`
- Deployment with 2 Pods C1 (`10.40.0.33`) and C2  (`10.40.39.15`) serving HTTP traffic exposed as Service C (`gh-commander-api.nx-devices`) with ClusterIP `172.20.225.244`

Now, we exec into Pod A and from within that Pod we execute the following statement (a), which works as expected:
```shell
curl http://172.20.53.184:8000/ -H "l5d-dst-override: gh-mgmt-service-api.nx-devices.svc.cluster.local:8000"
```
Then we execute the following statement (b) still from within Pod A:
```shell
curl http://172.20.225.244:8000/ -H "l5d-dst-override: gh-commander-api.nx-devices.svc.cluster.local:8000"
````
Now, this request (b) is actually forwarded to Pod B1 or B2 instead of C1 or C2. Tapping into the traffic of Pod B1 and B2 revealed the following request headers for (b):

- `host: 172.20.225.244:8000` (the ClusterIP address of Service C)
- `l5d-dst-canonical: gh-commander-api.nx-devices:8000` (the DNS name and port of Service C)

While both headers are set correctly, the traffic arrives at the wrong Pods (B1/B2 instead of C1/C2). This is very confusing and we have to assume that this is caused by the outbound linkerd-proxy on Pod A, which somehow uses the wrong IPv4 address as target for the request. Note, we double checked all things several times and all Pods and Services are configured correctly and there is no overlapping of backend Pods (Service Endpoints resp. IPv4 addresses) between the Services B and C.

### Logs, error output, etc

Here is a small (redacted) excerpt from the ingress’ (Pod A) linkerd-proxy log. I have not much experience with linkerd-proxy logs, but the mere fact that IP addresses from Pods of both services (B & C) appear in the same log message looks suspicious to me:

```json
{"log":"{\"timestamp\":\"[   344.440286s]\",\"level\":\"DEBUG\",\"fields\":{\"message\":\"Upgrading request\",\"version\":\"HTTP/1.1\",\"absolute_form\":false},\"target\":\"linkerd_proxy_http::orig_proto\",\"spans\":[{\"name\":\"outbound\"},{\"client.addr\":\"10.40.39.46:45722\",\"target.addr\":\"10.40.39.15:8000\",\"name\":\"accept\"},{\"v\":\"1.x\",\"name\":\"http\"},{\"dst\":\"gh-commander-api.nx-devices.svc.cluster.local:8000\",\"name\":\"target\"},{\"dst\":\"gh-commander-api.nx-devices.svc.cluster.local:8000\",\"name\":\"logical\"},{\"addr\":\"gh-mgmt-service-api.nx-devices.svc.cluster.local:8000\",\"name\":\"concrete\"},{\"peer.addr\":\"10.40.0.78:8000\",\"name\":\"endpoint\"},{\"name\":\"orig-proto-upgrade\"}],\"threadId\":\"ThreadId(3)\"}\n","stream":"stdout","time":"2021-03-30T21:36:46.129499937Z"}
{"log":"{\"timestamp\":\"[   344.440245s]\",\"level\":\"DEBUG\",\"fields\":{\"headers\":\"{\\\"host\\\": \\\"gh-commander-api.nx-devices.svc.cluster.local:8000\\\", \\\"user-agent\\\": \\\"Wget\\\", \\\"authorization\\\": \\\"Basic redacted\\\", \\\"l5d-dst-canonical\\\": \\\"gh-commander-api.nx-devices.svc.cluster.local:8000\\\"}\"},\"target\":\"linkerd_proxy_http::client\",\"spans\":[{\"name\":\"outbound\"},{\"client.addr\":\"10.40.39.46:45722\",\"target.addr\":\"10.40.39.15:8000\",\"name\":\"accept\"},{\"v\":\"1.x\",\"name\":\"http\"},{\"dst\":\"gh-commander-api.nx-devices.svc.cluster.local:8000\",\"name\":\"target\"},{\"dst\":\"gh-commander-api.nx-devices.svc.cluster.local:8000\",\"name\":\"logical\"},{\"addr\":\"gh-mgmt-service-api.nx-devices.svc.cluster.local:8000\",\"name\":\"concrete\"},{\"peer.addr\":\"10.40.0.78:8000\",\"name\":\"endpoint\"},{\"name\":\"orig-proto-upgrade\"}],\"threadId\":\"ThreadId(3)\"}\n","stream":"stdout","time":"2021-03-30T21:36:46.129476157Z"}
{"log":"{\"timestamp\":\"[   344.440199s]\",\"level\":\"DEBUG\",\"fields\":{\"method\":\"GET\",\"uri\":\"http://gh-commander-api.nx-devices.svc.cluster.local:8000/settings/latest/m:RVIQO0\",\"version\":\"HTTP/1.1\"},\"target\":\"linkerd_proxy_http::client\",\"spans\":[{\"name\":\"outbound\"},{\"client.addr\":\"10.40.39.46:45722\",\"target.addr\":\"10.40.39.15:8000\",\"name\":\"accept\"},{\"v\":\"1.x\",\"name\":\"http\"},{\"dst\":\"gh-commander-api.nx-devices.svc.cluster.local:8000\",\"name\":\"target\"},{\"dst\":\"gh-commander-api.nx-devices.svc.cluster.local:8000\",\"name\":\"logical\"},{\"addr\":\"gh-mgmt-service-api.nx-devices.svc.cluster.local:8000\",\"name\":\"concrete\"},{\"peer.addr\":\"10.40.0.78:8000\",\"name\":\"endpoint\"},{\"name\":\"orig-proto-upgrade\"}],\"threadId\":\"ThreadId(3)\"}\n","stream":"stdout","time":"2021-03-30T21:36:46.129423316Z"}
```
#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ sp-validator webhook has valid cert

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.19
- Cluster Environment: EKS
- Host OS: Amazon Linux 2
- Linkerd version: 2.10.0

### Possible solution

As a work-around we no longer set the `l5d-dst-override` header on the ingress Pod A, which resolved our production incident. Hopefully, someone with more know-how about the inner workings of the “DNS name to IPv4 translation” in the linkerd-proxy can shed more light on what might be the root cause of this behaviour. (edited) 

### Additional context

This issue has already been triaged on [Slack](https://app.slack.com/client/T0JV2DX9R/C89RTCWJF/thread/C89RTCWJF-1617138891.328900).

Ingress Gateway: Gloo-Edge version 1.6.17.

Thera are no TrafficSplit resources in that cluster:

```shell
❯ kubectl get -A trafficsplit
No resources found
```

**Comment by Pothulapati** [comment]
With awesome help from @kleimkuhler, I was able to replicate this. I think the problem is with **a outbound proxy in ingress mode**. My guess is that this could be something to do with the cache logic there, as the proxy seems to choose the latest value from the header `l5d-dst-override` and route **all** requests with that header there.

Steps to replicate:

```bash
# Install a pod in Linkerd ingress mode. This is from where we would curl
kubectl apply -f https://gist.githubusercontent.com/Pothulapati/941eef18a862aee9adb805aeddaef844/raw/1f30aeb68076b9e1c181c1a4c59d8969cc226c09/shell.yaml

# Now, Install two services and deployments i.e my-nginx-1 and my-nginx-2
kubectl apply -f https://gist.githubusercontent.com/Pothulapati/1e96bf6c869b8e9bf03d51861b48b17f/raw/b76262a37ddd55c38601fad7c7da4ae697b36920/services.yaml

# Now tap into my-nginx-1 and my-nginx-2 in separate windows
# linkerd tap deploy/my-nginx-1
# linkerd tap deploy/my-nginx-2

# ssh into the ingress-mode pod and start sending requests
kubectl exec --stdin --tty shell-demo -- /bin/bash

# Curl my-nginx-1 with its header
curl -H "l5d-dst-override: my-nginx-1.default.svc.cluster.local:80" <my-nginx-1-svc-ip> -v
# Request can be seen in my-nginx-1's tap
# Now Curl my-nginx-2 with its header
curl -H "l5d-dst-override: my-nginx-2.default.svc.cluster.local:80" <my-nginx-2-svc-ip> -v
# Request can be seen to go to my-nginx-2's tap
# Curl my-nginx-1 with its header again
curl -H "l5d-dst-override: my-nginx-1.default.svc.cluster.local:80" <my-nginx-1-svc-ip> -v
# Now even this request goes to my-nginx-2....
```

Thanks @rustrial for raising this issue!

**Comment by divanikus** [comment]
Having just the same issue with my setup. Linkerd 2.10, Nginx ingress controller in `inject: ingress` mode and K8s 1.18.

**Comment by olix0r** [comment]
For nginx, there's a pretty simple workaround:

If you change `linkerd.io/inject: ingress` to `linkerd.io/inject: enabled`, the proxy won't use this buggy client caching logic.

Then, in order to enable traffic splits, etc, you can set the `nginx.ingress.kubernetes.io/service-upstream` annotation on your ingress resources so that nginx communicates directly with service IPs so that linkerd can do logical routing.

**Comment by kolloch** [comment]
@olix0r [The docs](https://linkerd.io/2.10/tasks/using-ingress/) suggest that service profiles etc only work with  `linkerd.io/inject: ingress`. 

For me, that was always weird because service profiles would also work in pod to service traffic in general. Do they mean if you don't set the `Host` header to the one used in your service profile?

Any downsides to not using the ingress mode? We use Gloo but currently use a static endpoint using the fully qualified cluster local DNS name.

**Comment by olix0r** [comment]
@kolloch The docs are probably a bit over-simplified to fit a configuration that works for all ingresses without having to dig into specific ingress features... and we've only recently learned about the `nginx.ingress.kubernetes.io/service-upstream` annotation. I'm unsure if similar configuration exists for other ingresses.

Since Linkerd 2.9, by default, Linkerd doesn't actually use request headers for routing. Instead, the proxy uses the target _ip:port_ for discovery. Most applications use a service's `clusterIP` as a target address, and so Linkerd is able to discover that this is a service and apply service profiles (and traffic splits) as you'd expect. However, ingresses tend to implement their own discovery and load balancing, and so instead of targeting a service by `clusterIP`, they initiate connections to individual pod IPs; and when traffic targets a pod IP, we aren't able to associate the traffic with a logical service (and never override the target address, as required by traffic split).

So _ingress mode_ exists as a way to make the outbound proxy ignore the original target address and instead route based on per-request metadata. I.e., when the ingress issues requests to _pod-ip:port_, Linkerd ignores this destination and uses request metadata for discovery.

So, if your ingress has an option to use a `clusterIP` (like the above-mentioned nginx annotation), you can safely use the proxy with `inject: enabled` instead of `inject: ingress` and Linkerd will discover and route as you'd hope. If the ingress does its own load balancing and you want service profiles / traffic split, you'll need to use `inject: ingress`.

> We use Gloo but currently use a static endpoint using the fully qualified cluster local DNS name.

This sounds like it may work, but the only way to be sure is to test it :)

**Comment by kolloch** [comment]
@olix0r timely, great and clear reply. Thank you very much!

I'd suggest to more or less to copy this to the docs :)

**Comment by rustrial** [comment]
> For nginx, there's a pretty simple workaround:
> 
> If you change `linkerd.io/inject: ingress` to `linkerd.io/inject: enabled`, the proxy won't use this buggy client caching logic.
> 
> Then, in order to enable traffic splits, etc, you can set the `nginx.ingress.kubernetes.io/service-upstream` annotation on your ingress resources so that nginx communicates directly with service IPs so that linkerd can do logical routing.

@olix0r Are you sure that only `ingress` mode is affected. We reconfigured our gloo gateway to run in `default` mode (`linkerd.io/inject: enabled`) and we still observe the behaviour described in this bug report.

**Comment by divanikus** [comment]
For my setup switching to `linkerd.io/inject: enabled` did helped. At least I can't reproduce it with my test. I have also removed the `l5d-dst-override` headers though.

**Comment by olix0r** [comment]
@rustrial 

>  Are you sure that only ingress mode is affected. We reconfigured our gloo gateway to run in default mode (linkerd.io/inject: enabled) and we still observe the behaviour described in this bug report.

Yeah, I'm pretty confident that the bug only impacted ingress mode -- the logic that could cause a cache collision is only present in the ingress code.

I'd start by double-checking that the ingress proxy is actually running in the correct mode:

```
:; kubectl get po -o yaml ... | grep -F LINKERD2_PROXY_INGRESS_MODE
```

This should not return anything.

Assuming that ingress is actually off, there are a few things we can try to get more information:

* Set `config.linkerd.io/proxy-log-level: linkerd=debug,warn` on the workload, which should include enough diagnostic information in the logs to understand what's going on.

* You can test a more recent proxy build with the fixes merged by setting workload annotations `config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy` and `config.linkerd.io/proxy-version: v2.141.0.74a16321` -- this is a build of the proxy version that will be released in today's edge release and, subsequently, in stable-2.10.1. But, again, I would only expect this to impact ingress-mode proxies.

* Otherwise, if you can share manifests for your example resources, we'd be happy to try to reproduce this on our side.
