### ISSUE TITLE
Ability to change the load balancing policy(algo) used by Linkerd

### ISSUE THREAD

**Issue by sagarpatil23192** [linkerd/linkerd2#6052]
Currently Linkerd only supports EWMA(exponentially weighted moving average ) algorithm for load balancing. Like the other service mesh in the market can we provide different LB's options to linkerd. Consul service mesh supports same feature where it provides various options for the same. Please refer to the link for the same: https://learn.hashicorp.com/tutorials/consul/load-balancing-envoy?in=consul/developer-mesh

**Comment by adleong** [comment]
@sagarpatil23192 can you tell us more about the problem that you're trying to solve here?  do you have a scenario where EWMA is not appropriate?

**Comment by olix0r** [comment]
Also, I should note that if your application implements an alternate load balancing scheme, Linkerd won't override it. But I agree with @adleong: we're unlikely to implement features purely for the sake of feature-parity. It would be most helpful to describe the problem at a higher level (what problem are you solving) so that we can prioritize the correct solutions to that problem.

**Comment by sagarpatil23192** [comment]
@adleong Currently the other service mesh products are providing multi LB options at the SM level. So it would be really good if we are able to select the algo ourselves so that we decide if we want to go with some other algo. So I have no problems with  the current algo but it is always better to have options

**Comment by adleong** [comment]
@sagarpatil23192 understood.  I'm going to close this issue as "Won't Fix" because the Linkerd philosophy is to solve problems in the simplest way possible and with as little configuration as possible.
