### ISSUE TITLE
stable-2.10.2 release sha changed

### ISSUE THREAD

**Issue by andig** [linkerd/linkerd2#6233]
### What is the issue?

Noticed during https://github.com/Homebrew/homebrew-core/pull/78666 that the release sha has changed.

Has this be re-released?

### Logs, error output, etc

```
❯ brew install --build-from-source linkerd
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 9f4874d11 to f1f7dc151.
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/services).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
Updated 2 casks.

==> Cloning https://github.com/linkerd/linkerd2.git
Cloning into '/Users/andig/Library/Caches/Homebrew/linkerd--git'...
==> Checking out tag stable-2.10.2
HEAD is now at 5535e9c4 Add service annotations fix to stable 2.10.2 (#6126)
Error: stable-2.10.2 tag should be fd03538b2641c56f6e6dc3bb5de1669ccd96278a
but is actually 5535e9c4edda7f5a8d8d21e351b61425bd3a8208
```

**Comment by adleong** [comment]
@andig that's right.  We ran into some problems during the stable-2.10.2 release and had to update the SHA.  Are there any steps we need to take to make Homebrew aware of the updated SHA?

**Comment by andig** [comment]
Thanks for confirming. No action required, we can update the SHA knowing that its not a security issue now.

**Comment by carlocab** [comment]
Just FYI, it'd be nice if you had just cut a new release tag instead of re-tagging the existing one. The [Git docs](https://git-scm.com/docs/git-tag#_on_re_tagging) have some pretty strong words about re-tagging.

**Comment by kleimkuhler** [comment]
@carlocab We usually stick to this for edge releases when we run into an issue during the release process and need to end up "skipping" a version. For stable it's a little different because skipping a minor version feels more significant.

That being said, we only do this when we have not released the binaries ourselves and can delete the GitHub release tag. Homebrew is the only "3rd party" release watcher that we have so unfortunately it doesn't pick up on this change.

For the future, if we end up needing to retag a release we'll make sure our release docs are updated to manually change this in Homebrew repository.
