### ISSUE TITLE
Destination should return a profile with an endpoint to the gateway for mirror services

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#6380]
When a service is mirrored from a target to a source cluster, the mirror's endpoints object will contain an address that points to the target cluster gateway.

In most cases, the mirrors only contain one address that corresponds to a `LoadBalancer` type service in the target cluster. In such cases, it would be more optimal to return an endpoint in the profile response; since we only have one address, we wouldn't need the subsequent `Get` call.

For example, for a mirror service `foo-remote` whose endpoints object contains an address to the gateway (172.0.0.1), when an outbound client proxy sends a profile request with `foo-remote`'s IP address, we would want to receive a profile response with the endpoint to the gateway instead of the normal profile response that would trigger a follow-up `Get` (and that would consequentially build a load balancer).

The proposal here is to change the destination service to account for these cases.

**Comment by adleong** [comment]
I'm not sure about this.  There are a few scenarios to keep in mind:

* The LoadBalancerStatus can contain multiple ingress objects; in other words, multiple IP addresses
* Some LoadBalancers (such as in AWS, for example) expose a hostname rather than an IP address.  We use DNS to resolve this hostname to a set of IP addresses
* Users can override the gateway addresses field in the Link resource to specify a list of gateway IPs
* NodePort services can be accessed by addressing any accessible node in the cluster

I'm not totally clear on why an ingress would have multiple addresses in some of these cases.  However, it seems more robust to consider all available addresses as options, especially in the case of NodePort services to allow the cluster to remain accessible even if a node is lost.
