### ISSUE TITLE
linkerd check --pre reports usage details despite right syntax

### ISSUE THREAD

**Issue by rdileep13** [linkerd/linkerd2#6422]
## Bug Report
When running 'linkerd check --pre' without underlying kubernetes infra (in the specific case minikube was down/stopped), after the error string, half page worth of usage is displayed.
This often side tracks user into checking wrong part of the system, like installation, etc.

### What is the issue?
Although the syntax of the command is right, linkerd displays usage details causing confusion

### How can it be reproduced?
run 'linkerd check --pre' after stopping minikube (using 'minikube stop')

### Logs, error output, etc
```text
Error: Error rendering install manifest: error configuring Kubernetes API client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
Usage:
  linkerd check [config] [flags]
  linkerd check [command]

Examples:
  # Check that the Linkerd control plane is up and running
  linkerd check

  # Check that the Linkerd control plane can be installed in the "test" namespace
  linkerd check --pre --linkerd-namespace test

  # Check that "linkerd install config" succeeded
  linkerd check config

  # Check that the Linkerd data plane proxies in the "app" namespace are up and running
  linkerd check --proxy --namespace app

Available Commands:
  config      Check the Linkerd cluster-wide resources for potential problems

Flags:
      --cli-version-override string   Used to override the version of the cli (mostly for testing)
      --expected-version string       Overrides the version used when checking if Linkerd is running the latest version (mostly for testing)
  -h, --help                          help for check
      --linkerd-cni-enabled           When running pre-installation checks (--pre), assume the linkerd-cni plugin is already installed, and a NET_ADMIN check is not needed
  -n, --namespace string              Namespace to use for --proxy checks (default: all namespaces)
  -o, --output string                 Output format. One of: basic, json (default "table")
      --pre                           Only run pre-installation checks, to determine if the control plane can be installed
      --proxy                         Only run data-plane checks, to determine if the data plane is healthy
      --wait duration                 Maximum allowed time for all tests to pass (default 5m0s)

Global Flags:
      --api-addr string            Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)
      --as string                  Username to impersonate for Kubernetes operations
      --as-group stringArray       Group to impersonate for Kubernetes operations
      --cni-namespace string       Namespace in which the Linkerd CNI plugin is installed (default "linkerd-cni")
      --context string             Name of the kubeconfig context to use
      --kubeconfig string          Path to the kubeconfig file to use for CLI requests
  -L, --linkerd-namespace string   Namespace in which Linkerd is installed ($LINKERD_NAMESPACE) (default "linkerd")
      --verbose                    Turn on debug logging

Use "linkerd check [command] --help" for more information about a command.
```
(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
same as above
```

### Environment

- Kubernetes Version: kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Cluster Environment: (GKE, AKS, kops, ...) minikube on local setup
- Host OS: ubuntu 21.x
- Linkerd version: Client version: stable-2.10.0

### Possible solution
modify the cli library to exit on failure without displaying usage if the syntax is actually right

### Additional context
from slack discussion looks like similar issues elsewhere were fixed
https://github.com/linkerd/linkerd2/pull/5678/files

Let me know if I can fix this.

**Comment by kleimkuhler** [comment]
@rdileep13 you're welcome to fix this if you are interested. Searching for `Error rendering install manifest` in the repo we can see this error occurs [here](https://github.com/linkerd/linkerd2/blob/48c5f70c399aeaa45ee125deca2253a3f9ce96e4/cli/cmd/check.go#L175). We can see based off a few lines above that `options.preInstallOnly` means this only runs when `--pre` is passed to `linkerd check`.

So, the error is being returned from `renderInstallManifest`. Looking into that function we can assume it's the error returned from the call to [install](https://github.com/linkerd/linkerd2/blob/48c5f70c399aeaa45ee125deca2253a3f9ce96e4/cli/cmd/check.go#L285). However, there is another place that `renderInstallManifest` can return an error; this is also not a _usage_ error though.

Therefore, we want to catch this error at the previously linked [L175](https://github.com/linkerd/linkerd2/blob/48c5f70c399aeaa45ee125deca2253a3f9ce96e4/cli/cmd/check.go#L173). So, instead of returning the error like we currently do with `return fmt.Errorf("Error rendering install manifest: %v", err)`, we would just want to exit here.

I think the fix that would be best here would be changing [the error check](https://github.com/linkerd/linkerd2/blob/48c5f70c399aeaa45ee125deca2253a3f9ce96e4/cli/cmd/check.go#L174-L176) to something like:

```
if err != nil {
        fmt.Fprint(os.Stderr, fmt.Errorf("Error rendering install manifest: %v", err))
        os.Exit(1)
}
```

**Comment by rdileep13** [comment]
Thanks Kevin! I will give it a go and verify the fix locally

**Comment by rdileep13** [comment]
Looks good on local testing.

**Comment by rdileep13** [comment]
PR pending at https://github.com/linkerd/linkerd2/pull/6433
