### ISSUE TITLE
Remove CONDUIT_PROXY_POD_* env dependencies

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#647]
The proxy currently depends on the `CONDUIT_PROXY_POD_NAME` and `CONDUIT_PROXY_POD_NAMESPACE` env variables.

The namespace is used to synthesize the DNS search path (poorly).  This should be replaced as follows:
* the proxy should use the default DNS search path (possibly prefixed by a proxy-specific search path) to bind authority names
* the proxy supports a `CONDUIT_PROXY_DESTINATION_DOMAINS` environment variable that lists domain suffixes that the destination service honors.
* the proxy resolves addresses via DNS or the destination service

This is related to #155

`CONDUIT_PROXY_POD_NAME` will not be needed once push telemetry is removed in #616.

The proxy will likely need some concept of an instance ID that it uses to request policy from the control plane, but this should be made more generic -- likely some url scheme.

**Comment by olix0r** [comment]
Furthermore, the `CONDUIT_PROXY_NODE_NAME` can likely be removed after #616

**Comment by briansmith** [comment]
`CONDUIT_PROXY_POD_NAME` is gone already.

`CONDUIT_PROXY_POD_NAMESPACE` is needed for the kubernetes integration since the namespace is not available at `linkerd inject` time, but only at runtime, unless/until we do injection via mutating webhook (maybe). Note that TLS works fine outside of Kubernetes if `CONDUIT_PROXY_POD_NAMESPACE` is not defined.

`CONDUIT_PROXY_POD_NAMESPACE` is used in another place, for service discovery in Kubernetes via the destination service, and in theory that could be replaced with a more generalized service discovery search mechanism, but the cost:benefit of doing that work is questionable. Note that one can already use the proxy without the destination service by not setting `CONDUIT_PROXY_CONTROL_URL`.

Similar applies to `ENV_CONTROLLER_NAMESPACE`, which is already optional. It is required for TLS to work but I'm working on removing this in #1274.

Thus, I believe the only change we should make in the short term is to make `CONDUIT_PROXY_POD_NAMESPACE` optional when `CONDUIT_PROXY_CONTROL_URL` is not provided and required when `CONDUIT_PROXY_CONTROL_URL` is required. (Currently it is wrongly always required.)

**Comment by olix0r** [comment]
> CONDUIT_PROXY_POD_NAMESPACE is used in another place, for service discovery in Kubernetes via the destination service, and in theory that could be replaced with a more generalized service discovery search mechanism, but the cost:benefit of doing that work is questionable. Note that one can already use the proxy without the destination service by not setting CONDUIT_PROXY_CONTROL_URL.

I think it's important to remove any kubernetes-specific logic from the service discovery client.

**Comment by briansmith** [comment]
> I think it's important to remove any kubernetes-specific logic from the service discovery client so that this service discovery interface can potentially be used in other environments

I'm not convinced the Kubernetes-specific logic can or should be totally removed from the service discovery client, since the use of `CONDUIT_PROXY_POD_NAMESPACE` isn't the only Kubernetes-specific logic and we need some Kubernetes-specific logic (e.g. always prioritizing the destination service over DNS) for things (especially DNS and load balancing) to work correctly in Kubernetes.

Another option is to make it work more like the TLS stuff, where if the pod namespace isn't given then we carry on a slightly different way without it, which might be much simpler.
