### ISSUE TITLE
Introduce integration test for multicluster with headless services

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#6563]
After PR #6090 is merged (_"Introduce support for StatefulSets across clusters"_), it would be good to write some integration tests to ensure the behaviour for this feature stays consistent. At the moment, there are no integration tests written that verify a headless service can be exported successfully and can be used in the source cluster.

We should test end-to-end how a headless service backed by a StatefulSet is created, exported and deleted (or unexported) and also test that an endpoint mirror belonging to the headless mirror can be used to send traffic to a specific instance from a StatefulSet. We can probably use the slow cooker as a client and nginx as the server.

**Comment by importhuman** [comment]
Can I work on this?

**Comment by kleimkuhler** [comment]
@importhuman sure that would be helpful! Let us know if you have any questions while working on it.

It may be helpful to work off the existing multicluster integration test which takes care of all the setup. Adding a test within that that mirrors a stateful set is probably going to be the simplest thing to do here.

**Comment by importhuman** [comment]
I'm a bit confused on what needs to be done. I looked through the changes in the mentioned PR #6090, and the test functions that were added/updated such as `TestRemoteEndpointsUpdatedMirroring` and `TestRemoteServiceCreatedMirroring`.

> It may be helpful to work off the existing multicluster integration test which takes care of all the setup. Adding a test within that that mirrors a stateful set is probably going to be the simplest thing to do here.

Does this mean that I should add test cases in the range `[]mirroringTestCase{}` in the test functions? I reckon I'll be working in the `cluster_watcher_test_util.go` file as well to set up the environment. Does this also mean that I don't need to work on specifically adding stateful set functionality to the test, instead writing a test that has the pods/service according to a stateful set is enough?

Thanks!

cc: @kleimkuhler @mateiidavid

**Comment by mateiidavid** [comment]
@importhuman hey 👋🏻  the changes in PR #6090 added some unit tests to the cluster watcher. For the integration tests, we'd likely want to do something a bit different.

Our integration tests are in [`linkerd2/test/`](https://github.com/linkerd/linkerd2/tree/main/test). We would likely want to add something to either the `source` or (another) `target` directories, in the multicluster integration tests. What we ultimately want to do here is to make sure that the new StatefulSet feature is working properly -- we will probably need to change the install command for the test as part of this to enable support for headless services. Here's what I recommend, without having spent too much time looking into it:

1. Have a look at the test scripts and see what needs to be changed; we will ideally want to add `--set "enableHeadlessServices=true` to the helper that bootstraps [multicluster testing](https://github.com/linkerd/linkerd2/blob/1e98ea1c201b5fb7646a2420f1a91b08ed6e599d/bin/_test-helpers.sh#L356).
2. Create a new target, perhaps, with a StatefulSet. There are a couple of options here: you can use emojivoto (that is already part of the test, you'd have to just duplicate and turn it parts of into a StatefulSet), you can use Nginx -- or any other manifests that you might see in test. The goal here is to have a StatefulSet that can be replicated. I think it will be easy to assert the same type of things that the current tests assert.
3. Create a `curl` pod (it can be a like a Debian image with a script to install curl, loop and send a few requests) or use the buoyant load generator used in other similar integration tests. Our goal for this will probably be to test connectivity and routing -- from a source cluster, can our curl pod target a specific instance of this statefulset that has been mirrored? E.g if we have 3 mirrors, pick one, curl the endpoint and then verify only that instance has been called. For an example on how you could do this, you should look into the opaque integration tests, we're using the CLI's diagnostics command to see how many open TCP connections we have to assert correctness.

Of course, these are all just some suggestions to give you an idea about what you can do. At a minimum, we probably want to make sure headless services are exported properly and direct endpoint communication works. All integration tests use the helpers, have a look and see if it makes sense.

If you have more questions let us know.

**Comment by importhuman** [comment]
Thanks @mateiidavid, this definitely helps to get started! I'm not too familiar with kubernetes or linkerd, so I'll try to learn the relevant components/topics mentioned while working on the issue. 

1. I get that we'll need to modify the helper in `testutil/test_helper.go`, but I can't tell where the shell script you mentioned is being used. I tried looking through the workflows, but couldn't find it mentioned there either. If the script is also to be modified, should we add `--set "enableHeadlessServices=true"` to [multicluster_link()](https://github.com/linkerd/linkerd2/blob/1e98ea1c201b5fb7646a2420f1a91b08ed6e599d/bin/_test-helpers.sh#L356) directly to see that the StatefulSet feature is working properly, or should we make another function (assuming that's what it's called in .sh files as well) for checking StatefulSet functionality?
2. I'll begin with this part.
3. I need to read and explore more before I can ask any specific questions about this.

**Comment by kleimkuhler** [comment]
So here is a little breakdown of our integration tests. It's best to keep in mind that the files in `bin/` are responsible for integration test _setup_, and the `.go` files in `test/integration/` are responsible for _execution_. There are setup changes you'll need to make such as passing the new `enableHeadlessServices` flag, and then execution changes you'll need to make in `test/integration/multicluster/` that install a new headless service application and make sure it is properly mirrored.

The `bin/tests` script is responsible for invoking each integration test. It calls `start_test` (exported from `_test-helpers.sh`) for each integration test. Following this, we can see that `start_test` handles multicluster [here](https://github.com/linkerd/linkerd2/blob/b98c86700f5a3d8b2fab74ea4c25b4b8bba25ebe/bin/_test-helpers.sh#L324-L325). Looking at [start_multicluster_test](https://github.com/linkerd/linkerd2/blob/b98c86700f5a3d8b2fab74ea4c25b4b8bba25ebe/bin/_test-helpers.sh#L343-L353) you'll see it sets up the source and target clusters and then starts the actual test with [run_multicluster_test](https://github.com/linkerd/linkerd2/blob/b98c86700f5a3d8b2fab74ea4c25b4b8bba25ebe/bin/_test-helpers.sh#L504-L521).

So it's in `run_multicluster_test` where we generate the link with `multicluster_link`; since we'd like to use this one setup for testing all of the multicluster functionality, it makes sense to change `multicluster_link` to always pass the headless services flag: `"$linkerd_path" multicluster link --api-server-address "https://${lbIP}:6443" --cluster-name "$1 --set "enableHeadlessServices=true"`

**Comment by mateiidavid** [comment]
Closed through #6749
