### ISSUE TITLE
`--context` does not work in `linkerd viz install` command

### ISSUE THREAD

**Issue by Hongbo-Miao** [linkerd/linkerd2#6603]
### What is the issue?

`--context` does not work in `linkerd viz install` command.

Assume, I am at `k3d-east` now. And I want to install on `k3d-west`

Tried these, all will install on `k3d-east`.

```sh
linkerd viz install --context="k3d-west" | kubectl apply -f -
linkerd --context="k3d-west" viz install | kubectl apply -f -
linkerd viz --context="k3d-west" install | kubectl apply -f -
```

### How can it be reproduced?

Create two clusters by k3d.

First, switch to east cluster by `kubectl config use-context "k3d-east"`.

Then try to install on west cluster by

```sh
linkerd viz install --context="k3d-west" | kubectl apply -f -
linkerd --context="k3d-west" viz install | kubectl apply -f -
linkerd viz --context="k3d-west" install | kubectl apply -f -
```

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

<details>
  <summary>Click to expand!</summary>
  
  ```shell
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
W0804 06:12:25.406515   76317 warnings.go:67] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-multicluster
--------------------
√ Link CRD exists
√ Link resources are valid
	* k3d-west
× remote cluster access credentials are valid
            * failed to connect to API for cluster: [k3d-west]: Get "https://192.168.32.2:6443/version?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    see https://linkerd.io/2.10/checks/#l5d-smc-target-clusters-access for hints
× clusters share trust anchors
    Problematic clusters:
    * k3d-west: unable to fetch anchors: Get "https://192.168.32.2:6443/api/v1/namespaces/linkerd/configmaps/linkerd-config?timeout=30s": context deadline exceeded
    see https://linkerd.io/2.10/checks/#l5d-multicluster-clusters-share-anchors for hints
√ service mirror controller has required permissions
	* k3d-west
√ service mirror controllers are running
	* k3d-west
√ all gateway mirrors are healthy
	* k3d-west

Status check results are ×

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
  ```
</details>

### Environment

- Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Cluster Environment: (GKE, AKS, kops, ...)
k3d

- Host OS:
macOS

- Linkerd version:
Client version: stable-2.10.2
Server version: stable-2.10.2

### Possible solution

Currently I need manually switch by cluster by

```
kubectl config use-context "k3d-west"
```

### Additional context

`--context` works well on `linkerd install`, but not `linkerd viz install`.

**Comment by mateiidavid** [comment]
Hi @Hongbo-Miao,

This is not necessarily an error, let me explain what happens underneath the hood and why `linkerd install` needs the flag and viz doesn't.

The `--context` flag is global to the CLI, this is because certain commands need to interface with the Kubernetes API, in doing so, we create a clientset that interacts with the cluster. These clients are build using the `kubeconfig` provided at runtime. In this sense, `--context` is used to provide a path for a `kubeconfig` file when it's preferred to override the default one. Most environments will have a `kubeconfig` by default whose path is set as an environment variable, in multicluster examples, we override this so that we don't install in the cluster that is set to default by accident.

When we install the control plane, we want to make sure that a previous installation doesn't exist, in part because of the configuration options that we set at install time in the configmap. This is why in the multicluster example, we provide an override for the context. This logic is in the `cmd/install.go` file:
https://github.com/linkerd/linkerd2/blob/742c5f404340fcc739759e666a45978e0497dc29/cli/cmd/install.go#L189-L193

If we look closer at the `errIfLinkerdConfigConfigMapExists` function, we'll see how we use the path when we create the clientset to check whether a configmap exists:
https://github.com/linkerd/linkerd2/blob/742c5f404340fcc739759e666a45978e0497dc29/cli/cmd/install.go#L520-L539

By contrast however, `linkerd viz install` has only one basic function: render viz manifests. This will be the same, regardless of environment -- we have no checks to make, hence no clientset to build. So in this case, we do not care what context we are working with. For the same reason, viz does not have an `upgrade` command, we just re-apply the manifests with a (newer) image version or any additional changes they might now come with. We can see this here:
https://github.com/linkerd/linkerd2/blob/742c5f404340fcc739759e666a45978e0497dc29/viz/cmd/install.go#L87-L111

Since viz doesn't take a config path and just renders the manifests, the config should be passed to `kubectl` instead, so that it can be applied to the right cluster. Using the example you posted, I'd do the following to install viz in both clusters:
```
linkerd viz install  | kubectl --context=k3d-west apply -f -
linkerd viz install | kubectl --context=k3d-east apply -f -

# or if you want to automate it:
for cluster in east, west; do
   linkerd viz install | kubectl --context=k3d-$cluster apply -f - 
done
```

Let me know if this makes sense and if it works.

**Comment by Hongbo-Miao** [comment]
Oh I see, thanks @mateiidavid!

Then can we remove it from output of `linkerd viz install -h` because it is a little bit misleading. And I spend some time debugging, then realize `--context` is not working.

```
➜ linkerd viz install -h
Output Kubernetes resources to install linkerd-viz extension.

Usage:
  linkerd viz install [flags]

Examples:
  # Default install.
  linkerd viz install | kubectl apply -f -

The installation can be configured by using the --set, --values, --set-string and --set-file flags.
A full list of configurable values can be found at https://www.github.com/linkerd/linkerd2/tree/main/viz/charts/linkerd-viz/README.md


Flags:
      --ha                       Install Viz Extension in High Availability mode.
  -h, --help                     help for install
      --set stringArray          set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray     set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray   set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --skip-checks              Skip checks for linkerd core control-plane existence
  -f, --values strings           specify values in a YAML file or a URL (can specify multiple)
      --wait duration            Wait for core control-plane components to be available (default 5m0s)

Global Flags:
      --api-addr string            Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)
      --as string                  Username to impersonate for Kubernetes operations
      --as-group stringArray       Group to impersonate for Kubernetes operations
      --cni-namespace string       Namespace in which the Linkerd CNI plugin is installed (default "linkerd-cni")
      --context string             Name of the kubeconfig context to use
      --kubeconfig string          Path to the kubeconfig file to use for CLI requests
  -L, --linkerd-namespace string   Namespace in which Linkerd is installed (default "linkerd")
      --verbose                    Turn on debug logging
```

**Comment by Hongbo-Miao** [comment]
Oh this is same to `linkerd install` I think.
I was using `linkerd install --context=k3d-east | kubectl --context=k3d-east apply -f -` which is why I thought it works for `linkerd install`.

**Comment by mateiidavid** [comment]
I'm very receptive to document it, or perhaps change the description in `-h` but removing it just from the `viz -h` command is infeasible in this case.

`--context` is a global flag so it will be applied to all commands, if we'd remove it as a global option, we'd have to manually add it to every subcommand. We are declaring the path and context variables here, in the root of the CLI:
https://github.com/linkerd/linkerd2/blob/742c5f404340fcc739759e666a45978e0497dc29/cli/cmd/root.go#L44-L45

The flags themselves are parsed as part of the `init()` function which will run before the rest of the `cmd` package is initialised:
https://github.com/linkerd/linkerd2/blob/main/cli/cmd/root.go#L98-L99

Because of this, removing it is quite difficult. Is there anything else we might be able to do here to make it less confusing to use?

**Comment by Hongbo-Miao** [comment]
Oh it makes sense. Thanks @mateiidavid !
