### ISSUE TITLE
add `via` header to http messages

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#703]
As an operator has deployed conduit, I want to be able to know whether a given message has been routed by the otherwise-transparent conduit proxy.

If the proxy appends a `Via` header, per [rfc7230](https://tools.ietf.org/html/rfc7230#section-5.7.1), operators can check the path of a message.  for example:

for h1:
```
via: 1.1 conduit
```

for h2:
```
via: 2.0 conduit
```

**Comment by briansmith** [comment]
> As an operator has deployed conduit, I want to be able to know whether a given message has been routed by the otherwise-transparent conduit proxy.

Why? Also, why is this a high priority (0.5.0)?

It isn't clear whether you're suggesting to do this for inbound messages (requests) or outbound messages (responses) or both. In general, I don't think we should add header fields to outbound (response) messages since those will likely leak outside the cluster and will have negative performance ramifications due to header bloat, especially if the message transitions through multiple (Conduit) intermediaries.

**Comment by olix0r** [comment]
> Why? Also, why is this a high priority (0.5.0)?

not a high priority

> It isn't clear whether you're suggesting to do this for inbound messages (requests) or outbound messages (responses) or both. In general, I don't think we should add header fields to outbound (response) messages since those will likely leak outside the cluster and will have negative performance ramifications due to header bloat, especially if the message transitions through multiple (Conduit) intermediaries.

this came from personal experience-- running requests in a pod, i have no way to know if the response transited conduit or not. we've previously had production users [ask for this feature in linkerd](https://github.com/linkerd/linkerd/pull/683) for this same reason.

i agree that it's the case that we should allow this to be disabled; but it's important that we give users good diagnostics, and this is a standard way of doing so.
