### ISSUE TITLE
linkerd not being in ready state during production cluster upgrade

### ISSUE THREAD

**Issue by saba-bakhshi** [linkerd/linkerd2#7055]
we noticed that in our prod environment, linkerd was not at a ready state during k8s upgrade. Is this a known issue? It was only observed once in Prod and isn't recurring. Just want to know if it's something worth investigating on our end.

**Comment by saba-bakhshi** [comment]
hi @adleong , can you please let me know what other info you're looking for? I'll try to provide.

**Comment by kleimkuhler** [comment]
@saba-bakhshi Steps for reproducing this would be most helpful. If you only observed this once then maybe that is difficult to provide, but otherwise there is not much action we can take to figure out if there is an actual issue.

If this was purely just a question about it being a known issue, we are not actively investigating any other issues related to this. We can keep this issue open for a little while to see if any other users chime in with similar reports.

**Comment by adleong** [comment]
I haven't heard any other reports of this issue.  Please open a new issue if you have steps for reproducing this.
