### ISSUE TITLE
Run install tests on our minimum supported k8s version

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7112]
We should test that a basic installation works on our minimum supported Kubernetes version so that if we introduce backwards-incompatible changes, we can be intentional about mitigating that or changing the minimum supported version

**Comment by Pothulapati** [comment]
I and @alpeb discussed a bit about this!

Currently, Integration tests are not pinned to either the latest or the min k8s version. It's whatever `./bin/k3d` binary has.

So, we could do the following:

- Update `helm-deep` to run on the min k8s version, as the min version is more of a safety check
- Update other tests to always be on the latest released k8s version, without us having to update the `./bin/k3d` binary version manually.

WDYT? 🤔

**Comment by kleimkuhler** [comment]
I think pinning `helm-deep` to always run on the minimum k8s version sounds good. Having at least one of the `deep` runs on the minimum version should cover our bases.

I also think switching to k3d GH action for the rest of the tests makes sense so that we can run those on the latest versions. Doing this by upgrading `./bin/k3d` each release doesn't feel as obvious as bumping the versions in the actual workflow files.
