### ISSUE TITLE
Support transparent TLS for proxy running in ingress mode

### ISSUE THREAD

**Issue by alex-berger** [linkerd/linkerd2#7238]
## Feature Request

Outbound `linkerd-proxy` running in *ingress mode* should transparently forward TLS traffic.

### What problem are you trying to solve?

We face a problem with linkerd (edge-21.9.4) running in *ingress mode* on our gloo-edge ingress gateways. Whenever the gloo-edge ingress gateway tries to connect to an upstream service via TLS, its outbound `linkerd-proxy` will not forward that request and it fails (without any log messages).

![image](https://user-images.githubusercontent.com/1087375/140740907-7adb165f-c679-4fdc-a359-90915bbfd1fa.png)

Note, this behavior is documented in https://linkerd.io/2.11/tasks/using-ingress/, where it states:

> You should annotate the pod spec with config.linkerd.io/skip-outbound-ports: 8001. The Envoy pod will try to connect to the Contour pod at port 8001 through TLS, which is not supported under this ingress mode, so you need to have the proxy skip that outbound port.

However, this behavior prevents us from using gloo-edge to forward traffic to upstreams (backends) which use TLS (and thus have no need for linkerd's mTLS feature).

### How should the problem be solved?

The outbound `linkerd-proxy` should use protocol detection and if traffic is already TLS encrypted, simply forward it to the original target (IP address & port). No `mTLS` must be applied and neither load-balancing nor *ServiceProfile* support is needed if traffic is already TLS encrypted.

### Any alternatives you've considered?

For now, we use the `config.linkerd.io/skip-outbound-ports` annotation on our *gloo-edge* ingress gateways to work-around this problem. However, `config.linkerd.io/skip-outbound-ports` is not a proper solution to this problem as it completely by-passes linkerd (no golden metrics) and as it will not work if there are multiple upstreams with the same port number and at least one of them not using TLS.

### How would users interact with this feature?

Nothing special here, I would even argue that the requested (new) behavior is what a user would intuitively expect.

**Comment by adleong** [comment]
Hi @alex-berger!

When Linkerd is running in `linkerd.io/inject=ingress` mode, it makes routing decisions based on the host, authority, or l5d-dst-override header.  (See: https://linkerd.io/2.11/tasks/using-ingress/#ingress-details)  However, if gloo-edge is initiating a TLS connection, the linkerd-proxy cannot read these headers and will not know how to route the traffic.  This means that inject=ingress mode is not appropriate when the ingress may initiate TLS connections.

I'll also note that Linkerd will never be able to provide golden metrics for connections where gloo-edge is initiating TLS because it cannot read the contents of those connections.

One option would be to switch to `linkerd.io/inject=enabled` mode instead of `inject=ingress` mode.  In this mode, Linkerd routes based on the original destination of the request.  If goo-edge targets requests at the cluster ip of a kubernetes service, then Linkerd will appropriately load balance to that service.  Otherwise, if gloo-edge target requests at individual endpoint ips, Linkerd will respect that decision and forward the request to that pod, skipping its own load balancing.

I hope that helps clarify things!

**Comment by alex-berger** [comment]
Hi @adleong 

What you explained, is how it works today. And what I am proposing with this feature request is how it should work in future :innocent:.

Unfortunately, many ingress provider do their own endpoint selection (load balancing) which cannot be disabled. And I guess that is also the reason, why for those ingress providers the linkerd documentation recommends to use ringres mode (`linkerd.io/inject=ingress`) in https://linkerd.io/2.11/tasks/using-ingress. 

In our specific case, using gloo-edge as ingress provider, we cannot turn-off its own endpoint selection, but still we want to profit from linkerd's features and thus we have to run it in *ingress mode*. However, we also need to route some traffic to backends that live outside the cluster (e.g. AWS EC2 instances and AWS Lambda Functions) and some of those (the EC2 instances) only speak TLS, which does not work with *ingress mode*.

What we need is *ingress mode* with the following behavior:
- If its already TLS just forward it (as if not running in *ingress mode*). 
- If its not TLS apply *ingress mode* (as it is today).

If the normal mode (non ingress mode) supports transparent TLS forwarding, why can we not support it in *ingress mode* as well?

> I'll also note that Linkerd will never be able to provide golden metrics for connections where gloo-edge is initiating TLS because it cannot read the contents of those connections.

Let me be more precise here, I was talking about TCP (level) metrics, which should be no problem (as they already are in place).

**Comment by adleong** [comment]
Ah, I gotcha.  This sounds reasonable.

**Comment by alex-berger** [comment]
Nope, this is not a stale issue!

**Comment by olix0r** [comment]
Fix proposed here https://github.com/linkerd/linkerd2-proxy/pull/1649
