### ISSUE TITLE
Ability to gradually warm newly started pods

### ISSUE THREAD

**Issue by ryan4yin** [linkerd/linkerd2#7277]
### What problem are you trying to solve?

some of our services used to run on AWS ECS and strongly relied on the slow_start function of AWS ALB,
After migrating to EKS, the scaleUp of the service is not as smooth as before.

### How should the problem be solved?

without overwhelming the newly started pods with a flood of requests, the traffic split to those pods should be gradually increased from a little rate.

related docs:

- [Slow start mode - envoy](https://www.envoyproxy.io/docs/envoy/v1.20.0/intro/arch_overview/upstream/load_balancing/slow_start#arch-overview-load-balancing-slow-start)
- https://github.com/istio/istio/issues/21228
- [AWS - Application Load Balancer Announces Slow Start Support for its Load Balancing Algorithm](https://aws.amazon.com/about-aws/whats-new/2018/05/application-load-balancer-announces-slow-start-support/)

**Comment by winterhalder** [comment]
This feature is actually available in AWS EKS now (if you're using the ALB load balancers). That said, it would be awesome if linkerd provided this sort of feature so that it would be available cross-cloud platforms... (a similar slow start feature is not available on Google Cloud or Azure load balancers <- that I've found anyway).
