### ISSUE TITLE
 cli: `<extension> install` should support `--ignore-cluster`

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7330]
It's frequently useful to run install to generate a manifest for visual inspection. While the main `linkerd install` supports `--ignore-cluster`, none of the extensions (multicluster, viz, jaeger, ...) seem to support this flag. They should!

**Comment by krzysztofdrys** [comment]
I would like to work on this. I will start with `viz` and see how far I can go.

**Comment by krzysztofdrys** [comment]
I think `linkerd viz install` has flag which does exactly this. Is it called `--skip-checks`:
```
--skip-checks              Skip checks for linkerd core control-plane existence
```
As a note `linkerd install control-plane` uses both `--skip-checks` and `--ignore-cluster`:
https://github.com/linkerd/linkerd2/blob/eec713221ff42d901fab7013220e6d15461c696a/cli/cmd/install.go#L178
 ```
 linkerd install control-plane --help | rg "skip|ignore"
      --skip-checks                               Skip checks for namespace existence
      --skip-inbound-ports strings                Ports and/or port ranges (inclusive) that should skip the proxy and send directly to the application
      --skip-outbound-ports strings               Outbound ports and/or port ranges (inclusive) that should skip the proxy
      --ignore-cluster             Ignore the current Kubernetes cluster when checking for existing cluster configuration (default false)
      ```

**Comment by krzysztofdrys** [comment]
I don't think we need both `--skip-checks` and `--ignore-cluster` for `linkerd viz install`. This command (unlike `linkerd install control-plane`) will emit the manifests even if `viz` is already installed. 

I would say we should either leave `linkerd viz install` as it is or add an alias `--ignore-cluster` which points to `--skip-checks`

What do you think @olix0r ?

**Comment by mateiidavid** [comment]
Hey @krzysztofdrys thanks for being so eager to work on this! Just wanted to expand a bit on what you said.

The main cli command needs a k8s client to check whether global resources are there. I think this was historically more for the configmap? We mainly check for webhook configs and crds, everything regarded as "pre-install" checks. `--ignore-cluster` will just bypass these checks.

With extensions, we don't really perform any checks (or, at the very least, not that I know of). The manifests will always be rendered, even if the extension is currently installed in the cluster. Because of this, extensions also have a different upgrade path. Instead of relying on a separate `upgrade` command (as we do with the control plane), we simply re-install extensions after we update the client (e.g bump up cli to new version, upgrade extension through `linkerd extension install`).

As a personal opinion, I'm leaning towards leaving things as is. We can inspect the manifests extensions generate (at the expense of a slightly more confusing upgrade path...). I think if we add a new flag for extensions, we'd have to probably also implement some checks (otherwise the flag wouldn't necessarily serve a functional purpose). We'd also need to at least document the new upgrade path; in order to upgrade we'd have to bump up the client and then re-install using the ignore cluster flag, (e.g `linkerd extension install --ignore-cluster`).

Not sure my opinion is super valid here, but thought I'd put it out there :)

**Comment by olix0r** [comment]
My preference would be that we support a common flag for all install commands for consistency. When a CLI supports `--skip-checks`, I think `--ignore-cluster` should imply `--skip-checks`. I don't feel _super_ strongly, though; so we could leave it as-is if it really doesn't make sense; but in general it's nice to be able to have a flag that asserts we won't try using the current kube context at all.

> The main cli command needs a k8s client to check whether global resources are there.

Yeah, it's to avoid regenerating trust anchors in a way that would break an existing installation.

**Comment by krzysztofdrys** [comment]
ok, so as much I would be happy to implement this, it seems that this needs some discussion before.

My personal vote would be for being consistent among other command. This would mean:
- in `linkerd viz install` add `--ignore-cluster` which is (right now) just an alias for `--skip-tests`,
- rework logic for `linkerd install control-plane` so that it is enough to add `--ignore-cluster` to skip k8s context (right now one needs to pass both `--skip-tests` and `--ignore-cluster`)

**Comment by mateiidavid** [comment]
Thank you both for the replies!

> but in general it's nice to be able to have a flag that asserts we won't try using the current kube context at all.

Yeah that makes sense. I'm very in favour of being consistent with all `install` commands too.

@krzysztofdrys don't block on account of me :). I think your plan makes sense; we'd be consistent throughout our `install` commands and `--ignore-cluster` will imply `--skip-checks`. I think we can address any other questions in the PR itself. I'd wait maybe one more day or so before starting to work? Just in case anyone will have any other concerns.

**Comment by krzysztofdrys** [comment]
@mateiidavid it was definitely more than one day, but I finally have something. Could someone take a look? https://github.com/linkerd/linkerd2/pull/7564/files
