### ISSUE TITLE
Linkerd changes the HTTP response codes

### ISSUE THREAD

**Issue by majidghs** [linkerd/linkerd2#7498]
### What is the issue?

The issue is that linkerd change the HTTP response status phrase.
For example, my web application response code is `400 Only Managers Can Do This`, but linkerd response to this request is `400 Bad Request`.
And in the case of custom HTTP codes, they are all shown as `none`.

### How can it be reproduced?

Create a web application that returns a custom http response, inject linkerd and then call the API.

### Logs, error output, etc

In my application, I have this API:
```
curl 'https://<URL>/apiv1/tokens' -X 'POST' --data-raw '{"email":"xxxxx@gmail.com","password":"xxxx"}'
```
The response is:
```
{"stackTrace":"Traceback:  File /path/to/stacktrace/file exceptions.HTTPIncorrectEmailOrPassword: 603 Incorrect Email Or Password"}
```

But the returned response from linkerd is as follow:
```
HTTP/1.1 603 <none>
Server: nginx/1.10.3 (Ubuntu)
Date: Sun, 19 Dec 2021 13:21:28 GMT
Transfer-Encoding: chunked
Connection: keep-alive
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================


Status check results are √
```

### Environment

- Kubernetes version: 1.21
- Cluster environment: Rancher RKE2
- Host OS: Ubuntu20.04.2
- Linkerd version: stable-2.11.1

**Comment by olix0r** [comment]
Our underlying libraries ([hyperium/http](https://github.com/hyperium/http), [hyperium/h2](https://github.com/hyperium/h2), etc) don't give us much control over this. And, in fact, in the HTTP/2 ecosystem, I don't think that there's any sort of support for custom messages for HTTP status codes.

I think we're unlikely to support this. It's probably more robust to convey this type of information in response payloads rather than status message.

**Comment by majidghs** [comment]
@olix0r Thanks for your reply.
What about the 400 status code? why linkerd changes the description to `Bad Request`?

**Comment by olix0r** [comment]
Linkerd uses Rust's [`http`](https://github.com/hyperium/http/) crate. When it parses responses into a [`StatusCode`]( https://github.com/hyperium/http/blob/abe651273f4cf19cf9a247f376e9ece85becc722/src/status.rs#L45) it only preserves the numeric status code value and when it serializes the response it uses the canonical status code message (e.g., "Bad Request").

I'm going to close this issue, since there's nothing we can do about this in the Linkerd project. As I mentioned, it's probably best to encode your application-specific information in response headers or bodies.
