### ISSUE TITLE
Add a timeout to `linkerd-await`

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#7659]
### What problem are you trying to solve?

[1]: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution

Linkerd's control plane comes with a `postStart` hook on the proxy container that calls `linkerd-await`'s binary. The binary is called without a command to execute after; the purpose of the hook is to block the main container from executing until the proxy is in a ready state. When `linkerd-await` exists, the main container in the pod can create.

 A `postStart` hook is fired asynchronously with the container's entrypoint; according to the k8s docs, if the hook takes too long to run (or hangs), the container will not reach a running state [[1][1]]. If the proxy is not in a ready state (for whatever reason, most common would be identity issues), the hook will block indefinitely. If the hook doesn't finish, we might get stuck in a `ContainerCreating` phase. If the hook doesn't finish, the next container will also not be run, so the whole pod will be stuck in `PodInitializing`.

This (chicken-n-egg) situation makes it hard to troubleshoot -- there is no access to logs -- which in turn makes it harder to figure out what the problem is. Is it the underlying network? Is it DNS (always)? Hard to know, the only reliable troubleshooting method is to describe the pod, which usually doesn't give any information. This painpoint is also described in https://github.com/kubernetes/kubernetes/issues/30042.

GH Discussion that exemplifies how difficult it can get to debug issues:

https://github.com/linkerd/linkerd2/discussions/7476#discussioncomment-1814018

```
$ kubectl -n linkerd logs pod/linkerd-destination-7b77fffcf6-lp7mp -c linkerd-proxy
Error from server (BadRequest): container "linkerd-proxy" in pod "linkerd-destination-7b77fffcf6-lp7mp" is waiting to start: PodInitializing
```

### How should the problem be solved?

The `postStart` hooks can be deleted (manually) from the install manifests. This generally provides enough insight about the problem, but people need to be aware of the difficulties in debugging and the shortcomings of hooks in advance. We could document what to do when the control plane fails to install (with pods stuck in `ContainerCreating`). In addition, we could also add a hardcoded timeout to `linkerd-await`.

One way to do this would be to start a timer and add a `select!` statement here:

https://github.com/linkerd/linkerd-await/blob/89fd9efacb487cfcbf5821aa04dfa454888e33df/src/main.rs#L78

If the timer runs out, we exit with a zero code (so the hook doesn't fail) and possibly a log message to let us know the ready check timed out. This should unblock the next container and let the pod spin up. It's likely the proxy will be in a bad state, but it makes it easier to debug. A hardcoded timeout of 5 minutes seems sensible to me.

### Any alternatives you've considered?

We could instead opt to just document this with hints on how to troubleshoot (i.e remove the hook).

### Would you like to work on this feature?

maybe

**Comment by olix0r** [comment]
Should the timeout cause the command to fail? What happens if a postStart hook fails?

**Comment by kleimkuhler** [comment]
After some further investigation, I think adding a timeout to `linkers-await` makes sense, but we don't get the exact error message we'd expect; we _can_ see that the command fails with `kubectl describe` output _and_ get logs from the containers.

---

I originally tested this with a manifest that deploys 2 containers. Once the first container has started, a `postStart` hook is called which echos `hi` and exits.

When this occurs, that container (`app`) will terminate, but the other container (`app-2`) will continue running. When `kubectl describe pod pod` is run, we can see the error message in the event output:

```
  Warning  FailedPostStartHook  19m (x3 over 21m)     kubelet            Exec lifecycle hook ([/bin/bash -c echo 'hi' && exit 1]) for Container "app" in Pod "pod_default(07b1375d-1637-43e1-8098-8869dccf08b0)" failed - error: command '/bin/bash -c echo 'hi' && exit 1' exited with 1: , message: "hi\n"
 ```

I then tested this with `linkerd-await` by adding a timeout which will error if the proxy fails to become ready within the given timeout (https://github.com/linkerd/linkerd-await/commit/b1347b6bda74db652c18fef319d1d2390c4f6b66).

If identity fails to become ready within some timeout—say `10s`—then the hook should error. This occurs, but we don't see the expected error message `linkerd-proxy failed to become ready within 10s timeout`.

```
  Warning  FailedPostStartHook  9m21s                  kubelet            Exec lifecycle hook ([/usr/lib/linkerd/linkerd-await -t 10s]) for Container "linkerd-proxy" in Pod "linkerd-destination-74f9bbd7d6-5fchq_linkerd(1cee69ad-321c-4631-b687-9bf98e0aedf6)" failed - error: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "1c424c2dd1255e71a5bdc2f386a9351b4fd145fb59cefc453e3b0bb01f079d95": OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec format error: unknown, message: ""
```

I believe this occurs because the `linkerd-proxy` container never actually starts, so it's not printing the full error message like we see in the `app` container example above.

That being said, we still can see that it failed the `postStart` hook and the command that was run. Additionally, we can get logs from the containers:

```
$ kubectl logs -n linkerd linkerd-destination-74f9bbd7d6-5fchq linkerd-proxy
...
[    29.319611s]  WARN ThreadId(01) policy:watch{port=8090}:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=Connection refused (os error 111)
[    29.820307s]  WARN ThreadId(01) policy:watch{port=8090}:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=Connection refused (os error 111)
[    30.003566s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
```

**Comment by olix0r** [comment]
Linkerd-await v0.2.5 supports this https://github.com/linkerd/linkerd-await/releases/tag/release%2Fv0.2.5
