### ISSUE TITLE
Proxy should gracefully shutdown control thread

### ISSUE THREAD

**Issue by seanmonstar** [linkerd/linkerd2#779]
I've noticed sometimes in tests a log like this:

```
controller error: Handshake(Error { kind: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) })
```

That tells me that the control thread was still active while the test case was tearing everything else down. It should have been shutdown before the main proxy thread. It seems likely that, for instance if Prometheus were scraping some stats when we received a shutdown signal, and we shutdown quickly enough, the response for `/metrics` would just be aborted.

**Comment by hawkw** [comment]
As far as I know, there shouldn't be anything scraping `/metrics` in a test case unless the test itself explicitly makes a request to `/metrics` --- we don't run a mock Prometheus in proxy tests.

**Comment by seanmonstar** [comment]
No, but the control thread establishes an h2 connection the controller as well. Instead of closing it, it was sitting there open when the proxy main thread closed up, allowing the support controller thread to close as well (and then proxy's controller thread saw the reset connection).

**Comment by briansmith** [comment]
The control thread needs to keep running, and the connection to the controller needs to stay open, until all requests have been routed, because load balancing requires information from the Destination service.

I agree that after the main thread stops doing work, if we're still serving a response to a `/metrics` request we should finish serving that request. I don't think this is a high priority to fix though.

However, I don't think there's any other significant benefit to trying to do a "clean" shutdown of the control thread. We don't need to shut down the connection to the controller cleanly as it is perfectly fine for the controller to see a reset.
