### ISSUE TITLE
initContainer - set cpu and memory requests/limits

### ISSUE THREAD

**Issue by mikebell90** [linkerd/linkerd2#7980]
### What problem are you trying to solve?

It looks like this ignores the proxy annotations and merely makes up it's own?
stable 2.11.1

```
Limits:
   cpu:   100m
   memory: 50Mi
  Requests:
   cpu:   10m
   memory: 10Mi
```

This is with setting various proxy-cpu-limit-request, etc annotations - which work fine on the main proxy container

This forces the entire pod into Burstable

### How should the problem be solved?

Annotations for the initContainer

```
config.linkerd.io/init-cpu-limit | Maximum amount of CPU units that the initContainer can use
config.linkerd.io/init-cpu-request | Amount of CPU units that the initContainer requests
config.linkerd.io/init-memory-limit | Maximum amount of Memory that the initContainer can use
config.linkerd.io/init-memory-request | Amount of Memory that the initContainer can requests
```

### Any alternatives you've considered?

There are none I'm aware of other than our own mutating controller ordered after linkerd-inject

### How would users interact with this feature?

They would add these annotations "normally", and linkerd-inject would do them

### Would you like to work on this feature?

maybe

**Comment by kleimkuhler** [comment]
The issue is more that annotations do not exist to configure the `proxyInit` resources. You _can_ set them during installation with the Helm flags

```sh
$ linkerd install --set proxyInit.resources.cpu.limit=150m
```

and you'll observe that all `proxyInit` contains now have a CPU limit of `150m`.

If you would like to configure these via annotations then we would need equivalent annotations for `proxyInit`. For example, `config.linkerd.io/proxyInit-cpu-limit` and all the plumbing that would need to take place during injection for checking these values.

**Comment by mikebell90** [comment]
After looking at the helm chart and @kleimkuhler comments. It's in the linkerd-config configmap. Probably that makes sense. I'd like to change this to

1. enhancement suggestion: Default is all the memory/cpu requests and limits do not burst (eg are equal). 
2. enhancement suggestion: yeah it would be nice to have annotations obey this, though not crucial

**Comment by kleimkuhler** [comment]
That sounds reasonable to make the memory and CPU requests and limits equal.

Keep in mind that this does not mean the Pod will now be assigned a QoS of `Guaranteed`. According to the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed), all containers within the Pod need to specify their CPU and memory requests and limits.

This _should_ avoid the case though where the `linkerd-init` container is the reason that a Pod is considered `Burstable` instead of `Guaranteed`.

**Comment by mikebell90** [comment]
Yes, that's exactly my point - linkerd should not default to values that change the existing QOS ;)
