### ISSUE TITLE
Redis Metrics support

### ISSUE THREAD

**Issue by AjithPanneerselvam** [linkerd/linkerd2#8061]
### What problem are you trying to solve?

`linkerd-proxy` has first-class support for the `HTTP` protocol, which is great. The application protocols other than HTTP traffic are proxied at TCP-level, meaning the proxy doesn't try to understand other than HTTP semantics. 

Redis, the in-memory store speaks the [RESP protocol](https://redis.io/topics/protocol). If the linkerd-proxy could understand the RESP protocol, it could provide us a wealth of information about the Redis traffic. 

### How should the problem be solved?

1. **Protocol detection:** According to RESP protocol, the client sends the Redis commands as **RESP array of Bulk Strings**. For example, the Redis Ping command will be represented in an array of bulk strings as `*1\r\n$4\r\nping\r\n`. By inspecting the raw TCP bytes, we could be able to detect the traffic is a Redis traffic or not. 
2. **RESP codec:** Once we detect the TCP raw bytes are RESP packets, we can use the RESP decoder crate to understand the Redis traffic. We have a crate to decode the RESP bytes - https://docs.rs/resp/latest/resp/struct.Decoder.html
3. **Metrics:** For an MVP, I would like to first classify the Redis requests (`GET`, `PUT`, etc.) and provide metrics like RPS, P95 Redis command-wise.

**Note:**  When we talk about proxy, we have inbound and outbound connections. For Redis metrics, I'm thinking of having the above implemented in the inbound proxy (Redis sidecar proxy).  

### Any alternatives you've considered?

I think handling it in the proxy layer is the way to go for specific application metrics in the service mesh. 

### How would users interact with this feature?

Linkerd Dashboard

### Would you like to work on this feature?

yes

**Comment by AjithPanneerselvam** [comment]
I'm intrigued by the inner workings of proxy and I would like to tackle this feature as my side project. I've started digging into the code and I will ask questions as I spend more time on this. I've started looking into [inbound](https://github.com/linkerd/linkerd2-proxy/tree/main/linkerd/app/inbound/src) crate. 

I would appreciate any advice on the implementation of this feature and pointing me to the code that I should start with would be great.

**Comment by olix0r** [comment]
I'd be a bit wary about the `resp` crate -- it hasn't seen any updates/maintenance in about 5 years. Beyond that, if we're going to participate in the REDIS protocol in a non-trivial way, we probably want to use an actual client/server implemented for `tokio`, ideally with bindings for `tower`. Tokio includes an example redis implementation, [`mini-redis`](https://github.com/tokio-rs/mini-redis), but this project is explicitly not production-ready. It might be a useful starting point for prototyping, but we'd want to use an actual maintained redis client before we merge support. If we're taking on dependencies, we need to be able to trust that they are actively maintained and that there's a community that can help us fix bugs, etc. Otherwise, it's just more code the Linkerd project has to maintain.

Given an arbitrary connection, how does a proxy know whether traffic is RESP? Do clients send some identifiable preamble? Or does the proxy need to be explicitly configured to handle traffic as RESP? If the latter, we'll need to make changes to the `Server` CRD, the discovery APIs, etc.
