### ISSUE TITLE
Linkerd Control Plane not restarting as expecting after rotating certificate

### ISSUE THREAD

**Issue by rynslmns** [linkerd/linkerd2#8282]
### What is the issue?

We started experiencing issues related to TLS and were led to this [article](https://linkerd.io/2.10/tasks/manually-rotating-control-plane-tls-credentials/).

We have done the following:

1. Generate a new trust anchor cert `step certificate create root.linkerd.cluster.local ca.crt ca.key \ --profile root-ca --no-password --insecure`
2. Issue certificate and key: `step certificate create identity.linkerd.cluster.local issuer.crt issuer.key \ --profile intermediate-ca --not-after 8760h --no-password --insecure \ --ca ca.crt --ca-key ca.key`
3. Pass certs to Linkerd `linkerd upgrade \  --identity-issuer-certificate-file=./issuer.crt \ --identity-issuer-key-file=./issuer.key \ --identity-trust-anchors-file=./ca.crt \ --force \ | kubectl apply -f -`

After doing this, the following occurred:
```‼ Rotating the trust anchors will affect existing proxies
See https://linkerd.io/2/tasks/rotating_identity_certificates/ for more information

namespace/linkerd unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-identity unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-identity unchanged
serviceaccount/linkerd-identity unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-destination unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-destination unchanged
serviceaccount/linkerd-destination unchanged
secret/linkerd-sp-validator-k8s-tls configured
validatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-sp-validator-webhook-config configured
secret/linkerd-policy-validator-k8s-tls created
validatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-policy-validator-webhook-config created
clusterrole.rbac.authorization.k8s.io/linkerd-policy created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-destination-policy created
role.rbac.authorization.k8s.io/linkerd-heartbeat unchanged
rolebinding.rbac.authorization.k8s.io/linkerd-heartbeat unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-heartbeat unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-heartbeat unchanged
serviceaccount/linkerd-heartbeat unchanged
customresourcedefinition.apiextensions.k8s.io/servers.policy.linkerd.io created
customresourcedefinition.apiextensions.k8s.io/serverauthorizations.policy.linkerd.io created
customresourcedefinition.apiextensions.k8s.io/serviceprofiles.linkerd.io configured
customresourcedefinition.apiextensions.k8s.io/trafficsplits.split.smi-spec.io configured
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector configured
serviceaccount/linkerd-proxy-injector unchanged
secret/linkerd-proxy-injector-k8s-tls configured
mutatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-proxy-injector-webhook-config configured
configmap/linkerd-config configured
secret/linkerd-identity-issuer configured
configmap/linkerd-identity-trust-roots created
service/linkerd-identity configured
service/linkerd-identity-headless configured
deployment.apps/linkerd-identity configured
service/linkerd-dst configured
service/linkerd-dst-headless configured
service/linkerd-sp-validator configured
service/linkerd-policy created
service/linkerd-policy-validator created
deployment.apps/linkerd-destination configured
cronjob.batch/linkerd-heartbeat configured
deployment.apps/linkerd-proxy-injector configured
service/linkerd-proxy-injector configured
secret/linkerd-config-overrides configured
```

Based on the documentation we then restarted the linkerd deployments: `kubectl -n linkerd rollout restart deployments`

However, when running `linkerd check --proxy` command we get this error

```linkerd-control-plane-proxy
---------------------------
/ The "linkerd-proxy" container in the "linkerd-grafana-585cd4675-jvpfc" pod is not ready
```

It is not clear to me what to do from here because that is where the documentation stops. Any tips on how to address from here would be amazing! Thanks.

### How can it be reproduced?

I am not sure specifically how to reproduce, but theoretically could install a certificate that is expired within the linkerd cluster.

### Logs, error output, etc

```
Info
2022-04-17 14:56:53.553 PDT
linkerd-proxy
[ 1305.784641s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate

Info
2022-04-17 14:56:54.055 PDT
linkerd-proxy
[ 642.824080s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:54.055 PDT
linkerd-proxy
[ 1306.286778s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:54.557 PDT
linkerd-proxy
[ 643.326498s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:54.557 PDT
linkerd-proxy
[ 1306.788892s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:55.059 PDT
linkerd-proxy
[ 1307.290893s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:55.060 PDT
linkerd-proxy
[ 643.829479s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:55.561 PDT
linkerd-proxy
[ 1307.792912s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
Info
2022-04-17 14:56:55.563 PDT
linkerd-proxy
[ 644.332361s] WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
```

### output of `linkerd check -o short`

```Linkerd core checks
===================

kubernetes-version
------------------
× is running the minimum kubectl version
    kubectl is on version [1.15.2], but version [1.17.0] or more recent is required
    see https://linkerd.io/2.11/checks/#kubectl-version for hints
```

### Environment

- Kubernetes Version: 1.15.2
- Cluster Environment: GKE
- Host OS: unix
- Linkerd version: Client version: stable-2.11.1| Server version: stable-2.10.2

### Would you like to work on fixing this bug?

no

**Comment by mateiidavid** [comment]
Hey @rynslmns, thanks for raising this :) 

When certificates are rotated, the identity trust anchors configmap should have your new root certificate. Each injected pod will have the root certificate injected as an environment variable, using the k8s downstream API:

```
    - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
      valueFrom:
        configMapKeyRef:
          key: ca-bundle.crt
          name: linkerd-identity-trust-roots
```

When the proxy first runs, it'll use whatever CA is in the env variable. You mentioned you restarted the pods in the `linkerd namespace`, but the pod you described in the output is a grafana instance, which normally would be under the `viz` namespace. Is it possible this pod wasn't restarted and it started-up with the old CA? If it uses the old CA, chances are certificate validation will fail.

Have you attempted to restart the other pods too so they can reload the env variable?

**Comment by rynslmns** [comment]
@mateiidavid Thanks for the quick response!

We actually have everything under the same `linkerd` namespace. Can definitely confirm that the pods restarted, the only difference is the yaml file section that you are referring to in GCP actually lists the actual certificate itself, not a reference to a config map. 

How do you recommend comparing the two and forcing it to update if they are not using the same? All of the other pods in the linkerd namespace except for these have restarted as we would expect.

**Comment by mateiidavid** [comment]
@rynslmns hey, will try to answer some of your questions as best as I can.

> We actually have everything under the same linkerd namespace. 

Hmm, we generally don't recommend that. We recommend that the metrics stack (i.e `viz`) is installed in its own namespaces. In k8s, namespaces declare ownership of a resource or group of resources; our operational model of choice is to have a clear separation between our manifests. For example, many of our extension namespaces have appropriate labels and annotations that feed into the cli commands, if the namespace is shared, you might find that an `uninstall` of the metrics stack can have undefined behaviour and take down the control plane as well. It's completely up to you how to manage this ofc, but you're less likely to run into trouble down the line if you keep the namespace boundary between all of the components.

> However, when running linkerd check --proxy command we get this error

Are all of your pods up? Or does the check report a false error? It's possible for the `check` command not to work properly because of what I said above.

> The only difference is the yaml file section that you are referring to in GCP actually lists the actual certificate itself, not a reference to a config map.

Interesting, is it possible your viz stack runs on a different version compared to the control plane itself? Are the certificates the same throughout the namespace? Have you tried to compare them and see if they have the same ID/expirty/SAN (or whatever else)?

> It is not clear to me what to do from here because that is where the documentation stops. Any tips on how to address from here would be amazing! Thanks.

I'm not entirely sure of what's going on. I'd start checking the certificates in the namespace:

- do you see your pods loading the trust anchor from the cm? If not, are they same as whatever certificate exists in the identity trust roots cm? Verify whether CAs line up.
- try restarting workloads again and see if that has an effect. Perhaps for some reason the update was botched? You could try to "upgrade" viz via `linkerd viz install | kubectl apply -f -`, see if that changes things?
- as far as I know, in the `linkerd` namespace we _don't inject workloads_, so I'm a bit confused as to how your viz resources have been set-up since they normally pass through the injector. Try to re-inject viz resources, or try to install in a different namespace so they can all go through the injector normally. I'd check if you have this label on the `linkerd` namespace:

```yaml
  labels:
    config.linkerd.io/admission-webhooks: disabled
```

I'm thinking: if your viz resources don't go through the injector it might explain why they don't have the new CA? Or why they don't have the CA from a `ConfigMap`(cm)? Hopefully this should be enough to get you started and help you collect more diagnostics. Let me know if you have any follow-up questions or if you have managed to track down the issue. :)

**Comment by mateiidavid** [comment]
Will close this out for now since there hasn't been any activity. Let me know if you want it re-opened :)
