### ISSUE TITLE
Linkerd pods are not evictable by the cluster autoscaler

### ISSUE THREAD

**Issue by rocketraman** [linkerd/linkerd2#8308]
### What problem are you trying to solve?

This is a follow-up to https://github.com/linkerd/linkerd2/issues/4067, but rather than linkerd workloads, it pertains to the deployments created as part of linkerd itself, specifically:

* linkerd-viz grafana
* linkerd-viz tap-injector
* linkerd-proxy-injector

These prevent the autoscaler from evicting them, and therefore downscaling nodes.

### How should the problem be solved?

I would suggest adding the `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` annotation by default to all of these pods when running linkerd in HA mode.

### Any alternatives you've considered?

1. Manually editing the deployment after installation.
2. Changing the cluster autoscaler configuration as documented at https://linkerd.io/2.11/features/ha/#working-with-cluster-autoscaler.
3. Creating a controller to add these annotations at runtime.

### How would users interact with this feature?

No user interaction necessary.

### Would you like to work on this feature?

maybe

**Comment by mateiidavid** [comment]
Would it be theoretically possible for the autoscaler to scale the injector down to 0 replicas? If so, we should tread a bit carefully; while for most Linkerd workloads (and meshed services), scaling down wouldn't necessarily be a problem, when we run in `HA` mode we always want to guarantee that _at least one injector replica is up and running_.

In `HA` mode, we want to make sure that workloads that are supposed to be injected do not run without a proxy, so we use a stricter failure policy for the injector Admission webhook. You can read more about it [here](https://linkerd.io/2.11/features/ha/#proxy-injector-failure-policy). We could change the failure policy to `Ignore` to be more relaxed, but my feeling is that when `HA` is used we want to guarantee pods will not run without the proxy when they should. Obviously, having no injector pod up means the admission webhook will fail and since it is run for any newly created pod, it'll prevent the injector itself from being scaled up, and any pod from being scheduled.

Is there a way to guarantee the injector won't be completely scaled down if we put the annotation on? From my perspective, we'd have to run with an admission failure policy of `Ignore` _by default_, if we want to add this annotation _by default_, and I'm not entirely sure if that's the right move here? I'm not sure if I'd recommend this to be a default value, but I'm interested in what you and other maintainers think on the topic :)

**Comment by rocketraman** [comment]
Adding a `PodDisruptionBudget` for critical pods will prevent the autoscaler from doing anything it shouldn't do.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md
