### ISSUE TITLE
priorityClassName missing in the latest helm chart, even if the feature got merged in 9 months ago

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/linkerd2#8824]
### What is the issue?

This commit introduced an ability to specify priorityClassName for linkerd pods via helm chart: https://github.com/linkerd/linkerd2/commit/d2e441dfe1f9c761b3604c862321d408a56c2c8c

Although this commit has been merged in 9 months ago, this feature is completely missing in the latest helm chart.

Main branch destination.yaml: https://github.com/linkerd/linkerd2/blob/73e4bf7750f3ab4458096dba0a02c216c9b4da34/charts/linkerd-control-plane/templates/destination.yaml#L312

stable-2.11.2 destination.yaml (missing priorityClassName): https://github.com/linkerd/linkerd2/blob/d7a3ddf4bf41babc32aef79fdc5c40ef2bfb9283/charts/linkerd2/templates/destination.yaml#L308

### How can it be reproduced?

Look at the helm chart content for destination.yaml for the latest helm chart vs. what is in main branch

### Logs, error output, etc

[N/A](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/destination.yaml#L312)

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

priorityClassName feature should be available via latest helm chart

**Comment by kleimkuhler** [comment]
Unfortunately #7005 has not made it into a stable release, but it is available on the current edge releases. The time between these stable releases has been unusually long which is why that change has not appeared in a stable release yet.

We did just release stable 2.11.3; while this does seem like a backwards compatible change it unfortunately did not make it into that release. If for some reason 2.11.4 seems necessary we can make sure to include that change.

**Comment by kleimkuhler** [comment]
Great I'm going to close this out then since it will be included.

**Comment by tommilligan** [comment]
@kleimkuhler Thanks for the explanation and update - just noting this would also be a useful feature for us and we're looking forward to it being released. Happy to contribute if I can help make it happen as a contributor in any way.
