### ISSUE TITLE
Fix multicluster on Kubernetes v1.24

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#9033]
There are changes to how ServiceAccounts/Secrets work in Kubernetes v1.24. We should at the very least test this before releasing 2.12

**Comment by mateiidavid** [comment]
As of Kubernetes `1.24` tokens for ServiceAccounts will not be automatically generated by Kubernetes. I tested this out in a few clusters to see how it would play out. 

In `2.12` we will introduce `serviceAccountTokenProjection` which will create tokens intended for Linkerd specifically. As far as the control plane is concerned, I didn't have any issues. It's worth mentioning that even without `serviceAccountTokenProjection` turned on as a feature, we still successfully generated certificates.

Our multicluster extension on the other hand seems to error out when we attempt two link two clusters together. I tested this with two k3d clusters, both running `v1.24`:

```
Error: could not find service account token secret for linkerd-service-mirror-remote-access-default
Usage:
  linkerd multicluster link [flags]

Examples:
  # To link the west cluster to east
  linkerd --context=east multicluster link --cluster-name east | kubectl --context=west apply -f -

The command can be configured by using the --set, --values, --set-string and --set-file flags.
A full list of configurable values can be found at https://github.com/linkerd/linkerd2/blob/main/multicluster/charts/linkerd-multicluster-link/README.md
```

Since the secret is no longer generated, the ServiceAccount doesn't have any token associated with it, and the link command fails.

**Comment by olix0r** [comment]
So, I think this means we need to update the multicluster manifest to include a `Secret` when it creates service accounts?

**Comment by mateiidavid** [comment]
> So, I think this means we need to update the multicluster manifest to include a Secret when it creates service accounts?

Essentially, yes. Looking at the [code](https://github.com/linkerd/linkerd2/blob/074f5e6cdf4c4fa6a2fd86546fa63b848fb61d0e/multicluster/cmd/link.go#L142-L146), I think what we really need is just the token, to embed in the kubeconfig (so we can create the remote cluster clientset in the service mirror).

With the above in mind, I spent a bit of time trying out different fixes for this issue. I was looking for a way to generate the necessary token in such a way that we preserve backwards compatibility (for people running older versions of Kubernetes). 

There are two ways in which we can fix this:

1. create a `Secret` that will be associated with the ServiceAccount;
2. request a token through the `TokenRequest` API (which should be enabled by default in k8s `v1.24` (docs on [Configuring ServiceAccounts in k8s](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume).

### (1) Creating a `Secret`

This seems to be the easiest way to manually create a ServiceAccount token. We can add a `Secret` to the multicluster template and it will be rendered when installing the extension. The token controller will automatically generate a token for it. 

In code, at the moment, we go through the `Secrets` directly attached to the ServiceAccount to get the secret name (since prior to k8s `v1.24` the secret would be auto generated and its suffix would be randomly generated).

https://github.com/linkerd/linkerd2/blob/ce35f209a82ee82618ebb031966ad0b7f417f640/multicluster/cmd/link.go#L112-L118

We'd have to change this bit to instead look for `Secrets` whose types are `kubernetes.io/service-account-token` and then use the one whose annotation value for `kubernetes.io/service-account.name` is the remote cluster ServiceAccount name.

The downside with this approach is that in Kubernetes versions leading up to `v1.24`, we will have two secrets generated, e.g

```
:; k get secrets -n linkerd-multicluster
NAME                                                       TYPE                                  DATA   AGE
# Generated by controller
#
linkerd-service-mirror-remote-access-default-token-c7fjg   kubernetes.io/service-account-token   3      91s
# Generated by us
#
linkerd-service-mirror-remote-access-default-token         kubernetes.io/service-account-token   3      91s
```

 We cannot request that a token is *not* automatically generated through annotations or labels, so we would have both in.

### (2) Generating a token through `TokenRequest` API

When a ServiceAccount has no `Secret` attached to it (see snippet above), we can opt to generate one ourselves. The code would look roughly like this:

```go
  tokenReq := &authenticationv1.TokenRequest{
                                       Spec: authenticationv1.TokenRequestSpec{
                                               // Default audience
                                               Audiences: []string{},
                                       },
                               }

                               saToken, err := k.CoreV1().ServiceAccounts(sa.Namespace).CreateToken(cmd.Context(), sa.Name, tokenReq, metav1.CreateOptions{})
                               if err != nil {
                                       return fmt.Errorf("could not create service account token secret for %s", sa.Name)
                               }
                               token = saToken.Status.Token
```

We can make use of the token the same way as before in the config we will write out in the cluster auth `Secret` (that will be used to create the remote clientset):

https://github.com/linkerd/linkerd2/blob/ce35f209a82ee82618ebb031966ad0b7f417f640/multicluster/cmd/link.go#L142-L147

This will preserve backwards compatibility since in older Kubernetes versions, the secret will be automatically generated. In newer versions, no secret will be created for the ServiceAccount. This imo reduces the visibility into what's happening in the cluster. Some downsides I think are obvious:

* Token will be subject to default validity period, unless we overwrite this and provide a reasonable default*.
* Token is created through an API request which might not be consistent with how the rest of the CLI tools work (opting to instead print the manifest for the operator to examine).

  \* rotating tokens is something that would be done automatically (I __assume__) when it is automatically generated, we can set the token to never expire (which might not be best practice).
 \** afaik we only use the token once when we link, even if the token expires, we'd have to re-link the clusters I'd assume to ensure we can still access the remote cluster through the kubeconfig?

**Comment by olix0r** [comment]
To summarize the conversation we had on this:

1. The `Secret` is probably the lowest-effort short-term solution.
2. We need to investigate future improvements--probably for 2.13--that can reasonably support token rotation, probably via the `TokenRequest` API.
