### ISSUE TITLE
Docker container runtime can run as non-root with allowPrivilegeEscalation set to true

### ISSUE THREAD

**Issue by teriyakichild** [linkerd/linkerd2#9552]
### What is the issue?

We are trying to run the proxy-init container as non-root for compliance reasons.  The installer errors out with this message:
```
there are nodes using the docker container runtime and proxy-init container must run as root user.
try installing linkerd via --set proxyInit.runAsRoot=true
```
In my testing, I've confirmed that the proxy init container is able to run successfully as non-root on Docker as long as `allowPrivilegeEscalation` is set to true.
```
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: false
      runAsUser: 65534
```
This seems to be much more secure considering that the default for `allowPrivilegeEscalation` is true when running containers as non-root. ([source](https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md#changes-of-securitycontext-objects))

### How can it be reproduced?

The easiest way to show this works is with the following command:
```
$ docker run  --cap-add NET_ADMIN --cap-add NET_RAW  -it  cr.l5d.io/linkerd/proxy-init:v2.0.0 --incoming-proxy-port 4321 --outgoing-proxy-port 1234
INFO[2022-10-04T18:06:28Z] /sbin/iptables-save -t nat                   
INFO[2022-10-04T18:06:28Z] # Generated by iptables-save v1.8.8 on Tue Oct  4 18:06:28 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Tue Oct  4 18:06:28 2022 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -N PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-common-chain/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -A PROXY_INIT_REDIRECT -p tcp -j REDIRECT --to-port 4321 -m comment --comment proxy-init/redirect-all-incoming-to-proxy-port/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -A PREROUTING -j PROXY_INIT_REDIRECT -m comment --comment proxy-init/install-proxy-init-prerouting/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -N PROXY_INIT_OUTPUT -m comment --comment proxy-init/redirect-common-chain/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -A PROXY_INIT_OUTPUT -o lo -j RETURN -m comment --comment proxy-init/ignore-loopback/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -A PROXY_INIT_OUTPUT -p tcp -j REDIRECT --to-port 1234 -m comment --comment proxy-init/redirect-all-outgoing-to-proxy-port/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables -t nat -A OUTPUT -j PROXY_INIT_OUTPUT -m comment --comment proxy-init/install-proxy-init-output/1664906788 
INFO[2022-10-04T18:06:28Z] /sbin/iptables-save -t nat                   
INFO[2022-10-04T18:06:28Z] # Generated by iptables-save v1.8.8 on Tue Oct  4 18:06:28 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PROXY_INIT_OUTPUT - [0:0]
:PROXY_INIT_REDIRECT - [0:0]
-A PREROUTING -m comment --comment "proxy-init/install-proxy-init-prerouting/1664906788" -j PROXY_INIT_REDIRECT
-A OUTPUT -m comment --comment "proxy-init/install-proxy-init-output/1664906788" -j PROXY_INIT_OUTPUT
-A PROXY_INIT_OUTPUT -o lo -m comment --comment "proxy-init/ignore-loopback/1664906788" -j RETURN
-A PROXY_INIT_OUTPUT -p tcp -m comment --comment "proxy-init/redirect-all-outgoing-to-proxy-port/1664906788" -j REDIRECT --to-ports 1234
-A PROXY_INIT_REDIRECT -p tcp -m comment --comment "proxy-init/redirect-all-incoming-to-proxy-port/1664906788" -j REDIRECT --to-ports 4321
COMMIT
# Completed on Tue Oct  4 18:06:28 2022 
```
This doesn't work when I set the `no-new-privileges` option which is equivalent to `allowPrivilegeEscalation=false`:
```
$ docker run  --security-opt no-new-privileges  --cap-add NET_ADMIN --cap-add NET_RAW  -it  cr.l5d.io/linkerd/proxy-init:v2.0.0 --incoming-proxy-port 4321 --outgoing-proxy-port 1234
INFO[2022-10-04T18:08:25Z] /sbin/iptables-save -t nat                   
INFO[2022-10-04T18:08:25Z] iptables-save v1.8.8 (legacy): Cannot initialize: Permission denied (you must be root)
 
ERRO[2022-10-04T18:08:25Z] aborting firewall configuration              
Error: exit status 1
Usage:
  proxy-init [flags]

Flags:
      --firewall-bin-path string           Path to iptables binary (default "iptables")
      --firewall-save-bin-path string      Path to iptables-save binary (default "iptables-save")
  -h, --help                               help for proxy-init
      --inbound-ports-to-ignore strings    Inbound ports and/or port ranges (inclusive) to ignore and not redirect to proxy. This has higher precedence than any other parameters.
  -p, --incoming-proxy-port int            Port to redirect incoming traffic (default -1)
      --log-format string                  Configure log format ('plain' or 'json') (default "plain")
      --log-level string                   Configure log level (default "info")
      --netns string                       Optional network namespace in which to run the iptables commands
      --outbound-ports-to-ignore strings   Outbound ports and/or port ranges (inclusive) to ignore and not redirect to proxy. This has higher precedence than any other parameters.
  -o, --outgoing-proxy-port int            Port to redirect outgoing traffic (default -1)
  -r, --ports-to-redirect ints             Port to redirect to proxy, if no port is specified then ALL ports are redirected
  -u, --proxy-uid int                      User ID that the proxy is running under. Any traffic coming from this user will be ignored to avoid infinite redirection loops. (default -1)
      --simulate                           Don't execute any command, just print what would be executed
      --subnets-to-ignore strings          Subnets to ignore and not redirect to proxy. This has higher precedence than any other parameters.
      --timeout-close-wait-secs int        Sets nf_conntrack_tcp_timeout_close_wait
  -w, --use-wait-flag                      Appends the "-w" flag to the iptables commands
```

### Logs, error output, etc

see previous section for relevant details

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
         --NODE NAMES REDACTED--
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2022-10-24T20:44:49Z
    see https://linkerd.io/2.11/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2022-10-24T20:44:49Z
    see https://linkerd.io/2.11/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2022-10-24T20:44:49Z
    see https://linkerd.io/2.11/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.11.4 but the latest stable version is 2.12.1
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.11.4 but the latest stable version is 2.12.1
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-6949787759-4sh48 (stable-2.11.4)
	* linkerd-destination-6949787759-czg9h (stable-2.11.4)
	* linkerd-destination-6949787759-rg8wj (stable-2.11.4)
	* linkerd-identity-6db699b97f-6stdj (stable-2.11.4)
	* linkerd-identity-6db699b97f-jtc8c (stable-2.11.4)
	* linkerd-identity-6db699b97f-qnd2w (stable-2.11.4)
	* linkerd-proxy-injector-687456d4b6-4v8sb (stable-2.11.4)
	* linkerd-proxy-injector-687456d4b6-4vh7w (stable-2.11.4)
	* linkerd-proxy-injector-687456d4b6-82zd2 (stable-2.11.4)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-buoyant
---------------
‼ Linkerd extension command linkerd-buoyant exists
    exec: "linkerd-buoyant": executable file not found in $PATH
    see https://linkerd.io/2.11/checks/#extensions for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2022-10-21T18:41:47Z
    see https://linkerd.io/2.11/checks/#l5d-tap-cert-not-expiring-soon for hints
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* grafana-db56d7cb4-6sfbz (stable-2.11.4)
	* metrics-api-595c7b564-54hlf (stable-2.11.4)
	* prometheus-5d4dffff55-5h86h (stable-2.11.4)
	* tap-55c5df56bc-qtptd (stable-2.11.4)
	* tap-injector-66597495f5-b4s4z (stable-2.11.4)
	* web-6b6f65dbc7-qbxq2 (stable-2.11.4)
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- Kubernetes Version: v1.22.11
- Cluster Environment: EKS
- Host OS: amazon-eks-node-1.22-v20220629
- Linkerd Version: 2.11.4 (also reproduced on 2.12.1)

### Possible solution

This could be solved in a number of ways.  The simplest would be to add a new option to set `allowPrivilegeEscalation` separately from `runAsRoot`.

**Comment by mateiidavid** [comment]
@teriyakichild thanks for raising this!

The docker runtime does indeed require proxy-init to run with root privileges. For the record, I'm not necessarily opposed to making `allowPrivilegeEscalation` configurable for proxy-init, but I don't think it would solve your compliance issue, or make things more secure. The following statement doesn't really match my understanding of how all of this is supposed to work:

> This seems to be much more secure considering that the default for allowPrivilegeEscalation is true when running containers as non-root. ([source](https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md#changes-of-securitycontext-objects))

I've looked at the KEP you linked (it has since been archived), and I can't find a mention of `allowPrivilegeEscalation=true` when running as non-root. That'd be a dangerous thing for security, particularly in the context of using Docker as the container runtime in the cluster. Traditionally, [Docker maintained a less privileged root user](https://docs.docker.com/engine/security/#linux-kernel-capabilities) in its containers.

Containers are conceptually a bunch of Linux namespaces (combined with cgroups) that isolate processes. Security related identifiers and attributes are handled through [user-namespaces](https://manpages.ubuntu.com/manpages/bionic/man7/user_namespaces.7.html). 

> "When a process in the new namespace subsequently performs privileged operations that operate on global resources isolated by the namespace, the  permission  checks  are performed according to the process's capabilities in the user namespace that the kernel associated with the new namespace."

Root users in containers do not necessarily correspond to root users on the host. And root in a container does not grant the same privileges as root on the host (depending ofc on the container runtime that you use, but I'd assume most of them use a similar model). If you allow privilege escalation, _it does mean that root on host is mapped to root in container_ which becomes more problematic. 

When a container runs as privileged (regardless of whether the uid of the process inside the Linux pid namespace is root), the container runtime will **grant all root capabilities to the container**. Let's exemplify it. Before, Linkerd's proxy-init used to run as root in all cases, yet privilege escalation was set to false. This meant that while our root user had a lot of root caps and privileges, it still couldn't interact with certain files and network interface settings on the host, unless we granted additional system capabilities. If we were to run as privileged, none of that would've been required, since the root user would've had all root caps by default. 

As far as security goes, at least based on the man page and docker docs that I've linked, it is more secure to run as root and grant only a subset of system caps, than to run as non-root and allow the container to run as privileged (in which case it the attack surface is much wider). 

Furthermore, through `allowPrivilegeEscalation`, a container may:

* Escape cgroup limitations (and use up as many resources as it wants)
* Allow processes to escape the containers and interact with other processes (or see other processes) which would've otherwise been isolated.

I'm not sure if making this configurable, and running with this in production will make things more secure for you. I'm also unsure if this is needed since dockershims are going to be deprecated, not sure how feasible it is for future users to run linkerd on recent k8s versions with dockershims. Granted, making this configurable might help us in other cases (such as running proxy-init in SELinux enabled envs).

Feel free to correct me if my understanding is wrong, not the most straightforward thing to look into :) 

cc: @olix0r and @stevej

**Comment by mateiidavid** [comment]
I'm going to go ahead and close this. For what it's worth, #9873 introduced the option to run proxy-init as `privileged`. When `privileged=true`, `allowPrivilegeEscalation` will also be true.

I strongly recommend against it. As explained above, I think a better option is to run as root and make sure `privileged` and `allowPrivilegeEscalation` are set to false. If you need to compromise somewhere, I'd compromise on running with root access since it will be a watered down root user in the container.

Thanks!
