### ISSUE TITLE
Update Linkerd serverauthorization & server policy templates to use version v1beta1 and remove deprecated v1alpha1

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#9711]
### What is the issue?

`linkerd2/charts/linkerd-crds/templates/policy/server-authorization.yaml` and `linkerd2/charts/linkerd-crds/templates/policy/server.yaml` should be updated to use `v1beta1` versions in place of the deprecated `v1alpha1` versions currently in place.

### How can it be reproduced?

Deploy linekrd-crd helm chart and observe deprecated versions being used in kubectl crd output.

### Logs, error output, etc

`deprecationWarning: "policy.linkerd.io/v1alpha1 Server is deprecated; use policy.linkerd.io/v1beta1 Server"`

### output of `linkerd check -o short`

n/a

### Environment

any environment using current `linkerd-crds` charts

### Possible solution

Update the `server-authorization.yaml` and `server.yaml` templates in `linkerd-crds` helm chart to use `v1beta1` by default and remove the deprecation message from template.

**Comment by mateiidavid** [comment]
Both versions are included in the crd afaict (at least from looking at https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-crds/templates/policy/server.yaml).

It seems that regardless of which order versions are defined in, and how many versions are defined, the default version for `kubectl` will always be one closest to GA (so beta would be the default because it's closer to GA than alpha is) [[1]](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-priority). 

You should only get the warning if you make an API Request to a deprecated version (so, I'd assume if you request a version that still uses `v1alpha1`). Or at least, that's what the docs seem to imply [[2]](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-deprecation).

We also seem to have `storage=true` only for `v1beta1`, only these versions should be persisted; this seems to be the mark of the "latest" version of a crd.

Just to be on the same page as you though, do you normally get this error when accessing resources (e.g a specific server resource), or when doing `kubectl get crd servers.policy.linkerd.io`?

**Comment by philomory** [comment]
The problem here is that some resources (e.g. `AuthorizationPolicy`, `MeshTLSAuthorization`, and `NetworkAuthorization`) only define `v1alpha1`, and not `v1beta1`. Kubernetes API versioning is supposed to be done at the API Group level, not the level of individual resource types; as it stands, it looks as if, in the transition from `policy.linkerd.io/v1alpha1` to `policy.linkerd.io/v1beta1`, the three resource types mentioned above were _removed_, and can no longer be used.

**Comment by adleong** [comment]
If you look at various apigroups throughout the k8s ecosystem, it's pretty normal to have different resources at different versions, even within an apigroup.  So I don't think there's any particular problem with the current state of things.

With that said, we should have a more cohesive plan going forward for how we plan to version these resources and then plan for eventually getting them to v1.
