### ISSUE TITLE
Simplify Opaque Port Manifests

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#9803]
### What problem are you trying to solve?

Currently our protocol detection opaque port markings are exclusive (i.e., we mark which ports we want to exclude from protocol detection), which creates issues for users who have to exclude massive port-ranges for integration with other infrastructure components such as syslog, for example. Adding massive ranges expands the manifest and we've seen issues where it also creates problems for the k8s api, not to mention the additional memory pressure on the proxies themselves which has to be accounted for.

**Comment by dwilliams782** [comment]
Just incase I'm misunderstanding, are you aware that the opaque-port annotation accepts a range, so `config.linkerd.io/opaque-ports: 1-65535` is a valid config?

**Comment by deusxanima** [comment]
@dwilliams782  good question. The issue presents specifically when port-ranges are used. With massive ranges each port in the range is added to the manifest which is then expanded to the point where it can 1. make the config and annotations a nightmare to manage, 2. increase proxy mem usage, and 3. overwhelm the k8s api due to the massive character count that is added to some events/requests.

**Comment by hawkw** [comment]
Proxy PR linkerd/linkerd2-proxy#2395 changes the proxy to accept port ranges in the `LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION` environment variable. Once this PR merges, we'll also need to change the proxy-injector to pass the ranges through when populating this environment variable, rather than populating it with each individual port in the range. That should fix this issue!

**Comment by hawkw** [comment]
We've now merged the proxy release that modifies the proxy to accept ranges in the environment variable. I'm working on modifying the proxy-injector to actually emit ranges when patching a manifest. 

This is somewhat more complex than simply removing code that turns a list of ranges into a list of individual port numbers, though, because the proxy-injector also performs filtering of the opaque port list so that it includes only those ports actually exposed by the Service: https://github.com/linkerd/linkerd2/blob/5f7bbbad32f4585996a79a9aca65dc8471d01897/pkg/inject/inject.go#L376-L427
