### ISSUE TITLE
Allow linkerd to terminate TLS connections

### ISSUE THREAD

**Issue by jroper** [linkerd/linkerd2#9911]
### What problem are you trying to solve?

In my setup, I have a service that receives gRPC traffic from other services, along with the GCE ingress controller. Now, since I'm using gRPC, I want the GCE ingress controller to forward traffic as HTTP/2. But, the GCE ingress controller has a policy that if using HTTP/2, the connections to the backend that it makes MUST use TLS, there's no way to disable this. The certificate that the backend service supplies can be anything, the GCE load balancer doesn't validate it.

Now, I don't want my application to have to terminate TLS. I want it to just serve HTTP, so that other services can just talk HTTP to it with transparent mTLS from linkerd, and allowing me to apply authorization policies etc. So, I would like the linkerd proxy, when it detects TLS in use, to terminate TLS. Of course, the GCE load balancer won't be supplying a valid client certificate, so the request is not going to have an associated identity.

### How should the problem be solved?

The linkerd-proxy could have an option that tells it that when it detects an SSL connection, it should terminate that SSL connection with its own certificate, not apply any client validation, and forward it to the application as a plain connection with no identity.

### Any alternatives you've considered?

The alternative that I'm going to have to implement for now is to have my application listen on two different ports, one for HTTPS with a self signed certificate, one for HTTP. Other services will communicate with it on the HTTP port, while GKE will communicate on the HTTPS port. One of the big down sides of this is that if I configure any authorization policies, those can be undermined simply by connecting to the HTTPS port instead of the HTTP port, so my application will have to block traffic on any paths that should have had an authorization policy applied if the traffic came in on the HTTPS port.

### How would users interact with this feature?

An annotation on the pod, eg `config.linkerd.io/terminate-manual-tls: true`.

### Would you like to work on this feature?

maybe

**Comment by adleong** [comment]
Hi @jroper!  This is an interesting case, but it seems like a pretty niche one.  At least, I haven't heard of anyone else with this use-case.  

Given that this is very different from how the Linkerd proxy usually behaves (where it terminates proxy-to-proxy mTLS but otherwise forward encrypted connections to the application container), I think it's unlikely that we'd add a special case to the proxy to handle this.

I will say, however, that the same components which we used to build the Linkerd proxy (tokio, tower, hyper, etc) would be perfect for building your own specialized microproxy just for terminating TLS.
