### ISSUE TITLE
Linkerd-Viz: Enable helm charts to set privileged escalation to false by default

### ISSUE THREAD

**Issue by calumrees99** [linkerd/linkerd2#9946]
### What problem are you trying to solve?

Currently Linkerd viz deployments are showing as non-compliant against the Azure Policy "Kubernetes clusters should not allow container privilege escalation"
Definition ID is:
/providers/Microsoft.Authorization/policyDefinitions/1c6e92c9-99f0-4e55-9cf2-0c234dc48f99

### How should the problem be solved?

Within the Security Context of Kubernetes privileged escalation is set to true by default. To adhere to best security practices, it would be great to have the ability to set `allowPrivilegeEscalation: false`

Looking at this PR, https://github.com/linkerd/linkerd2/pull/7521, this has previously been done for the control plane but wasn't completed for the viz extension (and possibly other charts).

### Any alternatives you've considered?

Un-sure if addition args can be used in this instance

### Would you like to work on this feature?

maybe

**Comment by Alcadeus0** [comment]
Can i take up this issue :)

**Comment by kleimkuhler** [comment]
@Alcadeus0 sure! Let us know if you have any questions.

**Comment by kleimkuhler** [comment]
Your best resource will probably be the PR that changed this for the core components https://github.com/linkerd/linkerd2/pull/7521. You can see the conversation that took place in there about making it non-configurable (always `false`) and updating the test files so that tests pass. Of course a broader understanding of Linkerd and the code won't hurt, but this change should be entirely in the Helm template files.

**Comment by Alcadeus0** [comment]
Gotcha, I had a feeling that PR would give me an overview on how to solve the issue. I plan to delve deeper into the codebase and have a better grasp. Will start working on the PR :)

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/9719
